Dash-Industry-Forum/dash.js

src/streaming/Stream.js, src/streaming/controllers/StreamController.js
Fix #2458 
As @bbcrddave stated, in case there is an issue while initializing Protection for any of the media types, stream is reset and then streamProcessors array. We need to take this into account while iterating streamProcessors.
=> Check streamprocessors while initializing protection

src/streaming/protection/controllers/ProtectionController.js
This PR reverts a modification mistakenly done in PR #2435.
That concerns key system access error not being triggered when selecting key system from manifest.
BTW, does anyone know why it has been done this way? I thought it could be to handle use case where key systems declared in manifest can't be accessed while pssh of additional key systems are contained in the stream. Then it gives priority to pssh in the stream.
Can anyone confirm or complete?
=> Revert ProtectionController

contrib/akamai/controlbar/controlbar.css, contrib/akamai/controlbar/snippet.html, samples/dash-if-reference-player/index.html
This PR fixes #2460. 
Simplified the layout of Seekbar component and its associated css. This removes the need of using z-index properties in the seeking bar because it could interfere with other components of the web layout.
=> Fix SeekBar style (ControlBar)

src/dash/DashAdapter.js, src/streaming/MediaPlayer.js, src/streaming/controllers/StreamController.js
This PR optimizes the `StreamController.onManifestUpdated()` method. It removes the manifest passed as argument to `adapter.getStreamsInfo()` because the `DashAdapter` instance already got regular periods for the current manifest. So it is useless to re-analyze the manifest once again to get them.
This PR also adds a new `limit` argument to `DashAdapter.getStreamsInfo()`. It allows to specify for how many streams we want to get info. Currently, some classes calls `getStreamInfos()` to uselessly get info for all streams but only use the first one.
=> onManifestUpdated and getStreamsInfo optimizations

src/streaming/Stream.js
This PR fixes a double call to the `createBuffers()` method in `Stream.activate()`.
There is no need to call `createBuffers()` again as it is already called by `initializeMedia()` just above.
=> Fix creation of buffers

src/dash/models/DashManifestModel.js, src/streaming/Stream.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/ScheduleController.js
Hi,
this PR has to improve fast track switch process and not reload abandonned request in this use case. As mentionned by @nweber, there was an issue when fast video track switch occured.
@nweber , could you, please, give us a feedback?
Nico
=> improve track switch process

src/core/FactoryMaker.js
This PR simplifies/optimizes the management of factories by using dictionaries to store them instead of object lists.
Using dictionaries, the retrieval/update of factories is more straightforward as it does not require to loop over the list of objects.
=> Simplification of factory management

package.json, src/dash/DashMetrics.js, src/dash/utils/Round10.js, test/unit/dash.utils.Round10.js
The licence associated with dependency round10 is unclear, as reported in #2487, so have reimplemented the required method natively.
=> Fix #2487 - remove dependency on round10

src/streaming/rules/ThroughputHistory.js
Fix #2497. Index used in getSampleSize to calculate throughtput change ratio was wrong.
=> Fix getSampleSize

src/streaming/text/TextController.js
Hi,
this PR has to solve issue #2489.
Nico
=> add polyFillFindIndex function in order to bug fix in IE11

src/mss/MssHandler.js, src/streaming/MediaPlayerEvents.js, src/streaming/utils/TTMLParser.js
Hi,
this PR has to add the new event called TTML_TO_PARSE. This event is triggered before ttml content is parsing by imsc1 library.
In MSS use case, it allows to replace wrong namespaces according to IMSC1 point of view. A test can be made with mss stream Prince Of Persia - Live. Subtitles style is not taken into a count but text is correctly shown.
Nico
=> add TTML_TO_PARSE event

src/mss/parser/MssParser.js
This PR adds mapping of StreamIndex subTypes to MPEG-DASH AdaptationSet role and accessibility (see ETSI TS 103 285 v1.1.1, section 7.1.2)
=> [MSS] Map subTypes to MPEG-DASH AdaptationSet role and accessibility

src/streaming/protection/controllers/ProtectionController.js, test/unit/mocks/ProtectionKeyControllerMock.js, test/unit/streaming.protection.controllers.ProtectionController.js
Hi,
this PR has to :
- add a first version of ProtectionController unit test
- return a DRM error if the challenge message from CDM is empty
Nico
=> Add empty challenge drm error

src/streaming/ManifestUpdater.js, src/streaming/MediaPlayer.js, src/streaming/models/MediaPlayerModel.js, test/unit/mocks/MediaPlayerModelMock.js, test/unit/streaming.MediaPlayerSpec.js
This PR fixes #2501 
It also adds new `setManifestUpdateRetryInterval()` and `getManifestUpdateRetryInterval()` method to manage the interval-frequency at which ManifestUpdater will check if the current manifest is still processed before downloading the next manifest once the minimumUpdatePeriod delay has expired.
=> Fix TimeSyncController/ManifestUpdater race condition

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/app/sources.json, samples/dash-if-reference-player/index.html, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/protection/drm/KeySystem.js, src/streaming/protection/drm/KeySystemClearKey.js, src/streaming/protection/drm/KeySystemPlayReady.js, src/streaming/protection/drm/KeySystemW3CClearKey.js, src/streaming/protection/drm/KeySystemWidevine.js, src/streaming/protection/models/ProtectionModel.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js
This PR adds support for persistent MediaKeySession loading.
This can be operated on chrome since chrome and Widevine CDM now support persistent sessions.
With this PR, if your license server can deliver persistent licences, you can configure the stream protection data to setup key system access with support of persistent licenses:
```
protData = {
"sessionType": "persistent-license"
}
}
```
Once such kind of stream is loaded and a persistent license is obtained, the session ID can be reused, when playing the same stream, to load a MediaKeySession with the persistent session ID, instead of creating a new MediaKeySession and request again the license.
The dash-if-reference sample provides functionnality to playback a session with a persistent session ID.
Once a …
=> Load persistent sessions

index.d.ts
Hi
This PR fixes an incorrect definition in index.d.ts file : 
In MediaPlayer.js, undefined can be passed as argument of time function, not in typescript.
This PR adds undefined type to time function declaration
Jérémie
=> Incorrect definition of time in index.d.ts

src/streaming/text/TextSourceBuffer.js
Fix regression that appeared after #2469.
Timescale could be not defined in the Representation (mpd), as happens in our CEA608 sample streams. So, let's use embeddedTimescale instead, as it is used for other timing related stuff of our CEA608 implementation.
=> Use embeddedTimescale for CEA608 instead of timescale in MPD

src/dash/models/DashManifestModel.js, src/streaming/controllers/StreamController.js
This PR adds a new `maxRepresentations` parameter to `DashManifestModel.getRepresentationsForAdaptation()`. It allows to specify how many  representations to get. Currently, some classes calls `getRepresentationsForAdaptation()` to uselessly get info for all representations but only use the first one, like in `StreamController.onManifestUpdated()`.
=> getRepresentationsForAdaptation optimization

src/streaming/Stream.js, src/streaming/controllers/MediaController.js
This PR is a small optimization for the addition of tracks:
In `Stream.initializeMediaForType()`:
* remove call to `MediaController.isMultiTrackSupportedByType()` as it is also done in `MediaController.addTrack()`
* fix: remove unused second argument passed to `MediaController.addTrack()`
The `MediaController.addTrack()` is also slightly refactored to:
* return early if no track passed or track type is not suppored
* use a direct reference to the track list to which passed track should be added.
=> Optimization of track addition

src/streaming/models/FragmentModel.js, test/unit/streaming.models.FragmentModelSpec.js
Hi,
as for #2530 PR, do not remove init segment in syncExecutedRequestsWithBufferedRange function.  Unit tests are also updated.
Nico
=> Update syncExecutedRequestsWithBufferedRange function

src/streaming/models/FragmentModel.js
Changed isFragmentLoaded method to ignore the track representation when comparing URL, this caused redundant segment downloads when quality changed.
This comparison was added at https://github.com/Dash-Industry-Forum/dash.js/pull/2252, the logic should still be valid for that case.
Fixes #2434
=> Fix redundant segment download when setQualityfor() is invoked many times

src/mss/MssHandler.js
This avoids errors in processFragment and subsequent problems of not having managed the error at this level.
=> [mss] do not process segment when onSegmentMediaLoaded gets an error

build/typings/index.d.ts, index.d.ts
Not all values are required when setting protection data but not passing them all throws a TypeScript error.
=> [Definitions] Mark values in protection data as optional.

src/streaming/utils/BaseURLSelector.js
The use case is to be able to seek after a segment download has failed. At the moment, when this happens,  an event Events.URL_RESOLUTION_FAILED is fired and stops the schedule controller.
If we want to seek further to bypass a missing segment, we can not start the playing again because the base url of the segment that failed is stored in the black list controller.
By resetting it after the event firing, it allows to try seeking further. Without this PR we can not seek at all after this event. So the only thing this PR changes is to at least let the client to jump over a missing segment.
If needed we can add a configuration to enable/disable this feature. What do you think ?
=> reset BlacklistController after url resolution failed

src/streaming/text/TextSourceBuffer.js, src/streaming/text/TextTracks.js
`addCue` method crashed with `Invalid argument` after seeking back, a simple track reset if the exception happens fixes this. #2524
=> Fixed an edge issue causing text track to stop working when seeking back

src/streaming/utils/TTMLParser.js
Have TTMLParser return an empty array of captions when the TTML document is valid but contains nothing to display (ie empty samples to maintain the timeline). Still throw an error if there was one.
I have not tested that it does not regress #2527 as I do not have access to Edge.
IMO this should be included in the upcoming release as it is a serious regression.
=> Fix #2547 - do not reject empty TTML docs as invalid

samples/dash-if-reference-player/index.html
Add a note to Live Latency parameter (Reference Player) to clarify latency estimate doesn't include the time taken by the encoder to encode the content.
=> Add note to live latency description

samples/getting-started-basic-embed/listening-to-SCTE-EMSG-events.html
This sample was generated in response to a question on Slack concerning how to listen for SCTE markers embedded inside EMSG boxes. It uses the live simulator stream as the input source.
=> Adding sample to show SCTE EMSG event capture from a live stream

samples/dash-if-reference-player/app/sources.json, src/streaming/controllers/BufferController.js
Fix a regression detected in clearNextRange (BufferController). First "if", responsible of checking whether there is a buffer and ranges to clear, was wrong and always returned false what caused inconsistencies in the Media Buffer.
This is a fix for #2556. @bbert, @nicosang, could you please let me know if you can still reproduce any issue in your end? Your opinion and feedback is highly appreciated.
=> Fix clearNextRange so it checks buffer properly

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/ManifestLoader.js, src/streaming/controllers/TimeSyncController.js, src/streaming/protection/drm/KeySystemPlayReady.js, src/streaming/protection/models/ProtectionModel_01b.js, src/streaming/rules/scheduling/BufferLevelRule.js, src/streaming/utils/CustomTimeRanges.js
Add changes to KeySystemPlayReady to make it compatible with some SmartTVs that don't pass an XML doc with a challenge in the key message but the challenge itself. 
Add triggering session creation and close events for ProtectionModel01b, as we are doing for all the other models. Catch exceptions when calling closeKeySession of ProtectionModel01b, as there are some devices (ex: LG SmartTVs) which raise exceptions when trying to close a session after the source being unloaded.
=> PlayReady DRM fixes for SmartTVs

build/typings/index.d.ts, index.d.ts, src/streaming/MediaPlayer.js, src/streaming/controllers/AbrController.js, test/unit/helpers/ObjectsHelper.js, test/unit/mocks/AbrControllerMock.js, test/unit/mocks/DashManifestModelMock.js, test/unit/mocks/VideoModelMock.js, test/unit/streaming.controllers.AbrControllerSpec.js
This PR adds a new method to the MediaPlayer to get the top quality BitrateInfo. It calls `getTopQualityIndexFor ` internally so portal size and max bitrate are checked. #2463
=> Max value limited by portal size

src/streaming/MediaPlayer.js, src/streaming/controllers/PlaybackController.js, src/streaming/models/URIFragmentModel.js
This PR provides a clean version of URIQueryAndFragmentModel.
Currently, URIQueryAndFragmentModel parses the URI of the attach manifest to detect if HTTPS is used, and extract data from the query string and the fragment part. However, only the fragment part is really used by dash.js.
This clean version removes the code parsing unused data. Only supported keys are extracted from the fragment part of the URI (t, xywh, track, id, s, r).
EDIT: by the way, I renamed this class to URIFragmentModel to better express its main purpose.
=> Clean URIQueryAndFragmentModel

src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/models/VideoModel.js, src/streaming/rules/DroppedFramesHistory.js, test/unit/mocks/VideoElementMock.js, test/unit/streaming.MediaPlayerSpec.js
Hi,
this PR has to solve issue #2490. Unit tests have been also updated by adding checking of element type.
@VincentFTS, could you, please, take a look at this PR?
Many thanks,
Nico
=> Add correct support of audio element

externals/objectiron.js, src/dash/parser/DashParser.js, src/dash/parser/maps/CommonProperty.js, src/dash/parser/maps/MapNode.js, src/dash/parser/objectiron.js, test/unit/dash.parser.maps.CommonProperty.js, test/unit/dash.parser.maps.MapNode.js
This PR is a refactoring of `objectiron.js` in order to greatly reduce the time to process manifests, especially on low resource devices like Chromecast. This reduces join time, and improves UX for live streams as manifests are downloaded repeatedly.
ObjectIron is used to apply inheritance of XML attributes and elements in the manifest. For example, SegmentBase, SegmentTemplate and SegmentList elements may be present in the Representation element. In addition, to express default values, they may be present in the Period and AdaptationSet ancestors. In the Representation element, SegmentBase, SegmentTemplate and SegmentList shall inherit attributes and elements from the same element on a higher level. This is processed using ObjectIron.
ObjectIron uses _mappers_ to define which elements …
=> Optimization of manifest processing (ObjectIron)

samples/dash-if-reference-player/app/main.js, src/dash/parser/DashParser.js, src/mss/parser/MssParser.js, src/streaming/ManifestLoader.js, src/streaming/ManifestUpdater.js, src/streaming/controllers/StreamController.js, test/unit/dash.DashParser.js, test/unit/mss.parser.MssParser.js, test/unit/streaming.ManifestUpdater.js
Hi,
this PR has to update manifest parsing error. The main idea is that each parser (dash or mss) has to throw an error if needed. This error is caught by the ManifestLoader class which has to trigger a INTERNAL_MANIFEST_LOADED event.
Finally, ManifestUpdater has to analyze error attribute of this event, and if needed, call manifestError function of ErrorHandler class. Thus, the call to manifestError function is centralized in ManifestUpdater only during parsing process.
A first version of ManifestUpdater unit test has also been added.
Nico
=> Update manifest parsing error

src/streaming/MediaPlayer.js, src/streaming/controllers/BufferController.js, src/streaming/rules/scheduling/BufferLevelRule.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js, src/streaming/text/TextController.js
When enabling dash will keep downloading and process fragmented text tracks even if all tracks are in mode "hidden"
=> Introduce new API enableForcedTextStreaming

contrib/akamai/controlbar/ControlBar.js
Fixed an ES5 incompatibility where `let` was used instead of `var`. Since this file is not compiled it needs to stay compatible with ES5 assuming that is the target. When running this file through the [uglify minifier](https://github.com/mishoo/UglifyJS), it throws an error since it thinks this is a syntax error.
I'm not entirely sure what compatibility is expected for `controlbar.js`, but this seemed like a reasonable assumption since the file is not compiled. The change was so small I went ahead and opened this PR instead of an issue first.
Thanks!
Semi-related, this is the PR where `let` came from https://github.com/Dash-Industry-Forum/dash.js/pull/2520
=> Fix ES5 Incompatibility in Controlbar

src/streaming/text/TextSourceBuffer.js
Caption parsers are added for every `mediaInfo` that's processed in the MPD. This causes a problem for multi-period feeds, as you'll get duplicate captions pushed out.
=> don't double-add caption parsers on period switch

src/dash/DashAdapter.js
Remove unnecessary `channel` to make the `lang` property an actual language
=> use just caption language for cea608 mediainfo language

src/streaming/controllers/BufferController.js
There appears to be a race condition that occurs sometimes in the `BufferController` where the controller thinks that it needs to prune some ranges, but it's not possible to do so. The `BufferController` already has checks to catch these scenarios, but the pruning state isn't flipped back to "not pruning", which causes the player to get stuck in a pruning state. This has the side effect of effectively halting playback since the `ScheduleController` will not executes requests while pruning.
This PR resets the pruning state if it is discovered that pruning cannot continue.
=> Bug with clear next range

src/streaming/text/TextTracks.js
Hi,
this PR has to solve issue #2564 by removing specific implementation of textTrack creation in Chrome browser. Before this PR, textTrack was created by calling document.createElement ('track'). By doing like this, cues added after parsing VTT subtitles was deleted by latest Chrome 66 version.
any feedback will be appreciate....
thanks,
Nico
=> Update TextTrack creation

src/streaming/ManifestLoader.js, src/streaming/controllers/StreamController.js
Fix a couple of race conditions that cause exceptions when resetting dash.js player while mediaSource is being opened (Fix #2535).
=> Fix couple of race conditions when resetting while loading

src/streaming/controllers/BufferController.js
This PR fixes the stream getting stuck in low latency mode if a buffer prune was called before it started playing, the index handler time went down to 0 and no fragments were downloaded.
=> Low latency stuck on start fix

src/streaming/net/XHRLoader.js, test/unit/streaming.net.XHRLoader.js
After aborting an event, the onloadend event fires still. This causes the aborted segment to look like an error and will be retried, and this causes a second scheduling loop to start up, leading to segments being downloaded multiple times concurrently (an example is in the logs in #2588 , but this occurs on all platforms).
=> Don't listen to events coming from aborted XmlHTTPRequests

src/streaming/text/TextSourceBuffer.js
Hi,
this PR adds accessibility information in order to be able to know if the track is, for instance, a hard of hearing one. 
According to the [spec](http://www.etsi.org/deliver/etsi_ts/103200_103299/103285/01.01.01_60/ts_103285v010101p.pdf) page 28, a main roles with an accessibility of 2 define a Hoh subtitle track.
Nico
=> add accessibility to TextTrackInfo

test/functional/config/streams.json, test/functional/tests.html
Fixed the functional tests on BrowserStack by removing the 4k video and muting the chrome video to make it auto playable. Closes #2616
=>  Fix functional tests 

src/streaming/controllers/PlaybackController.js
`wallclockTimeIntervalId` was set to `null` before stopping the interval.
May be related to #2593
=> Fixed a bug in playbackController causing multiple wallclockTime intervals

src/dash/models/DashManifestModel.js, src/streaming/MediaPlayer.js, src/streaming/protection/drm/KeySystemW3CClearKey.js, src/streaming/text/TextSourceBuffer.js, src/streaming/utils/DOMStorage.js, src/streaming/utils/TTMLParser.js, test/unit/dash.models.DashManifestModel.js, test/unit/streaming.protection.drm.KeySystemW3CClearKey.js
Partial refactor of getRegularPeriods method of DashManifestModel. Added a new check to cover situations in which multi period streams, for static assets, are not defining start and duration attributes of any of their periods. This avoids dash.js to throw exceptions, and logs a warning message to notify the user about the issue. 
Note: Having this situation implies a wrong mpd and that, even with this fix, there will be timing inconsistencies after the first period. However, IMHO, I prefer dash.js to play something whenever is possible. Once we add the flag to dash.js to allow/disallow playback of streams/assets out of DASH IOP guidelines, I will revisit this.
Added unit tests to cover this and regular situations (multiple combinations of period with combinations of start and duration …
=> Make more robust the period parsing. Add unit tests

build/typings/index.d.ts, index.d.ts, samples/dash-if-reference-player/app/sources.json, src/streaming/MediaPlayer.js, src/streaming/MediaPlayerEvents.js, src/streaming/controllers/PlaybackController.js, src/streaming/rules/scheduling/BufferLevelRule.js, test/unit/mocks/PlaybackControllerMock.js, test/unit/streaming.MediaPlayerSpec.js
Checking the buffer level and target live delay, if it's behind the playback rate will be increased by 5% by default, configurable from 0% to 20%
Fixes #2600
=> Low latency catch up

src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/ScheduleController.js, src/streaming/text/NotFragmentedTextBufferController.js, src/streaming/text/TextBufferController.js, src/streaming/text/TextController.js, src/streaming/text/TextSourceBuffer.js, test/unit/mocks/StreamControllerMock.js, test/unit/streaming.text.NotFragmentedTextBufferController.js, test/unit/streaming.text.TextController.js
Hi,
this PR has to optimize not fragmented subtitles management.
Indeed, when a stream is selected with not fragmented subtitle, like for instance https://vm2.dashif.org/dash/vod/testpic_2s/xml_subs.mpd, by default all the subtitles files are downloaded and parsed at the beginning. Then, if the user decides to seek somewhere in this content, the selected subtitle file is parsed a second time when this first seek command occurs.
So, these modifications allow to download only the selected subtitles file. Then, if the user wants to change subtitles track, the new file will be downloaded. Finally, if a seek command occurs, the useless parsing is not done.
Nico
=> Update not fragmented subtitles management

index.d.ts, src/streaming/MediaPlayerEvents.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js
Fix BUFFER_EMPTY never firing if buffer level never went above safe distance, also will check buffer when native video element triggers stalled or playing.
Fixes #2607
=> Fix BUFFER_EMPTY never fired

src/streaming/controllers/StreamController.js
Fixes a crash by checking if there is an active stream in the `StreamController` before trying to initialize `PlaybackController`
Fixes #2637
=> Fixed crash when calling attachView on an already initialized player

src/streaming/FragmentLoader.js, src/streaming/net/HTTPLoader.js
Fixes LOADING_PROGRESS event, an event required to be able to abandon requests and make the ABR algorithm work. Fixes #2632
=> Fix LOADING_PROGRESS event not being fired

src/streaming/text/TextSourceBuffer.js
This is just a minor fix. The `Cea608Parser` expects fields to be 1 or 2, not 0 or 1. This is made worse by [a `0 || 1` error in the parser](https://github.com/Dash-Industry-Forum/cea608.js/blob/master/lib/cea608-parser.js#L804), so its field will always be 1.
Note that the parser doesn't ever actually use the value of `this.field`, which is why this hasn't caused any bugs.
=> send proper field to Cea608Parser

src/streaming/SourceBufferSink.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js, src/streaming/models/FragmentModel.js, src/streaming/models/VideoModel.js, src/streaming/text/NotFragmentedTextBufferController.js, test/unit/mocks/TextBufferMock.js
This PR introduces buffer reuse for compatible codecs and preload of next periods to avoid jumps and freezes when switching periods.
It also introduces some changes to the SourceBufferSink to handle the appends and removes with a queue.
It's the same as #2575 but with clearer commit history.
Closes #1708
=> Smooth period transition

src/streaming/StreamProcessor.js, src/streaming/models/FragmentModel.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js
This PR adds a check in NextFragmentRule to see if the buffer is divided (IE, when appending out of order in safari) and react to that by downloading chunks for the active buffer.
Fixes #2588
=> Added checks in nextFragmentRule to see if the buffer was split (safari bug)

src/streaming/controllers/PlaybackController.js
Ending the stream from PlaybackController when it's supposed to be ended but native element didn't trigger the ended event.
Sometimes the video element stops a few milliseconds before the stream end and the `end` event is never fired, but we do fire PLAYBACK_ENDED. 
Now we listen for that event in order to pause the player and stop the `wallclock interval`
Fixes #2593
=> PlaybackController will end the stream if it's unfinished

contrib/akamai/controlbar/ControlBar.js
Fixed an ES5 incompatibility where a template string was used. Since ControlBar.js is an external module and is not compiled it should remain compatible with ES5.
Side note: ES6 will break uglifyjs since it expects ES5, there is a separate project uglify-es that has the ability to minify ES6.
Related: https://github.com/Dash-Industry-Forum/dash.js/pull/2576
=> Fix Another ES5 Incompatibility in ControlBar.js

src/streaming/controllers/StreamController.js
Fixed an issue causing a stream reload when seeking into the current stream but with reloaded manifest. Found on 2.8 RC1
=> Fixed stream reload when seeking

package.json, src/streaming/text/TextController.js, src/streaming/text/TextTracks.js
Hi,
this PR has to :
- update imscJS library version
- add tests of captionsContainer definition
- bug #2659 fix
Nico
=> Update subtitles support

src/streaming/SourceBufferSink.js
Executing all possible callbacks after appending to the buffer to avoid some of them getting stuck until next append / remove.
This fixes a random stall after seeking.
=> Fix stalling after seeking

src/streaming/controllers/ScheduleController.js
In live mode, until the first video segment is appended, the audio scheduling (via the BufferLevelRule) was considering audio buffer level always equal to 0.
Then in case 1st video segment takes some time to be downloaded, this can lead scheduler to request audio segments at live edge before they are available.
With this PR audio scheduler is correctly aligned with video scheduler.
=> Correct audio segments scheduling in live mode

src/streaming/controllers/BufferController.js
Hi,
this PR has to resolve issue du to PR #2672 => since PLAYBACK_SEEKING is not triggered for internal seek, reset seekStartTime of BufferControlled in PLAYBACK_SEEKED callback.
Nico
=> Fix regression due to internal seek

build/typings/index.d.ts, index.d.ts, src/streaming/MediaPlayerEvents.js, src/streaming/text/TextTracks.js
Adds a new CAPTION_RENDERED event that is triggered every time a caption is rendered on screen or when a caption is re-rendered due to a video resize.
=> Add CAPTION_RENDERED event

src/streaming/protection/controllers/ProtectionController.js
It's needed for our DRM provider for Chrome, perhaps others will as well.
If there are tests / documentation to update please let me know and I will update them.
=> pass distinctiveIdentifier and persistentState through to CDM

src/streaming/controllers/StreamController.js
When the stream is fully loaded, we set a timeout to preload the next stream in the future. This timeout was not cleared when seeking, so the stream could be preloaded several times causing weird behavior.
This PR fixes it.
=> Seeking will remove preload timer

src/mss/MssFragmentMoofProcessor.js
Hi,
this PR has to solve an issue about subitles in mss live stream. To reproduce it, in development branch, you just have to select mss Prince Of Persia - Live stream. After few or more seconds, subtitles will disappear. The origin of this issue is the removal of two segments in MssFragmentMoofProcessor instead of only one. The source code is modified by using precision of the second in this removal.
Nico
=> [MSS] Live subtitles bug fix

src/dash/models/DashManifestModel.js
Fixes #2700 by extracting event data either from the explicit messageData attribute, or from the text content of the XML element.
=> Fix #2700 - Load the Message Data for EventStream Events

src/streaming/controllers/PlaybackController.js
Hi,
this PR has to fix issue #2715 : no need to do an internal seek if earliestTime (common time of video and audio types) is 0.
Nico
=> Internal seek update

build/typings/index.d.ts, index.d.ts, src/streaming/MediaPlayer.js, src/streaming/models/MediaPlayerModel.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/models/ProtectionModel_01b.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js, src/streaming/protection/models/ProtectionModel_3Feb2014.js
The goal of this PR to enable maintining the MediaKeys instance and all valid MediaKeySessions during the MediaPlayer lifetime.
The use case is a live service for which you instantiate a MediaPlayer to playback all the streams.
Then you can specify the keep the MediaKeys instance when one zaps over all the streams/channels.
The benefits are:
- only 1 license request per channel during the MediaPlayer lifetime
- zapping time is reduced since you do request media key system access only at 1st playback, and do not need to request license if channel has been already played
By default, this option is disabled.
The condition before enabling this option is to ensure that the key system configuration (license type, audio/video robustness levels...) is the same for all streams/channels
=> Keep media keys

src/streaming/protection/controllers/ProtectionController.js
This PR prevents a rare player crash when a NeedKey event was fired before initializeForMedia was called, now it will retry a few times.
=> Protection Controller onNeedKey will be delayed until initializeForMedia is called

src/dash/DashHandler.js
**Use-case** : In a multi-period dynamic content with SegmentTimeline in MPD, the playback stops after first period. 
**Root-Cause**: The start time of second period is not available and playback fails. While starting the playback of the second period, start time calculation uses live edge. Live edge is not updated and it has the value of first period last segment. 
**Analysis** :  liveEdge is assigned only at the beginning of playback, when it NaN. It is not updated when the second period and segments added to the manifest. This value is used in calculation of start time in setLiveEdgeSeekTarget (ScheduleController.js).  
Fix for Issue #2639
=> Fix to update liveEdge in every segment list update

samples/dash-if-reference-player/index.html
To prevent console mixed-content warnings when page is loaded under https
=> Load favicon via https

build/typings/index.d.ts, index.d.ts
Fixed missing closing curly brace at the end of CaptionRenderedEvent in index.d.ts that prevented TypeScript projects from building.
=> Fixed error in index.d.ts.

samples/dash-if-reference-player/app/sources.json
As we decided in DASH-IF f2f in May, we will transition vm2.dashif.org to livesim.dashif.org. 
SSL certificates for both domains are now on the server. vm2 will be removed in 6 months or something like that.
Therefore we can now change all the URLs in reference player which is done in this PR.
Also changed some links from livesim-dev to livesim, since the functionality is no longer only on the dev version.
=> Change URLs from vm2.dashif.org to livesim.dashif.org

src/streaming/controllers/TimeSyncController.js
Fix #2732. IE11 doesn't provide an implementation for Math.trunc so we can't use it without checking its existence. I am not creating the typical "MathUtils" class that exports a trunc method to avoid overcomplicating the solution. We will re-think that in case trunc is used in more places of the code.
=> Math.trunc not supported by IE11

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/streaming/rules/scheduling/NextFragmentRequestRule.js
Hi,
this PR has to solve issue detected by @dsparacio in dashjs slack channel. 
_In 2.7.0 I added enableForcedTextStreaming and it is working as expected in 2.7.0.  However in 2.9.0 it still works upfront, but on a seek the text fragment is loaded over and over again rapidly and fills the text track with duplication of captions_
The bug could also occur by doing a simple seek command.
NextFragmentRequestRule has not to detect gap in buffers for fragmented Text media type because those buffers are never deleted when, for instance, a seek command occurs.
Nico
=> Update Gap detection in NextFragmentRequestRule

src/streaming/controllers/ScheduleController.js
Hi,
since the PR #2747, the bandwidth parameter is replaced for init fragment too. The problem is that for full subtitles file, the currentRepresentationInfo is undefined.
In order to test this issue, the stream 'TTML Sideloaded XML Subtitles' can be use.
Nico
=> update bandwidth replacement

src/streaming/protection/models/ProtectionModel_21Jan2015.js
This PR fixes potential uncaught exception in stop() method.
Closing MediaKeySession may throw an exception if MediaKeySession is not callable.
=> Fix ProtectionModel_21Jan2015

src/core/Debug.js, src/streaming/MediaPlayerEvents.js
This change makes it so that log events are sent regardless of log level. The log level only controls whether or not logs should be sent to the console.
This allows users to have the console logs off but still use the log messages for debugging in the case that an error occurred. In my app I store the log messages and send them to my own error reporting tool in the event that the player fails for some reason.
Fixes https://github.com/Dash-Industry-Forum/dash.js/issues/2749
=> log events are sent regardless of log level

samples/thumbnails/thumbnails.html, src/streaming/thumbnail/ThumbnailTracks.js, test/unit/streaming.thumbnail.ThumbnailController.js
Fix #2740
Support Thumbnails URI schema as defined in IOP 4.1 -> http://dashif.org/guidelines/thumbnail_tile
The previous URI schema, defined in the CR corresponding to thumbnails support, is also supported to ensure backward compatibility.
I took advantage of this PR to also clean up thumbnail sample.
=> Support URI schema for thumbnails as defined in IOP

src/streaming/protection/controllers/ProtectionKeyController.js
in ProtectionKeyController, restore issue fixing in PR #2318 that has been removed by error in PR #2451
=> Restore issue fixing in PR#2318

src/streaming/controllers/ScheduleController.js
Fix #2776.
In ScheduleController, scheduleWhilePaused config property should be checked in every call to schedule instead of using the value it had during initialization of the object. 
Furthermore, the "if" in schedule method implementing scheduleWhilePaused feature was wrong defined what made dash.js to always schedule segment requests, independently of the value of scheduleWhilePaused property.
=> Fix scheduleWhilePaused behavior

src/streaming/controllers/ScheduleController.js, src/streaming/models/FragmentModel.js
Use a threshold value in removeExecutedRequestAfterTime method to avoid small timing inconsistencies to cause gaps in the list of executed requests and then, playback stall issues.
This fixes playback issues reproduced in #2730.
=> Use threshold in removeExecutedRequestsAfterTime

src/core/errors/Errors.js, test/unit/core.errors.Errors.js, test/unit/streaming.controllers.SourceBufferSink.js, test/unit/streaming.text.TextSourceBuffer.js
Hi,
this PR has to modify error codes in order to be unique. Indeed, html5 video element returns error codes :
- 1 = MEDIA_ERR_ABORTED - fetching process aborted by user
- 2 = MEDIA_ERR_NETWORK - error occurred when downloading
- 3 = MEDIA_ERR_DECODE - error occurred when decoding
- 4 = MEDIA_ERR_SRC_NOT_SUPPORTED - audio/video not supported
- 5 = MEDIA_ERR_ENCRYPTED
So, dash.js error codes need to be shift to start at 10 value.
Nico
=> Change error codes

src/dash/utils/FragmentedTextBoxParser.js, src/streaming/text/TextSourceBuffer.js
This PR fixes an issue reported by @Gontran-Molotov and related with captioning. Couple of changes included:
- Fix in FragmentTextBoxParser when using subs atoms. Some times, when samples length was higher than subsamples one, an exception was raised because we were trying to read out of subsamples array bounds. 
- Fix the way we calculate firstFragmentedSubtitleStart. If first timestamp was exactly 0 we were not initializing first timestamp correctly and then the time offset used for deciding when to show each caption was wrong.
=> Fix issue with captions and subs atom box

build/typings/index.d.ts
Fix typings. An import was accidentally introduced in latest version of typings.
=> Remove import from typings file

src/streaming/controllers/ScheduleController.js
Change the "Playing at bleeding live edge" message to be a DEBUG one. I have also change the text of the message to avoid further confusions. It is not really playhead is close to live edge, but the end of the play buffer is. There are some cases in which this message was interpreted by users as an issue.
This is an internal message that just notifies about a regular situation that happens quite frequently while managing requests/fragments for live streams: playback buffer is still not full and there are no more fragments available.
=> Change type and text of bleeding live edge message

samples/dash-if-reference-player/app/main.js
In reference player, add a player reference to window object so developers can easily play with dash.js API. This also make easier some debug tasks in which methods/config parameters not exposed in the GUI are required to be call/modified.
Related with #2634
=> Allow easy testing of player API in Ref Player

src/streaming/protection/controllers/ProtectionController.js
Implement a retry mechanism for the HTTP requests needed to retrieve DRM licenses. Done to increase the resilience of dash.js when there are temporary network issues.
=> Add retry mechanism to license HTTP requests

src/streaming/protection/controllers/ProtectionController.js
This PR adds a new property to protData (httpTimeout) that allows configuring a timeout value for the xhr requests related with the DRM license retrieval process. Samples have also been modified as a way to demonstrate the use of this new property.
In case of not providing any value, its will be 8 seconds by default. Timeout is not used (not recommended) if protData.httpTimeout is set to 0.
=> Add timeout config for license requests

src/streaming/Stream.js
Workaround to #2795. Trying to reuse a MediaSource across two periods, in which one of them defines a DRM system and the other one not, makes Chrome to crash.
This PR avoid the crash although makes period transition in above cases to be not seamless. I will create a new ticket to investigate if this is a limitation of the browser. In that case I will create a ticket in Chromium project.
=> Force MediaSource reset when there are EME config changes

.gitignore, index.d.ts, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/app/sources.json, src/dash/utils/TemplateSegmentsGetter.js, src/dash/utils/TimelineConverter.js, src/streaming/FragmentLoader.js, src/streaming/MediaPlayer.js, src/streaming/MediaPlayerEvents.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/TimeSyncController.js, src/streaming/models/MediaPlayerModel.js, src/streaming/models/MetricsModel.js, src/streaming/models/VideoModel.js, src/streaming/net/FetchLoader.js, src/streaming/net/HTTPLoader.js, src/streaming/net/XHRLoader.js, src/streaming/rules/ThroughputHistory.js, src/streaming/rules/abr/InsufficientBufferRule.js, src/streaming/rules/abr/SwitchHistoryRule.js, src/streaming/rules/abr/ThroughputRule.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js, src/streaming/utils/SupervisorTools.js, test/unit/mocks/MediaPlayerModelMock.js, test/unit/mocks/PlaybackControllerMock.js, test/unit/streaming.MediaPlayerSpec.js, test/unit/streaming.controllers.PlaybackControllers.js, test/unit/streaming.models.MediaPlayerModel.js
Set of improvements for low latency mode:
- Implemented a new rate control mechanism similar to what was described in #2693. This enables playback synchronization across different clients.
- Rate control adaptations to overcome Safari limitations. Due to the way playbackRate works in Safari (stalls when playbackRate changes and the stream has an audio track), our rate control mechanism take this into account and when using Safari it increases the minimum acceptable playbackRate change.
- A new control mechanism has been added to dash.js to better recover from rebuffering situations when in low latency mode.
- Three new config methods added to control the new rate control mechanism: 
- `setCatchupPlaybackRate` - Sets the maximum playback rate variation (from 0-0.5 and with respect to …
=> Low latency improvements

src/streaming/models/FragmentModel.js
Fix #2821 following change suggested by @fvalleeHbbTV.
This PR limits the threshold used to do time -> segment number calculation to 0.5 seconds. Previous approach caused instability issues in streams using segments with long duration and timing sync issues.
=> Limit time threshold for segment request calculation

src/dash/models/DashManifestModel.js
Hi,
this PR has to fix an issue about definition of Event_asArray. In order to reproduce it, the stream http://vm2.dashif.org/livesim/periods_60/mpdcallback_30/testpic_2s/Manifest.mpd has to be started (Dash IF test vectors\mpd callback event)
Nico
=> Fix about Event_asArray attribute

CONTRIBUTING.md
Links to meriocratic governance model and release preparation documents are broken.
=> Fixing a couple of broken links in the contributing doc

src/dash/models/DashManifestModel.js, src/streaming/thumbnail/ThumbnailTracks.js
Support fragmented thumbnails in adaptationset with mimeType video/mp4 
(not only support image/jpeg, video/mp4 better matches format)
Reason for this is that we've updated our example stream to better match the IOP documents. Effectively the image track mimeType has changed from image/jpg to video/mp4.
=> Fragmented thumbnails mimeType fix

src/streaming/SourceBufferSink.js, src/streaming/Stream.js, src/streaming/controllers/StreamController.js, test/unit/streaming.Stream.js
Changes in the logic that takes care of seamless period transition:
- changeType support. In case the browser implements changeType method for SourceBuffer type of objects, then dash.js will use it for doing smooth period transition even when codec of the periods to be switched are not compatible. Requested in #2774.
- Re-factored the code that takes care of checking for codec and protection compatibility.
- Fixed an issue in jumpGaps features that caused problems when doing transition against not perfectly aligned periods.
=> Multiperiod transition logic changes

src/streaming/PreBufferSink.js, src/streaming/SourceBufferSink.js, src/streaming/models/FragmentModel.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js, test/unit/mocks/StreamProcessorMock.js
Remove threshold in removeExecutedRequestAfterTime because it causes more problems than solutions on streams with time alignment issues.
Modifies NextFragmentRequestRule so it calls to removeExecutedRequestAfterTime when there is a real discontinuity (buffer separated in 2 ranges itself doesn't mean there is a time discontinuity).
=> Remove requests only when there is a real discontinuity

src/streaming/controllers/BufferController.js, src/streaming/net/HTTPLoader.js, test/unit/streaming.net.HTTPLoader.js
Changes to address https://github.com/Dash-Industry-Forum/dash.js/issues/2837
Currently init segments caching in low latency mode is working incorrectly - it is storing only last  data chunk in cache.
Easiest way of fixing it is disabling fetch download for init segments. 
- Extended 'Append Init fragment' log msgs with data size info
- Use FetchLoader for media segments download only.
=>  Use FetchLoader for media segments download only to fix init segments caching issue in low latency mode 

src/streaming/text/TextSourceBuffer.js
Hi, 
this PR has to solve an issue found in the attached manifest.
[manifest.zip](https://github.com/Dash-Industry-Forum/dash.js/files/2603828/manifest.zip)
Id of the mediaInfo object is an unsigned int because it's an attribute of AdaptationSet :
`   <xs:complexType name="AdaptationSetType">     <xs:complexContent>       <xs:extension base="RepresentationBaseType">         <xs:sequence>           <xs:element name="Accessibility" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>           <xs:element name="Role" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>           <xs:element name="Rating" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/>           <xs:element name="Viewpoint" type="DescriptorType" minOccurs="0" maxOccurs="unbounded"/> …
=> Bug fix about id type of mediaInfo for subtitles

src/streaming/text/TextTracks.js
This PR adds the `CAPTION_RENDERED` event for text cues which are not html.
=> Add CAPTION_RENDERED event for non-html text cues

src/streaming/net/HTTPLoader.js
This PR fixes an issue in case we want to abort a request that will be retried.
When we abort a request for which a retry timeout has been set, then HTTPLoader simply cancels the retry timeout, but then LOADING_ABANDONED and therefore FRAGMENT_LOADING_COMPLETED events are not triggered and then schedule process in ScheduleController in never restarted.
To reproduce the issue, you can simulate an unavailable segment (using fiddler for example) and then attempt to perform a seek while segment download retries are executed.
=> HTTPLoader abort()

src/streaming/Stream.js
As the title implies, this replaces a use of `Array.prototype.find` with the `for () {}` equivalent since IE11 doesn't support `Array.prototype.find`
=> don't use Array.prototype.find because it doesn't exist for IE11

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/app/sources.json, src/streaming/protection/drm/KeySystemPlayReady.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js
This PR enables license persistence on Edge browser using 'com.microsoft.playready.recommendation' key system, as discussed in issue #2658.
Waiting for DASH test streams to be added in sample to validate this PR.
=> Edge licenses persistence

src/streaming/controllers/PlaybackController.js
Don't stop playback catchup when you haven't started it because it is disabled by setting catchup playback rate to value 0; e.g: leave playback rate alone in that case.
=> Fix disabling of catchup (leave playback rate alone)

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/controllers/AbrController.js, src/streaming/vo/MediaInfo.js, test/unit/dash.DashAdapter.js, test/unit/dash.models.DashManifestModel.js, test/unit/mocks/AdapterMock.js, test/unit/mocks/DashManifestModelMock.js, test/unit/streaming.Stream.js, test/unit/streaming.controllers.AbrControllerSpec.js
Hi,
this PR is a first step in order to isolate properly Dash "parser" classes as described in issue #2550.
- Remove mutual dependancy between dashManifestModel and dashAdapter
- Remove mediaController reference in dashAdapter
Nico
=> Remove mutual dependancy

src/dash/DashAdapter.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/EventController.js, test/unit/dash.DashAdapter.js
Changed the string used to identify incoming `eventStreams` in order to correctly handle multiple simultaneous events with different `value`s. fixing issue #2877.
=> A fix for issue #2877

src/streaming/models/VideoModel.js
Following @chevonc suggestion (#2873), this PR changes the way Promises support is checked in dash.js to support cases in which dash.js is bundled with a Promises library different than the native one.
=> Change the way Promises support is checked

src/dash/DashHandler.js, src/streaming/controllers/ScheduleController.js
Hi,
this PR has to solve issue #2911. When a track switch, with the need to reset buffer, occurs, ScheduleController has to wait that the reset process is over before doing another track switch.
@BucherTomas, could you, please, take a look at it and make me a feedback?
Thanks,
Nico
=> protect track switch

src/streaming/protection/controllers/ProtectionController.js, src/streaming/utils/LiveEdgeFinder.js
Fix how dash.js manages timeout of license requests. 
In this same PR I am fixing an issue I could reproduce quite sporadically related with live streaming playback. In one of my test streams sometimes getLiveEdge is called while DVRInfo is still not set what raised an exception.
=> Fix how timeout is handle in license requests

samples/dash-if-reference-player/app/sources.json
This PR allows some streams to be used when the client page is in https. At the moment, because of mixed content rule, many streams are not playable.
I have also tested the status (OK, NOK) of all test streams (sources.json and dashjs.json) with some remarks. It can be useful to clean up the list of streams. Some streams could simply be accessible in https and some manifests could be updated to use a <BaseUrl> in https too.
I have noticed that many live streams are stil broken in Chrome because of this issue #93 (MseBufferByPts feature not enabled by default)
See the results in this excel file (two sheets, one for sources.json streams and one for dashjs test vectors)
[Test_Streams_Status.xlsx](https://github.com/Dash-Industry-Forum/dash.js/files/2807155/Test_Streams_Status.xlsx)
=> switch MPD urls to protocol relative when available in https

src/streaming/controllers/ScheduleController.js, src/streaming/models/FragmentModel.js
Hi,
this PR has to solve issue #2937 by removing requests after a specific time only if the start time is less than this specific time.
In this issue, when the stream is reloaded the same request(audio or video) is downloaded, pushed and finally removed in an infinite loop.
@richardbushell, could you, please, take a look at this PR? Thanks
Nico
=> Regression bug fix

src/dash/models/DashManifestModel.js
play a live stream and watch below expressions in the debug console
```
document.getElementsByTagName('video')[0].duration
document.getElementsByTagName('video')[0].seekable.start(0)
document.getElementsByTagName('video')[0].seekable.end(0)
```
current: 
duration = 9007199254740991
start = 0
end = 9007199254740991
It does not follow the DVR window.
ref: https://bugs.chromium.org/p/chromium/issues/detail?id=623698
setLiveSeekableRange is ignored if the duration is not +Infinity.
https://github.com/Dash-Industry-Forum/dash.js/blob/548148bef7dd39c28f02992ffb0af147a7a85dc8/src/dash/models/DashManifestModel.js#L358-L369
It return Number.MAX_SAFE_INTEGER and set video duration = 9007199254740991, hence setLiveSeekableRange  is not working
```
function getDuration(manifest) {
let mpdDuration; …
```
=> fix for setLiveSeekableRange

src/streaming/protection/drm/KeySystemPlayReady.js, test/unit/streaming.protection.drm.KeySystemPlayReady.js
Some Playready 2.5 CDMs output the challenge part directly; 'PlayreadyKeyMessage' tag is not included in the key message.
JS player should check for 'PlayreadyKeyMessage' and do the base64 decoding if the tag is present. If it's not found, message should be
passed to the license server.
Also, the content-type header should use utf-8 or utf-16; utf8 & utf16 are not valid encoding types.
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>
=> fix for Playready Key message format parsing.

src/dash/models/DashManifestModel.js
Fix #2965 
Before this PR, it was not allowed defining an initialization segment using both a url and range.
=> Fix bug when parsing range of initialization segment

index.d.ts, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/controllers/ProtectionKeyController.js
This PR:
- adds a method to the ProtectionController to enable filtering and reorder key systems prioritization at application level
- reverts PR #2770 and then PR #2318 by considering all key systems declared in mpd (even if no pssh is provided)
This PR follows the conversation we have in issue #2249.
Then with the help of this PR, ClearKey protected content mentionned in #2249 can be supported by dash.js if we do explicitely consider only ClearKey key systems at application level.
This could be achieved this way:
```
var keySystems = player.getProtectionController().getKeySystems();
keySystems = keySystems.filter(keySystem => {
return (keySystem.systemString.indexOf('clearkey') > 0);
});
player.getProtectionController().setKeySystems(keySystems);
```
@JohnIball and @Murmur could you try …
=> Add possibility to filter and reorder key systems prioritization order at application level

contrib/akamai/controlbar/ControlBar.js, contrib/akamai/controlbar/controlbar.css, samples/control/controlbar.html
Current time set to display, in live, coherent values.
LiveThreshold set to 12 secs
=> Added live indicator to controlbar.

src/streaming/Stream.js
When stopping a stream, the event controller (and thus its timer) is never stopped.
Thus, we do create as many timers (with a 100ms interval) as loaded streams.
This PR fixes this issue.
=> Stop EventController

src/dash/DashMetrics.js, src/streaming/Stream.js
Hi,
this PR has to solve regression #2966 introduced by myself in PR #2881. This previous PR aimed to remove dependancy between dashAdapter and MediaController. The problem is that the first selected track is not set by function setCurrentMediaInfo because processors are not created at this specific time.
There is still an issue after this new PR that refer to issue #2970.... :-(
@sgadrat-anevia, could you, please, take a look at this PR?
Thanks,
Nico
=> Audio Bug fix

src/streaming/PreBufferSink.js, src/streaming/SourceBufferSink.js, src/streaming/controllers/BufferController.js
In BufferController, when seeking, a segment may being appended into the buffer.
Therefore if we do prune the buffer before the current segment appending process is completed, then the range to be removed is erroneous (does not take into account current segment being appended).
This can have side effects and leads to playback freeze.
On some devices, appending process can take a relatively long time and can more easily highlight this issue.
This PR attempts to fix this issue by waiting for segment appending process to be completed before pruning the buffer at seeking.
=> Fix seeking issue

src/streaming/PreBufferSink.js, src/streaming/Stream.js
Hi,
this PR has to solve a regression of preload mode. The main issue was that getBuffer function was not defined in PreBufferSink class. The second one was that the video StreamProcessor wasn't created because video element is undefined in this use case.
So, it solves issue #2984. @bknill, could you, please, take a look at it?
Nico
=> preload regression fix

src/streaming/text/TextTracks.js
When resizing the player while captions are rendered, it may occur that two DIV elements with the same ID are rendered at the same time. Both contain the same caption/text but one is for the previous player size and the other one for the new player size. The `cue.onexit()` method should remove all child nodes having a given cueID but the for loop used to remove those child nodes does not adjust the index variable when an element with this given ID is found and removed. As a result, the next child node is skipped. This PR is for a small patch that fixes the issue.
=> Fix cleaning of caption divs

index.d.ts
Error message: `'setMinAllowedBitrateFor', which lacks return-type annotation, implicitly has an 'any' return type.`
Related issue: #2918 also please check @raskri last comment
=> Fix annoying typings error

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/streaming/controllers/AbrController.js
Before the fix:
- set min allowed bitrate on player, for example 500kb/s
- start a new stream
- ABR controller selects highest quality as initial bitrate, for example 2Mb/s, since previous bitrate stored in local storage is high
=> then at first pass in ABR controller before downloading 1st video segment:
- no rule is applied
- a switch request with NO_CHANGE quality (=-1) is applied
- this quality (-1) is compared to min allowed quality
- since -1 < min allowed quality, min allowed quality is selected instead of highest quality
This PR fixes this issue.
Additionnaly, this PR adds the possibility to set min and max video bitrate in the options of the dash-if-reference-player sample webapp.
And it fixes also the assignement of ABR settings in the webapp.
=> Fix ABR controller if min allowed bitrate is set

src/dash/DashHandler.js, src/dash/controllers/SegmentsController.js
In DashHandler.setup(), StreamProcessor isn't available, so isDynamic() returns null.
This means the getters in segmentController were being generated with isDynamic set to null, so they would act as though the manifest was static and take the segment availablility as being the same as the manifest availablility.
https://github.com/Dash-Industry-Forum/dash.js/blob/18647a32064feec61ca33438eb16bfb0319232a4/src/dash/controllers/SegmentsController.js#L58
This fixes the problem by moving the isDynamic() call to initialize instead.
This is a fix for #3008
=> Stop the player from streaming past the availability range

src/streaming/Stream.js, src/streaming/controllers/ScheduleController.js, src/streaming/rules/scheduling/BufferLevelRule.js
Hi,
this PR has to solve two different issues about the management of fragmented subtitles. First issue can be reproduced by loading the stream https://livesim.dashif.org/dash/vod/testpic_2s/multi_subs.mpd. If the user seeks to a random position, and then change the language of the selected subtitle track, dash.js was downloading all the segments of the new track from the begining not from the current time.
Second issue can also be reproduced, with Prince of Persia MSS stream. The user can't switch between two subtitles languages.
Nico
=> Fragmented text bug fix

contrib/akamai/controlbar/ControlBar.js, src/streaming/controllers/PlaybackController.js
Hi,
this PR has to add a workaround to issue #3042. For static stream use case, if the user wants to seek to a time before the common earliest time (Audio and Video), the seek value will be replaced by this common time.
@tomraut , could you, please, take a look?
Nico
=> Seek value bug fix

src/streaming/controllers/EventController.js
Hi,
This is a fix for an issue where the array of pending media events would at no point remove events with a start time (presentation time) in the past. If an event stuck in this state repeats (for example with a looping pseudo-live MPEG-DASH stream) then future instances of this event would be discarded without being triggered.
Joe
=> Events with a presentationTime in the past are now removed.

samples/dash-if-reference-player/app/sources.json, src/mss/parser/MssParser.js
This PR integrates automatic buffers configuration according to live delay for MSS live streams, thus avoiding Precondition failed (412) errors.
Thanks to this PR you do not need anymore to provide live delay and buffes length configuration when loading a live MSS stream, except if you want a live delay different from default one (= segment duration x 4)
=> [MSS] Auto buffers length configuration for live streams

src/streaming/controllers/StreamController.js
Fix for bug where StreamController.reset() is called but event handler is called after the reset and mediasource.readystate is no longer open.
Playback fails with:
Uncaught DOMException: Failed to set the 'duration' property on 'MediaSource': The MediaSource's readyState is not 'open'
=> Error on setMediaDuration when mediasource readyState != 'open'

src/dash/utils/TimelineSegmentsGetter.js
Hi,
this PR has to solve issue #3056. The static stream (SegmentTimeline) has segments duration less than 0.5 second. So, the function getSegmentByIndex can't use 0.5 value to detect segment index : an infinite loop is started in this case.
@jeffcunat and I propose to replace the value 0.5 by half the duration of the previous segment (largest possible deviation is 50% of segment duration).
@sinjuice, could you, please, take a look at this PR?
Thanks,
Nico
=> Update getSegmentByIndex function in TimelineSegmentsGetter class

src/mss/parser/MssParser.js, src/streaming/MediaPlayer.js
fix problem related to #3051 
Old settings configuration was wrongly used instead of the new v3 settings configuration system
=> [MSS] use new settings system for MSSParser buffer  configuration

src/streaming/text/TextSourceBuffer.js, src/streaming/text/TextTracks.js
Fix for #3054 - Subs use up all memory
When the embedded subs are added there's no method to clear them out again. If you run a stream like the one on 3054 you can have a lot of subs in the text track, and if on Edge, there's a corresponding htmlElement for each one.
This PR watches for buffer cleared events and clears out any embedded subs between those times to keep the list small.
=> Clean out embedded subs with the video buffer pruning

Gruntfile.js
When updating grunt dependencies to latest one available in #2848, a regression on sourcemaps has been introduced.
As mentioned in [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify) documentation, sourceMapIncludeSources and sourceMapRoot options has been deprecated.
This PR should allow again debugging with breakpoints with sourcemaps
Related original issue : #977
=> Fix sourcemaps not including sources anymore

src/dash/DashAdapter.js, src/dash/constants/DashConstants.js, src/dash/models/DashManifestModel.js, src/streaming/MediaPlayerEvents.js, src/streaming/Stream.js, src/streaming/constants/Constants.js, src/streaming/controllers/PlaybackController.js, test/unit/dash.DashAdapter.js
Support for DVB-DASH LL streams, in which low latency configuration is announced in the stream manifest through the use of ServiceDescription and SupplementalProperty elements.
Dash.js now supports extracting all this information from the manifest and applies it right before the adaptationSet which includes SupplementalProperties is going to be loaded.
=> Support Service Description for DVB-DASH LL

src/dash/SegmentBaseLoader.js
Hi,
this PR has to solve issue with Segment base stream with 3.0 version. The [stream ](https://dash.akamaized.net/dash264/TestCases/1a/sony/SNE_DASH_SD_CASE1A_REVISED.mpd) can be used to reproduce the issue. 
We can see that for some representations, segments are not in the correct order. So, when the player call the getNextFragment, it's not the good segment that is returned. Indeed, if the current fragment has index 24 for time 0:56 , the next one, with index 25 may be at time 2:20.....
I can't explain now, why the issue didn't appear with 2.9.3....If someone can help me.... ;-)
Nico
=> Fix segment base issue

index.d.ts
The current definition of `MediaPlayerSettingClass` included in `index.d.ts` file causes that the TypeScript transpiler ask you to define the whole object while calling to `updateSettings` method of the `MediaPlayerClass`.
According to the documentation (http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html):
> updateSettings(settingsObj)
> **Update the current settings object being used on the player. Anything left unspecified is not modified.**
> 
> This function does not update the entire object, only properties in the passed in object are updated.
This PR set all the parameters of `MediaPlayerSettingClass` as optional parameters, so the user is able to define only the parameters s/he want to change.
=> types: allowing partial definition of setting obj

src/streaming/controllers/BufferController.js
Hi,
this PR has to solve issue #3098. As described in this issue, the ended event is not triggered by the video element when the auto loop option is disabled. When the signalEndOfStream function of MediaSourceController is called, buffers are empty. So, what I want to add in the code is to not trigger BUFFERING_COMPLETED event if buffer is empty.
Nico
=> ended event bug fix

src/mss/parser/MssParser.js
According to the MSDN specification (https://msdn.microsoft.com/en-us/library/ff469578.aspx), if the DVRWindowLength field is omitted for a live presentation or set to 0, the DVR window is effectively infinite.
=> [MSS] fix missing DVRWindowLength for live streams

src/streaming/rules/abr/AbandonRequestsRule.js
This PR fixes the AbandonRequestRule that ignores the min allowed bit rate when switching down the quality
=> Fix abandon switch request if min bit rate is set

contrib/akamai/controlbar/ControlBar.js, src/streaming/controllers/PlaybackController.js
Hi,
this PR has to solve issue #3104 by removing async word in ControlBar.js and replacing find function in PlaybackController by a for loop. Both functions are not available in IE11.
Nico
=> Fix IE11 issue

index.d.ts, src/streaming/protection/controllers/ProtectionController.js
The goal of this PR is to enable the key systems selection process to request the key systems access in a given priority order.
By default, in dash.js the key systems order is pre-defined in ProtectionKeyController:
https://github.com/Dash-Industry-Forum/dash.js/blob/f4418b56213e4d5889d9eb0b15074e45c42b7bb8/src/streaming/protection/controllers/ProtectionKeyController.js#L72))
As a use case, on some devices you may have 2 different available CDMs, and for a specific service you would require dash.js to select the second one in the pre-defined order.
Thus the user can set the priority in the protectionData in order to force dash.js selecting the key systems in the user-defined order.
For example, if you provide the following protectionData:
{
"serverURL": …
=> Key system priority

src/dash/DashHandler.js
Hi,
this PR has to update PR #3105 that included a regression about media finished detection. In dynamic manifest use case, dashHandler has to keep segmentIndex unchanged if no request has been found. In static manifest, in order to detect media finished status, segmentIndex has to be increased by one to be equals or greater than availableSegmentsNumber.
So, the stream [https://livesim.dashif.org/livesim/modulo_10/testpic_2s/Manifest.mpd](https://livesim.dashif.org/livesim/modulo_10/testpic_2s/Manifest.mpd) can be used to test that the previsous PR is always solved by this new PR. The first VOD stream in the sample page can be used to be sure that the end of the stream is correctly detected.
Nico
=> fix issue about media finished detection

contrib/akamai/controlbar/ControlBar.js
Remove seek to live on duration updatein sample application.
For each live stream, as soon as the first segment is pushed and thus the &lt;video&gt; duration is updated, a new seek is performed to end of segment (=duration). Thus first image is freezed, and loading/zapping time is increased (wait for more segment to be loaded).
@gitperonam Why did you introduced this seek to live on duration update?
=> Fix sample control bar

src/dash/DashMetrics.js, src/streaming/models/MetricsModel.js, src/streaming/vo/metrics/HTTPRequest.js
The segment quality information in HTTPRequest metrics can be useful at application level.
For example, we can compare the real encoding bit rate of a segment regarding the theoretical bit rate as indicated in the manifest.
=> Add segment quality in HTTPRequest metrics

src/streaming/protection/drm/KeySystemPlayReady.js, test/unit/streaming.protection.drm.KeySystemPlayReady.js
=> Fix PlayReady challenge format

src/streaming/net/HTTPLoader.js
When the AbandonRequestRule calls abandon on a segment load, it enqueues two segment replacement requests in ScheduleController (and re-loads the same segment at the lower quality twice). This is because the onAbort callback for HTTPLoader is called twice, once through the XHRLoader with `x.loader.abort(x)`, and again on `x.onabort()`.
So this PR removes the second x.onabort call.
=> onabort callback for HTTPLoader is called twice

src/dash/utils/TemplateSegmentsGetter.js, test/unit/dash.utils.TemplateSegmentsGetter.js
When replacement fragments are requested by ScheduleController, they flow into the getSegmentsForTime function in the templateSegmentsGetter. This function is returning indicies off by one, so replacement fragments would be ordered for the segment before what was wanted.
To reproduce:
Invoke a replacement by suddenly throttling and getting the abandon rule to abandon a high quality segment.
See that the replacement segment ordered is one segment early.
This PR removes the -1 that made the calculation from time incorrect.
=> getSegmentForTime is returning indicies off by one segment

src/dash/DashHandler.js
As 'getTimeBasedSegment' returns null if isSegmentAvailable is false,   
so segments' length could be smaller than fragments' length,  
then exception occurs here. 
This issue could be tested with video source 'https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd'
=> Play failed when some segments unavailable

src/streaming/controllers/PlaybackController.js
For live streams with SegmentTimeline thus manifest refreshes, when manifest is updated, the player checks if current playback time is not anterior to DVR window start, and then it seeks to DVR window start (I guess to ensure to download and play available segments)
However, when loading the stream, if manifest is first updated before live is started (currentTime still equal to 0) then a seek to DVR window start is performed.
This PR fixes this issue by ignoring DVR window resynchronization if stream is not started yet.
=> Fix starting of live streams with SegmentTimeline

src/streaming/controllers/PlaybackController.js
This solves issue https://github.com/Dash-Industry-Forum/dash.js/issues/2993
=> [Fix] Avoid jumps in the livestream when an incorrect currentTime is reported by video element

src/streaming/controllers/BufferController.js
Hi,
this PR has to solve issue #3010. The main problem is that when video buffer is cleared, metrics are not updated immediately. So, when scheduleController asks BufferLevelRule in order to know if new segments have to be requested, the rule returns that buffer is enough filled : wrong answer!
In this specific use case, buffer level metric is never updated at all, ScheduleController is not stopped but no new segment is requested because of the returned value by BufferLevelRule.
@budziq, could you, please, test on your side this fix?
Nico
=> Update buffer level metrics

samples/dash-if-reference-player/app/sources.json
by providing https licenser server URL
=> avoid Edge mixed-content Security issue 

index.d.ts, src/streaming/protection/vo/ProtectionData.js
Hi,
this PR has to solve issue #3156.
@mcereijo, could you, please, take a look?
Nico
=> Remove default value in typeScript

src/dash/utils/SegmentsUtils.js
Hi 
This PR solves the issue #3083.
The pb was that introduced function in 3.0.0, SegmentUtils::isSegmentAvailable was returning false in case of multiperiod streams if segment time was not found in current period. For live streams, play was never started, because no request was available  at startTime
Jérémie
=> Fix Issue #3083 for live streams with multiperiod.

src/streaming/MediaPlayer.js, src/streaming/controllers/MediaController.js, test/unit/streaming.controllers.MediaController.js
We can set a specific initial lang but in some cases (legacy manifest cases), a same audio track could be identified by two different langs.
In our case, our legacy manifests use `fr` or `vf` lang where our newest manifests use `lv` which stands for local version.
On the player side, the goal is to always start with the local language version (even if the user has changed it on a previous video).
This PR adds the capability to match the lang which a regex, in our case `/fr|vf|lv/`.
That change doesn't introduce a BC on the API, we can still use a classic string to match.
=> feat capability to match lang regex for initial settings

src/streaming/controllers/PlaybackController.js, test/unit/mocks/URIFragmentModelMock.js, test/unit/streaming.controllers.PlaybackControllers.js
Hi,
this PR has to solve regression issue #3136 . As this parameter is used like liveDelay settings, playbackController has to use it in computeLiveDelay function.
Nico
=> fix for 'r' parameter in uri

src/dash/SegmentBaseLoader.js, src/streaming/controllers/BufferController.js
Hi,
this PR has to resolve issue #2840 by reseting seekStartTime value in all cases when the stream begins to play. In this specific use case (SegmentBase multi period), no internal seek is done to start, for instance, the second period. The seekStartTime value is still 30.03s. the getWorkingTime function always returns 30.03s. BufferLevelRule doesn't have correct informations to decide or not to request new segment.
@niralipatelgoogle, I know this issue is open for a long time, but it would be great if you can take a look at this fix. Thank you! 
Nico
=> SegmentBase Multi period bug fix

src/mss/parser/MssParser.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/ScheduleController.js
Hi,
this PR has to avoid to push two initialize segments one after the other without any media segment between them.
It occurs, in ScheduleController, due to a call to checkPlaybackQuality of PlaybackController even if the last requested segment is a initialize one.
The issue can occured with the default stream in the sample page with debug log level.
Nico
=> Update schedule controller

src/streaming/net/FetchLoader.js
The FetchLoader() currently only adds '\n' which results in a concatenated headers string that is not the same as that produced by XMLHttpRequest() and thus not correctly parsed by the DashMetrics.parseResponseHeaders() function (https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/dash/DashMetrics.js#L434)
=> Fix bug: Headers string not appending \r 

src/mss/parser/MssParser.js
This PR addresses the issue described here: https://github.com/Dash-Industry-Forum/dash.js/issues/3187
=>  fix: use fallback ID if Name is undefined

src/streaming/models/VideoModel.js, src/streaming/text/TextTracks.js
Hi,
this PR has to not always create a new text track on the html5 video element when a new stream is loaded. Unfortunately, text track can't be removed.
The idea is, when a creation is asked, to detect if this kind of track (same label, same kind, etc....) has been already created. If it's true, this track is returned, otherwise a new track is really created.
does it solve issues #1294, #1394? @davemevans if you can take a look......thanks! ;-)
Nico
=> Update text track management

src/core/events/CoreEvents.js, src/dash/DashHandler.js, src/dash/SegmentBaseLoader.js, src/dash/WebmSegmentBaseLoader.js, src/dash/controllers/SegmentBaseController.js, src/dash/controllers/SegmentsController.js, src/streaming/MediaPlayer.js, src/streaming/StreamProcessor.js, src/streaming/thumbnail/ThumbnailTracks.js, src/streaming/vo/FragmentRequest.js, src/streaming/vo/HeadRequest.js, test/unit/dash.SegmentBaseLoader.js, test/unit/dash.WebSegmentBaseLoader.js
Hi,
this PR has to create a new static class, named SegmentBaseController, that has to send request to get init or media segments list in SegmentBase use case.
The idea is to isolate this part of code in order to have in SegmentController only functions to get segment (with time or id) without any network access. In SegmentBase use case, the SegmentController will trigger an event that will be catched by SegmentBaseController to send requests.
In ThumbnailTracks, SegmentBaseLoader was used, I updated this part of code but no tests have been made because the sample stream is not available. :-(
Nico
=> Add SegmentBaseController

index.d.ts
The `LogLevel` enum defined in `index.d.ts` declares an enum that is not exported from dash.js, so any references to `LogLevel` will pass compilation but fail runtime. 
By declaring this enum as `const enum` the value is inlined during compilation, removing any references to LogLevel in the compiled JavaScript. 
See https://basarat.gitbooks.io/typescript/content/docs/enums.html#const-enums for more info.
=> types: define enum LogLevel as const

index.d.ts, src/dash/DashMetrics.js, src/streaming/MediaPlayer.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/ScheduleController.js, src/streaming/models/CmcdModel.js, src/streaming/rules/abr/AbandonRequestsRule.js, src/streaming/rules/abr/BolaRule.js, src/streaming/rules/abr/InsufficientBufferRule.js, src/streaming/rules/abr/ThroughputRule.js, src/streaming/rules/scheduling/BufferLevelRule.js, test/unit/dash.DashMetrics.js, test/unit/mocks/DashMetricsMock.js
The goal of PR is to fix the DashMetrics class and its type declaration:
- add the method getCurrentBufferState()
- remove the method getLatestBufferInfoVO
- update types declaration
Questions (@epiclabsDASH ?):
- what's the use for the readonly parameter in DashMetrics methods? From outside dash.js, shouldn't it always be fixed to 'true'?
- why the input media type for DashMetrics methods is only either 'video', 'audio', or 'image'?
- more generally, in types declaration file, in many methods all possible media types are described (for example `type: 'video' | 'audio' | 'fragmentedText'`). why not declaring a general type "MediaType", to be used by all methods?
=> DashMetrics

samples/dash-if-reference-player/dashjs_config.json, src/core/Settings.js, src/mss/parser/MssParser.js, src/streaming/controllers/PlaybackController.js, test/unit/streaming.MediaPlayer.js
This PR changes the priority of the live delay calculation to the following descending order 
1. If low latency enabled set delay to 0
2. If live delay was set by the user use this value
3. If live delay fragment count was set by the user use this value
4. If r parameter is present in the url use this parameter
5. If suggestedPresentationDelay in included in the MPD use this value
6. If fragment duration is available use 4*fragment duration
7. Otherwise use minBufferTime*2
This PR also related to a fix applied regarding the suggestedPresentationDelay : https://github.com/Dash-Industry-Forum/dash.js/pull/3199
=> Bugfix live edge calculation

src/streaming/controllers/BufferController.js, src/streaming/controllers/ScheduleController.js
In ScheduleController there is a mechanism to restart the scheduler once buffer has been pruned in case of QuotaExceededError.
But scheduler may have been stopped for some other reasons/errors, for example if BaseURL resolution failed (after a segment download error for example).
And since there is a buffer pruning timer (every 10sec by default, see bufferPruningInterval parameter) then the scheduler was also restarted in this case, which is not the desired behavior.
We want the scheduler to restart automatically only after QuotaExceedeError.
This PR fixes this issue.
=> Restart ScheduleController once buffer is pruned only after QuotaExceedeError

src/streaming/controllers/ScheduleController.js
Improve the live startup logic: If the ScheduleController can not create a request object at the targeted live edge it should not start from the beginning but rather iterate through the DVR window to generate a valid segment request.
=> Feature live edge target

src/streaming/models/VideoModel.js
resolving an issue where if the user places the video element that dashjs is attached to inside a shadow dom at its root, it will throw an error.
this error is caused by the captions trying to use getBoundingClientRect() on the parent and in this case that will be a document fragment where getBoundingClientRect() will not be accessible.
the applied fix is to return the host value of the parent if available; which will instead return the web component node and then if host is not found fallback to the just the normal parentNode
=> adding fix for when using web components

test/functional/config/browsers/windows.js, test/functional/readme.md, test/functional/selenium/Win10nodeConfig.json, test/functional/selenium/startClient.bat
-Dwebdriver.edge.driver="msedgedriver.exe"
needs to point at correct Driver(correct version etc.)
For Legacy Edge Version 18 and 19, the Driver is a FOD for Windows and therefore
you dont need to point to the driver, but you need to delete the MicrosoftWebDriver.exe from the folder.
=> Edge Functional Tests

src/streaming/net/FetchLoader.js
Added missing `signal.onabort` in Fetch AbortController setup. The required onabort action to be called is the httpRequest.onabort() handler which deals with the abort cleanup and re-start logic for the media - as perfomed by the XHRLoader.
It leads to a question about how one handles the [legacy?] Chrome behaviour - see Pull Request:
https://github.com/Dash-Industry-Forum/dash.js/pull/3235
=> Add signal.onabort handler to AbortController

src/streaming/net/FetchLoader.js
Add onabort handling to the [legacy?] Chrome behaviour, or the code could be removed.
=> Add onabort handler to legacy Chrome abort code path

package.json, src/core/Version.js, src/streaming/protection/CommonEncryption.js, test/unit/streaming.protection.CommonEncryption.js
Remove newlines and whitespaces from the pssh string to avoid running into an infinite loop
=> Fix pssh parsing

index.d.ts, src/dash/DashAdapter.js, src/dash/parser/DashParser.js
...  in order to enable protocol detection once stream is loaded (to distinguish DASH from MSS streams):
`mediaPlayer.getActiveStream().getStreamInfo().manifestInfo.protocol`
=> Add protocol in stream's manifestInfo

src/streaming/rules/ThroughputHistory.js
The current `getSampleSize()` function expands the `sampleSize` based on checking the variance of subsequent samples from the beginning, but does so in the opposite order to which `getAverageSlidingWindow()` actually uses the resulting samples - which takes those from the end. This fix corrects the check so that it operates from the end(newest) items of the queue backwards.
=> Reverse order of samplesize variance test to match usage

src/core/events/CoreEvents.js, src/dash/DashHandler.js, src/dash/constants/DashConstants.js, src/streaming/ManifestUpdater.js
Add support for transition phase between live and on-demand streams (see IOP section 4.6.4)
See issue #3263
=> Add support for transition phase between live and on-demand streams 

samples/captioning/multi-track-captions.html, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/streaming/MediaPlayer.js, src/streaming/controllers/MediaController.js, src/streaming/text/TextController.js, test/unit/mocks/MediaControllerMock.js, test/unit/streaming.MediaPlayer.js, test/unit/streaming.text.TextController.js
This PR will make setInitialMediaSettingsFor compatible with fragmentedText (like it is done with audio and video)
For example : 
```
player.setInitialMediaSettingsFor('fragmentedText', { 
lang: 'en',
role: 'caption'
});
```
This is useful to initialize the player for users that want to activate closed captions by default if they are present.
We are using the mediaController.matchSettings method inside the TextController to reuse the same mechanism than for audio and video.
We can keep the setTextDefaultLanguage method for backward compatibility but 
`player.setInitialMediaSettingsFor('fragmentedText', { lang: 'en' });` is equivalent to `player.setTextDefaultLanguage('en')`
=> allow setInitialMediaSettingsFor with fragmentedText media type

src/mss/MssHandler.js, src/mss/parser/MssParser.js
The goal of this PR is to restore live delay and buffer settings in case they are modified by MSS parser for live streams (for example to avoid 412 precondition failed errors)
=> [MSS] Restore default buffer settings

src/streaming/StreamProcessor.js, src/streaming/controllers/PlaybackController.js
Set live start time on PlaybackController according to video only timeline, to avoid requesting first staggered video and audio segments in case the audio and video segment timelines are staggered
=> Optimize live start

src/dash/controllers/RepresentationController.js, src/streaming/StreamProcessor.js
This PR fixes a regression introduced in v3.0.
Since v3.0, segments info lists are no more pre-computed, each segment info is now computed when requesting a segment.
As a consequence, segment duration for any representation is not set until a media segment is requested.
Since segmentDuration may be used prior to any media segment request (for example buffer target calculation for text tracks, or segment availability range computation), this leads to some dysfunction (for example text track switching for streams with SegmentTimeline).
=> Fix regression for representationInfo's segmentDuration

src/dash/controllers/RepresentationController.js, src/dash/models/DashManifestModel.js, src/streaming/StreamProcessor.js, test/unit/dash.models.DashManifestModel.js
This PR resolves issue mentioned in PR #3284, but more efficiently (segmentDuration is computed from SegmentTimeline in DashManifestModel)
=> Fix regression for representationInfo's segmentDuration (cont'd)

src/dash/controllers/RepresentationController.js, src/streaming/StreamProcessor.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, test/unit/streaming.controllers.PlaybackControllers.js
The goal of this PR is to fix/adjust live delay calculation:
- Fix live delay calculation for SegmentTimeline manifests for which no valid segment request could be generated with the initial live delay. Increase live delay until a valid segment is found instead of starting playback at the beginning of the DVR window
- When live delay is different from the value initially calculated by `computeLiveDelay` it gets adjusted in `StreamProcessor.findRequestForLiveEdge` -> `playbackController.setLiveDelay`
- If the live delay should be a multiple of the fragment duration use `@maxSegmentDuration` for multiperiod manifests. For single period manifests iterate through the available AdaptationSets and use the largest segment duration.
This PR is supposed to fix #3227 and #3146
Known Issues:
For …
=> Fix live delay computation

samples/captioning/caption_vtt.html, samples/captioning/multi-track-captions.html, samples/captioning/ttml-ebutt-sample.html, src/streaming/text/TextController.js, test/unit/streaming.text.TextController.js
As with PR #3245, we now disable text by default, we have introduced a regression. Using enableText(true) does nothing if setTextDefaultEnabled is not set to true.
This PR 
- fix this regression
- allows us to call enableText(true/false) even before text tracks are added
- enable text by default in sample multi-track-captions.html
=> Fix regression with enableText

src/core/events/CoreEvents.js, src/streaming/StreamProcessor.js, src/streaming/controllers/ScheduleController.js, src/streaming/text/NotFragmentedTextBufferController.js, test/unit/streaming.text.NotFragmentedTextBufferController.js
This PR Fixes a regression (since PR #3256) for non-embedded text tracks (displayed twice)
=> Fix regression for non-embedded text tracks

src/streaming/controllers/StreamController.js
Use max segment duration for single period manifests and live delay calculation
=> Feature use max segment duration

contrib/akamai/controlbar/ControlBar.js, index.d.ts, src/streaming/MediaPlayer.js, src/streaming/thumbnail/ThumbnailController.js, test/unit/streaming.thumbnail.ThumbnailController.js
Hi all
This PR make some improvements on thumbnails API. 
- Update index.d.ts file
- Rename getThumbnail by provideThumbnail : In some cases (SegmentBase for example), thumbnails are get in a asynchrounous way using callback. In some other cases, thumbnails are get in a synchronous way, using return of function. To uniformize the behaviour, thumbnails are always provided using a callback.
- Display thumbnails bitrate list in control bar (to test the fact we can choose thumbnails representation) 
Jérémie
=> Update thumbnails API

contrib/akamai/controlbar/ControlBar.js, src/streaming/MediaPlayer.js
Hi
This PR fixes problem on stream without thumbnails (regression of PR #3297)
Jérémie
=> Fix regression of PR #3297 about thumbnails

src/streaming/StreamProcessor.js
The goal of this PR is to fix #3224. Before this PR the seek target in the ScheduleController was reset regardless if a valid segment request could be generated or not. Now it is only reset if a request could be generated.
=> Only reset the seek target if a valid segment request has been found

contrib/akamai/controlbar/ControlBar.js
- document.exitFullscreen ->  document.fullscreenElement in exitFullscreen.
- document.exitFullscreen throws `TypeError: Document not active on exitFullscreen`
=> exitFullscreen ->  fullscreenElement

src/mss/MssFragmentMoovProcessor.js
To be confomed to ISO/IEC14496-12: "If the duration cannot be determined then duration is set to all 1s"
=> Fix moov duration fields

src/dash/utils/TimelineConverter.js
This PR enables calculating segment availability range according to effective segment timeline if timeShiftBufferDepth is not defined.
See issue #3263
=> Segment availability range if no timeShiftBufferDepth

src/streaming/controllers/StreamController.js
Fix regression for live delay computation, introduced in PR#3285: live delay was not computed in case start time was provided in uri parameters
=> Fix regression for live delay computation

samples/dash-if-reference-player/dashjs_config.json, src/core/Settings.js, src/streaming/controllers/PlaybackController.js, src/streaming/models/MediaPlayerModel.js, test/unit/streaming.models.MediaPlayerModel.js
The goal of this PR is to address the problem described in #3300 . The idea is to define a threshold for which the low latency catchup mechanism is activated. The threshold can be defined via the Settings object. If no threshold is specified by the user, the default value will be targetLatency * 2.
=> Define a threshold which controls catchup mechanism for low latency streaming

src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js, src/streaming/text/NotFragmentedTextBufferController.js, src/streaming/text/TextBufferController.js, test/unit/streaming.controllers.PlaybackControllers.js
This PR intends to refactor and simplify streams playback start process:
- always use seeking process from PlaybackController to seek controllersevent for initial playback start
- adjust seek time in BufferController according to effective appended ranges (in case of misalignement between manifest and coded fragments)
The changes are illustrated in following sequence diagram: https://sketchboard.me/nCcqJmksDzlb#/
=> Refactor streams playback start

src/streaming/Stream.js, src/streaming/controllers/PlaybackController.js
=> Playback start for SegmentBase streams

src/streaming/controllers/BufferController.js, src/streaming/rules/abr/InsufficientBufferRule.js, test/unit/streaming.rules.abr.InsufficientBufferRule.js
Seeking is causing problems with the insufficient buffer rule and causing the quality to drop to 0 occasionally on seek - This PR:
1. Prevents the rules being asked in ScheduleController when 'pruning is in progress' because we discard the result anyway in this case.
2. Changes the insufficient buffer rule to not clear the flag based on getMaxIndex() being called, so there's no side effects for this function if we discard the result.
3. Set the limit to two fragments instead of just one, for cases where we seek very close to the edge of fragment and lose the buffer.
You can test seeking close to segment boundaries with this on big buck bunny:
http://reference.dashif.org/dash.js/v2.9.1/samples/dash-if-reference-player/index.html
`$('video')[0].currentTime = -0.1 + 4 * 20`
=> Fixes for Insufficient buffer rule seek reset

src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js
Following PR #3308, this PR resolves live seeking for non-modern browsers for which seeking at a time on video element fails when there is no buffered data at requested time.
Data requires to be buffered first, before seeking video element to original seek target time
=> Live seeking

contrib/akamai/controlbar/ControlBar.js, samples/captioning/multi-track-captions.html, src/streaming/Stream.js, src/streaming/controllers/MediaController.js, src/streaming/text/TextController.js, test/unit/mocks/MediaControllerMock.js, test/unit/streaming.text.TextController.js
fragmentedText initial settings were already stored in localStorage but never used.
This PR allows to reuse previous subtitles settings stored in localStorage.
They are only used when loading a stream if
- settings streaming.lastMediaSettingsCachingInfo.enabled is true
- textDefaultEnabled is not explicitly false (can be undefined if setTextDefaultEnabled is not called)
- setInitialMediaSettingsFor('fragmentedText') has not been called to set preferred language and/or role
This means that, if no other settings are set, dash.js player will reuse previously used subtitles language/role when loading a new stream (like what is already done for audio content)
samples/captioning/multi-track-captions.html has been modified in order to test various settings combination (no more auto-load to be …
=> Store and use fragmentedText settings in localStorage

src/dash/controllers/RepresentationController.js, src/streaming/controllers/PlaybackController.js
The goal of this PR is to consider multiperiod manifests when updating the representations in the RepresentationController. The update of the Representations is postponed whenever live delay is larger than availwindow.end - availwindow.start. 
However, for multiperiod we might still be playing in the previous period when a new period is introduced and the respective RepresentationController updates the representations. Live delay might be too large so we need to consider the currently playing period as starttime anchor: Math.min(availwindow.start,currenttime)
=> Fix multiperiod representation update

index.d.ts, src/streaming/MediaPlayer.js, src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/protection/drm/KeySystemClearKey.js, src/streaming/protection/drm/KeySystemW3CClearKey.js
to fix #3349 
A new ProtectionDataSet interface is defined
ProtectionData will still describe protection data for a given key system (still used in ProtectionModel.js)
https://github.com/Dash-Industry-Forum/dash.js/blob/32b50c62aa2d5d2d127add3a7916536d5c4dbf80/src/streaming/protection/models/ProtectionModel.js#L116
=> fix ts definition for setProtectionData

src/streaming/controllers/PlaybackController.js
Instead of seeking to DVR window start which might not be in the buffer anymore at this time, seek to DVRwindow.end - liveDelay
=> Adjust seeking when the player is outside of the DVR window

src/streaming/Stream.js, src/streaming/controllers/FragmentController.js
This PR fixes the issue #3361.
There are as many FragmentController as periods in the manifest and they all reacted to Events.FRAGMENT_LOADING_COMPLETED. 
With this PR the streamInfo.id is stored in the FragmentController and now it only reacts to the events with the corresponding stream id.
=> fix multiple subtitles displayed for multiperiod streams

src/dash/DashAdapter.js, src/streaming/vo/IsoBox.js
This is to support https://github.com/Dash-Industry-Forum/dash.js/issues/3196. 
I have included a [test package](https://github.com/Dash-Industry-Forum/dash.js/files/4886180/testdata_for_3196.zip), which contains MPEG-DASH audio and video media segments with inband (embedded) version 1 `emsg` data in the video fragmented media segments. Each media segment is 2 seconds long. There are 25 segments for each representation (and, therefore, 50 seconds of playback.) Each fragmented media segment contains 4 `emsg` event boxes.
=> Initial commit to support version 1 events.

samples/dash-if-reference-player/dashjs_config.json, samples/offline/dashjs_config.json, src/core/Settings.js, src/dash/DashHandler.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js, src/streaming/models/FragmentModel.js, src/streaming/text/TextController.js, test/unit/Streaming.StreamProcessor.js
The goal of this PR is:
- to fix next segment request determination after buffer has been pruned, due to QuotaExceededError or automatic pruning process (bug existing since v3.0)
-  to update buffer lengths according to critical buffer size
- to prune buffer only beyond new buffer limits (instead of clearing all buffer) when a QuotaExceededError happended
BTW, I wonder about use of bufferAheadToKeep parameter. If one sets bufferAheadToKeep lower than bufferTimeAtTopQuality(LongForm) then the buffer will always be pruned before reaching buffer length.
Also, since bufferTimeAtTopQuality(LongForm) is used as a limit to append new segments, I don't get the need for bufferAheadToKeep parameter.
=> Fix buffer pruning

src/streaming/protection/CommonEncryption.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/protection/drm/KeySystem.js, src/streaming/protection/drm/KeySystemClearKey.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js, src/streaming/protection/servers/ClearKey.js
=> Feature clearkey by server

src/streaming/utils/TTMLParser.js
- Fixed `imageType` attribute name to align with http://www.smpte-ra.org/schemas/2052-1/2010/smpte-tt XSD
- Extended ns verification in TTMLParser with SMPTE ST 2052-1:2013 namespace since it has XSD identical to 2052-1:2010
Issue with `imageType` attribute was already raised in https://github.com/Dash-Industry-Forum/dash.js/issues/730#issue-103753899 and https://github.com/Dash-Industry-Forum/dash.js/pull/729#issue-43632363
=> Fixed imageType attribute name in TTMLParser

src/streaming/controllers/StreamController.js
- For now reset the Sourcebuffer for critical texttrack types because we can not resuse existing buffer
- Adjust getNextStream logic to account for larger period gaps
=> Fix multiperiod subtitles + getNextStream

package.json, src/core/Version.js, src/streaming/controllers/StreamController.js
=> Fix prebuffering static mpds

src/streaming/ManifestUpdater.js
Once the stream goes from 'dynamic' to 'static', then if the playback is resumed (after being paused) then manifest update timer is restarted every 100ms.
This PR is fixing this issue.
=> Fix ManifestUpdater for 'dynamic' to 'static' streams

src/dash/DashAdapter.js, src/dash/vo/MediaInfo.js
The idea of this PR is to move any functions out of the MediaInfo class. We are dispatching MediaInfo objects as part of getTracks() and use it in setTracks(). If the prototype of the instance is lost for some reason we run into an error because the functions defined in the MediaInfo class are not available.
=> Compare mediaInfo objects in DashAdapter

.gitignore, index.d.ts, samples/advanced/cmcd.html, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/metrics/MetricsReportingEvents.js, src/streaming/models/CmcdModel.js, test/unit/mocks/AbrControllerMock.js, test/unit/mocks/DashMetricsMock.js, test/unit/streaming.models.CmcdModel.js
Updating the CMCD implementation to the current specification.
- changed query key from 'Common-Media-Client-Data' to 'CMCD'
- omitting '=true' in query string for boolean parameters
- enclosing string values in double quotes, except tokens
- sorting CMCD metrics alphabetically by key name
- URL encoding CMCD metrics
- added new metrics: 
- bl (Buffer length)
- bs (Buffer starvation)
- su (Startup)
- tb (Top bitrate)
- pr (Playback rate)
- removed former metrics: 
- bs (Buffer size)
- did (Device ID)
- rounding values of metrics: 
- dl (Deadline)
- mtp (Measured throughput)
- added object type:
- o (other)
- omitting CMCD version if it is 1
- extended CMCD sample
- implemented unit tests for CMCD logic
resolves #3402
=> CMCD update

src/streaming/utils/TTMLParser.js
Turns out #3332 broke one of the test assets (https://livesim.dashif.org/dash/vod/testpic_2s/img_subs.mpd) so was easy to verify the fix.
=> Fix #3421 - accept non-compliant imagetype attribute name in SMPTE-TT image

index.d.ts, samples/dash-if-reference-player/app/main.js, src/core/Settings.js, src/streaming/MediaPlayer.js, src/streaming/constants/Constants.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/MediaController.js, src/streaming/controllers/ScheduleController.js, test/unit/streaming.controllers.MediaController.js
This PR adds two new settings parameters (may have been forgotten when new **updateSettings** function was created in v3)
```
{ streaming: 
{
trackSwitchMode: {audio: audioMode , video: videoMode},
selectionModeForInitialTrack: mode,
}
}
```
and deprecates setTrackSwitchModeFor and setSelectionModeForInitialTrack functions (still usable though)
=> updateSettings new streaming parameters : trackSwitchMode and selectionModeForInitialTrack

src/streaming/models/VideoModel.js
This mistake could lead to captions not visible at all (outside visible area)
=> fix captions bad top position (reference to a wrong parentElement)

src/streaming/text/TextTracks.js, test/unit/streaming.text.TextController.js
This PR will avoid polling every 500ms to check if video element size has changed to redraw HTML captions
It will be used on browsers that supports ResizeObserver (which is the case for most of them today)
[See support](https://caniuse.com/resizeobserver)
ResizeObserver can observe changes for the size of an element and call a callback only when needed.
=> use resizeObserver when available for resizing captions

AUTHORS.md, src/core/FactoryMaker.js, src/streaming/MediaPlayer.js
Fixes #3431
Adds a destroy method for when the user is completely done with the MediaPlayer and won't be using it again. This is necessary because reset() does not remove all references to the 'singleton instances' in FactoryMaker.
=> add MediaPlayer.destroy to free all memory

src/streaming/constants/Constants.js, src/streaming/metrics/reporting/reporters/DVBReporting.js, src/streaming/metrics/utils/ManifestParsing.js, src/streaming/metrics/vo/Reporting.js, test/unit/streaming.constants.Constants.js
If dvb:probability is absent in the Metric's Reporting descriptor it should default to 1000 (a reporting player) as per DVB spec (Clause 10.12.3.3). The typo that referenced dvb:priority instead of dvb:priority has been corrected in the DVB spec now for some time and it's probably fair (and safe) to remove the fallback to this.
Made some changes to be more explicit about attribute names and default values. I based these on how the DVB extensions are handled for BaseURL elements.
Straight off the bat, I work for the BBC and you should be able to see I'm part of the BBC's organisation on Github. We signed the CLA in 2014 (point 4):
https://github.com/Dash-Industry-Forum/dash.js/wiki/Meeting-Minutes#minutes-april-4th-2014
=> dvb:probability should be 1000 by default

src/streaming/controllers/ScheduleController.js, src/streaming/rules/scheduling/BufferLevelRule.js, test/unit/streaming.rules.scheduling.BufferLevelRule.js
This PR revert changes on BufferLevelRule in PR #3360, in order to restore alignement of audio buffer target to current video buffer level
=> Revert BufferLevelRule

index.d.ts, samples/getting-started/listening-to-events.html, src/core/events/CoreEvents.js, src/dash/DashHandler.js, src/streaming/ManifestUpdater.js, src/streaming/MediaPlayerEvents.js, test/unit/dash.DashHandler.js
This PR adds public MediaPlayer event DYNAMIC_TO_STATIC to be triggered at transition phase between live and on-demand contents
=> Add event DYNAMIC_TO_STATIC 

src/core/EventBus.js, src/streaming/StreamProcessor.js, src/streaming/controllers/ScheduleController.js, src/streaming/text/NotFragmentedTextBufferController.js
Fix regression introduced by PR #3372:
- add streamId and mediaType in events payload
- restore evet propagation management (for smooth streaming scenario)
=> Fix events payload

samples/advanced/listening-to-SCTE-EMSG-events.html, src/core/EventBus.js, src/mss/MssHandler.js, src/streaming/MediaPlayer.js, src/streaming/MediaPlayerEvents.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/EventController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, test/unit/core.EventBus.js, test/unit/mocks/PlaybackControllerMock.js, test/unit/streaming.controllers.EventController.js
=> Feature event on receive

src/streaming/protection/controllers/ProtectionController.js
I wanted to put up this PR to potentially start a discussion, or, if it's deemed appropriate, to get it merged.
For many encrypted streams, it's not uncommon to see the same initData appear repeatedly. This is especially true for live streams. In running some streams, we end up getting tons of warning logs due to this message.
Since there's no action to be taken, as this is a valid case, I was thinking that it should be at a lower log level than warn, which is generally used for more actionable issues.
Let me know what you think, and thank you.
=> Decrease already seen initData log from warn to info

package.json, src/core/Settings.js, src/core/Version.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/GapController.js
The intention of this PR is to:
- Adjust the gap jumping for live playback. We need to wait before jumping a gap in order to maintain a consistent live edge
- Adjust the threshold in the BufferController that determines if a period has finished buffering
=> Fix live gap jump

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, test/functional/tests/playFromTime.js, test/unit/mocks/StreamControllerMock.js, test/unit/mocks/StreamMock.js, test/unit/streaming.controllers.PlaybackControllers.js
This PR is fixing anchor time management in case of multiple periods
Anchor time shall be relative to 1st period but currently anchor time is computed as being relative to targeted (from anchor time) period start time
=> Fix url anchor time

contrib/akamai/controlbar/ControlBar.js, samples/dash-if-reference-player/app/src/cast.js
some functions or events have been renamed/introduced and broke cast controlbar implementation for controlling audio/text tracks
getThumbnail renamed into provideThumbnail
texttrack index not available when triggering dashjs.MediaPlayer.events.TEXT_TRACKS_ADDED from cast
=> Fix audio/text tracks management from controlbar in a cast sesssion

index.d.ts
This adds the following ABR strategies to the TypeScript definitions, since I assume they're all customizable from the settings:
- `abrDynamic`
- `abrBola`
- `abrL2A`
- `abrLoLP`
- `abrThroughput`
Or are they only available in some specific circumstances?
=> add missing ABR strategies to TypeScript defs

src/core/EventBus.js
This caused an error when processing source using Babel: "Attempted import error: 'EVENT_MODE_ON_RECEIVE' is not exported from '../streaming/MediaPlayerEvents'."
I've changed it to match the other uses of these constants, which caused my builds to succeed. E.g.:
https://github.com/Dash-Industry-Forum/dash.js/blob/7d4d208898c1f5c1dd68957583a9475f4b591cfd/src/streaming/controllers/EventController.js#L126
=> Fix invalid MediaPlayerEvents import

src/dash/DashAdapter.js, src/streaming/controllers/EventController.js, test/unit/dash.DashAdapter.js, test/unit/streaming.controllers.EventController.js
This PR aims to fix the issue described in #3485 and #3429:
- The events are now sorted by schemeIdUri and not by id. 
- Existing events are only overwritten for similar schemeId, value and id field values
- Events are added if they have similar ids, similar schemeIdUris but different values
- Added additional unit tests
- Fixed a bug in the calculation of Version 1 inband events. Use the PTO from the <InbandEventStream> element instead of the one from the <Representation> element
=> Fix: Account for schemeIdUri, value and id fields in EventController

index.d.ts, index.js, src/streaming/utils/Capabilities.js
Similar to https://github.com/Dash-Industry-Forum/dash.js/issues/2055, I was looking for an easy way to test for MSE support before falling back to HLS. This small change exposes the existing `supportsMediaSource` check into a `dashjs.isSupported()` function on the global module object.
Example usage:
```js
if (dashjs.isSupported()) {
const player = dashjs.MediaPlayer().create()
// ...
} else {
// fallback logic
}
```
=> Expose dashjs.isSupported utility for checking MSE support

index.d.ts, src/streaming/MediaPlayer.js, src/streaming/constants/Constants.js, src/streaming/controllers/MediaController.js, test/unit/streaming.controllers.MediaController.js
This PR adds a new initial track selection mode: "highestEfficiency". It picks the variant that offers the lowest bitrate for equivalent resolution (similar to the Shaka Player behavior referenced by @japettyjohn in https://github.com/Dash-Industry-Forum/dash.js/issues/3022#issuecomment-509937141). Similar to Shaka Player, this will prefer VP9 over MP4 if it's offered with a lower average bitrate, which is the behavior I was looking for.
In addition, this PR exposes `selectInitialTrack` and the `getTracksWithHighestBitrate`/etc functions on the class factory so that they can be overridden using `MediaPlayer.extend`, to allow end users to define their own custom strategy.
Included are new tests to cover the new track selection mode as well as the other existing ones.
Re: …
=> Add "highestEfficiency" initial track selection mode

src/streaming/net/HTTPLoader.js
**Related commit**: [2b6d778](https://github.com/Dash-Industry-Forum/dash.js/commit/2b6d778f0366a192ab4a7e18bece67e0e926a569#diff-37a9697c7cc9fba419e4d7d616e9a631133b28dabef5ed236f9160b5d1b342a5R249)
This is my first pull request, I have signed up to [the dash.js feedback agreement](https://groups.google.com/g/dashjs/c/r6KWiL_VbKM).
=> Fix the error of the arguments of the DashMetrics.addManifestUpdate when it is calling

index.d.ts, src/core/Settings.js, src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/controllers/StreamController.js, src/streaming/utils/Capabilities.js, src/streaming/utils/CapabilitiesFilter.js, test/unit/mocks/AdapterMock.js, test/unit/mocks/CapabilitiesFilterMock.js, test/unit/streaming.Stream.js, test/unit/streaming.utils.CapabilitiesFilter.js
This addresses issues #3510 and #3509
- Adds CapabilitiesFilter that filters Representations and Adaptations for each period(stream object)
- Removes unsupported AS and Rep based on media codec
- Removes unsupported AS and Rep based on EssentialProperty
- Can be disabled via Settings flag
The reason to add a new class here is to have a single point where all the necessary filtering is performed, prior to the initialization of the StreamProcessors. Additional filters might be added in the future
=> Feature capabilities filter

index.d.ts, samples/dash-if-reference-player/app/css/main.css, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/streaming/MediaPlayerEvents.js, src/streaming/constants/ConformanceViolationConstants.js, src/streaming/controllers/StreamController.js, src/streaming/utils/TTMLParser.js
This PR implements the conformance violation check as described in #3339 
- Added ConformanceViolationConstants.js to save all information on conformance violations
- Added two initial violation events for missing UTCtiming elements and wrong authoring of SMPTE 2052-1:2013 tags
- Added output area on reference client page (see screenshot)
=> Feature conformance warning

samples/samples.json
Doc updated for PlayReady DRM is supported only on Windows 10 on Microsoft Chromium Edge.
=> Updated text for PlayReady DRM

index.d.ts, samples/advanced/cmcd.html, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/dash/DashHandler.js, src/streaming/MediaPlayer.js, src/streaming/StreamProcessor.js, src/streaming/models/CmcdModel.js, src/streaming/protection/Protection.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/vo/metrics/HTTPRequest.js, test/unit/mocks/PlaybackControllerMock.js, test/unit/mocks/StreamControllerMock.js, test/unit/mocks/StreamMock.js, test/unit/mocks/StreamProcessorMock.js, test/unit/streaming.models.CmcdModel.js
- Adding CMCD metrics 'nor' and 'nrr'
- Adding CMCD object type 'tt' for ISOBMFF timed text tracks
- Adding CMCD metrics to license requests
=> Add further CMCD parameters

src/streaming/StreamProcessor.js
When a StreamProcessor for a first period is torn down, ABR stops working for the second period. The second period is fixed at whatever quality it's on when this occurs.
This is because `abrController.unRegisterStreamType` is called, but only after it's been set to the new period. The result is that the second period doesn't have a StreamProcessor and therefore `checkPlaybackQuality` doesn't get called. The solution here is not to call when keepBuffers is true, the StreamProcessor has already been overwritten.
=> Fix AbrController's reference to StreamProcessor lost when switching period

src/streaming/controllers/MediaSourceController.js, src/streaming/controllers/StreamController.js, test/unit/streaming.controllers.MediaSourceController.js
When setting duration on MediaSource, if any SourceBuffer is updating it throws an `InvalidStateError` exception:
`Uncaught DOMException: Failed to set the 'duration' property on 'MediaSource': The 'updating' attribute is true on one or more of this MediaSource's SourceBuffers`
This PR fixes this issue by check if no SourceBuffer is updating when setting MediaSource duration
=> Fix setting MediaSource's duration

src/streaming/controllers/BufferController.js
This PR fixes two issues with using the `preload()` function and discharging before it's filled up until buffer target:
1. If a video element is attached while it's still pre-loading content, the fragments appended from the discharge() function in BufferController send bytes_appended events out. This causes the scheduling loop to be triggered a second time, meaning remaining fragments will be downloaded 2 at time until buffer target is reached. To fix it, the fragments discharged from the PreBufferSink are tracked in array `dischargeFragments` and bytes_appended events are not sent out for those fragments.
2. If an init segment is discharged it is appended to the SourceBuffer twice. The discharge function checks the InitCache when `chunk` is an init segment. It returns the exact same init …
=> Fixes for discharging preloaded content

index.d.ts, samples/drm/license-wrapping.html, samples/samples.json, src/core/Utils.js, src/dash/DashMetrics.js, src/streaming/MediaPlayer.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/vo/LicenseRequest.js, src/streaming/protection/vo/LicenseResponse.js
This PR adds a new feature on MediaPlayer to enable filtering license requests and responses
=> Add feature for filtering license requests and responses

src/mss/parser/MssParser.js
This PR is fixing MSS parser for representations width and height.
The MSS parser was previously setting these values to NaN if not signaled in manifest (for non-video tracks).
=> [MSS] Fix representation's width and height

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/app/rules/DownloadRatioRule.js, samples/dash-if-reference-player/app/src/cast.js
See #3542.
This only fixes the reference player. I have not tested if the Cast stuff still work, though this change seems fairly low risk.
=> Remove IE11 unsupported ES6 features from ref player

samples/chromecast/receiver/js/DashPlayerService.js, samples/dash-if-reference-player/app/src/cast.js, samples/dash-if-reference-player/index.html
This PR is fixing a bug at track switching while casting on a cast device.
It also enables config parameter `flushBufferAtTrackSwitch` on player in receiver application to make immediately effective track switch on cast devices
=> [cast] Fix track switch

src/streaming/ManifestUpdater.js, test/unit/streaming.ManifestUpdater.js
When patch is applied the manifest object `loadedTime` needs to be updated to ensure the update poll is set properly, otherwise the player will attempt a full reload immediately. Was originally in a test case and missed in the publish time change enforcement refactor.
=> Ensure manifest loadedTime updated when patch applied

test/functional/config/browsers.json
Currently only for windows the config chromeOptions.w3c:false is set. This was missing for mac config, causing local tests using chromedriver and chrome browser terminating with 'unknown command: Cannot call non W3C standard command while in W3C mode' error message.
=> Fix execution of local functional tests on mac

package-lock.json, package.json, tsconfig.json
This should help to check the type declaration file to prevent errors being merged which in turn could compromise the build processes of some strictly types projects.
Should avoid such [problems](https://github.com/Dash-Industry-Forum/dash.js/pull/3551).
=> Check TypeScript type declaration file on every build

index.d.ts
These functions need an explicit response type to prevent warnings like the following:
index.d.ts (350,9): 'registerLicenseRequestFilter', which lacks return-type annotation, implicitly has an 'any' return type.
index.d.ts (351,9): 'registerLicenseResponseFilter', which lacks return-type annotation, implicitly has an 'any' return type.
index.d.ts (352,9): 'unregisterLicenseRequestFilter', which lacks return-type annotation, implicitly has an 'any' return type.
index.d.ts (353,9): 'unregisterLicenseResponseFilter', which lacks return-type annotation, implicitly has an 'any' return type
=> fix implicit "any" type in index.d.ts

index.d.ts
Hey, 
destroy method was added in #3432, but is missing in dashjs TypeScript typings.
=> add missing TypeScript type signature for destroy method 

index.d.ts
The `ProtectionController` can emit this event with an error, when the current license expires: 
1. https://github.com/Dash-Industry-Forum/dash.js/blob/75cf1a5535bcb5777a55f5b51a034be6022378e5/src/streaming/protection/controllers/ProtectionController.js#L635
=> Adding optional error to KeyStatusesChangedEvent type

src/streaming/controllers/PlaybackController.js
When doing internal seek (to adjust seek target or to jump gaps), re-enable 'seeking' listener once currentTime has been set on video element (do not wait for 'seeked' event).
This fixes some inconsistancies when user is seeking while internal seeking
=> Fix internal seek

src/streaming/MediaPlayer.js
This PR is fixing MediaPlayer.time() returning negative value for live streams not yet playing (<video>.currentTime = 0)
=> Fix MediaPlayer.time() for live streams

index.d.ts, src/core/Settings.js, src/streaming/controllers/EventController.js, src/streaming/controllers/StreamController.js, test/unit/streaming.controllers.EventController.js
=> Add a settings parameter for the EventController.js refresh delay

src/streaming/controllers/ScheduleController.js
#3568
checks `seekTarget` equals to `NaN` before executing `validateExecutedFragmentRequest`
=> fix: #3568 validateExecutedFragmentRequest while removing buffer may causes playback stall

samples/chromecast/receiver/js/DashPlayerService.js, samples/chromecast/sender/js/CastSenderController.js, samples/chromecast/sender/js/CastSenderService.js, samples/low-latency/l2all_index.html, samples/low-latency/lolp_index.html, samples/offline/app/main.js, samples/offline/app/offline/services/downloadService.js, samples/offline/app/rules/DownloadRatioRule.js
Removing arrow functions from samples as they are not supported by IE11
#3542
=> Replacing arrow function with regular functions in samples

src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js
fix #3558
Set buffering time to last *quota exceeded* segment time on *QuotaExceededError* occurs
=> fix: #3558

src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js
This PR is fixing some issues when switching periods, due to controllers lifecycle and seeking event handler.
For example it fixes the following javascript error when switching period:
```
BufferController.js:398 Uncaught TypeError: Cannot read property 'waitForUpdateEnd' of null
at pruneAllSafely (BufferController.js:398)
at Object.onPlaybackSeeking (BufferController.js:386)
at EventBus.js:124
at Array.forEach (<anonymous>)
at Object.trigger (EventBus.js:124)
at HTMLVideoElement.onPlaybackSeeking (PlaybackController.js:499)
```
=> Fix multiperiod switching

index.d.ts, src/core/Settings.js, src/mss/MssFragmentInfoController.js, src/mss/MssFragmentMoofProcessor.js, src/mss/MssFragmentProcessor.js, src/mss/MssHandler.js, src/mss/parser/MssParser.js, src/streaming/ManifestLoader.js, src/streaming/controllers/PlaybackController.js, src/streaming/net/HTTPLoader.js, src/streaming/vo/metrics/HTTPRequest.js
This PR is fixing a bug when seeking MSS live streams to DVR window range start.
While seeking to range start, segment timeline could be updated at the same time, thus having first segments to be removed from timeline.
This PR is fixing also an issue regarding SegmentInfo requests that could be aborted when seeking.
=> Fix MSS live seeking

src/streaming/controllers/ScheduleController.js
fix #3585
Currently the ScheduleController sets its current last initialized quality when it fires `INIT_FRAGMENT_NEEDED` event.
This seems correct most of the time except if appending init segment is failed.
Firing `INIT_FRAGMENT_NEEDED` does not guarantee that init fragment is appended. It can be cancelled or aborted by network error or something.
We have to set last initialized quality when the init segment is actually appended to the SourceBuffer.
If it can be accepted, I wish this to be merged into 3.2.x if possible.
=> fix: #3585 ensure init segment appended

Gruntfile.js, githook.js, package-lock.json, package.json
The hook is installed using a node script
Pulling this functionality out of https://github.com/Dash-Industry-Forum/dash.js/pull/3253
As discussed in https://github.com/Dash-Industry-Forum/dash.js/pull/3596
=> Remove grunt githook and replace with package.json's postinstall script

githook.js
With this fix 
* npm install 
* pre-commit script execution 
should not be an issue on Mac and Win anymore.
=> Git hooks: Fix path problem on Windows

index.d.ts, samples/dash-if-reference-player/app/main.js, samples/offline/app/main.js, src/core/errors/Errors.js, src/dash/DashAdapter.js, src/dash/DashMetrics.js, src/offline/controllers/OfflineController.js, src/offline/storage/IndexDBStore.js, src/offline/utils/OfflineIndexDBManifestParser.js, src/streaming/MediaPlayer.js, src/streaming/MediaPlayerEvents.js, src/streaming/SourceBufferSink.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, src/streaming/controllers/TimeSyncController.js, src/streaming/metrics/MetricsReportingEvents.js, src/streaming/protection/controllers/ProtectionController.js, test/unit/core.errors.Errors.js, test/unit/dash.DashAdapter.js, test/unit/mocks/AdapterMock.js, test/unit/streaming.controllers.BufferController.js, test/unit/streaming.controllers.TimeSyncController.js
- Add missing JSDoc to DashAdapter and Errors.js
- Cleanup: Remove non required events and errors
=> Feature cleanup errors

src/streaming/text/TextController.js
Fix a bug/regression for (segmented) text track selection.
Bug detected in stream "[Unified Streaming] Subtitles in multi period live" (https://pl8q5ug7b6.execute-api.eu-central-1.amazonaws.com/2.mpd), after disabled then enabled text track, text track is not enabled (segments not downloaded)
=> Fix segmented text track selection

src/core/Settings.js, src/dash/DashAdapter.js, src/dash/utils/TimelineConverter.js, src/streaming/Stream.js
- Fix a bug in calculation of the DVR window when fallbackToSegmentTimeline is activated. Only set the timelineAnchorAvailabilityOffset if DVR window is calculated based on SegmentTimeline
- Fix a bug for streams with multiple AdaptationSets and no id attribute specified
=> Fix multi audio and timeline

src/streaming/controllers/PlaybackController.js, src/streaming/text/TextController.js
Currently the code only makes any settings updates from ServiceDescription on presence of critical SupplementalProperty so this PR corrects the behaviour according to the DVB DASH spec:
- Only enable Low latency on presence of `urn:dvb:dash:lowlatency:critical:2019` SupplementalProperty (according to DVB DASH spec S10.20.5 - It is also mentioned in the spec that LL can be enabled due to two other conditions in the spec so these could also be added at a later date)
- On presence of Service Description set the low latency parameters in `settings`
- Correct setting of `maxDrift`, and `minDrift` according to DVB DASH spec (S10.20.6)
=> Updated _applyServiceDescription(): only enable LL on critical SupplementalProperty, correct min/maxDrift 

src/streaming/StreamProcessor.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/ScheduleController.js
When the quality is changed as part of the scheduling logic the ScheduleController.js should not call _getNextFragment
=> Fix a bug that lead to starting the the schedule timer twice. 

build/webpack.base.js, build/webpack.prod.js, index_mediaplayerOnly.js, package-lock.json, package.json
=> Feature webpack legacy

src/streaming/controllers/MediaController.js
for example with fragmentedText type that is not used anymore. It is for calls with the public API getCurrentTrackFor
=> avoid error when using getCurrentTrackFor with unknown type 

src/streaming/controllers/BufferController.js
This fixes issue #3705.
Changes proposed in this PR are the safest way to not make any regression. I'm not sure it this function is supposed to support strings such as `'10'` or not. If not - then I'd rather change this conditional to:
```js
if (typeof seekTime !== 'number' || isNaN(seekTime)) {
```
=> Do not clear entire buffer when seeking to 0

src/dash/DashMetrics.js, test/unit/dash.DashMetrics.js
HTTP headers are case-insensitive and `Headers` object keys are lowercase to accommodate for that.
`getLatestMPDRequestHeaderValueByID` is used only once within the project and it's called with a string `'Date'` which without being converted to lower case never matches any headers. This caused time synchronisation through `Date` header not to work.
=> Treat HTTP headers case-insensitively

package.json
See https://docs.npmjs.com/cli/v7/using-npm/scripts
`prepare` only runs when npm install is run locally without any arguments ie when called, rather than after every install. This means the pre-commit hook is installed for those developing the library, but not those for who it is installed as a dependancy.
=> Fix #3701 - use prepare rather than postinstall so dashjs can be used as a dependancy

src/streaming/controllers/EventController.js
EventController apparently was meant to trigger pending events on stop, but this was not happening because of what seems like a silly typo.
This in fact raised an exception which was consumed by an empty `catch` clause. This also does not seem intentional.
=> Fix EventController._triggerRemainingEvents not doing anything

src/streaming/metrics/utils/DVBErrorsTranslator.js
This can be generated when a request fails with a catch(), though it can occur if the status is uninitialised or explicitly set to null.
Also it seems that the check for `>= 600` is redundant since it will be caught but the earlier `>= 400` check.
=> Explicitly match null status

src/streaming/net/HTTPLoader.js
- Corrects reporting and logging of URL if modified (e.g. by CMCD)
The response.url is used by the logging and [DVB] reporting components (when activated) which only report the original url before any modifications have been made (e.g. by CMCD) so the used URL (i.e. including the query params) isn't correctly reported. This also fixes some issues with identification of redirection (#3721).
=> Set response.url to modifiedUrl

src/mss/parser/MssParser.js
Set availabilityTimeOffset to Infinity since segments are available as long as they are present in timeline
=> [MSS] Fix availabilityTimeOffset for live MSS

src/dash/DashHandler.js, src/streaming/StreamProcessor.js
Only check if the stream is completed if no request could be generated. Otherwise we stop buffering to early after a transition from dynamic to static manifests.
=> Fix transition from live to static

index.d.ts, src/core/Settings.js, src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/dash/vo/MediaInfo.js, src/streaming/constants/Constants.js, src/streaming/controllers/MediaController.js, test/unit/dash.models.DashManifestModel.js, test/unit/streaming.controllers.MediaController.js
This PR adds a track selection mode based on the selectionPriority attribute defined manifest. We make this the default mode and fallback to TRACK_SELECTION_MODE_HIGHEST_BITRATE and TRACK_SELECTION_MODE_WIDEST_RANGE in case no selectionPriority is given.
**From 23009-1:** 
_selectionPriority: specifies the selection priority for the described data structures, i.e. the one described by the containing element. In the absence of other information, higher numbers are the preferred selection over lower numbers._
**From IOP v4.3**
_This attribute should be used to disambiguate Adaptation Sets within one group for selection and expresses the preference of the MPD author on selecting Adaptation Sets for which the DASH client does make a decision otherwise.
Examples include two video codecs …
=> Add track selection mode based on selectionPriority attribute

src/dash/utils/SegmentsUtils.js, src/dash/utils/TimelineConverter.js
=> Fix wrong timing calculation for client/server clock drift.

index.d.ts, src/core/Settings.js, src/streaming/controllers/BufferController.js
=> Fix live playback on WebOS (#3750)

src/streaming/Stream.js
As for every other error. 
This is up to the application to stop/reset the session.
=> Stream: do not reset() on protection error

src/streaming/protection/controllers/ProtectionController.js
This pull request fixes issue: [#3769](https://github.com/Dash-Industry-Forum/dash.js/issues/3769)
Some DRM license providers are using different response codes, however it seems that dash.js is failing if response status code is not 200. Since most of the 2XX HTTP are success codes, we should not consider license request as failed.
If you have any ideas or comments how we can improve it, just let me know and I will be more than happy to fix it.
=> Fix: #3769 - Handle all 2XX status codes on license request 

index.d.ts, src/core/Settings.js, src/streaming/StreamProcessor.js, src/streaming/controllers/GapController.js
This PR enables gap jumping when seeking close to the end of a period. This is supposed to solve #3713, cases in which there is a gap right before the end of the period and the user seeks very close to this gap. In that case the video element will remain in seeking state although there is data in the buffer.
=> Activate gap jumping when seeking close to the end of a period.

src/streaming/net/URLLoader.js
This PR fixes an issue introduced when added offline support with SchemeLoaderFactory.
It avoids creating one HTTPLoader instance per http request.
This may have side effects in case we are sending requests in parallel by the same FragmentLoader and want to abort them. First request therefore would not be aborted.
One use case is sending of MSS FragmentInfo requests in parallel of media segments.
=> Avoid creating one HTTPLoader instance per request

src/streaming/ManifestUpdater.js, src/streaming/Stream.js
In case of live MSS, manifest needs to be refreshed when switching audio or text track.
This PR avoids requesting twice the manifest when simultaneoulsy switching audio and text track
=> [MSS] Do not update manifest if already updating at tracks switching for live streams

src/streaming/StreamProcessor.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js
Do not update currenttime when manifest update is in progress to avoid using a wrong DVR window
=> DVR Window Refactoring

index.d.ts, src/dash/DashAdapter.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/protection/drm/KeySystemClearKey.js, src/streaming/protection/drm/KeySystemPlayReady.js, src/streaming/protection/drm/KeySystemW3CClearKey.js, src/streaming/protection/drm/KeySystemWidevine.js, src/streaming/protection/models/ProtectionModel.js, src/streaming/protection/models/ProtectionModel_01b.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js, src/streaming/protection/models/ProtectionModel_3Feb2014.js, src/streaming/protection/vo/SessionToken.js, test/unit/streaming.protection.drm.KeySystemPlayReady.js
The goal of this PR is to fix key rotation in order to rely on key id updates instead of initData updates.
Some live streams may have initData being updated in manifest updates but with same key id, thus this PR would avoid requesting unnecessarily a new license.
This required some refactoring in order to store key ids and then to simplify API protection models API (load/createSession).
Still in progress:
- in case of 'encrypted' event, shall we extract key id from pssh in order to compare it?
- then shall we remove completely initData duplication checking?
=> Refactor protection and fix key rotation

src/streaming/MediaPlayer.js, src/streaming/StreamProcessor.js, src/streaming/controllers/AbrController.js, src/streaming/rules/ThroughputHistory.js, src/streaming/rules/abr/InsufficientBufferRule.js
Add dynamic attribute for calls to throughputHistory.getAverageThroughput
=> Add dynamic attribute for calls to getAverageThrougput

src/mss/parser/MssParser.js
MSS manifest with audio codec value fourCC="AACH" is not converted into dash by MSSParser.js.
Supported codecs list does not have 'AACH'.
Audio was not playing because of this.
Adding AACH to SUPPORTED_CODECS list plays audio fine.
=> Adding AACH in the list of supported codecs for mssparser

src/dash/models/DashManifestModel.js
In order to parse Content Programme Metadata as specified in DVB DASH spec in section 9.1.2, the XML parser and Dash Events need to support CDATA in the payload.
This PR preserves CDATA when the manifest is parsed and assigns the CDATA to the `event.messageData` if the attribute exists.
Would welcome feedback on whether preserving CDATA should be driven from a player settings configuration.
There doesn't seem to be any specific existing test coverage in these areas, but the whole suite continues to pass and I have tested access to the CDATA within a player event using scheme `urn:dvb:iptv:cpm:2014`.
As this is my first dash.js contribution, I've also uploaded a feedback agreement to the mailing list.
=> feat: Preserve cdata on manifest parsing and expose on dash event messageData

src/core/Settings.js
#3823 changes the calculation in `TimelineSegmentsGetter.js`. In order to seek over gaps at playback start we need to enable `enableSeekFix`
=> Enable gap seek fix by default

src/core/Settings.js
This PR enables throwing an error in case of invalid, non-existent setting parameter.
Since some settings parameters may be moved or renamed depending on the version, this would avoid issues during dash.js integration.
=> Throw new error in case of invalid settings

src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js
Fix: Load the last remaining segment when the user seeks to the very end of the timeline: currentTime = duration
Potential fix for #3846 . Needs to be further tested especially with track switches and multiperiod before merging
=> Fix: Load the last remaining segment when the user seeks to end

src/dash/models/DashManifestModel.js, src/streaming/controllers/EventController.js
This PR fixes a memory leak for inline events without id and presentation time. Before this PR the events were not removed from the list of outdated events leading to large memory consumption for longtime playback.
=> Fix events without presentation time and id

src/streaming/controllers/BufferController.js
This PR is fixing errors when stopping playback.
When resetting BufferController and aborting then removing source buffers from MediaSource, we can face the following error, due to asynchronous processes:
`[SourceBufferSink][video] getAllBufferRanges exception: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source. 
`
=> Fix SourceBufferSink reset process

samples/drm/clearkey.html, samples/drm/mpds/laurl.mpd, samples/drm/system-string-priority.html, samples/samples.json, src/streaming/constants/ProtectionConstants.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js, test/functional/config/smokeVectors.json
The idea of this PR is to support different system strings when calling `requestMediaKeySystemAccess` for the same DRM system. As an example, Playready can be initialized with `com.microsoft.playready`, `com.microsoft.playready.recommendation` or `com.microsoft.playready.hardware` . 
To be backwards compliant with previous dash.js versions, we introduce a new field `systemStringPriority` in `protData`. If this field is present and contains values then we use these values instead of the default system string. If the field is absent we use the default system string.
````javascript
"protData": {
"serverURL": "https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/?specConform=true",
"systemStringPriority": ["com.widevine.something", "com.widevine.alpha"]
}, …
```
=> Add support for multiple system strings for a single key system

src/streaming/controllers/GapController.js
Since StreamController is reset before GapController, activeStream may be null on wall clock time update.
In a more general view, reset process may raise such issues due to cross references betwenn StreamController and PlaybackController, and the use of timers (such as WALLCLOCK_TIME_UPDATED)
=> Fix issue in GapContoller when reset playback

src/streaming/controllers/BufferController.js
This PR is fixing the following issue:
if enableSeekDecorrelationFix is enabled, than after a track switch BufferController::_adjustSeekTarget may execute by mistake an internal seek (to buffered range start), since seekTarget may differ from playback currrent time (which may have progressed in the meantime)
=> Fix issue after a track switch if enableSeekDecorrelationFix is enabled

src/streaming/models/VideoModel.js
This PR is fixing an issue when getting video model current time and seeking state, after setting current time but while waiting for video element ready state to have metadata.
One example of issue with current version is track selection once 'loadedmetadata' event is received for live streams (or on demand with start time > 0):
- edit reference sample application main file, and add the following code:
```
$scope.player.on(dashjs.MediaPlayer.events.PLAYBACK_METADATA_LOADED, function (e) { /* jshint ignore:line */
$scope.player.enableText(true);
$scope.player.setTextTrack(2);
}, $scope);
```
- load reference sample application
- edit options and disable "Enable Text At Loading"
- load content "Subtitles and Captions / [DASH-IF] TTML Segmented Subtitles Live (livesim)"
The player shall …
=> Fix VideoModel currentTime and seeking

src/streaming/controllers/PlaybackController.js, test/unit/mocks/PlaybackControllerMock.js, test/unit/streaming.controllers.PlaybackControllers.js
- The original issue https://github.com/Dash-Industry-Forum/dash.js/issues/2796 no longer occurs
* We reran the test using the same test stream (https://akamaibroadcasteruseast.akamaized.net/cmaf/live/657078/akasource/out.mpd) on the same OS (MAC 10.13.6) and browser version (FF62, also tested FF62.0.1, FF61) - we used the v2.9.1 dash reference player with low latency enabled - and could not reproduce the error. Maybe the stream has changed?
- The function leads to incorrect `currentLiveLatency` calculation with streams where the current media time is greater than the AST - particularly when AST is small but non zero.
- We have successfully tested this PR on current browsers (FF96.0.3& Chrome98 on MacOS11.6.2&MacOS10.13.6, Chrome 97.0.4692.99 and Firefox 91.6.0esr in Windows 10) with the …
=> Remove getNormalizedTime

src/streaming/MediaPlayer.js
Before this PR the timestamps for the Thumbnails were provided relative to period start. This lead to calculation of wrong urls or 404s on thumbnails
=> Fix calculation of thumbnail timestamp for multiple periods

src/streaming/MediaPlayer.js, src/streaming/constants/MetricsConstants.js, src/streaming/metrics/controllers/MetricsController.js, src/streaming/metrics/reporting/ReportingFactory.js, src/streaming/metrics/reporting/reporters/DVBReporting.js, src/streaming/vo/metrics/HTTPRequest.js, test/unit/streaming.constants.MetricsConstants.js
See #3897 for more context.
Provides a way of setting a 'withCredentials' true/false on DVB Metrics Reporting requests. Uses getXHRWithCredentialsForType() and setXHRWithCredentialsForType() in MediaPlayer to achieve this.
=> DVB Metrics Reporting 'withCredentials'

src/streaming/rules/abr/BolaRule.js
On audio track switch, if trackSwitchMode is set to TRACK_SWITCH_MODE_ALWAYS_REPLACE for audio, then audio buffer becomes empty and BOLA rule resets the placeholderbuffer level to 0, for BOTH audio and video.
Therefore, a quality switch to lowest level may be performed on video track when switching audio track.
This PR is fixing this issues by resetting the placeholderbuffer only for the media type which buffer is empty.
=> Fix BOLA rule on track switch

src/streaming/models/MetricsModel.js, src/streaming/rules/ThroughputHistory.js, src/streaming/vo/metrics/HTTPRequest.js
The `t` metric should not be included in the reported HttpList metrics as it is not part of the MPEG-DASH specified set of reported metrics. The metrics `t` variable has been renamed to `_t` to indicate that it should not be included in reported metrics.
=> Remove non-standard `t` metric from HttpList reports

src/streaming/controllers/PlaybackController.js
This PR fixes an issue in case of concurrent internal seeks, for example when seeking live streams and audio and video buffers attempt to perform an internal seek in parallel, at the same time. In that case one of the seeks would not be considered as an internal seek.
=> Fix concurrent internal seeks

src/streaming/controllers/ServiceDescriptionController.js, test/unit/streaming.controllers.ServiceDescriptionController.js
See #3922 for details.
- Only parameters from a single ServiceDescription element applied.
- `urn:dvb:dash:lowlatency:scope:2019` takes precedence.
- Use last listed ServiceDescription element if multiple applicable.
=> Change precedence of ServiceDescription elements

src/streaming/protection/controllers/ProtectionController.js
When selecting key system from init data, key system priority was not applied
=> Fix regression in key system selection based on priority

src/dash/utils/TimelineConverter.js, src/dash/utils/TimelineSegmentsGetter.js
This PR is fixing a bug when searching a segment in a SegmentTimeline from a requested media time.
In some cases, due to lost precision when applying timescale, requested media time may be a in "virtual" gap in the timeline introduced by the way the segments start and end time are calculated.
For example, with following timeline:
```
<SegmentTimeline>
<S t="990366987247" d="1200" r="8" />
<S d="1199" />
<S d="1200" r="5" />
</SegmentTimeline>
```
If you seek and request segment at time `1650611665.40999` the TimelineSegmentsGetter will fail to find a segment while requested media is in timeline range.
=> Fix SegmentTimeline's  segment getter from requested time

src/streaming/controllers/BufferController.js
The player may stall in certain cases due to a rounding difference when computing if a period is completely buffered or not. This is seen in multi-period scenarios, in our use case, server side ad insertion). The result is that the player does not start pulling segments for the next period and eventually stalls.
This was seen while testing the Pluto.Tv service. It is difficult for me to provide an example stream as our streams are dynamically generated and DRM protected.
The root cause is the comparison between a number that is rounded to 5 decimal places and a number that is not rounded inside of `BufferController.js`. `playbackController.getTimeToStreamEnd()` is rounded and `bufferLevel` is not rounded.
An example seen while testing:
`getTimeToStreamEnd()` result: `15.23113` …
=> Fix for a rounding error not allowing BUFFERING_COMPLETED to get fired

src/streaming/protection/controllers/ProtectionController.js
Extends the License Request Complete event to include the original server response when DRM errors are reported
=> Extends the License Request Complete event to include the original server response when DRM errors are reported

src/streaming/models/MetricsModel.js, src/streaming/net/FetchLoader.js, src/streaming/net/HTTPLoader.js, src/streaming/rules/ThroughputHistory.js, src/streaming/vo/metrics/HTTPRequest.js
Currently the `d` trace httpList metric always contains the time calculated using the 'Data Chunks' Low Latency throughput calculation, regardless of the `fetchThroughputCalculationMode` setting. This means the httpList reporting contains the incorrect `d` value in the default situation where MOOF parsing mode is used. 
The addition of the 'throughput' (`t`) trace entry leads to other issues:
1) It is not currently taken account of in L2ARule (which this PR would fix): https://github.com/Dash-Industry-Forum/dash.js/blob/7fdbf4e54a9975f31818e18dc6a67cc44a5933eb/src/streaming/rules/abr/L2ARule.js#L388
2) It adds complication with metric reporting (addressed in #3883)
This PR aims to:
- Ensure 'd' (Measurement period duration) trace httpList metric reflects that used by ABR
- Limit use of …
=> Fix `d` trace httpList metric reporting

.circleci/config.yml, test/functional/runTests.js, test/functional/streams.js
We need to add a groupname attribute to the functional tests to run only the testvectors that belong to a certain category for the default list of reference streams. By combining name and groupname as we did before we test the same testvectors multiple times.
=> Run functional tests by groupname

samples/advanced/extend.html, src/streaming/net/FetchLoader.js, src/streaming/net/XHRLoader.js, src/streaming/utils/RequestModifier.js
Solution proposal for #3995. I've added an object as a secondary argument of `modifyRequestHeader` so that it is easily extensible in the future if someone wanted to add e.g. `method` or other XHR parameters.
=> Pass url to RequestModifier.modifyRequestHeader (#3995)

samples/index.html
Allows to send direct links to specific sample sections
=> Add hashtag mechanism to sample menu selection

contrib/akamai/controlbar/ControlBar.js, index.d.ts, samples/low-latency/testplayer/main.css, samples/low-latency/testplayer/main.js, samples/low-latency/testplayer/testplayer.html, src/core/Settings.js, src/streaming/MediaPlayer.js, src/streaming/controllers/CatchupController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, src/streaming/models/MediaPlayerModel.js, test/unit/mocks/PlaybackControllerMock.js
This PR implements the seeking catchup logic as discussed during the F2F in Berlin. The basic idea is to adjust the liveDelay when the user seeks. Then catchup mode is applied with the new live Delay as target value. At the same time we save the original live delay as calculated during start. By calling `player.seekToLive` the app can jump back to this original live delay.
As part of this PR the `latencyThreshold` parameter has been removed from the settings.
The same mechanism is applied when the user triggers play.
=> Implement new catchup seeking/pausing logic as discussed during F2F

src/streaming/StreamProcessor.js
According to the docs in Settings, the value used by `StreamProcessor` was wrong.
The problem occurred on an environment with high latency and low bandwidth, where segments' length was 3s, which is significantly longer than previously hardcoded 1.5s.
=> Fix stalling when using buffer.fastSwitchEnabled setting

src/streaming/MediaPlayer.js, src/streaming/controllers/MediaController.js, test/unit/streaming.controllers.MediaController.js
* adding BCP-47 module
* use BCP-47 extended filter in settings matcher
- [] create unit test
- [] resolve test error (from 'npm test')
=> make language matching more robust

src/core/Settings.js, src/streaming/controllers/BufferController.js
In WPE WebKit (a WebKit-based embedded browser used in many commercial set-top-boxes), the buffered range of the currentTime has high chances to have been internally enqueued for playback (an action that can't be undone, there's no way to unenqueue other than flushing the whole playback pipeline). If that range is pruned, an internal flush is triggered, but in order to keep playing from the currentTime onwards, the needed samples must be enqueued again at least since the previous sync sample. This can cause a lot of stress to the video decoder and generate stuttering.
This patch solves the problem by avoiding pruning (deleting) ranges belonging to the same buffered range where the currentTime (or seek target) is. This only applies to WebKit based browsers.
See also: …
=> WPE fix: Avoid pruning buffered ranges already enqueued for playback

samples/advanced/timing-object.html, samples/samples.json
This PR adds an example which shows how a dash.js player can be connected to a TimingObject.
The example uses three small libraries that implement parts of the [Timing Object specification](https://webtiming.github.io/timingobject/). I used [JSPM](https://jspm.org/) for now to load those libraries. Please let me know if there is a better way to do this.
The example deliberately disables all the default video controls to make sure they don't interfere with the synchronization. The play and pause buttons are wired up manually.
It might be an option to move this logic into dash.js itself to simplify the process. It could reduce the example to a one-liner in the end.
```js
player.setTimingSrc(timingObject);
```
I think it would also be possible to implement this as an extension which …
=> Add TimingObject example

src/streaming/controllers/MediaController.js, test/unit/streaming.controllers.MediaController.js
This change should fix both https://github.com/Dash-Industry-Forum/dash.js/issues/3961 and also https://github.com/Dash-Industry-Forum/dash.js/issues/3967
More intense testing or samples deemed beneficial.
=> separate settings matcher to work on each property individually

index.d.ts, src/core/Settings.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js
This PR fixes an issue when timescale in manifest differs from timescale in init segments.
This inconsistency can be reproduced using ffmpeg with SegmentTemplate mode: https://trac.ffmpeg.org/ticket/10134
Even though this inconsistency is not conformed to DASH spec, this PR adds robustness to get around this issue.
Test stream that encounters this issue: https://akamaibroadcasteruseast.akamaized.net/cmaf/live/657078/akasource/out.mpd
=> Fix timescale inconsistency

src/streaming/net/HTTPLoader.js
- The return value should match that of the function [`XMLHttpRequest.getAllResponseHeaders()`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders) which returns a string of valid headers, or `null` if no response headers have been received, or empty string on a network error.
- The existing fallback return value (`[]`) would lead to an error when passed to `Utils.parseHttpHeaders()`
=> Corrected fallback responseHeaders value to be `null`

package-lock.json, package.json
Resolves #3371.
I have tested that dash.js build and tests pass successfully with version 1.1.3 of imsc.js.
I have locally packaged a new version of dash.js and tested that subtitles still work on a couple of our test streams that include EBU-TT-D subtitles.
=> chore: Update IMSC.js version to 1.1.3

src/streaming/utils/EBMLParser.js
Currently, [`EBMLParser.getMatroskaUint`](https://github.com/Dash-Industry-Forum/dash.js/blob/0911c2d68caebf7172aeb95740624903cb8d8246/src/streaming/utils/EBMLParser.js#L230-L240) will fail for values exceeding `0x7FFFFFFF` due to JavaScript's bitwise operators converting numbers to 32-bit signed integers. This change should partially improve the handling of values when `size` is 5 or greater, up to [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).
Since JavaScript numbers using 64-bit floats under the hood, this function will still fail if the value would exceed `MAX_SAFE_INTEGER`. As such, an error is thrown in these cases. To resolve this, [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScri …
=> Update getMatroskaUint to handle larger integer values

package.json, src/streaming/text/TextSourceBuffer.js, src/streaming/utils/VTTParser.js
Fix styling of embedded WebVTT cues by adding support for sttg box. Requires addition of the `sttg` box to Isoboxer, see https://github.com/Dash-Industry-Forum/codem-isoboxer/pull/54
=> Fix styling of embedded WebVTT cues by adding support for sttg box

src/streaming/SourceBufferSink.js, src/streaming/controllers/StreamController.js
Fixes [issue/4148](https://github.com/Dash-Industry-Forum/dash.js/issues/4148) by offering client an option to use `useChangeTypeForTrackSwitch` flag to avoid errors involving changeType() not being supported on certain platforms.
=> Fix: changeType() is Not Fully Implemented on Sony PS5

src/streaming/text/TextTracks.js, src/streaming/utils/VTTParser.js
Fixes two issues with the new VTT styling:
**Line**
https://developer.mozilla.org/en-US/docs/Web/API/VTTCue/line it's either a number or "auto". Setting it to a string number throws errors.
**snapToLines**
https://www.w3.org/TR/webvtt1/
> If the last character in linepos is a U+0025 PERCENT SIGN character (%), then let cue’s [WebVTT cue snap-to-lines flag](https://www.w3.org/TR/webvtt1/#webvtt-cue-snap-to-lines-flag) be false. Otherwise, let it be true.
It's true by default.
=> fix: VTT line styling failing, invalid snapToLines value

src/dash/parser/maps/RepresentationBaseValuesMap.js
This addresses: https://github.com/Dash-Industry-Forum/dash.js/issues/4125
This is just a quick hack to get ObjectIron to process `EssentialProperty_asArray` in addition to `EssentialProperty`.
This is required since `DashManifestModel.js/getEssentialPropertiesForRepresentation() only processes `EssentialProperty_asArray`, but not `EssentialProperty`.
I have not checked whether any other entry in `commonProperties` suffers from the same issue.
@dsilhavy : Please comment on how to proceed with this issue - IMHO it would be good to get this fixed for V4.7.0.
(Note: I've not seen any unit test on ObjectIron at all.)
=> Fixing essentialProperties in ObjectIron

index.d.ts
Fixed discrepancy of the "type" variable between the classes FragmentRequest and TextRequest in index.d.ts.
=> Initial, fixed FragmentRequest 'type' typing

src/streaming/net/HTTPLoader.js, src/streaming/rules/abr/lolp/LoLpRule.js
This PR is fixing throughput history by taking into account metrics of aborted requests.
In case of bandwidth dropping leading to aborted requests, this fix enables throughput rule to consider measured throughput (or returned by CMSD response header) on the aborted requests.
=> Fix throughput on abort

src/core/Settings.js
Copy of #4204 as a quick fix until CLA is signed
=> Fix JSDoc in Settings.js

index.d.ts, package-lock.json, package.json, tsconfig.json
the `type` property was fixed in https://github.com/Dash-Industry-Forum/dash.js/pull/4191
this is a follow up fix for the `url` property, and to ensure it never silently fails again.
closes #4210
=> fix(types): TextRequest url property

index.d.ts, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/MediaPlayer.js, src/streaming/controllers/MediaController.js, test/unit/streaming.controllers.MediaController.js
Hi here,
If `streaming.lastMediaSettingsCachingInfo.enabled` is disabled, from my understanding, dash.js should not take last selected track into account.
But from current implementation, if a a track set by `MediaPlayer.setCurrentTrack()`, it will be treated as `lastSelectedTrack`, see L209
https://github.com/Dash-Industry-Forum/dash.js/blob/2ed723974b0d7fabb76b70572dfef271d5d1e342/src/streaming/controllers/MediaController.js#L209
then it will affect which track will be selected, see L64
https://github.com/Dash-Industry-Forum/dash.js/blob/2ed723974b0d7fabb76b70572dfef271d5d1e342/src/streaming/controllers/MediaController.js#L63-L65
So need to get a way to avoid to set  `lastSelectedTrack` when `streaming.lastMediaSettingsCachingInfo` is disabled. `storeLastSettings` seems to be a proper …
=> Fix init value for storeLastSettings

index.d.ts, package-lock.json, samples/multi-audio/multi-audio-default-lang-acc.html, samples/samples.json, src/core/Settings.js, src/dash/DashAdapter.js, src/dash/vo/MediaInfo.js, src/streaming/MediaPlayer.js, src/streaming/constants/Constants.js, src/streaming/controllers/MediaController.js, test/unit/dash.DashAdapter.js, test/unit/streaming.MediaPlayer.js, test/unit/streaming.controllers.MediaController.js
https://github.com/Dash-Industry-Forum/dash.js/issues/4205
This PR addresses:
* settings structure is kept as close as possible with previous version; if used as with v4.x, default schemeIdUri are assumed
* no changes to selection logic except that schemeIdUri are compared as well
* deprecates old elements and uses descriptorType elements only
* updated/cleaned unit test
Let's discuss some details in next week's call (2023-08-10).
=> descriptor type updates v5.0.0

src/streaming/text/TextSourceBuffer.js
**Description:**
Currently, in low latency streams, the sequence number is always set to 1, leading to redundant restarts of embeddedCea608FieldParsers. Consequently, most subtitles are not displayed as expected.
**Proposed Solution:**
To address this issue, I suggest implementing a check for the continuity of the chunks when the sequence number is always 1. By ensuring the proper continuity of the chunks, we can avoid unnecessary parser restarts and ensure the correct display of subtitles during low latency streams.
**The solution is tested and works in production on many LL channels.**
=> Prevent redundant CC parser restarts during Low Latency streams

index.d.ts
We use this method in our codebase but noticed it was missing in the type definitions.
=> Added getTargetLiveDelay method to type definitions

package-lock.json, package.json
This is a 5 year old, unmaintained version of the already used `@babel/preset-env` dependency.
=> Remove `babel-preset-env`

index.d.ts, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/controllers/MediaSourceController.js, src/streaming/controllers/StreamController.js
As discussed on slack https://dashif.slack.com/archives/C11R69M96/p1693394978870319
On WebOS 4.x ( Chrome 53 ) seeking in live content is currently broken because when duration is Infinity seeking back in time causes the seekable end time to move to the seek point so once you’ve seeked back in time you can never go to live again.
The solution is to set the duration of the MediaSource to something high so that you’re not blocked from appending segments eg. Math.pow(2, 32); eg. like shaka https://github.com/shaka-project/shaka-player/blob/main/lib/media/streaming_engine.js#L922
=> add setting to change mediasource duration from infinity to math.pow(2, 32)

AUTHORS.md, index.d.ts, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/MediaController.js, src/streaming/controllers/StreamController.js
Noticed on webOS 4, when switching audio track from one codec to another. A MEDIA_ERR_DECODE error is thrown and `_handleMediaErrorDecode` resets MSE. Waiting for decode error to occur is not favourable, thus introducing a new buffer setting `resetSourceBuffersForTrackSwitch` that resets MSE when we're switching to a new track with a different codec than the active track.
=> Reset MSE when switching codec if changeType is unstable or unavailable

samples/dash-if-reference-player/app/sources.json
There are some updates to BBC R&D DASH test content that we thought may be useful to have in the dash.js reference player. These are made available on our [Adaptive Bitrate Test Media site](https://rdmedia.bbc.co.uk/).
There is also a [post on the BBC Research & Development blog](https://www.bbc.co.uk/rd/blog/2023-10-streaming-media-testing-dash-hls) that details these updates.
The following table details the additions to the list of test streams, including some HEVC variations.
<html><body>
Category | Name
-- | --
Live | Live Testcard - Multiple Languages, AVC Video
Live | Live Testcard - Multiple Languages, HEVC Video
Low-Latency | Low-Latency Live Testcard - 4 Chunks per Segment, Multiple Languages, AVC Video
Low-Latency | Low-Latency Live Testcard - 4 Chunks per Segment, Multiple …
=> Add new BBC R&D Test Streams to Reference Player

src/streaming/controllers/CatchupController.js
When the buffer is safe the playbackRate should still be chosen ( as with the default mode ) based on `deltaLatency` eg. if you _don't_ want to slow down the stream if user is able to play closer to the edge than the target.
=> for lldash use min/max playbackRate when the buffer is safe in mode: liveCatchupModeLoLP

index.d.ts, src/streaming/MediaPlayer.js, src/streaming/controllers/StreamController.js, test/unit/mocks/ManifestUpdaterMock.js, test/unit/mocks/StreamControllerMock.js, test/unit/streaming.MediaPlayer.js, test/unit/streaming.controllers.StreamController.js
Add capability to refresh the manifest through the MediaPlayer API. 
We call this before seeking in a dynamic stream if we expect the steam could become static, to ensure users can't seek past the end.
=> Add MediaPlayer capability to refresh manifest

index.d.ts
`PlaybackErrorEvent` interface definition is duplicated in `index.d.ts`. This commit removes the duplicate.
=> Remove PlaybackErrorEvent duplicate in index.d.ts

index.d.ts
Currently `index.d.ts` has a duplicate and slightly overlapping definition of `MediaPlayerEvents` interface.  Although allowed in Typescript which merges both definitions, it seems to be a needless and confusing duplication.  This commit removes the duplication and replaces it with a union of duplicated interface definitions.
=> Remove MediaPlayerEvents duplicate in index.d.ts

index.d.ts, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/text/TextTracks.js
Closes #4332 by allowing imscJS's `displayForcedOnlyMode` and `enableRollUp` parameters to be configured in `settings.streaming.text.imsc.displayForcedOnlyMode` and `settings.streaming.text.imsc.enableRollUp`. Adds configuration check-boxes to the reference player to allow them to be adjusted at playback time.
=> Add text.imsc settings for rollUp and displayForcedOnly

src/streaming/text/TextTracks.js
This is detailed further in issue #4358.
This is a proposed fix to prevent subtitle flickering, where the time between removal and appending of divs representing subtitle cues can have gaps in between. Using the stream in the reference player titled “[BBC] On-demand Elephant's Dream - with EBU-TT-D 'Snaking' Subtitle Track (random text) - lines grow over time simulating live subtitles”, it’s clear to see the effect before and after this code is applied.
These changes preserve the work done by @bbert in #4103 & #4155. Extending identical cues is still preserved and I have checked [the test stream mentioned in the PR](https://broadpeak-tv.github.io/test-content/dash/imsc-image/imsc1_img.mpd) still operates as expected. Additionally, this PR doesn’t affect the operation of WebVTT subtitles …
=> Fix flickering/blinking IMSC Subtitles

index.d.ts, src/dash/controllers/ContentSteeringController.js, src/dash/models/DashManifestModel.js, src/dash/vo/BaseURL.js, src/streaming/metrics/reporting/reporters/DVBReporting.js, src/streaming/metrics/utils/ManifestParsing.js, src/streaming/metrics/vo/Reporting.js, src/streaming/utils/baseUrlResolution/DVBSelector.js, test/unit/dash.models.DashManifestModel.js, test/unit/streaming.utils.DVBSelector.js
As mentioned in #4338, it would be preferable if existing references to DVB extension properties consistently use camelCase. This should handle the following MPD elements@dvb extensions.
- BaseUrl@dvb:priority
- BaseUrl@dvb:weight
- Reporting@dvb:reportingUrl
- Reporting@dvb:probability
=> Consistent use of camelCase for DVB extension properties

index.d.ts, test/unit/streaming.controllers.PlaybackControllers.js
`PlaybackErrorEvent` when triggered in `PlaybackController`, attaches the original `MediaError` as `error` property.  This commit corrects the TS typing to reflect that.
See here for reference: https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/controllers/PlaybackController.js#L714
We've encountered this as we pass errors using `MessageBus` and we failed to serialise this one as it carries an `object` property (thus becomes an `object` itself) which was not correctly reflected in `PlaybackErrorEvent` TS type.
Also see here: https://html.spec.whatwg.org/multipage/media.html#dom-media-error
=> Fix PlaybackErrorEvent error TS typing

src/streaming/net/HTTPLoader.js
due to abusive copy/paste error
=> [v5] Fix CommonMediaResponse resourceTiming.encodedBodySize

src/streaming/models/ThroughputModel.js, src/streaming/net/HTTPLoader.js
in case PerformanceResourceTiming is not usable (due to cross-origin restrictions)
=> [v5] Fix CommonMediaResponse.resourceTiming info

index.d.ts, samples/abr/abr.html, samples/abr/custom-abr-rules.html, samples/dash-if-reference-player/app/main.js, samples/low-latency/testplayer/main.js, src/core/Settings.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/ThroughputController.js, src/streaming/net/HTTPLoader.js, src/streaming/rules/abr/ABRRulesCollection.js, src/streaming/rules/abr/AbandonRequestsRule.js, test/unit/streaming.rules.abr.ABRRulesCollection.js
This PR addresses #3840 
* The `AbandonRequestRule` now uses the traces that are populated in the `_onprogress` event of `HTTPLoader`. The current throughput is calculated based on these traces aalso removing the first sample from the calculation as it includes latency.
* Removed `fragmentDict` and `throughputArray` from `AbandonRequestRule` as they are not needed and blow up the code.
* Allow configuration of the relevant parameters for the `AbandonRequestRule` via `Settings.js`. 
* Refactor the code in `AbandonRequestRule` for better structuring and easier understanding.
=> Improve the AbandonRequestsRule.js by using traces from progress event

index.d.ts, src/core/Settings.js, src/streaming/controllers/PlaybackController.js
On low end devices, we noticed an increasing burden on the CPU during live streams. This setting adds a threshold that must be passed in order for `PlaybackController` to push another time sync instruction during dynamic manifests.
This is very comparable to `wallclockTimeUpdateInterval` but it does not interfere with other logic based on wall clock such as gap jumping (which is a way less heavy instruction for low end CPU's to handle).
=> Added liveUpdateTimeThreshold to control time syncing during live streams

src/core/Settings.js, src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/dash/vo/DescriptorType.js, src/dash/vo/MediaInfo.js, src/streaming/constants/Constants.js, src/streaming/thumbnail/ThumbnailTracks.js, src/streaming/utils/Capabilities.js, test/unit/dash.DashAdapter.js, test/unit/dash.models.DashManifestModel.js, test/unit/streaming.utils.Capabilities.js
* adding option to register custom essentialProps in preferences to make them known in Capabilities.js
* expose essentialProps in MediaInfo
=> enhanced essential property handling

src/core/Utils.js, src/streaming/constants/Constants.js, src/streaming/controllers/CommonAccessTokenController.js, src/streaming/net/HTTPLoader.js, test/unit/core.Utils.js, test/unit/streaming.controllers.CommonAccessTokenController.js
This PR adds basic support for the `Common Access Token` as requested in #4395.
* Adds a new `CommonAccessTokenController` that manages the access tokens for the different hosts
* Adds a new function in `Utils` to extract the host from a given URL
* Enhances the `HttpLoader` to call the `CommonAccessTokenController` for each request and response. The goal is to extract the Common Access Token and save it for future requests. The `common-access-token` is added for each request to a specific host
=> Add basic support for the Common Access Token

src/streaming/net/FetchLoader.js, src/streaming/net/HTTPLoader.js, src/streaming/net/XHRLoader.js, test/unit/streaming.net.XHRLoader.js
This PR is fixing HTTPLoader in order to apply network response interceptors in all use cases, including aborted requests, request on timeout and for all error types (HTTP errors or network error)
=> Fix HTTPLoader

index.d.ts
`KeyErrorEvent` is triggered with `error` (`DashJSError`) instead of `data`.
`KeySystemSelectedEvent` has incorrect `error` type:  it's `DashJSError` as well instead of `string`.
As a result, `KeyError` type becomes redundant and can be removed.
`KeyErrorEvent` is triggered here:
https://github.com/search?q=repo%3ADash-Industry-Forum%2Fdash.js+path%3A%2Fsrc%2Fstreaming%2Fprotection%2Fmodels%2F*+KEY_ERROR&type=code
`KeySystemSelectedEvent` is triggered here:
https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/protection/controllers/ProtectionController.js#L249
=> Fix TS typings for KeyErrorEvent and KeySessionCreatedEvent error

test/functional/config/karma.functional.conf.cjs
Overcome the following error:
15 04 2024 12:43:51.521:WARN [Chrome 123.0.0.0 (Windows 10)]: Disconnected (3 times) reconnect failed before timeout of 2000ms (transport close)
=> Adjust disconnect values for functional Karma tests

src/streaming/controllers/CatchupController.js
- This avoids the situation where the playbackrate can get stuck at a non 1.0 rate, if the rate change is less than minPlaybackRateChange. If even a small non 1.0 playbackrate persists it leads to playback buffer and latency decrease (or increase) over time.
=> Override the minPlaybackRateChange check when newRate=1.0

index.d.ts
Found a few TS overrides in my code, they're better off being fixed upstream.
```javascript
// Types that are missing or wrong in dashjs, should push this upstream too.
declare module "dashjs" {
class DashAdapter {
getAvailabilityStartTime(externalManifest?: object): number;
getIsDynamic(externalManifest?: object): boolean;
getDuration(externalManifest?: object): number;
}
}
```
=> TypeScript - externalManifest is optional for several methods.

src/streaming/models/MediaPlayerModel.js
This will make it possible to disable catchup with seeking as described in the documentation.
Problem explained in issue #4527
=> Update liveCatchup.maxDrift logic to allow zero value.

build/webpack.base.cjs, build/webpack.dev.cjs, build/webpack.prod.cjs
This PR adds support for ECMAScript Modules (ESM). It adjusts the webpack build script to provide an ESM bundle in the `dist/esm` folder.
I would like to collect feedback on this PR to understand if this is what is required by dash.js users and if this is the preferred way to implement it. 
This addresses #4190
=> Output ESM via webpack build script

src/streaming/controllers/MediaController.js
This PR adds the ability to set initial media settings using ID and filter tracks by their id.
This is necessary so that in the absence of other parameters (lang, index, viewPoint, role, accessibility, audioChannelConfig, codec) it was possible to uniquely initialize the track
=> Add matchSettingsId to mediaController

src/core/Utils.js, src/streaming/ManifestUpdater.js, test/unit/test/core/core.Utils.js, test/unit/test/streaming/streaming.ManifestUpdater.js
This fixes an issue reported on Slack causing the CMCD string to be appended multiple times to the MPD requests
=> Remove outdated CMCD parameters from MPD request

src/dash/DashAdapter.js, src/dash/constants/DashConstants.js, src/streaming/utils/CapabilitiesFilter.js, test/unit/mocks/AdapterMock.js
Let me know if you need a copy of the spec.  With this change, DolbyVision Profile 8 now works.
For example, on Windows11 with DolbyVision:
* manifest: https://ott.dolby.com/browser_test_kit/cbcs/p81/24/dash.mpd
* playready license url: https://playready.ezdrm.com/cency/preauth.aspx?pX=DCB4DB
* robustness: 3000
=> Add support for scte214:supplementalCodecs

src/dash/models/DashManifestModel.js
ProducerReferenceTime's id attribute should be as `xs:unsignedInt`
=> Fix ProducerReferenceTime id attribute parsing

index.d.ts, src/dash/models/DashManifestModel.js
Event's id attribute should be as `xs:unsignedInt`
=> Fix Event id attribute parsing

build/webpack.base.cjs
Address #4619 and transform to plain ES5 code. This is done to enable easy testing on all platforms. The configuration will be revisited before the release of v5.
=> Transpile to plain ES5

build/webpack.base.cjs, package-lock.json, package.json
Change the babel and webpack config to polyfill missing functionality for the defined babel target.
This is the next attempt to solve #4619. The missing functions like `Object.values` should be polyfilled by `core-js`now. This needs to be optimized, probably providing different build jobs later for different targets. Like a legacy build with polyfills for older platforms and a default build for modern browsers.
=> Change the babel and webpack config to polyfill missing functionality

index.d.ts, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/StreamController.js, test/unit/test/streaming/streaming.utils.Capabilities.js
This fixes an issue that was reported on Slack by @Murmur. 
> Multiperiod test stream randomly stops on V5 but V4.7.4 playbacks forever, tested on Win10-Edge/FF/Chrome. [See this test stream](https://refapp.hbbtv.org/videos/multiperiod_v9.php?drm=0&advert=1&scte=1&emsg=0&video=v1,v2,v3&audiolang=eng,fin&sublang=0&mup=2&spd=8&config=multiperiod_00llama_h264_scte)  Logs does not tell anything I can think of but the video buffer goes empty.
Two main changes in this PR:
With v5 we take the duration of the next media segment to be downloaded into account when checking if we would exceed the buffer target. That can lead to a later media segment download compared to v4 in which we only compared the current buffer level to the target buffer (no consideration of the duration of the next media …
=> Fix issues for multiperiod preloading

package.json
Based on https://github.com/Dash-Industry-Forum/dash.js/issues/4664#issuecomment-2621554195 this PR exports the MSS bundles from the `package.json`
=> Add ./mss MSS bundles to package.json

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, test/unit/test/dash/dash.DashAdapter.js, test/unit/test/dash/dash.models.DashManifestModel.js
This PR re-establishes the use case that Supplemental- and EssentialProperties can be assigned to either AdaptationSets or Representations.
=> propagate Properties common to all Representations to MediaInfo

src/streaming/protection/controllers/ProtectionController.js, test/functional/config/test-configurations/streams/smoke.json
This fixes #4692 . In a multiperiod MPD with new key ids for each period dash.js was filtering Representations assuming no valid key is present
=> Fix a bug that lead to filtering of a track in multiperiod MPDs

index.d.ts, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/controllers/BufferController.js
In some cases when using Dash.js in Low Latency mode - seen in this caue with chunks of 0.96s in duration, `BUFFER_EMPTY` events are not raised when the player is observed to stall.
Current operation has a catch for low-latency mode in the `checkIfSufficientBuffer` within the `BufferController` which says if the player is in low latency mode only when the buffer reaches 0 is a `BUFFER_EMPTY` raised.
In some low latency use cases the player can stall in low-latency mode with a buffer level greater than 0. Particulary when chunk sizes are greater than just a handful of frames.
Outside of low-latency mode the BUFFER_EMPTY event is raised whenever the buffer is below the `stallThreshold` setting. Set by default to 0.3s.
This PR solves the above by adding a seperate `lowLatencyStallThreshold` …
=> Add Low Latency Stall Threshold

src/streaming/text/TextSourceBuffer.js
In case of TTML parsing error, dash.js raise a javascript error:
With this fix:
=> Fix TTML parsing error catching

index.d.ts, src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/utils/CapabilitiesFilter.js, test/unit/mocks/AdapterMock.js, test/unit/test/dash/dash.models.DashManifestModel.js
This fixes a small bug that did not account for framerates defined in the format "x/y" when checking for support with the Media Capabilities API
=> Calculate correct framerate when using MediaCapabilitiesAPI

index.d.ts, src/core/Settings.js, src/streaming/constants/AudioChannelConfiguration.js, src/streaming/constants/Constants.js, src/streaming/controllers/MediaController.js, test/unit/test/streaming/streaming.constants.AudioChannelConfiguration.js, test/unit/test/streaming/streaming.controllers.MediaController.js
this improves track selection as discussed here: https://github.com/Dash-Industry-Forum/dash.js/issues/4701
=> improvements on (audio) track selection

index.d.ts, src/core/Settings.js, src/streaming/controllers/EventController.js
This fixes #4740.
The idea is to allow applications to define a timeout, after which the message data of an event is deleted. This timeout value is relative to the start time of an event.
The PR also removes the logic to clone events to avoid the performance issues described in #4740. The previously described timeout should provide applications with enough time to create a copy of an event if required.
If people have suggestions for a more elegant solution, I am open to changing this behavior.
=> Addresses performance issues for event dispatching

AUTHORS.md, package-lock.json, package.json
see: #4711 & https://github.com/streaming-video-technology-alliance/common-media-library/issues/190
=> fix: allow large ints to be passed in as time values for processUriTemplate

src/streaming/text/TextTracks.js, src/streaming/utils/VTTParser.js, test/unit/test/streaming/streaming.utils.VTTParser.js
Closes #4771
Fixes #4765 
I also did some quick performance tests with a large file (40k cues), and it seems like these changes reduced the parsing time in ~60%.
=> [VTTParser] Support for lineAlign and positionAlign

src/streaming/utils/VTTParser.js
Fixes a regression introduced in #4773
=> Fix regression when setting size of VTT cue

src/streaming/models/VideoModel.js
This workaround should no longer be needed.
[Example](https://cdpn.io/cpe/boomboom/index.html?editors=1011&key=index.html-a4f8b9b5-68e0-2c5c-d0b6-7399f093b82d) of a `preload="metadata"` video element firing `canplay`
=> Avoid modifying element preload attribute as canplay event is baseline in Firefox

index.d.ts
This changes the `id` parameter of `setRepresentationForTypeById` from `number` to `string` to match `Representation['id']`.
Fixes https://github.com/Dash-Industry-Forum/dash.js/issues/4820
=> TypeScript fix for MediaPlayerClass

index.d.ts, test/unit/mocks/RulesContextMock.js
* DashAdapter: Rename getVoRepresentation to getVoRepresentations
* StreamProcessor: Remove getVoRepresentation
* RulesContextMock: Remove getVoRepresentation which doesn't exist in RulesContext
Code references:
* [DashAdapter](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/dash/DashAdapter.js#L1261)
* [StreamProcessor](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/StreamProcessor.js#L1513-L1546)
* [RulesContext](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/rules/RulesContext.js#L93-L105)
=> TypeScript fix for DashAdapter and StreamProcessor

src/dash/utils/TimelineSegmentsGetter.js
Fellow-up of https://github.com/Dash-Industry-Forum/dash.js/pull/3928
This PR is fixing a bug when searching a segment in a SegmentTimeline of next period from a requested media time.
In some cases, due to lost precision, no segment of next period will be found, so playback stalled.
For example, with following timeline:
```
<SegmentTemplate timescale="1000000" presentationTimeOffset="1755760276636011" startNumber="292626713" media="media_$RepresentationID$-$Number$.m4s" initialization="init_$RepresentationID$.m4s">
<SegmentTimeline>
<S t="1755760276636011" d="6006000" r="3" />
</SegmentTimeline>
</SegmentTemplate>
```
If you seek and request segment at time 1755760276.636011 the TimelineSegmentsGetter will fail to find a segment due to `precisionRound` returns 1755760276636010.
=> fix: can't switch to next period due to precision
