- app/js/dash/DashHandler.js
This was breaking for SegmentList manifests with SegmentURLs missing a
"media" attribute (e.g. MP4Box may produce these). Section 5.3.9.3.2 of
the dash spec says that the media element should default to any BaseURL
element in this case.
> SegmentURL: Default to baseUrl when "media" attribute absent

- app/js/streaming/rules/ABRRules/LimitSwitchesRule.js
Too much chatter in logs that is not needed.
> commenting out log lines in limitswitchrule

- app/js/streaming/rules/ABRRules/LimitSwitchesRule.js
92bdb99 removed all references to self in LimitSwitchesRule:execute which causes JSHint to error.
Removed self.
> Fix JSHint error due to unused self

- build/package.json
See #368.
tl;dr it's nicer not to see warnings when installing the package, and the right version number.
> Fix npm install warnings [low priority]

- src/streaming/rules/SchedulingRules/BufferLevelRule.js
#283 and #345 relate to a problem with presentations longer than 600s. When long presentations are detected, the player allows buffering much further ahead (300s vs 30s) which can fill the source buffer if the representation bit-rate is high.
It has been observed that, as the buffer becomes full, Chrome does not appear to follow correctly the coded frame eviction algorithm which can cause frames at the current play head to be evicted, leading to playback stalling unrecoverably. I am not sure if IE is affected.
Whilst this is clearly a UA issue, I believe that dash.js needs to work around this type of problem until it is fixed. Limiting the buffer length to thirty seconds regardless of presentation duration solves this in the short term.
Our research suggests that it is not sensible to …
> Address issues #345, #283 - unrecoverable video stall

- samples/dash-if-reference-player/index.html
- src/streaming/Stream.js
- src/streaming/controllers/ProtectionController.js
- src/streaming/extensions/ProtectionExtensions.js
- src/streaming/models/ProtectionModel.js
- src/streaming/models/ProtectionModel_01b.js
- src/streaming/models/ProtectionModel_3Feb2014.js
- src/streaming/protection/CommonEncryption.js
- src/streaming/protection/drm/KeySystem.js
- src/streaming/protection/drm/KeySystem_ClearKey.js
- src/streaming/vo/protection/ClearKeyKeySet.js
- src/streaming/vo/protection/KeyPair.js
I have developed a KeySystem implementation that will allow the playback of ClearKey DRM protected content.  ClearKey support is mandated by the W3C Encrypted Media Extensions specification, however it does not define anything except the format of the message that should be passed to add keys to a session.  Specifically, it does not define an initialization data format so that the application would know how to retrieve the keys.
I have developed a new PSSH box definition that allows the decryption keys to be retrieved from:
* The content itself (in the PSSH)
* A remote server using a simple URL with query string arguments
The PSSH format is documented in KeySystem_ClearKey.js (requestClearKeyLicense() function).  I will be posting some encrypted test content in a few days that will …
> Proposed Clearkey DRM Support

- .travis.yml
- build/package.json
The current travis builds doesn't actually run any tests. In fact the .11 nodejs build even writes "Error: no test specified"
The only reason they are marked as passed, is that "cd build" makes them return 0. This fixes it, so it actually testes the builds.
> Fix travis builds

- src/dash/TimelineConverter.js
use new Date, only one time. getTime is done in calcPresentationTimeFromWallTime function.
> Remove unuseful New Date call.

- src/streaming/models/ProtectionModel_21Jan2015.js
protectionExt parameter is used in createKeySession function, but it's not defined.
> Bug in new EME version management

- samples/dash-if-reference-player/app/sources.json
- src/streaming/extensions/ProtectionExtensions.js
- src/streaming/models/ProtectionModel_21Jan2015.js
- src/streaming/models/ProtectionModel_3Feb2014.js
- src/streaming/protection/CommonEncryption.js
- src/streaming/protection/drm/KeySystem_ClearKey.js
- src/streaming/vo/protection/ClearKeyKeySet.js
- src/streaming/vo/protection/KeyPair.js
- src/streaming/vo/protection/ProtectionData.js
[The EME spec has been updated to add much more detail to the ClearKey key system.](https://w3c.github.io/encrypted-media/#clear-key)  This includes a newly defined [PSSH format](https://w3c.github.io/encrypted-media/cenc-format.html#common-system) for ClearKey.  With the release of Chrome 41, this makes the previous version of ClearKey incompatible.  This PR updates dash.js to support the latest ClearKey on Chrome 41+.
One caveat of having the PSSH defined in the spec is that we are no longer free to come up with our own formats.  Previously, this freedom was used to define a format that allowed carriage of keys within the PSSH itself.  Since this is no longer possible, and since we do not want to require an external ClearKey license server for testing purposes, there is now a set of …
> Updates to Support Latest Clearkey

- src/dash/extensions/DashManifestExtensions.js
Pushing  MAX_VALUE workaround into dev branch. we can not wait for chrome to fix and leave live streaming broken.
> Temp workaround for issue #428

- samples/dash-if-reference-player/app/sources.json
- src/streaming/protection/CommonEncryption.js
- src/streaming/protection/drm/KeySystem_ClearKey.js
- src/streaming/protection/drm/KeySystem_Widevine.js
Added a standard way to support initData in the MPD for both
Widevine and ClearKey.  A Widevine representative has confirmed
that this is the standard way to format their ContentProtection
element.  For ClearKey, I have chosen to use the same format,
since it is very simply and works well.
Updated the sources.json to add new test content for common encryption
with and without init data present in the MPD.
Removed PlayReady/ClearKey content from the sources.json.  IE11 does
not support PSSH version 1 (which ClearKey requires).  Just the presence
of the ClearKey PSSH in the file causes an error, so we won't be able
to test this combination of DRMs until the next version of IE (Spartan)
is released.
> Support initData in MPD for ClearKey and Widevine

- samples/dash-if-reference-player/index.html
- src/dash/controllers/RepresentationController.js
- src/dash/extensions/DashManifestExtensions.js
- src/dash/vo/Representation.js
- src/streaming/Context.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/StreamController.js
- src/streaming/utils/DOMStorage.js
- src/streaming/utils/LocalStorage.js
During playback when a quality level changes it is recorded into local storage now. 
Upon starting a stream this information is retrieved and if it not expired (< 1 hour old) then it is used to pick the starting quality for playback. If it is not present or expired we default back to the bit rate nearest 1000kpbs
> Feature to make auto selecting a starting bit rate a little more intelligent.

- src/streaming/controllers/PlaybackController.js
Using a #s= URI fragment to set the start time wasn't working. See https://github.com/Dash-Industry-Forum/dash.js/commit/1b7fef1ced77e3418f2adb078a7e43894608ac52#diff-e221af84d9071cb5d32527f0192eb867.
> fix getting URI fragment start time

- src/dash/controllers/RepresentationController.js
- src/dash/extensions/DashMetricsExtensions.js
- src/streaming/MediaPlayer.js
- src/streaming/StreamProcessor.js
- src/streaming/controllers/AbrController.js
- When switching multi-bitrate content (auto or manual mode) this property specifies the maximum bitrate allowed.  
- If you set this property to a value lower than that currently playing, the switching engine will switch down to  satisfy this requirement. 
- If you set it to a value that is lower than the lowest bitrate, it will still play that lowest bitrate.
- If you set this property lower than the initial bitrate value it will start on the lower value of the two.
- You can set or remove this bitrate cap at anytime before or during playback.  
- To clear this setting you must use the API and set the value param to NaN. 
- This feature is typically used to reserve higher bitrates for playback only when the player is in large or full-screen format.
> Added API and ability to set maximum bitrate cap

- src/streaming/StreamProcessor.js
- src/streaming/rules/ABRRules/InsufficientBufferRule.js
reset the value of bufferStateDict[type].firstBufferLoadedEvent each
time seeking occurs.
Also use fragment duration to detect lowBuferMark.
> Seek bug in InsufficientBufferRule

- samples/dash-if-reference-player/app/contributors.json
Fix a broken link to the Fraunhofer page
> Fix broken FH link

- build/test/js/dash/TimeLineConverterSpec.js
- src/streaming/MediaPlayer.js
- src/streaming/TimeSyncController.js
- src/streaming/controllers/StreamController.js
Added two new steps to live edge detection before binary search kicks in
1. If UTCTiming is not defined in the manifest not there is a default time scheme and time server defined. There is an API to add more time servers, to remove time servers and to clear all time servers.  
2. If you clear all time servers AND have exposed the Date header that value will be used instead of calling a time server, if non of the above exist, the binary search will be used.
> Added two new steps to live edge detection

- src/streaming/ManifestLoader.js
Fixes issue #481 - see that for more details.
- IE does not currently provide a responseURL property for requests. Instead, it will currently continue to have the same behaviour it does now.
- This covered all requests it needed to from what I can see, but if I missed any out, let me know
> Follow redirects for the manifest file

- samples/dash-if-reference-player/index.html
- src/streaming/Context.js
- src/streaming/FragmentLoader.js
- src/streaming/MediaPlayer.js
- src/streaming/StreamProcessor.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/rules/ABRRules/ABRRulesCollection.js
- src/streaming/rules/ABRRules/AbandonRequestsRule.js
- src/streaming/rules/ABRRules/BufferOccupancyRule.js
- src/streaming/rules/ABRRules/InsufficientBufferRule.js
- src/streaming/rules/ABRRules/ThroughputRule.js
- src/streaming/rules/SchedulingRules/AbandonRequestsRule.js
- src/streaming/rules/SchedulingRules/SameTimeRequestRule.js
- src/streaming/rules/SchedulingRules/ScheduleRulesCollection.js
- src/streaming/vo/FragmentRequest.js
This feature will abandon fragments that are going to take too long (more than fragment duration * multiplier ) to download and call for a switch to a quality that matches the real time measured bandwidth during download progress. This feature will only work when parallel request are turned off. (off by default now)
A new API was created in MP to allow to set the number of parallel requests desired.
> Segment abandonment as an ABR rule instead of Scheduling rule.

- src/streaming/rules/ABRRules/AbandonRequestsRule.js
- src/streaming/rules/ABRRules/ThroughputRule.js
moved check in throughput rule below where averaged so that during abandonment lockout we have accurate averaging.
> Small bug fix in abandonment logic

- src/dash/TimelineConverter.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/rules/ABRRules/ThroughputRule.js
- src/streaming/rules/SynchronizationRules/LiveEdgeWithTimeSynchronizationRule.js
when trackInfo.useCalculatedLiveEdgeTime = true need to use the actual live edge.  Added same code to LiveEdgeWithTimeSynchronizationRule that exists in LiveEdgeBinarySearchRule since we fork based on new live edge logic and never reach the logic in LiveEdgeBinarySearchRule unless the API is used to force binary search.
> Live edge fix

- src/streaming/ManifestLoader.js
Initialize baseUrl to "" instead of null so that if the Manifest
URL is relative without a "/", then we return an empty baseUrl
rather than null. Without this change, if a manifest url is
relative without a "/", then the media URL will be resolved as
null + media_url. Where as the correct media URL will be
"" + media_url.
> ManifestLoader: Initialize baseUrl to "" instead of null.

- src/dash/controllers/RepresentationController.js
- src/streaming/models/MetricsModel.js
Fix for issue #570 
When manifests are loaded outside the player, no metrics will be collected for those manifest updates.  Once the manifest is attached to the player for playback of the media, manifest update metrics will resume collection.
The code changes in this PR simply prevent null-reference exceptions when manifest update information is not available.
> Don't update metrics for externally loaded manifests

- samples/dash-if-reference-player/app/sources.json
- src/streaming/Stream.js
- src/streaming/controllers/ProtectionController.js
- src/streaming/controllers/StreamController.js
- src/streaming/extensions/ProtectionExtensions.js
- src/streaming/models/ProtectionModel.js
- src/streaming/models/ProtectionModel_01b.js
- src/streaming/models/ProtectionModel_21Jan2015.js
- src/streaming/models/ProtectionModel_3Feb2014.js
ProtectionController now managed at the StreamController instead of
Stream to prevent destroying key information when changing periods
Better support for preventing session creation for initialization data
we have already seen
New multi-period, protected content added to sources list
Moved key system selection out of ProtectionExtensions.  The parts of
key system selection that apps would want to change (returning
prioritized list of keys systems, etc) are still in extensions.
> Fixes for multi-period protected content

- src/streaming/TTMLParser.js
<tt:br> elements can be used to insert a forced line break in a <tt:span> element. The XML parser strips these out so the TTML parser needed additional logic to construct the cue text correctly.
While I was in there, I fixed issue #604. Thanks to @TobbeMobiTV for the fix.
> Respect tt:br elements in tt:span elements.

- samples/dash-if-reference-player/app/sources.json
Add main manifests from http://rdmedia.bbc.co.uk/dash/ondemand/testcard/ and http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/ to test stream drop down.
Note that these streams are delivered on a best efforts basis and are subject to change so we recommend they are always accessed through the index page.
> Add BBC Testcard and EBU-TT-D reference streams

- src/streaming/MediaPlayer.js
- src/streaming/controllers/ProtectionController.js
- src/streaming/controllers/StreamController.js
- src/streaming/models/ProtectionModel.js
- src/streaming/models/ProtectionModel_21Jan2015.js
- src/streaming/models/ProtectionModel_3Feb2014.js
Added events to allow the protection system to be torn down asynchronously.  Since the latest EME APIs are mostly asynchronous, this is necessary to ensure proper shutdown prior to changing streams.
Shutdown the media source before shutting down the protection system.  On Chrome, this is necessary because MediaKeys can not be set to null until the src has been cleared.
> Bug # 623 Async Protection teardown

- src/streaming/StreamProcessor.js
- src/streaming/controllers/ScheduleController.js
onLiveEdgeSearchCompleted was called before the currentTrackInfo is valid,
since this is only valid once the segment list has been generated.
The fix is to ensure that the DATE_UPDATE_COMPLETED handler for the
schedule controller is called before that of the stream (by subscribing
them in the correct order). This ensures that the current track info is
valid before the live edge search is started and there is something for
the live edge search completed handler to reference.
Additionally, scheduling is no longer started in the live edge search
complete handler but in the stream updated handler, as (I think) was
intended when that handler was added.
> Uninitialized currentTrackInfo cause assertion in onLiveEdgeSearchCompleted at availabilityStartTime

- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/StreamController.js
While testing Firefox MSE implementation a couple of issues were noted:
- Event.srcElement is not available in Firefox. Event.target should be preferred where available. (#590)
- I noticed that e.error was needlessly logged on video error when it was not defined, adding nothing helpful to the logs.
> Use Event.target not Event.srcElement where possible

- src/streaming/controllers/StreamController.js
- src/streaming/rules/SynchronizationRules/LiveEdgeWithTimeSynchronizationRule.js
Fix for issue #619 - Will not make time source attempt for static streams unless UTC timing in manifest advise to do so.
Partial Fix for issue #601
* Avoids using "utc timing sources or date header if SegmentTimeline is present.  
* Maintains the same live edge detection steps as 1.4 if not SegmentTimeline.
* Will still use MPD  based time sources if present (same functionality as 1.3)
> Fix for Issue #619 & Partial fix for #601

- src/streaming/Context.js
- src/streaming/ManifestLoader.js
Since we've made ManifestLoader a class, we also need to make ```XlinkController```/```Loader``` classes as well.  ```ManifestModel``` is updated when xlink resolution is completed, but we don't want to update ```ManifestModel``` when we allow applications to load their own manifests (```MediaPlayer.retrieveManifest()```) with their own ```ManifestLoader``` instance.
> Convert XlinkController/Loader to classes

- build/jsdoc/jsdoc_conf.json
- src/dash/DashCreate.js
- src/streaming/Context.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/ProtectionController.js
- src/streaming/extensions/ProtectionExtensions.js
- src/streaming/models/ProtectionModel.js
- src/streaming/models/ProtectionModel_01b.js
- src/streaming/models/ProtectionModel_21Jan2015.js
- src/streaming/models/ProtectionModel_3Feb2014.js
- src/streaming/protection/drm/KeySystem.js
- src/streaming/protection/drm/KeySystem_Access.js
- src/streaming/protection/drm/KeySystem_ClearKey.js
- src/streaming/protection/drm/KeySystem_PlayReady.js
- src/streaming/protection/drm/KeySystem_Widevine.js
- src/streaming/protection/servers/ClearKey.js
- src/streaming/protection/servers/DRMToday.js
- src/streaming/protection/servers/LicenseServer.js
- src/streaming/protection/servers/PlayReady.js
- src/streaming/protection/servers/Widevine.js
- src/streaming/vo/protection/ClearKeyKeySet.js
- src/streaming/vo/protection/KeyError.js
- src/streaming/vo/protection/KeyMessage.js
- src/streaming/vo/protection/KeyPair.js
- src/streaming/vo/protection/KeySystemAccess.js
- src/streaming/vo/protection/KeySystemConfiguration.js
- src/streaming/vo/protection/LicenseRequestComplete.js
- src/streaming/vo/protection/ProtectionData.js
- src/streaming/vo/protection/SessionToken.js
Most all of the protection system has decent JSDocs now.  Also updated some related MediaPlayer documentation to help fill out some of the JSDoc links
Users must update to the latest grunt-jsdoc module because the new documentation depends on JSDoc 3.3.
> Add JSDocs to all protection/DRM-related code

- src/streaming/MediaPlayer.js
Adding getter for system in MediaPlayer so I can access object that I override with custom context and set properties on extension object.
> Adding getter for system in MediaPlayer

- src/streaming/MediaPlayer.js
Per @greg80303 comments in PR #653 making this a little more abstracted so you can not access system externally.
> changed API to not return system but object based on context string name.

- src/streaming/controllers/PlaybackController.js
PlaybackController.removeAllListeners does not stop listening for canplay. For symmetry, unlisten for this event.
> removeAllListeners does not remove all listeners

- src/dash/controllers/RepresentationController.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/ScheduleController.js
Following 33e5a74, streams which have availabilityStartTime in the future would fail to play. This is because the live edge calculated in onLiveEdgeSearchCompleted changed to be a runtime configured value of multiples of segment duration which turned out to be more than the hardcoded delay in postponeUpdate. The outcome was that startTime would be calculated to be negative and a valid segment at which to start could never be found.
Fix by ensuring postponeUpdate waits the same amount of time as will subsequently be subtracted, and also belt and braced by ensuring that startTime can never be negative.
There are probably a ton of other magic numbers we need to weed out, but this was noticed as we are currently experimenting with publishing manifest with future aSTs and they were failing to …
> Fix live offset when availabilityStartTime in future

- samples/dash-if-reference-player/app/eme-main.js
- samples/dash-if-reference-player/app/sources.json
- samples/dash-if-reference-player/eme.html
- src/streaming/controllers/ProtectionController.js
- src/streaming/extensions/ProtectionExtensions.js
- src/streaming/models/ProtectionModel_01b.js
- src/streaming/models/ProtectionModel_21Jan2015.js
- src/streaming/models/ProtectionModel_3Feb2014.js
- src/streaming/protection/servers/ClearKey.js
- src/streaming/protection/servers/DRMToday.js
- src/streaming/protection/servers/LicenseServer.js
- src/streaming/protection/servers/PlayReady.js
- src/streaming/protection/servers/Widevine.js
- src/streaming/vo/protection/KeyMessage.js
- src/streaming/vo/protection/KeySystemConfiguration.js
- src/streaming/vo/protection/LicenseRequestComplete.js
- src/streaming/vo/protection/ProtectionData.js
- src/streaming/vo/protection/SessionToken.js
In order to fully support persistent key sessions, we need to handle other types of CDM messages besides just "request-license".  When key sessions are closed, the CDM may generate a "license-release" message so that the license server knows that the keys associated with the license are no longer usable by the client.  In the case of a "check-out/check-in" use case where a piece of content may be played on no more than X clients simultaneously, it is the responsibility of the client to inform the license server when licenses are requested and released.  [There are other license server messages defined by EME as well](https://w3c.github.io/encrypted-media/#idl-def-MediaKeyMessageType).
***Note: the only platform that currently supports persistent sessions is Chrome OS, so you will need a …
> Persistent key session and CDM "message type" support

- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/app/metrics.js
- samples/dash-if-reference-player/index.html
- src/dash/DashHandler.js
- src/dash/extensions/DashMetricsExtensions.js
- src/streaming/FragmentLoader.js
- src/streaming/ManifestLoader.js
- src/streaming/XlinkLoader.js
- src/streaming/models/MetricsModel.js
- src/streaming/vo/metrics/HTTPRequest.js
Recently I have been looking a Metrics Reporting and noticed that there were a few disparities between the DASH spec and the client implementation, notably redirect reporting and HTTP trace reporting and a few other things as well.
I have also enabled viewing of stream-related (manifest loading, xlink resolving) metrics in the sample player, as well as viewing traces for all metrics types.
The same fix as requested in #597 is in here which I had already spotted.
> Make HTTP Metrics more spec compliant

- src/streaming/rules/ABRRules/ThroughputRule.js
My recent changes to HTTPMetrics (#675) broke ThroughputRule if the last request resulted in a non-2xx response code since no trace would be appended. There was no test of trace since it was (correctly) always assumed to be there, but this now causes an unhandled exception.
Traces appended to these requests would almost certainly be meaningless in terms of throughput measurement so fix is to ignore requests which do not have a trace.
> Fix ThroughputRule broken by #675

- src/streaming/controllers/ProtectionController.js
- src/streaming/extensions/ProtectionExtensions.js
- src/streaming/models/ProtectionModel.js
Moved most of the license request code into ProtectionController.  This
leaves ProtectionExtensions with a much cleaner set of functions for
applications to override.
> Refactor common license request code out of extensions

- src/streaming/models/ProtectionModel_01b.js
The media element is set to null on teardown in ProtectionController. ProtectionModel_01b attempts to add event handlers to the new element without checking it is not null.
I simply copied the basic checks from the other ProtectionModels and it looks good now.
@greg80303 can you take a look at this patch.
> ProtectionModel_01b teardown throws exception on Safari

- src/streaming/controllers/StreamController.js
Following 5687245 (#627), streams with no video would completely fail with an uncaught TypeError. This is because video is hardcoded as the only stream type queried when determining if automatic time syncronisation is required.
This PR allows audio only streams to be played.
We have a number of audio streams for testing available from http://rdmedia.bbc.co.uk/dash/ondemand/testcard/radio/ which will play after this patch has been applied. Live audio only is also reenabled by this patch.
> Don't throw exception when attempting to play audio only stream

- src/streaming/extensions/SourceBufferExtensions.js
Safari makes some dubious claims about codec support in both HTMLMediaElement.canPlayType and Mediasource.isTypeSupported. Presumably based on the same logic, it will allow SourceBuffers to be created for types it does not actually understand.
A native SourceBuffer is created for type application/mp4;codecs="stpp", but when the initialisation segment for that stream is appended the browser crashes with SIGSEGV.
This patch checks the codec type and ensures the native addSourceBuffer is never called for application/mp4;codecs="stpp". No current UA supports this type so this change should not affect any UA other than Safari (I am happy to be corrected if I have this wrong). I have verified this with IE11, Edge, FF (Nightly), Chrome and Safari.
Currently attempting to play …
> Never create a native SourceBuffer for fragmented text

- src/streaming/extensions/SourceBufferExtensions.js
2ff50a0 in #674 did not fix the case where chunk is required to be passed to TextSourceBuffer.append - getIsTextTrack did not resolve correctly for fragmentedText and TypeError was thrown in append since chunk was not passed correctly.
I chose to fix this using hasOwnProperty to search for a property which should never appear on the native version. The other option I considered was using Function.length to determine the number of arguments append would accept. Both seem smelly, but it seems unlikely a native SourceBuffer will ever have a getTextTrackExtensions method.
This fix enables playback of http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-all.mpd which used to work and was subsequently broken.
EDIT: checking for fragmentedText in getIsTextTrack isn't really …
> Stop TypeError when chunk.mediaType === fragmentedText

- src/streaming/controllers/PlaybackController.js
Startup used to attempt to seek to an time which was not initially seekable. As documented in #665, this is not compliant with the spec.
Rather than setting the currentTime on the media element, send a ENAME_PLAYBACK_SEEKING event to all interested parties and wait for segments to be downloaded and appended to the sourcebuffers. Once this has occured for all streams, *then* seek the media element (since the start time is now seekable).
The code to do the seeking after the first segments were appended was already there since it is used for syncing audio and video which don't have identical start times.
> Fix #665 - don't wait on seeking event which may never come

- src/streaming/controllers/BufferController.js
this is a fix for the issue discussed on google groups: https://groups.google.com/forum/#!topic/dashjs/ZCH-6_hI7Xs
basically we now do not take care of timeToEnd in checkIfSufficientBuffer as this is causing stalls before end of stream
tested and verified by our internal QA dep.
> fix stalling before stream ends

- src/dash/DashParser.js
Currently, BaseURL resolution is performed with a hardcoded test for `BaseURL.indexOf("http://") === 0`. URLs returning true are deemed to be absolute and all others relative
When serving media from an absolute HTTPS BaseURL, these BaseURLs are therefore deemed to be relative and are resolved incorrectly.
This PR replaces the string comparison with a regex testing for (case insensitive) http or https.
> Resolve HTTPS BaseURLs correctly

- src/streaming/FragmentLoader.js
- src/streaming/controllers/BufferController.js
- src/streaming/rules/SchedulingRules/PlaybackTimeRule.js
during our long term playback tests we realized a lot of playback crashes. we realized that it always happens when there are a lot of rejected requests in parallel. therefore we limited the amount of pending requests in PlaybackTimeRule.
Additionally we made retry attempts and interval configurable. If you set the attempts to a very high number, the player now - with limiting pending requests - can resume playback correctly after lost internet connection (fixes Issue: https://github.com/Dash-Industry-Forum/dash.js/issues/599)
> limit pending requests

- samples/captioning/multi-track-captions.html
- samples/captioning/ttml-ebutt-sample.html
- src/streaming/MediaPlayer.js
- src/streaming/TextSourceBuffer.js
- src/streaming/extensions/TextTrackExtensions.js
This PR rebases the IE Timed Text fix on all the recent merges as well as pulls in the Big EBUTT additions.  
IE Changes include. 
Detection of IE11 - May need to include Edge in this. Need to test. 
If IE11 use the addTextTrack method and have poor cleanup of tracks between sessions. 
Also remove event driven text track changes since IE fails here as well and breaks the HTML spec for track events.  
API added to make changing tracks clean and simple.
> Time text merge ie fix

- src/streaming/extensions/TextTrackExtensions.js
The "SMPTE-TT" backgrounImage subtitling for non-HTML rendering got broken in PR #705.
It has now been repaired and tested with a prepared content for both html and non-html rendering.
However, both in its former and present state there are a number of issues with this implementation compared to SMPTE-TT.
* It is on the <p> level instead of <div> level. (SMPTE-TT only supports background images for full duration).
* imagetype should be imageType.
* The region parameters for placement on screen are completely neglected.
> Restored image subtitle rendering functionality

- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/index.html
- src/dash/DashAdapter.js
- src/dash/extensions/DashMetricsExtensions.js
- src/streaming/models/FragmentModel.js
- src/streaming/models/MetricsModel.js
- src/streaming/vo/metrics/RequestsQueue.js
add new metric 'RequestsQueue' and show it in debug area at the bottom of dash-if-reference-player index.html in new tab 'Requests'
this helps understanding the algorithm in combination with the visual documentation mentioned in https://groups.google.com/forum/#!topic/dashjs/pQRlJLVyEo4
> include requests queue to metrics

- src/dash/extensions/DashMetricsExtensions.js
Fixes #721 in two ways:
* ensure headers[id] is always accessible by declaring headers to be an empty Object.
* reverse iterate through the request list to find the last MPD request in case there have been subsequent requests since.
As mentioned before, this function can only return the Date header if the correct CORS headers were specified in the response.
> Fix #721 - get date header for last mpd request

- src/dash/DashHandler.js
- src/dash/TimelineConverter.js
Patches to:
1. TimelineConverter.calcSegmentAvailabilityRange:
a. Availability start window is from Period start and not 0.
b. Availability window end when time >= period end contains the last segment of the period, regardless how small it was. This case creates issue when the last segment of the period is smaller and time is at [period end , period end + delta] where delta is the difference of the duration of the last segment.
c. It is quite confusing why d is calculate from representation.segments[representation.segments.length-1].duration, the method is called to update the length in itself in the first place, so why access its last index? I have left it untouched.
2. DashHandler.updateRepresentation
If playback is attempted before AST, we must wait till …
> Patches to TimelineConverter.calcSegmentAvailabilityRange and DashHandler.updateRepresentation for live

- src/streaming/extensions/TextTrackExtensions.js
TTML HTML Resizing stopped working when entering fullscreen after clip had been reloaded, since the videoSizeCheckInterval never got initialized a second time.
> Fixed TTML HTML rendering after clip reload in Safari fullscreen

- src/streaming/extensions/TextTrackExtensions.js
This fixes #770. Should get into an update of 1.5 release.
> Call clearCues as part of deleteAllTextTracks(). Fixes issue #770.

- src/streaming/TTMLParser.js
- src/streaming/extensions/TextTrackExtensions.js
- src/streaming/models/VideoModel.js
Changed the z-index for the caption area to only take to the maximal value in fullscreen mode. Otherwise, it is not set.
Fixes #776.
> Fixes problem with subtitles overlapping menu in reference player.

- src/streaming/TextSourceBuffer.js
The if-statement always returned true, because kind can't be both caption and subtitle at the same time.
> Fixed text track issue, text tracks always showed up as "captions"

- src/streaming/TextSourceBuffer.js
- src/streaming/extensions/TextTrackExtensions.js
Fixes #795 and #796.
The styling is needed since empty native cues are visible on Chrome, and we only use them to trigger our own HTML-rendered subtitles.
Now we also only do this for Chrome.
> Cleaned up the setting of style on native cue on Chrome. 

- contrib/akamai/controlbar/ControlBar.js
- src/dash/extensions/DashManifestExtensions.js
- src/streaming/TTMLParser.js
Replacement of unsafe constructs (innerHTML) with textContent, and filtering of characters in lang attribute in manifest to allowed ones.
Fixes #787.
Test content:
http://async5.org/dash/ED_OnDemand_5SecSeg_Subtitles.mpd
http://streamtest.eu/dash/vod/testpic_2s/bug_subs.mpd
The first one is from #787 for the "lang" attribute. The second is for TTML subtitle text.
> Fix for unsafe constructs

- samples/captioning/multi-track-captions.html
- samples/captioning/ttml-ebutt-sample.html
- samples/dash-if-reference-player/app/main.js
- src/streaming/extensions/TextTrackExtensions.js
The full-screen HTML rendering of subtitles is working in IE11 from #797.
Thus we can now enable this rendering in IE11. It also works in Edge similarly to IE11, so the IE11 test was extended to Edge. Fixes #748.
Also made a fix to the sample captioning apps which repeated subtitle tracks because they listened to the wrong event.
> Enable HTML-rendered captions in all browsers

- src/streaming/TextSourceBuffer.js
Fix for #804.
The player stops fetching data when no text track is visible, but the cues are not cleared in this case. The  easiest way to reproduce the problem is to play content with HTML-rendered subtitles (like the reference player), and pause when subtitles are shown. When turning off the subtitle tracks, the text remains onscreen.
> Clear all previous track data for HTML-rendered tracks when disabling all tracks.

- contrib/webmjs/example.html
- samples/ad-insertion/adinsertion_inband.html
- samples/ad-insertion/adinsertion_inline.html
- samples/ad-insertion/xlink.html
- samples/captioning/caption_vtt.html
- samples/dash-if-reference-player/eme.html
- samples/dash-if-reference-player/index.html
Sounds pointless but, as reported in #688, requests for the DASH-IF icon return 403. This is annoying as it sticks a red entry in the console which confuses debugging.
Replace with a URL for what I assume is the same icon but which returns 200.
> Fix #688 - specify a valid icon for sample pages

- src/streaming/TextSourceBuffer.js
- src/streaming/extensions/TextTrackExtensions.js
Previously, the order that the text tracks turned up in the menu was arbitrary and depended on the order that the parallel download requests were finished.
> Bug fix: The text tracks are now sorted in same order as in Manifest.

- src/dash/DashParser.js
- src/lib/xml2json.js
- src/streaming/ManifestLoader.js
- src/streaming/TTMLParser.js
While testing another feature I discovered that XML parsing errors are handled differently across platforms and not caught in a sensible way on any. This could lead to the player attempting to continue with an incomplete manifest (Chrome, Safari) or fail but not for the correct reason (Firefox, but only because its error response contains a Processing Instruction node which causes the json conversion to barf).
This PR reliably detects parsererrors and forces a sensible (undefined) response from parser which makes the player act as I believe was intended. IE stop attempting to play the malformed manifest.
Please note I have NOT tested this on IE11/Edge as I don't have access to those browsers right now. Could someone try this out and let me know?
> Handle XML parsing error sensibly

- src/streaming/MediaPlayer.js
- src/streaming/controllers/StreamController.js
Now only applies to default time source.  Left code in stream controller to allow us to apply to other time source in future with API we find the need.
> Changes made for Fix for #777 based on code review comments.  

- src/streaming/controllers/PlaybackController.js
Reduction of timer period since it induces a corresponding stall in the live startup time. 
Lowered the value from 1000ms to 50ms. See issue #838.
> Removal of live startup stall by reducing time value.

- src/streaming/MediaPlayer.js
- src/streaming/TextSourceBuffer.js
- src/streaming/extensions/TextTrackExtensions.js
Fixed issue #837 that it was impossible to turn off subtitles and getting back to the same language (for fragment-based subtitles).
Also unified with XML-file-based TTML subtitles and detecting TTML already from the codec/mime-type instead of from the cues.
In all cases, if the video is paused as subtitles are shown, they vanish as the subtitles are turned off.
> Fix for getting back to the same subtitle after turning them off.

- contrib/webmjs/app/main.js
- samples/dash-if-reference-player/app/main.js
- src/dash/extensions/DashMetricsExtensions.js
Metrics display in the reference player had become broken due to some attribute renaming. Fixed references to renamed attributes.
> [1.5.2] Fixup metrics display in reference player

- src/lib/base64.js
None of the dash.js code uses btoa and atob, but the other code in this file. However, the btoa and atob  polyfills have caused some issues when integrating with jwplayer.
> Commenting out unused btoa and atob polyfills. 

- samples/dash-if-reference-player/app/main.js
- src/core/FactoryMaker.js
FactoryMaker: If context argument has not been passed - implicitly create and use new context object
> Es6 refactor

- src/streaming/TextSourceBuffer.js
Fix for #917.
Don't clear buffer on switching fragmented text track to avoid that player stalls, and segment fetching does not recover.
It will take some time until new content appear, though.
Can be tested with http://vm2.dashif.org/livesim/testpic_2s/multi_subs.mpd
> Fix for #917. Don't clear fragmentedTextBuffer on text track switch.

- src/dash/extensions/DashMetricsExtensions.js
Added a missing factor of 1000 when downloading segments is very fast.
Fixes #937.
Test-content http://rdmedia.bbc.co.uk/dash/ondemand/testcard/1/client_manifest-events.mpd
> Corrected throughput calculation

- src/streaming/controllers/BufferController.js
Makes sure to only call sourceBufferExt.remove() if there is anything to remove.
Fixes #936.
> Fixes that the prunings gets into a bad state.

- samples/live-streaming/live-delay-comparison.html
This sample shows the effect of both segment duration and setLiveDelayFragmentCount on end-to-end live stream latency. 3 different settings of live delay fragment count (0,2,4) are used in combination with two different segment durations - 2s and 6s.
> Adding live delay sample

- src/streaming/controllers/AbrController.js
Currently, if you attempt to play content with no video track, AbrController will error attempting to check the MediaInfo for the video track. This PR adds a check to prevent this.
> Don't error when playing audio-only content

- src/core/events/CoreEvents.js
- src/dash/controllers/RepresentationController.js
This is one of the features added in 1.6.0 that was not in 1.5.1. I'm not entirely confident on how this is how to externally trigger events now - let me know if it's wrong!
> Add back astinfuture event

- samples/dash-if-reference-player/app/css/main.css
This patch fixes the position of SMPTE-TT image subtitles (with embedded PNG) which was displayed out of video screen. Textual subtitles works well.
> Fix style of cue-image

- src/streaming/ManifestLoader.js
When loading fragments, the requestModifierExt is applied to both the
URL and the headers. This allows doing things like setting
`withCredentials` on each fragment request. Apply the same handling to
the manifest load in case the manifest load and fragment loads need to
be routed to the same server in a load balanced situation.
> Apply requestModifierExt to the headers on manifest load.

- src/streaming/extensions/MediaSourceExtensions.js
Currently, if you play a piece of audio/video content that is only one fragment long, you may sometimes have only the audio or only the video played out.
This check ensures a stream cannot be flagged as complete until at least one fragment has been put into each track.
Will this potentially have issues with tracks which have been explicitly switched off so are not being loaded?
> Don't close a media source that is a single fragment long prematurely

- src/streaming/MediaPlayer.js
It's possible for there to be no DVRInfoMetric, which will cause dash.js to break. Add a check so that this doesn't happen.
> Don't error if there is no DVR window

- contrib/videojs/videojs-dash.js
Request to update className in Html5DashJS.hideErrors. The class is currently appended to an existing class and therefore invalidating said class.
> Update className in Html5DashJS.hideErrors

- Gruntfile.js
- package.json
- src/All.js
This produces sourcemap files that are valid for dash.js code.
When running uglify with the beautify parameter set to true, some sourcemaps are corrupted.
For an example you can enable maps for .debug and add a breakpoint in Stream.js setup function
which results in a breakpoint in the BufferController onCurrentTrackChanged function.
> Fix sourcemaps for dash.js code. #977

- src/core/Debug.js
- src/dash/DashHandler.js
- src/streaming/controllers/ScheduleController.js
Adding back timestamps to console log messages by default. I think this highlights some timing problems and there is an API to remove it from the log lines if you don't like it.
Also, making certain log statements clearer. For example:
Was: "stop"
Now: "Schedule controller stopping for video"
> Updating log messages

- samples/ad-insertion/adinsertion_inband.html
- samples/ad-insertion/adinsertion_inline.html
- samples/ad-insertion/xlink.html
- samples/captioning/caption_vtt.html
- samples/captioning/multi-track-captions.html
- samples/captioning/ttml-ebutt-sample.html
- samples/chromecast/index.html
- samples/dash-if-reference-player/eme.html
- samples/dash-if-reference-player/index.html
- samples/getting-started-basic-embed/auto-load-multi-video.html
- samples/getting-started-basic-embed/auto-load-single-video-src.html
- samples/getting-started-basic-embed/auto-load-single-video-with-context-and-source.html
- samples/getting-started-basic-embed/auto-load-single-video-with-reference.html
- samples/getting-started-basic-embed/auto-load-single-video.html
- samples/getting-started-basic-embed/manual-load-single-video.html
- samples/live-streaming/live-delay-comparison.html
- test/helpers/DashUtil.html
This replaces the dash.debug.js which no longer exists.
This fixes the fact that the samples were broken in #1004.
> Update samples to reference dash.all.debug.js

- Gruntfile.js
- package.json
This avoids the uglify with beautify builds that were problematic.
It also reduces the number of steps necessary to do a full dist build.
@AkamaiDASH this is an alternative way of producing our `.debug` files. I tried describing it the other day, but this seems like an easier way to convey the idea.
Let me know what you think.
> Debug files straight from browserify.

- src/core/FactoryMaker.js
In other news the getSingletonFactory method also has a bug that can result in two instances being created. The following code will create two instances in the same context:
> Fix for second issue described in #980.

- src/streaming/models/VideoModel.js
This PR reintroduces changes in the VideoModel that were not present in 1.5.1.
> Add 1.6 VideoModel changes

- .jshintrc
- externals/cea608-parser.js
- samples/dash-if-reference-player/app/css/main.css
- samples/dash-if-reference-player/app/sources.json
- src/dash/DashAdapter.js
- src/dash/extensions/FragmentExtensions.js
- src/streaming/Stream.js
- src/streaming/TextSourceBuffer.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/MediaController.js
- src/streaming/extensions/TextTrackExtensions.js
- src/streaming/utils/IsoFile.js
- src/streaming/vo/TextTrackInfo.js
We have added support for CEA-608 video captioning embedded in the video tracks.
This is signalled in the MPD as Accessibility of the video adaptation set as described in the DASH-IF IOP 3.1. CC1 and CC3 tracks are supported and can coexist with other type of text tracks.
If the MPD does not signal the availability of CEA-608, the video segments will not be scanned for captions.
Test content with multiple colors was added at the bottom of the content list of the reference player.
The link is http://vm2.dashif.org/dash/vod/testpic_2s/cea608_and_segs.mpd
There are two CEA-608 tracks and one subtitle track using segmented TTML.
The corresponding simulated live stream is also available as: http://vm2.dashif.org/livesim/testpic_2s/cea608_and_segs.mpd
> New feature: embedded CEA-608 captioning support

- src/streaming/protection/models/ProtectionModel_3Feb2014.js
When playing audio or video only stream, don't error out in IE with
ProtectionModel_3Feb2014 protection model.
> If player is trying to playback Audio only stream - don't error out.

- src/streaming/TTMLParser.js
- src/streaming/VTTParser.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/utils/DOMStorage.js
Ensure all calls to parseInt that currently do not have a radix have a radix to ensure predictable behaviour.
However, it's probably worth considering whether the second TTMLParser parseInt (L534) is necessary, or whether a Math.floor/round would be more preferable.
> Always have a radix for parseInt

- src/streaming/controllers/MediaController.js
When there are initial media settings that match more than one AdaptationSet, ensure selectInitialTrack is called. Otherwise, you may not end up with the desired AdaptationSet.
> Fix initial track selection with media settings

- src/dash/DashParser.js
- src/dash/extensions/BaseURLExtensions.js
This should resolve #521 
Once I got this running with the path-absolute URLs I ran into an issue where we were sending the `Range` header with a value of `bytes=NaN-NaN` which clearly isn't workable. The second commit on here fixes that issue.
> Add support for path-absolute paths in BaseURL

- src/streaming/rules/scheduling/NextFragmentRequestRule.js
Steps to reproduce issue:
1. Start playing an MPD longer than a couple of minutes, such that early buffer is purged
2. Seek to a few seconds before the end (or play naturally through)
3. Wait for content to end
4. Click play again
Expected behaviour:
Playback restarts from the beginning of the media
Actual behaviour:
Playback never starts
> Fix replaying of content in Firefox

- src/streaming/controllers/AbrController.js
This adds an additional guard to ensure we don't go out of the range of available indexes in the portal size rule.
> Fix for #1033

- src/dash/DashHandler.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/MediaController.js
- src/streaming/models/MediaPlayerModel.js
- src/streaming/protection/models/ProtectionModel_3Feb2014.js
- src/streaming/utils/DOMStorage.js
Move creation of some controllers to mediaplayer init.  Moved some DOM storage logic into mediaplayer model.
> Fix for [2.0] Some API methods don't work before play #973

- samples/dash-if-reference-player/app/eme-main.js
- samples/dash-if-reference-player/app/main.js
- src/core/FactoryMaker.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/StreamController.js
Restructured how reset works so now you can do:
player = MediaPlayer().create();
player.initialize(element, url, true);
player.reset();
player.attachView(document.getElementById("video1"));
player.attachSource(url);
OR 
player = MediaPlayer().create();
player.initialize(element, url, true);
player.reset();
player.attachSource(url);
player.attachView(document.getElementById("video1"));
OR AutoPlay false
player = MediaPlayer().create();
player.initialize(element, url, false);
player.play();
player.reset();
player.attachView(document.getElementById("video1"));
player.attachSource(url);
player.play()
> Fix for #947

- src/streaming/MediaPlayer.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/StreamController.js
Currently, playback resumes if you pause then seek if both autoplay and scheduleWhilePaused are true.
This is because after a see, a canplay will fire from the media element once content is in the buffer. Dash.js considers this the same as it does the first at startup and starts playback.
However, removing the startAutoPlay line from the onCanPlay event results in further problems. We use the autoplay property of the media element itself to track whether or not we are actively "trying to play", with the bonus of actually starting playback on a canplay event if that is the case.
I'm sure you'll think the direct access of element.autoplay here isn't great, and I agree and am open to ways to handle this better. I'd like to do it all in the playbackController, but part of the problem is that …
> Fixes #1018

- src/streaming/MediaPlayer.js
Ensure `errHandler` is available if required due to capabilities failure. #1063
> Fixes #1063

- web.config
Previous web.config did not consider that inherited configuration may already define the .json MIME type mapping. Now any inherited configuration is removed before applying a new one.
> Will now remove previous mimeMap entry to avoid conflicts

- src/streaming/MediaPlayer.js
- src/streaming/controllers/MediaController.js
Key lookup returns undefined because DOMStorage is not being imported correctly in MediaController.
DOMStorage needs to be imported for access to its constants.
Unless I am missing something, DOMStorage is a singleton so does not need to be passed in as a configuration object but an instance can simply be acquired.
Discovered whilst investigate FF localStorage issue.
> Use correct key when saving settings to local storage

- samples/getting-started-basic-embed/auto-load-single-video-with-reference.html
- samples/live-streaming/live-delay-comparison.html
- src/streaming/MediaPlayer.js
Bufferlength is a core metric to track in player QoS. The prior solution to extract the buffer length from mediaPlayer requires:
var metrics = player.getMetricsFor('video'),
-                metricsExt = player.getMetricsExt(),
-                bufferLevel = metricsExt.getCurrentBufferLevel(metrics);
This is non-intuitive for new users. To facilitate easier extraction of the buffer length, I have added a new getter for MediaPlayer:
player.getBufferLength()
This takes optional arguments of "video" or "audio". If no argument is passed, the video buffer length of video is returned.
Updated two sample files to show this API in action.
> Adding getBufferLength() method to MediaPlayer

- .jshintrc
- Gruntfile.js
- externals/objectiron.js
- externals/xml2json.js
- package.json
- src/dash/DashParser.js
- src/streaming/TTMLParser.js
- src/streaming/controllers/XlinkController.js
- src/streaming/protection/CommonEncryption.js
- src/streaming/protection/drm/KeySystemPlayReady.js
- src/streaming/protection/servers/DRMToday.js
- src/streaming/utils/BoxParser.js
Attempting to use dash.js with module loader javascript frameworks such
as web pack or browserify was not working well. This was because of
global libraries that were not being included using require or import
syntax.  Removing this global variable leak fixes the issues when
incorporating it into many modern stacks.
External libraries have been updated and all source files requiring
them are explicitly using the ‘import from …’ syntax.  Gruntfile and
.jshintrc have been updated.
It now builds into a single all.min.js file
> Clean up externals global variables so it works with module loaders.

- src/streaming/protection/Protection.js
fix EME detection: only check if first function is supported in order to decide which EME workflow should be used. Not 100% sure if this works in all cases.
> restore_eme_detection_for_IE11_2

- src/streaming/MediaPlayer.js
1. Updated to handle new response from getMetricsExt().getCurrentBufferLevel()
2. Added in fragmentedText buffer length to min operation if no arg is supplied.
> Updating getBufferLength()

- src/streaming/controllers/StreamController.js
- src/streaming/rules/abr/ThroughputRule.js
Whilst rebasing I failed to notice that #1051 removed the STREAM_TEARDOWN_COMPLETE event trigger from StreamController.
Metrics Reporting plugin relies on this event to reset correctly.
Also noticed a check was required when testing HTTPRequest.Trace length in ThroughputRule since this may be deleted if the last request failed which could cause uncaught exception.
> Re-add STREAM_TEARDOWN_COMPLETE event needed for metrics reset

- src/streaming/FragmentLoader.js
If FragmentLoader was reset before attempting to load any fragments, `.abort` would attempt to check the length of `xhrs`, assuming it was an Array. Prior to refactor, `xhrs` was declared as an Array so this worked. Post-refactor, the type was only declared upon the first load.
PR declares type on module initialisation.
> Fix obscure possible uncaught exception

- src/streaming/TTMLParser.js
A series of typos in TTMLParser meant that `line-height` style would be ignored.
> Fix typos in TTMLParser which caused line-height not to be honoured

- src/streaming/controllers/BufferController.js
This is a PR that reintroduces the simpler part of the buffer pruning change added in 1.6.0. It simply allows the pruning of data behind the playhead even if there's gaps in it. 1.6.0 also attempted to remove data substantially ahead of currentTime but I've left that out for now.
> Enable buffer pruning to span multiple buffered ranges

- src/streaming/MediaPlayer.js
- src/streaming/controllers/PlaybackController.js
Fixing getBufferlength() to handle new API change on metrics.
Fixing issue#1089 for the constant live delay being seen under Firefox.
> Fixing getBufferLength API and issue #1089

- src/streaming/controllers/AbrController.js
- src/streaming/rules/scheduling/BufferLevelRule.js
- src/streaming/utils/DOMStorage.js
At first we tried to make the bufferlevelrule too complex with different logic for live.  In reality for live we should have the same targets as vod and with live we just make best attempt to reach that target pending on the liveDelay.   This way we can use all the same stable buffer and top quality logic and expand from there in the future.    Bottom line this is simplified code that enhances buffer target logic for live!
> Fix for #1110

- src/dash/controllers/RepresentationController.js
Purpose is to provide update(s) to support ATSC-DASH type of content with a few characteristics:
Dynamic content with or without updates.
Playback from a local cache (high bandwidth link, low latency)
Playing from close to AST.
Playing close to live edge.
Small initial playback delay.
Transitioning over period boundaries.
...
> Updates for ATSC-DASH type of content (2nd)

- src/streaming/controllers/PlaybackController.js
This commit essentially undoes PR #1111 which broke segmentTimeline playback.
> Restoring segmentTimeline playback

- src/dash/controllers/RepresentationController.js
- src/streaming/ManifestLoader.js
- src/streaming/rules/abr/InsufficientBufferRule.js
A number of leaks were occurring around event handlers:
* Missed `.off` in RepresentationController (and also a missed `.on`)
* Differing scope passed by `.on` and `.off` in InsufficientBufferRule
* xlinkcontroller was never reset so event handler was left each time
> Ensure symmetry in event registration

- Gruntfile.js
- README.md
- contrib/akamai/controlbar/ControlBar.js
- index.js
- package.json
- samples/ad-insertion/inband.html
- samples/ad-insertion/inline.html
- samples/ad-insertion/js/scte.js
- samples/ad-insertion/xlink.html
- samples/captioning/caption_vtt.html
- samples/captioning/multi-track-captions.html
- samples/captioning/ttml-ebutt-sample.html
- samples/chromecast/receiver/js/main.js
- samples/dash-if-reference-player/app/eme-main.js
- samples/dash-if-reference-player/app/main.js
- samples/getting-started-basic-embed/auto-load-multi-video.html
- samples/getting-started-basic-embed/auto-load-single-video-src.html
- samples/getting-started-basic-embed/auto-load-single-video-with-context-and-source.html
- samples/getting-started-basic-embed/auto-load-single-video-with-reference.html
- samples/getting-started-basic-embed/auto-load-single-video.html
- samples/getting-started-basic-embed/manual-load-single-video.html
- samples/live-streaming/live-delay-comparison.html
- src/streaming/MediaPlayer.js
- src/streaming/MediaPlayerFactory.js
This should resolve #1023 
Global properties have been migrated into the `dashjs` namespace.
Also adjusted the `main` script in the `package.json` which should make this library more friendly for importing into es6 style projects that are using WebPack or Browserify.
> Migrate globals into dashjs namespace

- README.md
- index.js
- samples/getting-started-basic-embed/auto-load-multi-video.html
- samples/getting-started-basic-embed/auto-load-single-video-src.html
- samples/getting-started-basic-embed/auto-load-single-video.html
- src/streaming/MediaPlayerFactory.js
This should resolve #1136 
This also has new instructions that should replace #1135 
@wilaw @AkamaiDASH any input on this would be great. I feel like this simplifies the overall usage of dash.js, especially for users who don't want / need any custom settings.
> Cleanup MediaPlayerFactory simplifying declarative setup

- samples/dash-if-reference-player/app/sources.json
Added content to the new content hierarchy of the reference player.
This is important since subtitling and captioning gets broken repeatedly and is rarely tested.
> Added links for testing TTML subtitles and embedded CEA-608 captions.

- samples/dash-if-reference-player/app/sources.json
Removed 2 cases of duplicated content and specified where livesim and livesim-dev is used (livesim-dev to be replaced by livesim later). Also made subtitle content clearer and changed live subtitle multi-period to 1min instead of 2min. (periods_30 -> periods_60).
> Updated reference player content.

- src/streaming/ManifestLoader.js
- src/streaming/Stream.js
- src/streaming/StreamProcessor.js
- src/streaming/models/FragmentModel.js
- src/streaming/protection/controllers/ProtectionController.js
I looked at all the reset methods for instances where modules are reset then the reference to them set to null and put guards around these so that multiple calls to reset do not attempt to call methods on undefined.
The longer term answer is to fix this properly by understanding object ownership and ensuring reset code can only be called by the correct modules.
If there is going to be a RC5, it'd probably be worth sticking this in.
> Fix #1153, #1130 - Guard against dereferencing null objects

- src/dash/controllers/RepresentationController.js
- src/streaming/controllers/MediaController.js
- src/streaming/utils/DOMStorage.js
This PR refactors the storing of cached bitrate and media settings information, so that anything dealing with localStorage is handled in one place.
It also adjusts the timestamp used in the localStorage, rounding it to the nearest ten minutes. This prevents the timestamp from potentially being considered as unique or personally identifying data.
This changes was in 1.6, but I don't think it needs to be in the 2.0 milestone and can wait for 2.1.
> Move all DOMStorage things to DOMStorage, anonymise data

- src/dash/controllers/RepresentationController.js
- src/streaming/controllers/AbrController.js
- test/dash.RepresentationControllerSpec.js
- test/helpers/DOMStorageHelper.js
RepresentationController tests ultimately call a method from DOMStorage which throws a (caught) exception which prints a warning to the console since `window` is not available in the test environment.
Replaced DOMStorage with a helper object which just returns a number since that functionality is not important when testing RepresentationController.
> Fix console warning about window when running tests

- src/streaming/TextTracks.js
- src/streaming/utils/TTMLParser.js
I found a few issues while looking at the TTML parser
* Fixes #1170 - `checkVideoSize` needs to calculate `actualVideoWidth` and `actualVideoHeight` whether there are active cues or not.
* Typos in the CSS which is generated
* related to #1168 - parser throws a (caught) exception when no layout or styling in TTML document, whereas that should have been caught by the structural contraints test.
> Various TTML fixes

- samples/dash-if-reference-player/app/main.js
Turn on the rich subtitle rendering in other browsers than Firefox for the reference player.
Still need to fix #1164, but Firefox keeps the non-styled rendering for now.
> Re-enabled html-renderered subtitles for other browsers than Firefox.

- src/streaming/TextSourceBuffer.js
- src/streaming/utils/TTMLParser.js
TTML does not require styling and layout elements in head, but EBU-TT-D does, and the TTML parser threw an exception when not present. Now fixed so that the parsing continues. Also logs TTML parser exceptions.
> Fixed crash when EBU-TT-D mandatory TTML head elements not present.

- .npmignore
This ensures that we don't cause users to donwload files that aren't
necessary when they're installing via a package manager.
This is progress on #1173
> Add npmignore file.

- src/dash/DashHandler.js
- src/streaming/models/FragmentModel.js
isFragmentLoaded() was returning false if the fragment was loaded at a different quality. This is because the url does not match. The updated version compares the fragment index rather than the fragment url, thus avoiding redownloading the same fragment at different quality.
The update also checks the adaptation index so that fragments from different AdaptationSets do not match. The adaptation index is being stored in the request Object inside DashHandler to enable this change.
> FragmentModel isFragmentLoaded update

- src/streaming/TextSourceBuffer.js
- src/streaming/utils/TTMLParser.js
Fixes #1183.
Tested with content mentioned in #1168 http://media.axprod.net/dash/ED_TTML_NEW/Clear/Manifest_sub_in.mpd
which earlier produced multiple subtitle lines (especially visible in non-HTML-mode).
> Added TTML sample time interval to TTML parser as clipping interval.

- samples/getting-started-basic-embed/listening-to-events.html
Adds a new sample file /samples/listening-to-events.html which illustrates the various events available on the MediaPlayer object to which page script can subscribe. The sample allows you to dynamically add events from a list as well as a remove them. The payload of each event received is traced out in both the console and a UI component.
> Adding sample to show how to listen to events

- src/streaming/controllers/StreamController.js
Rep switch caused data to update and eventually triggered startAutoPlay check.  This would not happen with audio /video if paused unless schedulewhilepause was true and ABR switch occurred while paused, unlikely but possible.   Fragment Text on the other hand, controlled by UI,  can cause a rep update while paused so we prevent this if not the initialPlayback.  Will fix A/V edgecase as well.
> Fix for issue #1172

- src/streaming/MediaPlayer.js
- src/streaming/models/VideoModel.js
Added @deprecated tag to getVideoModel. 
Added API that some may use  from videoModel to MediaPlayer.  (Only some should be public)
Added API docs to new API in MediaPlayer
store video element in Video Model only and always reference from there. 
Removed unneeded checks in initializePlayback as it is internally called and not part of Play() anymore. 
Moved hack for preload firefox into video model.
> Fix for issue #1154

- src/streaming/FragmentLoader.js
- src/streaming/ManifestLoader.js
- src/streaming/XHRLoader.js
- src/streaming/XlinkLoader.js
- src/streaming/controllers/XlinkController.js
- src/streaming/models/MediaPlayerModel.js
- src/streaming/utils/ErrorHandler.js
- src/streaming/utils/URLUtils.js
- src/streaming/vo/HeadRequest.js
- src/streaming/vo/TextRequest.js
Fixes #1048, at least the refactor part of it. All of the common code is contained in XHRLoader, with the previous loaders calling this, leaving just the unique code in these.
Extended MediaPlayerModel to allow different number of retries and intervals per resource type, although these are not actually used anywhere right now.
I haven't attempted to abstract anything too much in order to enable alternative transports, although this shouldn't be too tricky.
Note that diff'ing (Fragment|Xlink|Manifest)Loader isn't that helpful since they have changed radically.
> Refactor common loader code into XHRLoader

- src/streaming/FragmentLoader.js
- src/streaming/models/FragmentModel.js
Gah, the perils of manual testing on a high-bandwidth connection!
I missed that `abort` and `reset` need to be different in the case of the FragmentLoader since abort is called when the FragmentModel wishes to abort in-flight requests on Representation switch.
Sorry!
> Fix FragmentLoader TypeError on fragment abandonment

- src/dash/models/DashManifestModel.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/MediaController.js
- src/streaming/vo/BitrateInfo.js
- test/helpers/VOHelper.js
- test/streaming.AbrControllerSpec.js
@davidgarry commited a pr to enhance getBitrateInfoListFor api but it
was not merged into dash.js v2.0.0 release.
This commit based on his commit to make these information available in
dashjs 2.0.0 again
> Add video width and height to api getBitrateInfoListFor

- src/streaming/XHRLoader.js
- src/streaming/models/FragmentModel.js
- src/streaming/rules/scheduling/NextFragmentRequestRule.js
When fragment download is delayed by ScheduleController.setTimeToLoadDelay(), there was a race condition when a stream ends during a delay for loading a fragment.
> fix playback hanging for delayed fragment at end of stream

- src/streaming/Stream.js
- src/streaming/StreamProcessor.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/controllers/SourceBufferController.js
- src/streaming/controllers/StreamController.js
* Fix for #1217
* Partial fix for FireFox MP - can now seek into period no end event prevents stream switches from automatically happening. 
* Reduces code for setting index handler time for MP or track switch.
> refactored how seek and index handler time offsets work - preserves commonEarliestTime logic

- src/streaming/controllers/MediaSourceController.js
- src/streaming/models/VideoModel.js
Given the discussion at https://github.com/w3c/media-source/issues/53 and the linked W3C spec text [Best practices for authors using media elements](https://www.w3.org/TR/html5/embedded-content-0.html#best-practices-for-authors-using-media-elements), we should probably be following that advice in order to release correctly any resources which are no longer needed.
I have tested this on Safari (9.0.3), IE11, Edge, FF (Nightly) and Chrome.
> Detach MediaSource correctly when no longer required

- src/dash/DashHandler.js
- src/dash/utils/ListSegmentsGetter.js
- src/dash/utils/SegmentsGetter.js
- src/dash/utils/SegmentsUtils.js
- src/dash/utils/TemplateSegmentsGetter.js
- src/dash/utils/TimelineSegmentsGetter.js
The purpose of this refactoring is simplification of `DashHandler.js` by extracting segment list updating responsibility into separate classes. This makes code easier to maintain and simplifies working with segment lists, especially if someone is extending default dash.js behavior and needs access to segment list currently processed by player or wants to create arbitrary segment list range for his own needs. Writing unit tests for segment list updating should be easier now too.
Overview of what was done:
1. Renamed `getSegments` into `updateSegments` to better reflect what it actually does.
2. Code related to specific segments referencing scheme was separated into 3 classes(timeline, template, list).
3. Extracted code that was shared by these 3 classes and `DashHandler.js` to separate …
> Improvements in DashHandler.js

- README.md
Changed the link text for the v2.0 migration documentation
> "here" links are evil

- src/dash/utils/ListSegmentsGetter.js
- src/dash/utils/SegmentsUtils.js
- src/dash/utils/TemplateSegmentsGetter.js
This is a fix addressing the comment https://github.com/Dash-Industry-Forum/dash.js/pull/1270#issuecomment-200542800
**What was done:**
1. moved `decideSegmentListRangeForTemplate` method from `ListSegmentsGetter` and `TemplateSegmentsGetter` to `SegmentsUtils`.
2. added `timelineConverter` & `isDynamic` params to `decideSegmentListRangeForTemplate` to make it working in `SegmentsUtils`
> removed code duplication by extracting decideSegmentListRangeForTemplate method to SegmentsUtils

- samples/live-streaming/live-delay-comparison-alternate-config.html
- samples/live-streaming/live-delay-comparison.html
- src/dash/controllers/RepresentationController.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/models/MediaPlayerModel.js
- src/streaming/rules/scheduling/BufferLevelRule.js
There's currently no easy way to specify how many seconds of latency you want for live streams:
-  `setLiveDelayFragmentCount` will result in random latency if segments have variable durations
- if I understand it right, the maximum latency is [limited to a half manifest duration](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/controllers/ScheduleController.js#L384)
I introduced an additional setter which specifies the target latency in seconds.
- If set, this target latency will take precedence over `setLiveDelayFragmentCount`, DVRWindowSize and so on
- if not set, the current behavior is used
> Add option to force live latency to a given number of seconds

- src/streaming/controllers/BufferController.js
Cleaned up leftovers around `minBufferTime` in `BufferController`:
- public getter and setter were unused
- the only part of the code where it was used was [here](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/controllers/BufferController.js#L549)
- it was only set to `manifestInfo.minBufferTime` [here](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/controllers/BufferController.js#L608)
:warning: WARNING: 
- the [setTimeout](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streaming/controllers/BufferController.js#L549) was never executed because `clearBuffer(getClearRange())` is not not a function. My pull request will allow it to execute again but it might have side effects if this behavior was actually not …
> clean up minBufferTime in BufferController

- src/streaming/XHRLoader.js
Clear onloadend so aborted xhrs are not rescheduled. See #1291 for discussion.
> Fixes #1291

- .jshintrc
- src/core/events/CoreEvents.js
- src/dash/DashHandler.js
- src/dash/DashParser.js
- src/dash/SegmentBaseLoader.js
- src/dash/models/DashManifestModel.js
- src/dash/vo/BaseURL.js
- src/streaming/ManifestLoader.js
- src/streaming/MediaPlayer.js
- src/streaming/Stream.js
- src/streaming/XHRLoader.js
- src/streaming/controllers/BaseURLController.js
- src/streaming/controllers/BlacklistController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/controllers/StreamController.js
- src/streaming/metrics/utils/DVBErrorsTranslator.js
- src/streaming/models/BaseURLTreeModel.js
- src/streaming/models/MetricsModel.js
- src/streaming/rules/baseUrlResolution/BasicSelector.js
- src/streaming/rules/baseUrlResolution/DVBSelector.js
- src/streaming/utils/BaseURLSelector.js
- src/streaming/utils/ObjectUtils.js
- src/streaming/vo/metrics/HTTPRequest.js
- test/dash.DashHandlerSpec.js
- test/dash.DashManifestModel.js
- test/helpers/ObjectsHelper.js
- test/streaming.BasicSelector.js
- test/streaming.BlacklistController.js
- test/streaming.DVBSelector.js
This PR adds BaseURL support.
It currently has two modes - DVB and "Basic". Basic mode selects BaseURLs in the order they are specified in the manifest. DVB mode is compliant with DVB A168 section 10.8.2. DVB is automatically selected if the DVB profile is listed at the top level of the MPD, otherwise basic mode is used.
In all cases, if a BaseURL has failed it will not be retried. Failures are carried across manifest updates (unless the available BaseURLs have changed), but are reset at the end of a session.
BaseURL elements are supported at all levels of the manifest as specified in ISO23009-1.  Implementation of this, as well as DVB mode, has made the entire solution more complicated than it might have been, but has led to the most flexible solution.
I've done a reasonable amount of …
> BaseURL support

- AUTHORS.md
- src/streaming/MediaPlayer.js
- src/streaming/controllers/StreamController.js
Change to MediaPlayer.time() as suggested in https://groups.google.com/forum/#!topic/dashjs/Zk0nzEfYNi0
Logic was put into a new function StreamController.getTimeRelativeToStreamId() to keep it grouped with other stream processing related logic.
> Enable querying time relative to arbitrary Period start time

- src/core/events/CoreEvents.js
- src/streaming/MediaPlayerEvents.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/StreamController.js
Added discrete event for loaded/empty parallel to BufferStateChange. So now you have maximum versatility.
```js
mediaPlayer.on(dashjs.MediaPlayer.events.BUFFER_EMPTY, onBufferEmpty)
mediaPlayer.on(dashjs.MediaPlayer.events.BUFFER_LOADED, onBufferLoaded)
mediaPlayer.on(dashjs.MediaPlayer.events.BUFFER_LEVEL_STATE_CHANGED, onBufferStateChange)
function onBufferStateChange(e) {
if (e.mediaType === "video") {
console.log("onBufferStateChange", e.state);
}
}
function onBufferLoaded(e) {
if (e.mediaType === "video") {
console.log("onBufferLoaded");
}
}
function onBufferEmpty(e) {
if (e.mediaType === "video") {
console.log("onBufferEmpty");
}
}
``` 
Another change committed in this PR is part of the fix for #1033
> Fix for issue #1257 and partial fix for #1033 

- samples/dash-if-reference-player-beta/index.html
- samples/dash-if-reference-player/index.html
- src/streaming/MediaPlayer.js
- src/streaming/controllers/MediaController.js
`MediaController[mode]` only works externally when you `import MediaController` in other modules - you can't use it within the module definition.
`MediaController.trackSelectionModes[mode]` doesn't work for the same reason and also because `MediaController.trackSelectionModes` is not defined.
Given the comments in `MediaPlayer` (fixed), this looks like a hangover from v1.
Also fixed the ref player which had outdated strings so wouldn't have worked anyway.
> Fixes #1282

- src/dash/DashHandler.js
- src/dash/models/DashManifestModel.js
- test/dash.DashManifestModel.js
See #1321 for discussion. Also added some tests for the same issue and others.
Also noticed that http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd no longer played back correctly. I'm not convinced the signalling in the manifest is legal, but it used to work so made it work again.
I would recommend this gets pulled in for 2.1.0.
> Fix #1321 - relative MPD@BaseURL are not resolved correctly

- src/streaming/ManifestLoader.js
- src/streaming/XHRLoader.js
See #1323 for discussion.
07fe4f0 absolutely must go in to 2.1.0 in my opinion - this is a serious regression and a spec violation if it does not work.
a5673fa ought to go in as otherwise IE11 will fail to do anything useful in the rare case that a relative MPD URL is used.
> Fixes #1323

- src/streaming/controllers/PlaybackController.js
Found issue with this line.  I added the isFirst but the return statement check solves the reason why I add isFirst check in the first place. With check some streams in some browsers do not start if non 0 pst
This resolves this.
Test thoroughly.
> Fix for regression of FF and Multiperiods test stream startup

- src/streaming/MediaPlayer.js
Moving where we set the protection vars to null. Works fine if you set new prod data, switch streams or DRM or key systems etc.
Before fix you could not “reload” any given protected content due to nulling out info.
> Minor fix for prod data and controller

- src/streaming/controllers/AbrController.js
I don't think this is urgent enough to require being included in any future RC3 (i.e. this PR can wait until 2.2).
> Prevent low values attempting to use representation -1

- src/streaming/controllers/PlaybackController.js
Fixes #1333, this prevents the check that enables a first period to start after 0 cause a seek back once buffer is pruned, whilst still allowing forward seeks.
> Only seek forward on PST check

- src/dash/models/DashManifestModel.js
- test/streaming.BlacklistController.js
- test/streaming.DVBSelector.js
This small change removes an unused section of code, with a corresponding comment to clarify what is happening. This also increases the test coverage for getBaseURLsFromElement to 100%.
The additional tests for BlacklistController and DVBSelector brings the test coverage for those modules to 100% (even though, in theory, the cases dealt with in DVBSelector should never be able to occur).
> Improve test coverage for BaseURL

- src/streaming/utils/TTMLParser.js
Two problems were found in #1340:
* if no `tts:origin` was set, the default values for `top` and `left` would attempt to place the text near the bottom. Set them to `auto` as specified in TTML1. @TobbeEdgeware, @nigelmegitt - do you agree this is sensible (esp. given that all compliant EBU-TT-D will have origin set)?
* even if `tts:origin` (or any other region-specific styling) was specified, this was only honoured if found as an inline attribute of region, as required by EBU-TT-D. This constraint is not applicable for TTML, so made parsing of referenced styles on regions more lenient (ie allowed region-specific styling non-inline).
> Fixes #1340 - make TTMLParser more permissive of non-EBU-TT-D

- src/dash/DashHandler.js
- src/dash/DashMetrics.js
- src/streaming/ManifestLoader.js
- src/streaming/VirtualBuffer.js
- src/streaming/XHRLoader.js
- src/streaming/XlinkLoader.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/FragmentController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/controllers/StreamController.js
- src/streaming/models/MediaPlayerModel.js
- src/streaming/models/MetricsModel.js
- src/streaming/rules/abr/BolaRule.js
- src/streaming/rules/abr/ThroughputRule.js
- src/streaming/vo/metrics/HTTPRequest.js
- src/streaming/vo/metrics/ManifestUpdate.js
- src/streaming/vo/metrics/PlayList.js
- test/helpers/VOHelper.js
Based on the comment: `//TODO we need exports for all the sub objects.  These should all be class VO`, these classes are now exported individually.
> Refactor metrics VOs which contained multiple definitions so all are exported individually

- src/streaming/XHRLoader.js
See #1370.
Additionally, if it had ever worked, initialisation segment download failures would have been reported incorrectly as content.
> Initialise DownloadErrorToRequestTypeMap properly

- src/streaming/Stream.js
With commit ddd264285fe4f362db55c51e5a07a09ffeed3fc8 I removed the line causing the bug reported in #1369.  This was done as a hack before I fixed the actual problem with MP for FireFox and issue #1217
> This commit will fix #1369

- src/dash/DashParser.js
- src/dash/models/DashManifestModel.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/metrics/utils/HandlerHelpers.js
- src/streaming/utils/TTMLParser.js
Whilst debugging some TTML streams I noticed that the parser logged any exceptions as `undefined`. Turns out this is because the parser throws strings and logging code was looking for `e.message` of an Error object which is obviously undefined if you throw a string. Fix was to change all string throws to new Error throws.
Throwing strings seems pretty bad form - Errors allow for stack tracing etc - so I changed all the other instances for good measure.
> Throw new Errors rather than strings

- src/streaming/MediaPlayer.js
- src/streaming/XHRLoader.js
- src/streaming/models/MediaPlayerModel.js
Added a new API on MediaPlayer: `setXHRWithCredentials`. Pass it a boolean which is used to set `XHR.withCredentials`.
Defaults to false.
NOTE: I **have not** tested this on any browser other than to check it does not break anything when set to false which I have verified in Chrome at least. Could those who want this feature (@kamranhameedpl, @ShanePhelan etc) please pull locally and test across all UAs, OS etc. I would not recommend pulling this until we have some feedback.
Addresses #1006.
> Optionally set withCredentials on XHR requests

- test/dash.DashManifestModel.js
The diff looks nasty, but this simple change ultimately pushes all the BaseURL tests in DashManifestModel under a getBaseUrlsFromElement heading.
There are no functional changes.
> More appropriate labelling of tests in DashManifestModel

- src/streaming/controllers/BufferController.js
Assume this was left in for debug purposes.
Fixes #1406.
> Don't print 'try to prune buffer' all the time.

- src/streaming/controllers/PlaybackController.js
I have tested this in Chrome (where it seems to fix the issue) and Firefox (where it is, correctly, ignored because `play` does not return a `Promise`).
It would be good if someone can test this in Edge, IE11 and Safari.
This is probably a sticking plaster - we should possibly consider refactoring all the play/pause/load operations so this exception is not thrown.
(Note: The commit message is strictly incorrect as the catch is not silent - a log message is printed)
> Fixes #1372 - catch pending play request exceptions

- src/streaming/controllers/XlinkController.js
- src/streaming/utils/URLUtils.js
- test/streaming.utils.URLUtils.js
Addresses first part of #1380, also allowing secure origins.
> Xlink href must be HTTP-URL

- src/streaming/controllers/PlaybackController.js
This partially resolves #1361. It doesn't deal with period/as/track.
> Support t as well as s in URL fragments, seeing as t is the standard

- src/dash/utils/SegmentsGetter.js
- src/dash/utils/SegmentsUtils.js
- src/dash/utils/TimelineConverter.js
This PR resolves #1362. Currently, the DVRInfo event only uses the current available time and the dvrwindowlength to derive the available start/end times.
By checking the AST of the first segment currently available and the AET of the last segment currently available, we ensure we only report times that are actually currently available.
> For SegmentTemplate, only include available segments in DVRInfo

- src/streaming/controllers/PlaybackController.js
Reverts Dash-Industry-Forum/dash.js#1390.
Merged the wrong branch! My excuse is it's early in the UK ...
> Revert "Support t as well as s in URL fragments, seeing as t is the standard"

- src/streaming/TextSourceBuffer.js
- src/streaming/TextTracks.js
- src/streaming/utils/TTMLParser.js
Fixes #920 by checking if there is timing information in the span elements and using them to create extra cues.
Checked with all other subtitle/caption content in the reference player and with the content mention in #1168 which needs clipping.
Also moved check for image-based subtitling out to the div level as a first step towards supporting IMSC-1 subtitles (#1418).
> Fix ttml span timing + moved image subtitles to div level

- package.json
- src/dash/DashMetrics.js
- src/streaming/MediaPlayer.js
This is fairly uncontroversial - see discussion in #1393.
I have used a module from npm which we have done with isoboxer but not something we do all the time in this project, and I'm not really sure why. Perhaps the project grandees have an opinion.
> Fixes #1393 - don't use Number.MAX_SAFE_INTEGER

- samples/dash-if-reference-player/app/sources.json
- samples/dash-if-reference-player/index.html
Added the test vectors in the issue.
This is a starting point - we could definitely do with more - but good enough to get going. Some HE-AAC would be useful I think.
Also made use of the moreInfo attribute Axinom added a while back, and added it for BBC streams.
> Fixs #1423 - add audio only test vectors

- src/streaming/MediaPlayer.js
- src/streaming/controllers/AbrController.js
This supersedes PR #1030 by @nickygerritsen - resolving the conflicts and adding an API to control the feature.
> Use device pixel ratio to calculate size of portal for max representation size (with API)

- src/streaming/controllers/AbrController.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
- test/helpers/SpecHelper.js
- test/streaming.AbrControllerSpec.js
Cleaned up how other objects get the default setting for ABR quality.  Restored default back to 0 from -1.  
Both streams mentioned in issue #1437 are RTE free now and I maintained the original intent.
> Fix for #1437

- src/streaming/TextTracks.js
- src/streaming/utils/TTMLParser.js
See #1432 for detail.
Also added non-prefixed box-decoration-break which is currently only supported in Firefox which doesn't support HTML captions anyway, but hopefully will soon.
> Fix #1432 - cellResolution does not convey aspect ratio

- src/streaming/controllers/BaseURLController.js
- src/streaming/utils/URLUtils.js
- test/streaming.utils.URLUtils.js
#1280 caused a regression to the fix for #521.
This patch restores correct joining of origin and path-absolute URIs.
> Fix #521 - properly support path-absolute BaseURLs

- src/streaming/controllers/ScheduleController.js
Fixes #1482, and potentially others.
This prevents media segments from being loaded before the init segments have been, and therefore will prevent a race condition where the media is appended first and causing dash.js to fail.
> Block on init segment loading

- src/streaming/rules/RulesController.js
When the rules controller was choosing between multiple rules, it was always copying the reason from the last rule visited.  E.g. a switch request coming from the ThroughputRule was still giving an "InsufficientBufferRule" reason.
> fix switchRequest reason for multiple rules

- src/streaming/utils/TTMLParser.js
This log line currently outputs the same variables twice, which is confusing and misleading.
> Fix up TTML log line

- src/core/events/CoreEvents.js
- src/dash/controllers/RepresentationController.js
- src/streaming/MediaPlayerEvents.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
- test/dash.RepresentationControllerSpec.js
**Important!!!  Event CONST and String name have changed for Quality Change.** 
2.1 and below we only had QUALITY_CHANGED event that was triggered when a change is requested, manual or ABR.  There was not a follow-up event for when the requested change actually was in the buffer and rendering. 
In 2.2 I added the other event showing the change was complete and being rendered. A bug was filed #1439 saying you should get a complete event for all start events IF they render on screen. 
* So in this PR I have changed both event names, removed duplication of one event and made it dispatch render event every time there is a render change on screen regardless of ABR or manual switching requested.  (E.g.  FastSwitch is not enabled and you have many qualities in the buffer, you seek back and you …
> Fix for #1439 and much more!

- samples/dash-if-reference-player/app/sources.json
1. 10 seconds availabilityTimeOffset:
http://vm2.dashif.org/livesim-dev/ato_10/testpic_2s/Manifest.mpd
2. Infinite offset (all segments available at availability start):
http://vm2.dashif.org/livesim-dev/ato_inf/testpic_2s/Manifest.mpd
Thanks to Waqar for posting, Yi for implementing and Torbjörn for integration.
> Adding two new livesim samples to ref player

- src/streaming/rules/abr/ThroughputRule.js
Currently it appears to be possible to try to run the ThroughputRule when there are no samples yet, which results in an error.
> Don't error if there are no throughput samples

- src/streaming/XHRLoader.js
xhr.abort will trigger onprogress which we don't want when deliberately aborting inflight requests - set it to undefined so it's not called. Already done for onloadend and onerror.
Caused an infrequent race condition if a higher level app was listening on for metrics changes.
> Don't fire progress events when deliberately aborting xhrs

- src/dash/SegmentBaseLoader.js
When the `indexRange` is unknown, dash.js will search for the sidx box. It possibly won't be at the start of the byte range.
This has been proven to fix loading of:
* http://dash.edgesuite.net/dash264/TestCasesMCA/dolby/1/1/ChID_voices_51_256_ddp.mpd
and proven not to break the following test vectors
* http://dash.edgesuite.net/dash264/TestCases/1a/sony/SNE_DASH_SD_CASE1A_REVISED.mpd (SegmentBase, no indexRange), 
* http://dash.edgesuite.net/dash264/TestCases/4b/qualcomm/1/ED_OnDemand_5SecSeg_Subtitles.mpd (SegmentBase, indexRange and indexRangeExact='true' both present), and
* http://dash.edgesuite.net/dash264/TestCasesHEVC/1a/1/TOS_OnDemand_HEVC_MultiRate.mpd (SegmentBase, indexRange and indexRangeExact='true' both present, and Initialization@range present)
`indexRange` is mandated by …
> Fix #1517 - don't assume sidx is at offset zero in byte range

- samples/dash-if-reference-player/app/main.js
Fairly pointless, but gives one less potential red exclamation mark while I was trying some other things out.
> Don't throw TypeError if Load clicked in ref player when no URL specified

- samples/dash-if-reference-player/app/sources.json
Simple fix to PR #1529 which was merged to early.
Styling of image subtitles is coming in a later PR as is a fix for the erroneous behavior that subtitles are not removed as content is reloaded.
> Removed local test URL from sources

- Gruntfile.js
- package.json
The intent of this PR is to provide an ES5 version of the source files for use in Browserify workflows (this would resolve #1483).
cb8978673ebfbe447da6e40c45d062cf1e303d7a does add a way for Browserify to work but it currently requires the user to have babel and babelify as dependencies.
> Include babelified files in the dist

- src/streaming/rules/abr/BolaAbandonRule.js
- src/streaming/rules/abr/BolaRule.js
Major changes in the BOLA code, including:
removed some redundant features,
do not artificially limit buffer to a low level,
change startup heuristic,
handle low-latency live streaming better.
> BOLA updates

- src/streaming/MediaPlayerEvents.js
- src/streaming/controllers/PlaybackController.js
will solve issue/feature #1541 by adding new event: MediaPlayerEvents.PLAYBACK_NOT_ALLOWED
> implemented Event MediaPlayerEvents.PLAYBACK_NOT_ALLOWED

- src/streaming/rules/abr/AbandonRequestsRule.js
- src/streaming/rules/abr/ThroughputRule.js
Added cache detection to TP rule, fixes issues with Abandonment rules.  Fixes issues on transfer from cached to not cached sections of presentation.  Solves major oscillation issue in TP rule.  All changes were confirmed with the ABR testing tool.   
For Oscillations we now have an algorithm to detect variation in the average array and will increase or decrease the sample amount based on variation.  
Some results:  BOLA vs Traditional after major improvements in both ABR.
ABR							bola	               default
rebuffers (low/other quality)	        0 (0/0)		0 (0/0)
average rebuffer seconds		0.000		0.000
up switches (in Mbps)			4 (70.582)	9 (34.184)
down switches (in Mbps)		6 (56.410)	5 (25.030)
oscillations within 10s			9			1
average bitrate in Mbps			11.222		10.724
count q=0 (0.254Mbps) …
> Solves various ABR issues based on #1530.  

- .gitignore
- .npmignore
- package.json
This PR is in response to #1509. The babelified source files will live in `build/es5/`
> Publish ES5 files for node.js import

- samples/dash-if-reference-player/app/css/main.css
- samples/dash-if-reference-player/app/sources.json
- src/streaming/TextTracks.js
- src/streaming/controllers/SourceBufferController.js
- src/streaming/utils/TTMLParser.js
Support for embedded image subtitles with positioning and scaling.
The layout support is for `origin and extent` in region in units of either % or px. In the latter case, the px are used relative to `extent` specified in the `<tt>`element.
There is also support for `origin and extent` specified in the `<div>` element, which is not according to standard.
A test sequence http://vm2.dashif.org/dash/vod/testpic_2s/img_subs.mpd has all three types of layout specified as different tracks.
> Image subtitles with layout

- samples/ad-insertion/scte.html
Fix a wrong reference to the dash.js library in the scte ad insertion sample site
> Use dash.all.debug.js in scte ad insertion sample site

- src/streaming/StreamProcessor.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/controllers/StreamController.js
1. Multiperiod duration was getting set with call to source signalEnd at non last period stream. 
2. cleans up hack for calling signalEnd from buffercontroller by setting the value to the event is fired the second time a stream is complete if replayed not reloaded
3. Allows replay of stream if play is called after complete event with new schedule logic. 
4. Cleaned up some old es5 code in areas I made adjustments but then stopped doing that since it is code freeze.  I left in what I started as it was minor.
All changes are pretty minor but solve some critical stuff.
> Fixes three issues found while testing RC1 v2.3.0

- src/core/events/CoreEvents.js
- src/dash/controllers/RepresentationController.js
- src/streaming/MediaPlayerEvents.js
The astinfuture event was created with the intention for players to use it to identify when playback will not start until a later point.
So it should probably be public so players can use it.
> AST_IN_FUTURE should be a public event.

- index.js
- src/streaming/MediaPlayerFactory.js
Added additional undefined checks before referencing window, so dash.js can be used in module form in non-browser environments.
Primary example for this would be a server side rendered view that includes dash.js.
Not a frequent OSS contributor so let me know how I can help get this through :^)
> additional undefined checks before referencing window

- externals/xml2json.js
- src/dash/parser/DashParser.js
- src/dash/parser/matchers/StringMatcher.js
This PR is intended to fix #1573 . It adds a `StringMatcher` to the DASH parser.
The issue identified the specific case of `Period@id` attributes, however there are many other attributes in the DASH MPD that, according to the schema, are also type `xs:string`. `StringMatcher` therefore contains a mapping table listing every attribute I could find the the schema that is defined as being of type `xs:string`.
The `StringMatcher` needs to know the name of the node as well as the name of the attribute. `xml2json.js` was therefore modified to provide this as an argument to the test method. Although attributes currently have an `ownerElement` property that would provide this information (without needing to modify `xml2json.js`) this will eventually be deprecated in DOM4+ according to …
> MPD xs:string parse fix

- samples/dash-if-reference-player/index.html
"Attributes should be seperated by whitespace" said the warning text.
> Fix Edge malformed start tag warning

- src/streaming/controllers/BufferController.js
This fixes an exception occurring here when a SourceBuffer is undefined in case `SourceBufferController.createSourceBuffer` returns `null`
> Add check in `pruneBuffer`if SourceBuffer is defined

- src/streaming/MediaPlayer.js
Should allow integrations / player plugins for checking if other components set this concurrently
> Adds getLiveDelay to MediaPlayer API

- samples/dash-if-reference-player/app/sources.json
Updated the v6 test vectors to v6.1, to fix some missing text segments. Now there should be no 404s in any of the Axinom test vectors.
> Updated Axinom conservative test vectors

- externals/xml2json.js
- src/dash/parser/DashParser.js
- src/streaming/controllers/XlinkController.js
- src/streaming/utils/TTMLParser.js
See #1267 for discussion.
Thanks to @bwidtmann and his team for doing some testing which appears to be positive.
Reviewing this change will be very hard even with whitespace supression turned on (ninja tip: add `?w=1` to any diff URL) but I'd appreciate a once over from people. I suppose you could argue that we never bother reviewing any other dependencies, so you could ignore xml2json and just check the handful of touch points in our code.
Most important is that as many people test as possible. Perhaps we should merge into dev branch asap and see if anyone finds anything before next release - this can be backed out easily if needs be.
> Fix #1267 - update externals/xml2json to v1.2

- src/streaming/protection/vo/KeySystemConfiguration.js
It seems that passing `[]` as a `MediaKeySystemMediaCapability` in `MediaKeySystemConfiguration` causes the `requestMediaKeySystemAccess` call to fail with NotSupportedError.
See #1224 and discussion on Slack today (19/9/2016) for background.
This PR checks whether the capabilities are empty and does not include them in the configuration object in that case.
I have tested this on Chrome with both clearkey and widevine. It'd be great if someone could take a look with other UA/CDM instances.
> Fix #1224 - only set non-empty MediaCapabilities on MediaKeySystemConfiguration

- .jshintrc
- src/dash/DashHandler.js
- src/streaming/ManifestLoader.js
- src/streaming/controllers/BaseURLController.js
- src/streaming/utils/URLUtils.js
- test/streaming.utils.URLUtils.js
Most streams using BaseURLs that I have ever seen have sensible-looking urls which can simply be concatenated together.
Recently, I became aware of someone using an example like below (truncated for brevity):
```
<MPD>
<BaseURL>http://www.example.com/manifest.mpd</BaseURL>
<Period start="PT0S">
<AdaptationSet>
<SegmentTemplate media="video/v$RepresentationID$_$Number$.m4s" initialization="video/IS.mp4"/>
<Representation id="1"/>
```
Whilst it looks ridiculous, according to the specification, URLs must be resolved according to RFC3986 to give e.g. `http://www.example.com/video/v1_1.m4s`, which is not what was happening.
This PR solves this by using the in-built browser URL parser, where available, to resolve URLs correctly with respect to a base URL. Where that URL parser is not available …
> Resolve relative BaseURLs more in line with the spec

- samples/dash-if-reference-player/app/main.js
Firefox 49 was released a couple of days ago and now has the required functionality to fix #1164.
This PR adds a test to the existing UA sniffing to check if the Firefox version number is at least 49, and enables HTML-rendered TTML subtitles in that case, as well as the existing cases (ie !Firefox).
> Enable HTML-rendered TTML in ref player if Firefox is at least v49

- src/streaming/MediaPlayer.js
- src/streaming/controllers/AbrController.js
checkPortalSize got the clientWidth of the video element, which caused an expensive reflow and potential for dropped frames. Only get the clientWidth when the element resizes.
> Only check element clientWidth on window resize

- src/streaming/controllers/ScheduleController.js
Looks like this stopped working after 636f4f9, because ScheduleController.start() isn't called. This fixes it, but @AkamaiDASH might want to check it doesn't undo any of his fix from that commit.
> Fix #1618 for setScheduleWhilePaused(false)

- src/streaming/MediaPlayer.js
- src/streaming/XHRLoader.js
- src/streaming/models/MediaPlayerModel.js
As requested by Trevor Hunsaker on Slack.
> Allow xhr.withCredentials to be set per request type

- Gruntfile.js
- package.json
To avoid confusion over which version is deployed on the nightly server/anywhere.
Adds (e.g) `/*! v2.4.0-905c978, 2016-10-04T08:28:27Z */` at the top of all uglified output.
> Fix #1521 - add banner with version, git sha1, build time and date to uglified JS

- src/streaming/TextSourceBuffer.js
* If composition_time_offset flag is not set in trun box header, it is
leading to garbled CC text rendering.
* This is caused by "undefined" sample.sample_composition_text_offset
field.
* codem-isoboxer expects the caller to resolve to the defaults.
> Bugfix for rendering CEA608 captions embedded in H264 SEI

- src/streaming/models/VideoModel.js
When the player buffers during playback, stream is stalled. Seeking removes the stalled stream, and updates the playbackRate. However, setPlaybackRate was being called before enough data was loaded to play (ready state 3, "HAVE_FUTURE_DATA").
Now, if readyState<3, an event listener is added to update playbackRate once "canplay" is triggered.
Similar issue when trying play/pause during buffer is fixed by #1616.
> Fix #1447 - Wait for data before updating element playbackRate

- samples/dash-if-reference-player/app/sources.json
- Added Clear Key variants of Axinom v7 test vectors.
- Split Axinom test vectors into two batches, as the menu was getting uncomfortably large to use; the modern variants (with H.265 and fancy features) are in one menu, with conservative ("should play everywhere" style content) in another menu.
- Renamed Axinom test vectors to be a bit more human-readable (hopefully).
Note: the Clear Key test vectors do not actually play in dash.js. This is expected, as the dash.js implementation of Clear Key does not conform to IOP.
> Added Axinom Clear Key test vectors

- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/index.html
copy item when setting the selectedItem.url to avoid altering original json menu object,  removed binding blocking the custom input
> Fix for #1653

- src/streaming/utils/TTMLParser.js
Dash.js wasn't playing any TTML that had explicit namespacing. The problem lay with the removeNamespacePrefix function on 2 points: it cancelled parsing and afterwards it turned out to not have catered for tt being a substring of tts so it removed tt and so the :extent region attribute was born. 
The test framework needs examples of EBU-TT-D with and without default namespace to prevent such an error hiding.
> Fixing namespaced TTML malfunction

- src/streaming/controllers/TextController.js
add in TextController, the 'getIsBufferingCompleted' function.
in a dash content with a TTML file, this function was missing.
In the start function of the SchedulleController, an error was reported.
> missing 'getIsBufferingCompleted' function in TextController

- src/dash/models/DashManifestModel.js
if in the dash manifest, the range for initialization is set, use the baseUrl for initialization request.
> Do not send request to know init index range when the information has been set in the manifest

- AUTHORS.md
- package.json
- samples/dash-if-reference-player/app/sources.json
- src/dash/models/DashManifestModel.js
- src/dash/utils/FragmentedTextBoxParser.js
- src/streaming/TextSourceBuffer.js
- src/streaming/controllers/SourceBufferController.js
- src/streaming/utils/IsoFile.js
- src/streaming/utils/TTMLParser.js
Implementation of #1418.
An extension to support image subtitles packaged as ISOBMFF segments with png images in subsamples in the same sample as the TTML document. This required the implementation of a new box `subs` in the iso parser including codem-isoboxer.
This follows IMSC1 which disallows the base64-encoded embedded images in the TTML documents.
Support was also added to handle the extended codecs value `stpp.ttml.im1i` which what CMAF DIS lists as the proper value.
A new test asset has been produced and added to the reference player:
http://vm2.dashif.org/dash/vod/testpic_2s/img_subs.mpd
> imsc1 image subtitle support

- src/streaming/controllers/ScheduleController.js
When the max representation available to ABR changes because of updateQuality or Portal Bitrate change, the Buffer Level rule prevents switching because the buffer is larger than the stable bitrate buffer target (12 or 20s). The previous "top quality" target buffer size of 60s means that any appending to the buffer is suppressed for 48s so the user sees their buffer collapse.
Any change in getTopQualityIndexFor() now allows an immediate update of the rules. This should prevent the buffer near exhausting when quality changes and therefore reduce risk, especially as this happens whenever a user goes fullscreen.
Expensive bufferLevelRule is also not called now if getNextFragment is already triggered by isReplacement or topQualityChanged.
> Allow immediate switching when top quality index changes

- samples/dash-if-reference-player/app/sources.json
- src/streaming/utils/TTMLParser.js
Fix of minor bug introduced with IMSC1 image subtitle commit.
Made TTML subtitles without metadata not working, such as
http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/client_manifest-snake.mpd
> Bug fix image subtitles

- src/streaming/controllers/BaseURLController.js
- src/streaming/utils/URLUtils.js
- test/streaming.utils.URLUtils.js
I have tested this against various MPDs from other BaseURL issues, the Twitter MPD from the issue, and also checked all the previous tests still pass as well as the new tests.
> Fix #1682 - correctly test for absolute URLs

- src/streaming/metrics/utils/MetricSerialiser.js
- test/streaming.metrics.utils.MetricsSerialiser.js
We noticed during some metrics gathering we have been doing that the reporting format did not quite match the DVB specification.
Fixed and added a couple of tests for the serialiser.
> Metrics Reporting: fix List type serialisation and add a couple of tests

- src/streaming/MediaPlayerFactory.js
Quick fix to guard against creating elements before dashjs has loaded. Assumes there's no expectation for MediaPlayerFactory to create elements if loaded dynamically (as in #1680).
> Fix #1680: Prevent MediaPlayerFactory creating elements if dashjs hasn't loaded

- src/streaming/controllers/ScheduleController.js
We are currently testing BaseURL switching and it seems to be fairly broken by some changes that have happened in the ScheduleController since BaseURL was originally implemented. More details to follow as we have them, and I'll open a holding issue now.
This one, though, has always been there and is definitely incorrect. The `serviceLocation` attribute belongs to a `request` and will never be found on the `event`. Without this fix, failed requests will never be retried on a new BaseURL. With it, for now, they still won't be rerequested as there are other problems with request replacement.
> [BaseURL] serviceLocation is a request attribute, not an event attribute

- src/streaming/controllers/ScheduleController.js
As discussed in #1702, the fast switch changes meant that alternate base urls were not failed to in the event of a download failure. This is fixed by kicking the scheduler once the replacement queue has been populated.
Additionally, extra checks are needed to ensure that if it was an initialisation segment that failed this can be rerequested since next fragment rule will not replace these.
> Fix #1702 - ensure replacements are rerequested on failure

- src/streaming/controllers/BaseURLController.js
- src/streaming/utils/BaseURLSelector.js
- test/streaming.controllers.BaseURLController.js
Debugging #1701 showed a bug that has always existed but was only exposed once the fast switch changes were added.
If URL resolution fails, an event is fired which stops the scheduler. If you subsequently try to resolve a Base URL after this (which in theory should never happen, but can in certain circumstances), the resolver can return unexpected results. This change ensures that no sensible result is returned once a failure has occurred.
This is a one line change (L91, BaseURLController) - all the other stuff is simply to get the test running to verify the fix.
> Fail properly when Base URL Resolution fails

- .travis.yml
As per https://github.com/nodejs/LTS/#lts-schedule:
- Node 0.12 is no longer supported after 31st Dec 2016
- Active LTS versions are 4 and 6.
Node 0.12 seems to be causing intermittent failures of our Travis builds for network-related reasons, which are not seen on the Node 4 job. Removing it should make our Travis badge more likely to remain green.
> Use recent node versions in travis builds

- samples/dash-if-reference-player/app/main.js
Add possibility to specify the auto loaded full stream object (url, protData, ...) as an url parameter (in base64 string) of the webapp.
This enables testing other streams not in sources.json for which you have to specify other parameters than only the manifest url.
Example usage:
```
var stream = {
"name": "CableLabs Cenc PR/WV",
"url": "http://html5.cablelabs.com:8100/cenc/prwv/dash.mpd",
"protData": {
"drmtoday": true,
"serverURL": "https://lic.staging.drmtoday.com/license-proxy-widevine/cenc/",
"httpRequestHeaders": {
"dt-custom-data": "eyJ1c2VySWQiOiIxMjM0NSIsInNlc3Npb25JZCI6ImV3b2dJQ0p3Y205bWFXeGxJaUE2SUhzS0lDQWdJQ0p3ZFhKamFHRnpaU0lnT2lCN0lIMEtJQ0I5TEFvZ0lDSnZkWFJ3ZFhSUWNtOTBaV04wYVc5dUlpQTZJSHNLSUNBZ0lDSmthV2RwZEdGc0lpQTZJR1poYkhObExBb2dJQ0FnSW1GdVlXeHZaM1ZsS …
```
> Sample player: add auto loaded stream as param url

- src/dash/DashMetrics.js
Trim headerStr to fix a MS Edge bug with xhr.getAllResponseHeaders method which send a string starting with a "\n" character
Sources :
- https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5403401/
- https://connect.microsoft.com/IE/feedbackdetail/view/1929694/ie-edge-incorrectly-return-the-header-with-a-leading-new-line-character
- https://github.com/exceptionless/Exceptionless.JavaScript/issues/23
> [MS Edge bug] Response header string starts with \n

- src/dash/DashHandler.js
- src/streaming/controllers/PlaybackController.js
When trying to play from a currentTime outside of a live stream's availability window, getActualPresentationTime previously shifted to the live-edge. Now it will return trailing-edge if requested time < window start.
Play live steam -> pause -> drift outside of DVRWindow -> try to play -> be moved to start of window
This works well for BBC where live-rewind window is 2 hrs. For much shorter windows, perhaps an option to force playback from live edge regardless may be preferred?
930717e fixed issue where segments were updated out of order such that previously fetched index was no longer valid.
> getActualPresentationTime returns nearest DVRWindow edge 

- externals/xml2json.js
Remove explicit AMD support as requested in #1726.
Best reviewed with the ?w=1 querystring - it's actually only a few lines changed.
> Fix #1726 - remove explicit amd support from xml2json fork

- src/streaming/MediaPlayerFactory.js
Fixes #1722 caused by #1694, without re-breaking initial issue (#1680).
When MediaPlayerFactory tries to create elements:
- document is complete and dashjs loaded -> continue as normal
- document is not complete (#1722) -> add a load event listener
- document is complete but dashjs undefined (#1680) -> set an interval to wait for dashjs
There's probably a less icky way of achieving this without the need for the interval though?
> Fix #1722: Wait for dashjs before creating element(s) if loaded asynchronously

- src/streaming/protection/controllers/ProtectionController.js
Currently if the end user provides any protection data for the Key System
our library no longer retrieves the license server URL from the initData.
The above combines with the fact that the ProtectionKeyController skips Key
Systems without protection data if protection data is provided for any
key system in a bad way.
The end result is that if you want to provide some
data for one key system you can't get the serverUrl from the initData for
a different key system. This ensures that even if protection data was passed,
if no serverURL or laURL is provided we try to get the url from the initData.
> Allow providing protData without requiring serverURL

- src/dash/DashHandler.js
- src/dash/SegmentBaseLoader.js
- src/dash/WebmSegmentBaseLoader.js
- src/dash/controllers/RepresentationController.js
- src/dash/models/DashManifestModel.js
- src/dash/utils/SegmentsUtils.js
- src/dash/vo/Representation.js
The manifest in #1731 showed up an issue where `BaseURLs` were not resolved properly for `SegmentBase` elements if they had a path in them because the path element appeared to be resolved twice. The reason for this was that `SegmentBase` and `BaseURL` manifest types were copying the `BaseURL` element to `initialization`, but still resolving the BaseURLs anyway, leading to the behaviour seen.
Further, once the BaseURL resolution had been performed at startup time for these manifest types it could not be redone so they would not be able to benefit from BaseURL redundancy (although this is probably less of an issue since they are for on-demand use).
I tested these specific changes using:
- http://timcin-wedding.s3-eu-west-1.amazonaws.com/videotest-album/hls/a5b3f3f0d4d711e6b653affe68f4ebc2/pl …
> Fix #1731 - ensure BaseURLs are resolved properly for SegmentBase

- src/streaming/controllers/ScheduleController.js
So when I refactored for Dynamic multiperiod I noticed a "way too complex" system used for liveedge search as a rule.  I removed a ton of code to simplify this and that was successful except I missed one line that was critical for segmentTimeline since it does not use Timesync. 
timelineConverter.setTimeSyncCompleted(true);
So for SegmentTimeline the seekAtStart was not called properly. 
I believe setting this from a single point,  at live edge search complete handler in schedule controller is the best place in the code.  Other option is,  we can add back in the handler into timelineConverter just to set this locally but I think that actually makes it more confusing .  IMHO. 
I tested with some URLS in the issues as well as all of the live streams in the live section in the player. 
All …
> fix for segmenttimeline live start #1729

- src/dash/DashHandler.js
Fixes #1759 caused by 930717e.
Original reason for 930717e was a problem were segment lists were updated out of order such that the previously fetched index was sometimes no longer valid. For instance, if a paused player drifted outside of the rewind window, when seeking back, the `getSegmentByIndex` and `getIndexForSegments` functions would be using different segment lists.
Moving `updateSegments` fixed the issue, but caused problems for other streams where the segment list needs to be updated on every `getSegmentRequestForTime` call.
6650178 now works, but the whole thing could probably do with refactoring and the first `updateSegments` should probably go somewhere else.
> Fix #1759 (regression) resume correctly after seek

- Gruntfile.js
Build was failing if code was grabbed as archive rather than cloned from git repo.
See https://www.npmjs.com/package/grunt-githash#optionsfail
> Fix #1749 - do not fail to build if not a git repo

- src/dash/utils/TimelineConverter.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/utils/LiveEdgeFinder.js
This PR should solve all the issue raised in #1729 - This is a fix to restore but we need some work here so I am adding an issue about timesync refactor 
We need to figure out if we want to timesync for segmentTimeine where useCalculatedLiveEdge = true.   If not, we should bypass code in StreamController's onManifestUpdated entry point to timeSync and other places.
> fix for all live edge issues mentioned in  #1729

- src/core/EventBus.js
Stop mutating `handlers[type]` in `EventBus#off`. Doing so prevents all handlers from being run if `off()` is called while executing a callback.
Fixes #1773
> Fix bug where EventBus handlers are removed before execution

- Gruntfile.js
- index.js
- package.json
- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/app/sources.json
- src/dash/models/DashManifestModel.js
- src/dash/vo/Representation.js
- src/mss/MssFragmentProcessor.js
- src/mss/MssHandler.js
- src/mss/parser/MssParser.js
- src/streaming/ManifestLoader.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/controllers/TextController.js
- src/streaming/utils/InitCache.js
We, at Orange Labs (me and my colleague @nicosang), started integration of smooth streaming support into dash.js, as we proposed last year during dash.js f2f meeting.
For the time being, we have achieved to extend dash.js in order to support smooth streaming static streams, clear and encrypted (with PlayReady).
What we have done:
-	Add of ‘src/mss’ source package. 
-	Add of smooth streaming parser MssParser, that parses smooth streaming manifest and converts it into dash manifest object: mapping from smooth streaming nodes to dash nodes including creation of SegmentTimelines
-	Add of MssHandler that hands processing of initialization and media segments. This class is registered on INIT_REQUESTED and FRAGMENT_LOADING_COMPLETED in order to trigger these segments processing. We took benefit …
> Smooth Streaming support

- src/streaming/TextSourceBuffer.js
The `insertInOrder` method fails to insert the CC packets in order and causes issue with CEA-608 caption dispaly. A simpler sort method can be used after the data is found to sort the data.
```
var a = []
insertInOrder(a, 1, [1]);
insertInOrder(a, 2, [2]);
insertInOrder(a, 3, [3]);
insertInOrder(a, 2.5, [2.5]);
insertInOrder(a, 2, [2]);
console.log(a);
```
the following quick test exposes the issues with `insertInOrder`.
> fix: ordering of cea606 data

- src/streaming/TextSourceBuffer.js
Assuming an AdaptionSet has roles defined, the only way to access them is via [`MediaPlayer#getTracksFor('text')`](http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html#getTracksFor__anchor). If the manifest is using fragmented text, then `MediaPlayer#getTracksFor('text')` will return `[]` and the only way to get the text track list is to listen for `TEXT_TRACKS_ADDED`. However, the `tracks` in the `TEXT_TRACKS_ADDED` event is `TextTrackInfo[]`, which does not include the original `roles`.
This will pass through whatever `roles` are parsed, allowing them to be accessed for all text track types.
Possibly a workaround for #1236
> feat(TextTrackInfo) Passthrough roles even if dash can't parse them

- index.js
- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/app/sources.json
By default, smooth streaming management has not to be included in dash.all. In the 'dash-if-reference' web app, smooth streaming samples are stored at the end of the list.
Finally, in this webApp, smooth samples are showned to the user only if the mss package has been added in the index.html file.
> Mss package management

- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
with multiPeriod VOD sample, when the playback changes from period, some objects was undefined. A call to reset function had destroyed these objects.
Add validity tests...
> undefined object when switching of period.

- src/streaming/models/MetricsModel.js
Arising from #1389. Metrics can become really large objects, and it's not clear that they're actually used. Long running streams can experience performance issues as these stores continue growing.
As (a crude means of) mitigation, cap the size of each metrics list (set to 1000 arbitrarily).
Ran a short 2-hour test on two instances of a live stream (which had been running for a while already) - one without and one with the metrics cap. Heap snapshot profiles taken before/after showed the uncapped stream's overall object memory grew by 15MB, while the capped one grew by 0.6MB.
> Fix #1389: Restrict size of metrics lists

- src/streaming/controllers/SourceBufferController.js
The current placement of the try/catch is not correct.  waitForUpdateEnd() may execute the callback asynchronously, and the thrown errors (for example, QuotaExceededError) are not caught.
> Fix try/catch for append and remove

- src/streaming/Stream.js
- src/streaming/controllers/StreamController.js
the call to checkVideoPresence was made in the first call to SwitchStream, done from composeStreams. The problem is, at this specific time, no StreamProcessor has been built. The return value of this function is always false.
I suggest to call this function in activateStream, the first time.
> Move check video presence call.

- src/streaming/utils/VTTParser.js
Please see https://github.com/Dash-Industry-Forum/dash.js/issues/1825 for a description of the issue this resolves.
> Don't use decodeURI when parsing cue text

- src/dash/DashAdapter.js
- src/streaming/controllers/FragmentController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/models/FragmentModel.js
fragmentModel is referenced in ScheduleController. ScheduleController was referenced in fragmentModel : removing this dual "dependence".
fragmentModel doesn't need ScheduleController, streamInfo is set in each request object
> Code simplification : remove an unecessary reference.

- .jscsrc
- .jshintrc
- Gruntfile.js
- src/core/Debug.js
- src/dash/parser/matchers/StringMatcher.js
- src/mss/parser/MssParser.js
- src/streaming/StreamProcessor.js
- src/streaming/TextSourceBuffer.js
- src/streaming/controllers/BufferController.js
- src/streaming/metrics/MetricsReporting.js
- src/streaming/metrics/controllers/MetricsController.js
- src/streaming/metrics/utils/RNG.js
- src/streaming/protection/Protection.js
- src/streaming/protection/drm/KeySystemWidevine.js
- src/streaming/protection/servers/ClearKey.js
- src/streaming/protection/servers/DRMToday.js
- src/streaming/protection/servers/PlayReady.js
- src/streaming/protection/servers/Widevine.js
When I looked at CodeClimate I couldn't believe that we weren't seeing these flagged in the JSHint output. Turns out that test is, amongst others, long deprecated or removed.
I fixed the problem, then added the JSCS equivalents and removed the deprecated options in JSHint, so we shouldn't see these issues checked in anymore.
> Fix trailing commas, update JSCS and JSHint configs

- externals/xml2json.js
When using a polyfilled shadow DOM, the node.childNodes object is not a NodeList, but an array. The .item() method does not exist for Arrays.
> Support XML parsing when node.childNodes is Array

- src/dash/DashHandler.js
- src/mss/MssHandler.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/FragmentController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/utils/InitCache.js
- src/streaming/vo/DataChunk.js
- src/streaming/vo/FragmentRequest.js
I used the sample http://wowzaec2demo.streamlock.net/vod/_definst_/ElephantsDream/smil:ElephantsDream.smil/manifest_mvnumber.mpd in order to test audio switch management. I found the first downloaded init audio segment was always used for each language switch.
With this specific sample, it works maybe because the two audio configurations are very similar.
What I propose in this PR is to store init segment by adding the id of adaptationSet. Indeed, two audio languages could have the same quality in two different adaptationSet.
> Audio switch management update

- src/streaming/TextTracks.js
Fixes issue #1833.
To see the problem, use the reference player with asset http://vm2.dashif.org/dash/vod/testpic_2s/imsc1_img.mpd
and open the content menu and a submenu which goes behind the subtitle.
Now fixed.
> Fix bug with z-index for image subtitles

- src/streaming/text/TextSourceBuffer.js
When sorting CC packets, those that are received at the same time
should be ordered by the order in which they were receiving, such that
correct ordering will be maintained when displaying them.
Otherwise you end up with garbled captions being displayed.
> Fix CC packet sorting

- src/streaming/text/TextBufferController.js
https://github.com/Dash-Industry-Forum/dash.js/issues/1903
Caused by https://github.com/Dash-Industry-Forum/dash.js/commit/ed2005a31df7e227a295de8281a565c5604d41df#diff-d10a4783ead24da292fe133eb36db75bR154
> fix(TextBufferContoller): only export one default

- src/streaming/text/EmbeddedTextHtmlRender.js
I was getting problems where a mid-row caption change to italics
was trimming away space between spans on the same row. This change
fixes that over-zealous trimming so that spaces between spans are
preserved.
> Fix over-zealous trimming

- src/mss/parser/MssParser.js
- src/streaming/MediaPlayer.js
- src/streaming/text/TextController.js
- src/streaming/text/TextSourceBuffer.js
- src/streaming/utils/TTMLParser.js
Hello
The goal of this PR is to fix a pb on Smooth Streaming subtitles.
The TTML begin and end tags are absolute. But in this case they are relative to fragments start time.
> Smooth Streaming Support : TTML Captions

- src/streaming/text/TextTracks.js
- src/streaming/utils/TTMLParser.js
Added support for embedded base64-encoded SMPTE-TT image element.
Tested with http://vm2.dashif.org/dash/vod/testpic_2s/img_subs.mpd
Compared to before imscJS integration, I saw the following differences:
The name space `xmlns:tts="http://www.w3.org/ns/ttml#styling"` needed to be corrected (was `#style#`).
Of the three variants on using `tts:extent` and `tts:origin`:
http://vm2.dashif.org/dash/vod/testpic_2s/img_subs_px.xml
http://vm2.dashif.org/dash/vod/testpic_2s/img_subs_percent.xml
http://vm2.dashif.org/dash/vod/testpic_2s/img_subs_div.xml
the two first still work, but the third does not since it specifies `tts:extent` and `tts:origin` in the `div`element, and this is not allowed by TTML.
> Add support for SMPTE-TT base64-encoded  subtitles images.

- samples/dash-if-reference-player/app/css/main.css
- samples/dash-if-reference-player/index.html
Center the video-caption div on top of the videoContainer by setting videoContainer position.
Fixes #1942
> Fix to center subtitles in reference player [#1942]

- src/dash/DashHandler.js
- src/streaming/Stream.js
- src/streaming/StreamProcessor.js
- test/dash.DashHandlerSpec.js
- test/helpers/ObjectsHelper.js
indexHandler is an attribute of StreamProcessor. This PR suggests to move createIndexHandler function in StreamProcessor. In the same way, SegmentBaseLoder is moved in DashHandler class.
> Create index handler in stream processor

- src/core/Debug.js
- src/core/FactoryMaker.js
- src/dash/DashHandler.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
This PR enables to extend debug log messages with callee class name, and media type if available. 
This may facilitate debugging by filtering log messages in the browser console.
For example, if you filter log message related to DashHandler for video track, then you would get the following messages to displayed:
By the default, class names and types are not displayed.
This can be enabled by calling 
`player.getDebug().setCalleeNameVisible(true);
`
> Enhanced debug

- src/streaming/controllers/MediaSourceController.js
- src/streaming/controllers/StreamController.js
This continually sets the seekable attribute on the mediaSource to be the same as the current DVR window. It implements #1384 and is a fix for #1867
> Set the seekable range on the mediaSource

- src/streaming/MediaPlayer.js
- src/streaming/metrics/controllers/MetricsCollectionController.js
Hi,
the aim of this PR is to manage properly metricsReportingController. Before thoses changes, the call to resetAndInitializePlayback set metricsReportingController to null, without doing any unregister events call. 
So, I suggest that a call to a reset function on metricsReportingController in reset function of MediaPlayer should be made. This reset function has to unregister events. After this step, metricsReportingController could be set to null.
Nicolas
> Metrics controller for all streams

- samples/getting-started-basic-embed/auto-load-multi-video.html
- samples/getting-started-basic-embed/auto-load-single-video-src.html
- samples/getting-started-basic-embed/auto-load-single-video-with-context-and-source.html
- samples/getting-started-basic-embed/auto-load-single-video-with-reference.html
- samples/getting-started-basic-embed/auto-load-single-video.html
- samples/getting-started-basic-embed/listening-to-events.html
- samples/getting-started-basic-embed/manual-load-single-video.html
- samples/live-streaming/live-delay-comparison-custom-manifest.html
- samples/live-streaming/live-delay-comparison-using-fragmentCount.html
- samples/live-streaming/live-delay-comparison-using-setLiveDelay.html
This week I have been looking at Google's [cobalt](http://cobalt.foo/), and I thought I'd see if I could get dash.js to run on it.
The manual-load-single-video sample works great, but `<body onload>` doesn't work to get the application running, so I needed to change it to using an event listener. This should be a harmless on other platforms - I have verified all examples still work in Chrome.
I also noticed that most samples did not have a closing head tag, so I fixed that up.
> Fix up getting-started samples so they work on more platforms

- src/streaming/ManifestLoader.js
This implements the use of Location@MPD not only for manifest updates, but also as BaseURL for fetching of segments as discussed in #1887.
As the manifestUpdate, only the first Location element is used.
A test vector is available at http://vm2.dashif.org/dash/vod/Location.mpd
> Using Location as baseURL for segments [Fixes #1887]

- index.d.ts
- src/dash/models/DashManifestModel.js
- src/dash/vo/Representation.js
- src/streaming/controllers/AbrController.js
- src/streaming/vo/BitrateInfo.js
In response to issue #1880 
The goal of this PR is to expose the scanType of a representation in order to allow implementations to show it to the user when selecting qualities, or even filter by scanType
> Added scanType field

- src/streaming/MediaPlayer.js
- src/streaming/rules/abr/ABRRulesCollection.js
Whilst debugging another issue, I noticed that each time InsufficientBufferRule was created (once per session), it added a handler for the playback seeking event which was never released.
This PR ensures that rules which have a reset method have that method called at the start of each new session.
> Ensure ABR Rules are cleaned up correctly when player is reset

- src/streaming/controllers/AbrController.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/StreamController.js
- src/streaming/models/VideoModel.js
- src/streaming/text/TextController.js
- src/streaming/utils/TTMLParser.js
Hi,
the main goal of this PR is to centralize and protect all access to HTML5 video element in VideoModel class. Responsibility was shared between videoModel and PlaybackController. Some access still remains in Protection module....
Nicolas
> Video model modification

- src/dash/utils/FragmentedTextBoxParser.js
- src/streaming/text/TextSourceBuffer.js
- src/streaming/utils/IsoFile.js
- src/streaming/vo/IsoBox.js
I don't expect this PR as it currently is to get accepted, but it's a good place to discuss.
Right now, dash.js only parses out the text information from the first `moof` in a segment. It would be nice if the text data could be pulled out of _all_ the `moof`s in a segment.
This PR patches in support for multiple `moof`s per segment for CEA608 captions.
Is there anywhere else in the code where multiple `moof`s per segment are rejected, or is it only the text stuff?
> allow multiple moofs per segment

- src/streaming/MediaPlayer.js
- src/streaming/models/MediaPlayerModel.js
Exposed manifest loader retry attempts function and retry interval functions as was listed in the the following issue - https://github.com/Dash-Industry-Forum/dash.js/issues/1939
> expose manifest retry function

- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
When QUOTA_EXCEED is thrown when appending to the source buffer, the isFragmentProcessingInProgress flag isn't cleared, so no more scheduling occurs after this happens.
> Make quota_exceed reset isFragmentProcessingInProgress

- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/models/ProtectionModel_21Jan2015.js
This PR enables setting the server certificate which will be required from chrome 59, in order to avoid the server certificate request before each license request.
The server certificate has to be provided in base64 format in protectionData:
```
player.setProtectionData({
"serverURL": "<licenser_url>",
"serverCertificate": "<server_certificate_in_base64>",
...
});
```
Since the server certificate is specific to every license server, I am not able to provide any certificate for the test streams of sample webapp.
> Server certificate

- package.json
- src/streaming/models/BaseURLTreeModel.js
- src/streaming/utils/ObjectUtils.js
- test/streaming.utils.ObjectUtils.js
If objects have same parameters but declared in a different order, string obtained using JSON.stringify() will be different and the method will return false, whereas it should return true.
The fix uses deep-equal module to avoid this bug.
I have although added a unit test to test the solution (in streaming.utils.ObjectUtils.js file) : using JSON.stringify(), the unit test fails, using deep-equal module, the test is in success
> Fix a bug in ObjectUtils::areSimpleEquivalent method

- src/streaming/MediaPlayer.js
- src/streaming/controllers/AbrController.js
- src/streaming/rules/abr/ABRRulesCollection.js
- src/streaming/rules/abr/AbandonRequestsRule.js
- src/streaming/rules/abr/BolaAbandonRule.js
- src/streaming/rules/abr/BolaRule.js
- src/streaming/rules/abr/ThroughputRule.js
Hi 
This PR proposes modifications about ABRRulesCollection creation :
- Now instanciated by AbrController (function createAbrRuleCollection), no more in mediaplayer (removes a link)
- Not a singleton anymore (used only in ABRController)
- metricsModel, dashMetrics, mediaPlayerModel are given in config at the creation 
- add a reset function called by ABRController::reset
Jérémie
> ABR Rules Collection creation

- src/streaming/controllers/AbrController.js
- src/streaming/rules/DroppedFramesHistory.js
The outstanding dropped frames statistics in the VideoModel correspond to the old quality.
> old quality should be reported to droppedFrameHistory onQualityChangeRendered

- src/streaming/controllers/AbrController.js
- src/streaming/controllers/ScheduleController.js
- test/unit/streaming.AbrControllerSpec.js
Hi,
this PR has to use,  actually, streamProcessorDict attribute. Each time a streamProcessor is created,it is stored in  streamProcessorDict array. So, the consequence is that the functions of AbrController just need type as parameter, not the streamProcessor reference.
Nicolas
> update the use of streamProcessorDict in AbrController

- samples/dash-if-reference-player/index.html
to suppress mixed content warnings when player is loaded under https
> Removing hard-coded protocol on github buttons 

- test/unit/streaming.utils.ObjectUtils.js
In PR #1956 unit tests have been moved to test/unit folder.
PR #1979 adds a new unit test. When merging in development version, the new unit test have not been moved to test/unit.
This PR merge the pb. 
Jérémie
> Fix bad merge when PR #1979 and PR #1956 have been merged in development

- src/streaming/MediaPlayer.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/MediaController.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/StreamController.js
- src/streaming/rules/abr/AbandonRequestsRule.js
- src/streaming/rules/abr/ThroughputRule.js
- src/streaming/text/TextSourceBuffer.js
Hi,
in some files, the reset function was calling the setup function :
- AbrController.js
- PlaybackController.js
- AbandonRequestsRule.js
- ThroughputRule.js
The main consequence was an unnecessary call to getInstance function when the user changed the video stream. So, I propose to do the reverse : setup function calls the reset. The setup function only calls the different getInstance reference. The others attributes are initialized in the reset function.
Nicolas
> Update reset functions

- src/streaming/rules/SwitchRequestHistory.js
Adding those requests breaks the SwitchHistoryRule
Fix  #1892
(New PR due to some merge issues)
> Do not add SwitchRequests with NO_CHANGE to SwitchRequestHistory

- src/streaming/controllers/BufferController.js
- src/streaming/utils/IsoFile.js
Hi,
this PR has to remove properly the emsg box before to append segment in video buffer.
> //TODO Discuss why this is here. inbandEventFound is never set to true!!
I'm not sure that it is really needed to remove this box. is there someone that can confirm this needed?
If it's not, I will update this PR by remove this part of the code.
[Fraunhofer sample](http://se-mashup.fokus.fraunhofer.de:8080/tests/dsi/mws15/dash.js/samples/ad-insertion/adinsertion_inband.html)
> update emsg box management

- src/dash/utils/FragmentedTextBoxParser.js
Hi,
this PR has to fix a bug on  images CMAF subtitles. Images subtitles  were cut for this
[stream](http://vm2.dashif.org/dash/vod/testpic_2s/imsc1_img.mpd).
it's a regression after PR 1954
Nicolas
> bug fix on images CMAF subtitles

- src/dash/controllers/RepresentationController.js
- src/streaming/controllers/AbrController.js
- src/streaming/rules/ThroughputHistory.js
- src/streaming/rules/abr/ABRRulesCollection.js
- src/streaming/rules/abr/InsufficientBufferRule.js
- src/streaming/rules/abr/ThroughputRule.js
Move the throughput/latency estimation from ThroughputRule to a separate ThroughputHistory.
Update the InsufficientBufferRule to also avoid downloading bitrates that are more prone to lead to rebuffering.
> split ThroughputHistory out of ThroughputRule, update InsufficientBufferRule

- src/streaming/MediaPlayer.js
It's not true that the media player isn't initialised after calling reset() - it's in exactly the same state as calling initialize() with no arguments. It's still in a valid initialized state and possible to call attachView(), attachSource() and playback afterwards.
> Don't set initialized flag to false in MediaPlayer.reset()

- index.d.ts
Fix return-type annotation in index.d.ts for setRobustnessLevel to void as it has implicit 'any' return-type
> Fix return-type annotation in index.d.ts for setRobustnessLevel

- src/core/events/CoreEvents.js
- src/streaming/MediaPlayerEvents.js
Fix https://github.com/Dash-Industry-Forum/dash.js/issues/2005
I could also rename this event to something more explicit like `PLAYER_RESET` if necessary
> Move STREAM_TEARDOWN_COMPLETE to MediaPlayerEvents

- build/typings/index.d.ts
- src/dash/models/DashManifestModel.js
in some browsers, Number.isInteger function is not defined.
This PR fix the issue #2028
> bug fix #2028

- src/streaming/MediaPlayer.js
- test/unit/mocks/AbrControllerMock.js
- test/unit/streaming.MediaPlayerSpec.js
This is really helpful to build debug graphs for the ABR logic
> Add getter for average throughput on MediaPlayer's API

- src/dash/controllers/RepresentationController.js
- src/mss/parser/MssParser.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/rules/scheduling/NextFragmentRequestRule.js
Hi 
This PR solves a pb encountered by @qchroman (cf Issue #1938) , when playing streams
https://djkxw9frc3oss.cloudfront.net/live/live.isml/Manifest
https://djkxw9frc3oss.cloudfront.net/live/Sintel_0500.isml/Manifest
It has to be noticed that using these streams, some fragments are quite long (10s) and sometimes getFragmentRequestForTime doesn't return the right fragment corresponding to time, but the previous one, because of threshold in FragmentModel:getRequestForTime. That's why there is a loop in nextFragmentRuel, to get the first next not loaded fragment.
Another point is buffer parameters are :
"liveDelay": 18,
"stableBufferTime": 16,
"bufferTimeAtTopQuality": 16,
"bufferTimeAtTopQualityLongForm": 16
> Fix issue # 1938 - MSS with dvrWindowsSize = 0

- Gruntfile.js
Hi,
in the previous PR #1846, @jeremco has introduced the ability to overide abr rules outside of dash.js. It works well when the dash.all is used, it doesn't when the different modules are used.
So, I suggest that we add a factorymaker module in order to be able to overload the rules outside the dash.js.
Nicolas
> Custom Abr Rules v2

- test/unit/streaming.controllers.XLinkController.js
Hi
This PR solves a problem in development branch on XLinkController unit tests, due to merge with PR #2054 (Dash Parser unit tests)
Jérémie
> Fix a problem on XLinkController unit tests

- src/streaming/rules/ThroughputHistory.js
- src/streaming/rules/abr/ThroughputRule.js
#2003 changed the behavior at startup when only cached segments are available to calculate throughput.  When no uncached segments are available, a throughput estimate is taken from cached segments.  This is not ideal, but ABR rules need something to go by.  As from #2003, the cached-fragment throughput is incorrectly divided by a factor of 1000.  This PR fixes that issue.
> fix handling of cached segments in ThroughputHistory

- src/streaming/controllers/MediaSourceController.js
Fix for issue #2089, implementing the preconditions, start is positive and less than end, and the mediaSource has readyState open. I didn't do much investigation here into the underlying question of why we would have such a strange availability window, so that remains a mystery.
> Don't let crazy rewind window be applied to mediaSource seekable range

- Gruntfile.js
- index_mediaplayerOnly.js
- samples/dash-if-reference-player/app/rules/DownloadRatioRule.js
HI 
PR #2057 was not sufficient to export FactoryMaker instance (using a module, 2 different instances were created). The idea here, is to export FactoryMaker directly in module mediaplayer, so that, there is only one instance of FactoryMaker.
This PR also updates sample custom ABR rules
Jérémie
> FactoryMaker exports

- src/mss/parser/MssParser.js
- src/streaming/MediaPlayer.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/controllers/ProtectionKeyController.js
- src/streaming/protection/drm/KeySystemWidevine.js
Hi
This PR adds support of decoding for MSS streams using Widevine
For these streams, PSSH can be given by setting ProtectionData in media player
protData: {
"<key_system>": { ....
pssh: "<pssh (as Base64 string)>" // Considered for Widevine key system only
} 
Jérémie
> Mss widevine pssh

- contrib/akamai/controlbar/ControlBar.js
Added a null check so that `togglePlayPauseBtnState` will not explode if the button does not exist. In my particular context this was being fired after destroy was being called, so the button did not exist.
Also fixed what is presumably a typo. `reset` does not exist in that context, although `this.reset` should work.
Please do let me know if you'd like to change anything else!
> Fix Destroy in ControlBar.js

- src/streaming/rules/scheduling/BufferLevelRule.js
At the end of a stream, the videoBufferLevel is less than 1. If the fragmentDuration is less than 1, then floor(max(videoBufferLevel, fragmentDuration)) is 0 and the audio buffer target is set to 0. That causes the video to not play through to the end #1901.
> fix audio buffer target when videoTrackPresent

- src/streaming/controllers/XlinkController.js
I noticed that xlinked content which does not include an XML declaration was incorrectly handled by xlinkcontroller which would cause remote Period resolution to fail.
The XML declaration is optional (the spec only says it SHOULD be included).
This fixes at least the first issue in #1414.
> Detect xmldecl (or lack of) correctly when resolving xlink

- src/dash/DashHandler.js
Hi,
this PR has to fix a bug for live segment Timeline. Since PR #2030 , it was impossible to play live stream based on segment timeline.
Nicolas
> bug fix for segment timeline streams

- src/dash/controllers/RepresentationController.js
- src/streaming/utils/DOMStorage.js
Storing the bitrate of one of the available representations can lead to excessive rounding down (#2124) when different video streams are available for the same origin.
Also some ABR rule other than ThroughputRule can cause a drop in quality. E.g. if a live streaming session has a very shorter buffer, then InsufficientBufferRule will be conservative and limit the quality to a bitrate lower than the throughput. In such a case we want the throughput and not the representation bitrate to be stored in localStorage.
> store throughput in localStorage, not bitrate of last quality

- samples/dash-if-reference-player/app/sources.json
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/drm/KeySystemWidevine.js
This PR enables setting the audio/video robustness levels in protData, in order to avoid warning on chrome ("It is recommended that a robustness level be specified...")
An exemple of robustness level values is provided for sample stream "Axinom Test Content (conservative/legacy) / 1080p with PlayReady and Widevine DRM, single key"
> Robustness levels

- src/streaming/controllers/BufferController.js
When the last segment is buffered, BufferController sets isBufferingComplete. If there is a seek after that time, isBufferingComplete was being cleared and never set again. When the player is eventually allowed to play the end of the stream, it incorrectly triggers a BUFFER_EMPTY event.
> BufferController isBufferingComplete cleared on seeking

- src/streaming/controllers/StreamController.js
Issue #2129.
This PR generates a PLAYBACK_ENDED event from the StreamController when the video element fails to do so. StreamController was already working around this problem for multiple period content, this PR extends that workaround by passing the event to other (non-StreamController) event handlers.
> generate ended event artificially when player element fails to do so

- src/streaming/controllers/PlaybackController.js
Fixes https://github.com/Dash-Industry-Forum/dash.js/issues/2088
When you initialize the stream with a parsed manifest object instead of the URL of a MPD, `getStreamStartTime` in `PlaybackController` tries to get the parsed media fragments but it's undefined since the parsing is never done for a parsed manifest object, it's only parsed from the URL of an MPD.
Example manifest that is passed in as a string to the parser: https://gist.github.com/CaliAlec/4ae753844344aab7da98e2418b22a624
In order to parse the manifest string, I'm using internal classes:
```
const manifest = MANIFEST_STRING;
const parser = DashParser().create();
const xlink = XLinkController().create({});
const mpd = parser.parse(manifest, xlink);
```
> Fix undefined fragData when using parsed manifest object

- test/unit/streaming.controllers.XLinkController.js
Enough said, I think. It was causing tests to fail. Not sure how Travis was passing.
> fix typo in unit test

- src/dash/models/DashManifestModel.js
Using 4K stream (https://dash.akamaized.net/akamai/streamroot/050714/Spring_4Ktest.mpd)
In the manifest, period id value is "". Then the method DashAdapter::getAdaptationForMediaInfo returns null, because of the test (!mediaInfo.streamInfo.id).
This PR fixes the pb by checking length of id
> Fix a pb if realPeriodId is "".

- src/dash/parser/DashParser.js
- src/mss/parser/MssParser.js
- src/streaming/ManifestLoader.js
- src/streaming/controllers/XlinkController.js
Hi
This PR changes the way matchers and iron parameters are given to XLinkControllers, to uniformize API of parsers 
Jérémie
> XlinkController matchers set in ManifestLoader

- src/streaming/Stream.js
- src/streaming/StreamProcessor.js
- src/streaming/controllers/ScheduleController.js
Hi,
as explained in the issue #1928, the audio track switch is broken for segmentTimeLine dash manifest.  I think that it's unnecessary to destroy audio stream processor when an audio switch occurs. What dash.js player has to do is to restart scheduleController, load the new init segment and continue .... :-)
In order to this PR has to work properly, PR #2144 needs to be merged. I also would like to do more tests with dash streams with many audio tracks, if you have some.....thanks! ;-)
Nicolas
> Update audio track switch

- build/typings/index.d.ts
- src/streaming/MediaPlayer.js
- src/streaming/controllers/SourceBufferController.js
- src/streaming/models/VideoModel.js
- src/streaming/text/TextController.js
- src/streaming/text/TextSourceBuffer.js
- src/streaming/text/TextTracks.js
- src/streaming/vo/TextTrackInfo.js
- test/unit/mocks/VideoElementMock.js
- test/unit/mocks/VideoModelMock.js
- test/unit/streaming.text.TextController.js
Hi,
this PR has to fix the issue #2084 : the index of the subtitles track is a reference of textTrackInfo array. textTrack array of html5 video element has a different index.
In the same way, user can use the different subtitles with Firefox or Edge for instance. Indeed, before this PR, it was impossible to see subtitles in some specifc use cases (for instance, a first stream with one subtitles track, stop, load a second one, with two subtitles track).
Nicolas
> Update subtitles management

- src/streaming/rules/abr/SwitchHistoryRule.js
- test/unit/mocks/RulesContextMock.js
- test/unit/streaming.rules.abr.SwitchHistoryRule.js
Hi,
in issue #2178, a division by zero has been detected, that is why a SwitchHistoryRule unit test is added. I don't know exactly what is expected because in javascript a division by zero returns INFINITY, not really an error.
Nico
> add a SwitchHistoryRule  unit test

- package.json
Travis dit not launched any unit tests because the location of unit tests was not specified in the npm test script
> specify test folder for npm run test (makes Travis launch unit tests)

- src/dash/DashAdapter.js
- src/dash/models/DashManifestModel.js
- src/streaming/Stream.js
- src/streaming/utils/Capabilities.js
Hi,
as explained in issue #1643, only codec of the first representation is verified by dash.js. Unfortunately, the others codec are not tested. In this PR, when an unsupported codec is detected, the representation is deleted from the adaptation.
Nicolas
> Add  unsupported codecs detection

- .gitignore
- src/streaming/text/TextTracks.js
Fix for issue #2182. 
Due to the way the videoSizeCheck timer was created, we couldn't be 100% sure checkVideoSize was working with the selected text track. With these changes, timer is now started when the selected text track is html based and we are restarting it whenever a text track change is requested.
> Fixes in management of the video size check timer of TextTracks

- src/streaming/controllers/PlaybackController.js
Hi,
a second PR in order to bug fix #2192, start time past in parameter was not used. Stream started always at the beginning of a segment (audio or video).
Nicolas
> Bug fix about start time

- src/streaming/controllers/BufferController.js
There's a bug in Safari on macOS, where appending a segment to the start of a buffered range causes a portion of the original start of the buffer to be removed.
To reproduce this bug:
Seek to a point in the video, buffer for a few seconds.
Seek back 15-20 seconds, play the video forward to the first seek point.
The video stops for lack of buffer at the point first downloaded segment. Dash.js believes it has already downloaded this segment, so will fetch later ones instead.
This fixes it by watching the onSeeked event, and then removing any buffered ranges ahead of the currentTime(for macOS user agents only). There's no point just re-fetching and replacing the missing segment because the problem occurs again filling in that gap.
> Fix Safari backwards seek bug

- src/core/events/CoreEvents.js
- src/streaming/FragmentLoader.js
- src/streaming/XHRLoader.js
- src/streaming/controllers/AbrController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/models/FragmentModel.js
Hi,
this PR has to solve the issue #2186 by notifying the scheduleController when a request has been aborted.
Nico
> Abort management update

- src/streaming/protection/models/ProtectionModel_01b.js
Fix for reported issue #2149. Following specification, for Protection Model 01b, both Key and InitData parameters must be wrapped under Uint8Array.
> Fix #2149 - webkitAddKey argument mistmatch

- src/streaming/protection/controllers/ProtectionController.js
Hi
This PR ignores 'encrypted' event in case the key system has already been selected and pssh already processed.
This avoids to call requestKeySystemAccess each time an init segment is pushed in sourcebuffer (each time bitrate is changed)
This may lead to a crash of CDM.
This can be the cause of issue #2159
Jeremie
> [DRM] Ignore 'encrypted' event

- samples/dash-if-reference-player/app/rules/DownloadRatioRule.js
- src/dash/DashAdapter.js
- src/dash/controllers/RepresentationController.js
- src/streaming/controllers/MediaController.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/models/MetricsModel.js
- src/streaming/rules/RulesContext.js
- src/streaming/rules/abr/AbandonRequestsRule.js
- src/streaming/rules/abr/InsufficientBufferRule.js
- src/streaming/vo/RepresentationInfo.js
- src/streaming/vo/metrics/ManifestUpdate.js
Hello
The goal of this pull-request is to rename TrackInfo to RepresentationInfo. 
The name TrackInfo was not comprehensive and was confusing.
In RulesContext, the method getTrackInfo was returning the parameter representationInfo, which was initialized using config.streamProcessor.getCurrentRepresentationInfo(); 
getCurrentRepresentationInfo was creating an object of type TrackInfo.
It's a little bit confusing.
> Rename TrackInfo VO to RepresentationInfo VO 

- src/streaming/MediaPlayer.js
This intended change from #2016 was reverted as part of a refactor https://github.com/Dash-Industry-Forum/dash.js/pull/2007 (https://github.com/Dash-Industry-Forum/dash.js/commit/3abca12a1eeb0df89224d4676d6089b4e64d9485)
> Bring back change from #2016 (Don't set initialized flag to false in MediaPlayer.reset() )

- src/streaming/utils/DOMStorage.js
Don't trust the contents of local storage to be uncorrupted, assume parseInt can throw, parseFloat can throw, extend the try-catch around them.
> Safer DOMStorage.js

- src/core/FactoryMaker.js
- src/dash/models/DashManifestModel.js
- src/streaming/MediaPlayer.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/servers/PlayReady.js
- test/unit/dash.models.DashManifestModel.js
- test/unit/streaming.controllers.BufferControllerSpec.js
- test/unit/streaming.protection.servers.PlayReady.js
- Use MAX_SAFE_INTEGER in getDuration of MPD for live streams, as suggested by @devaublanc in PR #1678 (long time on hold because CLA was not accepted). @devaublanc, thanks for the change suggestion.
- Modify PlayReady test to get licenseServerData in beforeEach.
- Set OnSeekEnd listener in BufferController just for Safari on Mac. For other browser/OS combinations there is no need to listen for this event.
- Fix getBufferLength in MediaPlayer according to documentation. Buffer Length should be NaN when there are no tracks of valid media types.
- Some format changes of previously sent PRs
> Format and minor changes of recently merged PRs

- src/streaming/controllers/StreamController.js
- src/streaming/utils/URLUtils.js
- test/unit/streaming.utils.URLUtils.js
Ensure a fully resolved URL is used when deciding what the manifest scheme is. This failed when the supplied manifest URL was relative. `e.manifest.url` resolves fully at manifest load time.
See #1884 for discussion.
> Fix #1884 - correctly apply manifest scheme to default time server request

- samples/modules/webpack/package.json
Use latest version of dash.js 2.x.x package in current webpack module example.
> Use latest version of dash.js package in webpack example

- src/streaming/utils/TTMLParser.js
Fix #2202 
In Edge browser, whenever a TextTrackCue object has an startTime greater than its endTime, an exception is raised avoiding all the other parsed cues to be shown.
Note: Although this issue is raising an issue within captions provided by the user (external or fragmented using wrong startTime/endTime values), we need to make dash.js resilience against this kind of situations. So, this PR.
> Check startTime of cues is lower than endTime

- externals/xml2json.js
Following @bbcrddave suggestion, patch (from @Stealthfox) to resolve an XML parse error: syntax error in Firefox/Edge/IE for MPD files.
Important: I don't see any possible caveat but before merging we have to test this in as many browsers as possible. I have already tested it successfully in many different browsers/versions (local env + browserStack) but four eyes see more than two.
This fixes #1665
> Patch in xml2json to resolve xml syntax error in Firefox/IE/Edge

- contrib/akamai/controlbar/ControlBar.js
- contrib/akamai/controlbar/README.md
akamai/controlbar: support for multiple instances using a suffix to be set for existing controls in snippet, provided in initialize method. A better solution would autogenerate the snippet, but this is quick and backwards compatible.
Updated README.md.
Fixes #1890
> Control bar: allow multiple instances

- src/mss/MssFragmentInfoController.js
- src/mss/MssHandler.js
- src/streaming/StreamProcessor.js
Hi,
This PR fixes a pb with MSS Fragment Info management
- Each time stream was seeked, a new FramgentInfoController was created and registered in streamProcessor -> it leads to 412 errors because each FragmentInfoController asks next fragment in indexhandler to create the fragment info request. In this case, indexHandler will return request that are not yet available in server.
- Solution is to check that there is only one fragment info controller registered in stream processor.
Jérémie
> [MSS] Fix a problem with MSS Fragment Info integration

- src/streaming/controllers/ScheduleController.js
Hi,
this PR has to avoid to push initialize segment twice. In the beginning of the scheduleController, the attribute 'switchTrack' is set to true value. So, the scheduleController will request the init segment. At the second iteration, since lastInitQuality was not set, the initialization was pushed again.
Nico
> Bug fix on Init segment pushed twice, smooth content only

- src/dash/controllers/RepresentationController.js
- src/streaming/controllers/AbrController.js
- test/unit/helpers/ObjectsHelper.js
- test/unit/streaming.controllers.AbrControllerSpec.js
Issue #2034 
Value set on setMinAllowedBitrateFor was not being applied.
Created two new methods in ABRController (getMaxAllowedIndexFor, getMinAllowedIndexFor).
> Fix minimum bitrate setting (setMinAllowedBitrateFor)

- src/dash/DashAdapter.js
- src/streaming/rules/abr/AbandonRequestsRule.js
- test/unit/mocks/RulesContextMock.js
Fix #2245
Due to rename changes included in #1856, AbandonRequestRule stopped working. Reason behind this is AbandonRequestRule was checking for the existence of getTrackInfo method, that was removed in that PR. 
This PR is modifying AbandonRequestRule to check the right method name. I am also take advantage of this change to rename some function parameters that still were using trackInfo naming instead of RepresentationInfo.
> Fix AbandonRequestRule is not applied

- src/streaming/controllers/AbrController.js
- src/streaming/rules/abr/ABRRulesCollection.js
- src/streaming/rules/abr/AbandonRequestsRule.js
- src/streaming/rules/abr/BolaRule.js
- src/streaming/rules/abr/DroppedFramesRule.js
- src/streaming/rules/abr/InsufficientBufferRule.js
- src/streaming/rules/abr/SwitchHistoryRule.js
- src/streaming/rules/abr/ThroughputRule.js
- test/unit/mocks/DashMetricsMock.js
- test/unit/mocks/MetricsModelMock.js
- test/unit/mocks/RulesContextMock.js
- test/unit/streaming.rules.abr.AbandonRequestsRule.js
- test/unit/streaming.rules.abr.InsufficientBufferRule.js
- test/unit/streaming.rules.abr.ThroughputRule.js
In InsufficientBufferRule we are not checking if fragmentDuration is set. In live streams defined with SegmentTimeline and with short live delay time I have seen some cases in which fragmentDuration is NaN when evaluating this rule due to the fact that next segments list is empty. This makes the ABR algorithm to fluctuate a lot between the lowest bitrate and the right one according to Throughput/latency/buffer level values.
This PR avoid evaluating InsufficientBufferRule when there is no enough information to evaluate (it needs fragmentDuration). 
Alternatively we could not evaluate any rule when fragmentDuration is NaN (fragmentDuration is NaN when there are no segments and then, player won't request anything) but I preferred to patch just InsufficientBufferRule. Just thinking in cases …
> Check if fragmentDuration is defined in InsufficientBufferRule

- externals/base64.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/controllers/ProtectionKeyController.js
- src/streaming/protection/drm/KeySystem.js
- src/streaming/protection/drm/KeySystemClearKey.js
- src/streaming/protection/drm/KeySystemPlayReady.js
- src/streaming/protection/drm/KeySystemWidevine.js
- src/streaming/protection/models/ProtectionModel_3Feb2014.js
- test/unit/streaming.protection.drm.KeySystemPlayReady.js
This PR to add Playready custom data support which is needed for IE11 with ProtectionModel_3Feb2014
It takes some custom data from the protection data object and add it (after an appropriate transformation) inside the SOAP request for the Playready licenser server
It has been tested successfully with Orange Playready licenser server
A unit test is provided
> Playready custom data for IE 11

- Gruntfile.js
- package.json
Improve build process of grunt for developers to make a change in the source code and automatically load the browser.
I add a web server to serve statics and Browsersync to reload the browser. The server includes a middleware to add the code necessary for Browsersync in html files. 
To launch the live reloading of the browser, execute 'grunt dev'.
To launch only a web server, execute 'grunt serve'.
> Add reloading browser for development

- Gruntfile.js
Set [`compact`](https://babeljs.io/docs/usage/api/#options) option of babel to true explicitly to avoid the following warning message during compilation:
`[BABEL] Note: The code generator has deoptimised the styling of "D:/nginx/html/dash.js-2.0/src/streaming/MediaPlayer.js" as it exceeds the max of "100KB".`
Fix #2244
> [build] Set compact option to true explicitly

- src/streaming/controllers/ScheduleController.js
QUALITY_CHANGE_RENDERED must be fired when we change of audio track (even if there is only one quality) because they can have different bitrates. It was the case before 2.6.1
> Quality change rendered event fired

- src/dash/controllers/RepresentationController.js
- src/streaming/Stream.js
When we switch from an audio track with one representation to another track with 2 or more, currently we don't change of quality (stuck to quality 0) due to #2151 and the fact we do not recreate audio stream processor anymore.
This PR fixes this problem
> fix switch track audio with different number of representations

- src/streaming/metrics/controllers/MetricsController.js
- src/streaming/metrics/controllers/ReportingController.js
- src/streaming/metrics/reporting/ReportingFactory.js
https://github.com/Dash-Industry-Forum/dash.js/pull/2154 (specifically https://github.com/Dash-Industry-Forum/dash.js/commit/e6a1a4ffa6fd55f0f3e44bf74aaf3bed0c632c38) broke metric reporting because it did not pass MetricsConstants to all necessary modules - ReportingFactory and the modules it creates require this config.
I also changed some `let` to `const` whilst there.
> Fix MetricsReporting - pass correct config to ReportingFactory

- src/streaming/Stream.js
Hi,
the goal of this PR is to update management of multi period streams. 
First, when a switch stream occurs, streamProcessors array is destroyed. It's the reason why abrController don't have to keep references on those streamProcessors.
Then, after a stream switch, executedRequests array (in FragmentModel) was not cleaned. That's why if we seek back to the initial stream at an already played time, the getNextRequestTime returns a request at the time of the end of the last executed Request...not the wanted time. A test can be done with the stream https://dash.akamaized.net/dash264/TestCases/5a/1/manifest.mpd : play the initial stream (about 10 seconds), seek in the second stream (for instance at 4mn30s), and then after 5 seconds seek to the initial stream at 10 seconds. The stream plays …
> Update multi period management

- src/streaming/Stream.js
- src/streaming/controllers/MediaController.js
Hi,
this PR has to solve two issues related to multiperiod streams :
- create EventController only once.
- update function to test if a track has already been set in tracks array.
For this second point, when a user seeked in two different periods in a multiperiod streams, a new track was always added to tracks array.
Nico
> Multi period bug fix

- contrib/akamai/controlbar/ControlBar.js
- src/streaming/controllers/PlaybackController.js
Issue #2175 
This allows the player to update the playhead position.
akamai/controlbar: updates duration label on STREAM_INITIALIZED event, resets time/seekbar/play button on STREAM_TEARDOWN_COMPLETE event.
> PLAYBACK_TIME_UPDATED is now fired on paused live streams

- src/streaming/controllers/ScheduleController.js
- src/streaming/models/FragmentModel.js
- src/streaming/models/VideoModel.js
- src/streaming/text/TextController.js
- src/streaming/text/TextSourceBuffer.js
- src/streaming/text/TextTracks.js
Hi,
this PR has to solve issues about subtitles. 
- A subtitle track may have same kind, label and lang but a different format (vtt, ttml, etc...). We have to be able to distinguish both tracks.
- When text track switch occurs, all cues are deleted but executedRequests array was not cleaned. So, when the user seeked back, subtitles was not downloaded again.
Both issues can be reproduced with the stream https://media.axprod.net/TestVectors/v8-MultiContent/Clear/Manifest.mpd. The default text track didn't show due to first issue. Change text track selection and seek back in order to see second issue.
Nico
> Subtitles track with same lang bug

- samples/dash-if-reference-player/app/sources.json
- src/streaming/constants/Constants.js
- src/streaming/protection/CommonEncryption.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/controllers/ProtectionKeyController.js
- src/streaming/protection/drm/KeySystemClearKey.js
- src/streaming/protection/drm/KeySystemW3CClearKey.js
- src/streaming/protection/models/ProtectionModel_21Jan2015.js
- test/unit/streaming.protection.drm.KeySystemW3CClearKey.js
Hello!
I was experiencing the similar issues as in https://github.com/Dash-Industry-Forum/dash.js/issues/2249
After quite a bit of digging, I discovered that the ClearKey `ContentProtection` information in my manifest was being ignored since they did not have `pssh` entry. This is not the case with the Shaka player so I am submitting this as a fix. My understanding is that ClearKeys only need the key id specified and the actual key used should simply be provided to the player for use at the time of playback.
In the case of a ClearKey key system, I would still push that as a supported KeySystem. Since, at that time, I do not yet have the actual decryption key, I need to set `initData` to `null` so that I can properly set it later with my key. I'm not sure if this is the best way of doing …
> Basic ClearKey support

- src/streaming/MediaPlayer.js
- src/streaming/models/VideoModel.js
A playing event is fired by the media element if you pause then play on the element while stalled - . This PR watches for such a playing event, and if it fires while the player is still stalled, it fires the waiting event, so if watching the events, you still have the correct player state.
> Fire a waiting event if a playing event comes out while the stream is stalled

- .travis.yml
- Gruntfile.js
- package.json
Configures a continuous deployment process for development branch. Whenever changes are pushed to development branch, and only if build and test tasks were successful, resulting files are automatically deployed and can be tested using the url http://reference.dashif.org/dash.js/development/samples/dash-if-reference-player/index.html.
Deployment is done in development folder (instead of nightly one) to not interfere in current auto deployment process. Once this change is pushed and tested successfully for a few weeks, we will replace nightly build with this new process.
> Set up continuous deployment process for development branch

- src/streaming/text/TextTracks.js
Hi,
this PR has to solve issue #2302 by updating scaleCue function.
Nico
> update scaleCue function for TTML subtitles use case.

- build/typings/index.d.ts
- index.d.ts
- index.js
- samples/modules/README.md
- samples/modules/typescript/index.html
- samples/modules/typescript/package.json
- samples/modules/typescript/src/entry.ts
- samples/modules/typescript/webpack.config.js
- samples/modules/webpack/index.html
- samples/modules/webpack/package.json
- samples/modules/webpack/webpack.config.js
This PR Fixes the issue related with dash.js and Webpack integration (#2300).
It includes MediaPlayer in the main module export, apart from setting it as a property of the dashjs object as we did before.
This PR also fixes the declaration files, that were previously generating issues both in Babel and Typescript based projects. For testing purposes a new sample has been added that shows how to use dash.js in typescript based projects.
Note: Please, note both samples (webpack and typescript one) are fetching dash.js library from npm. This means this change can't be tested as usual until the new version is released and published in npm. In the meantime the way of testing this is retrieving all package.json dependencies as always (npm install) and then, replacing the content of dash.js …
> Webpack integration and JS declarations fixes

- src/streaming/MediaPlayer.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/models/FragmentModel.js
Hi
This PR solves problems in case of live playing with DVR.
If we seek to end, next fragments may be not available.
To avoid this, this PR adds use of liveDelay in getDVRSeekOffset function
Jérémie
> Seek and Live playing - take liveDelay into account

- package.json
Upgrade codem-isoboxer dep to use, specifically, its version 0.3.5
> Set a specific version for codem-isoboxer

- .travis.yml
- Gruntfile.js
- package.json
- test/functional/config/applications.js
- test/functional/config/selenium.js
Hi,
this PR suggests to use functional test page of #2242 PR to execute tests on a browserStack service. As previously, build process is executed on each branch with Travis. Functional tests are executed only on branch on which a travis cron job has been defined. Some informations have to be updated like :
- browserStack username
- browserStack accesskey
- deployed functional test page
Nico
> Functional tests with browserStack

- Gruntfile.js
Don't copy functional test tools when deploying development branch.
> Dont copy functional test tools when deploying

- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/controllers/ProtectionKeyController.js
- src/streaming/protection/drm/KeySystemClearKey.js
- src/streaming/protection/drm/KeySystemW3CClearKey.js
- src/streaming/protection/models/ProtectionModel.js
- src/streaming/protection/models/ProtectionModel_01b.js
- src/streaming/protection/models/ProtectionModel_21Jan2015.js
- src/streaming/protection/models/ProtectionModel_3Feb2014.js
ClearKey + License server worked before 2.6.4 and was broken after adding Basic ClearKey support (ClearKey support with keys passed as parameters instead of using a license server). This PR is recovering ClearKey + License server support while keeping the new Basic ClearKey functionality.
> Fix an issue when using ClearKey with license server

- src/dash/models/DashManifestModel.js
- src/streaming/Stream.js
Hi,
MSE isTypeSupported function manage a codec parameter with width and height values. This PR adds thoses values in order to fix a bug in firefox 57 with high resolutions #2323.
Nico
> Update the use of isTypeSupported function

- src/dash/models/DashManifestModel.js
- src/streaming/Stream.js
Fix an issue that appeared after merging #2328.
Although passing resolution (with/height) information to isTypeSupported method is fully valid, seems EME has some issues with that. Both Chrome and Firefox fails when selecting the keysystem if we use a MediaKeySystemMediaCapability whose contentType field includes width/height information. Following spec (https://www.w3.org/TR/encrypted-media/#bib-RFC6381, https://tools.ietf.org/html/rfc6381) I don't see any indication that says width or height parameters could be allowed parameters for contentType field.
This issue is making any stream using DRM not working.
> Fix issue with codec definition and EME

- src/dash/vo/Representation.js
Fix issue #2327. HasInitialization is true if range is defined and segmentInfoType is either BASE_URL or SEGMENT_BASE.
> Fix condition in hasInitialization

- src/streaming/controllers/PlaybackController.js
Fix for issue #2238. This fix avoids doing initial seeking operation, that takes into account buffer status, in cases in which the user did a seek operation while the stream was loading.
> Don't do initial seek if there is another seek running

- src/streaming/Stream.js
- src/streaming/StreamProcessor.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/controllers/StreamController.js
- src/streaming/models/FragmentModel.js
- src/streaming/rules/scheduling/NextFragmentRequestRule.js
Hi,
this PR has to fix the bug #2129. The problem was that scheduleController pushed initialize segment after the signalEndOfStream was called. 
Nicolas
> Bug fix on ended event not triggered

- externals/xml2json.js
- package.json
- test/unit/dash.DashParser.js
- test/unit/mss.parser.MssParser.js
- test/unit/streaming.controllers.XLinkController.js
- test/unit/streaming.protection.servers.PlayReady.js
Also added a test.
Requires jsdom as no other node xml parser I can find seems to follow the spec wrt `parsererror`. We could consider replacing xmldom used elsewhere to cut out a dev dependency.
> Fix #2355 - check for correct DOM error on XML parse failure

- src/streaming/controllers/PlaybackController.js
- src/streaming/controllers/StreamController.js
Hi,
since dash.js 2.6.0 version, the definition of start time, in uri parameters, for multi period streams may not be taken into account. This could happen if the desired time is not in first period range.
In order to fix it, this PR adds, in composeStreams function, the selection of period based on uri parameters. If no period is found, the first one is selected which is the previous behavior.
Nico
> Multiperiod with uri start time bug fix

- .travis.yml
- package.json
These changes reduce build time from 3-4 minutes to around 2 minutes. Changes:
* Setup cache for node_modules folder to speed up build times in Travis and so our CI process
* Don't build on prepublish npm task. That implies Travis building two times the project per request (one after npm install, the other one to prepare the deployment). Furthermore, for local environment, I don't see any reason for building the project during npm install.
> Speed up build time in Travis

- build/typings/index.d.ts
- index.d.ts
- src/streaming/MediaPlayer.js
- src/streaming/models/MediaPlayerModel.js
- src/streaming/rules/ThroughputHistory.js
- test/unit/mocks/MediaPlayerModelMock.js
- test/unit/streaming.MediaPlayerSpec.js
See discussion in #1992.
Allow the user to define its own thresholds for the cache detection mechanism. This threshold is used by the ABR algorithm to detect when the response to a request is coming from browser cache. 
After lot of empirical tests trying to find optimum values for cache load thresholds, I didn't find ones that behave better than the ones currently defined (they highly depends on the bitrate of the video/audio and the cpu/gpu of the device). So, this PR is keeping default values as they are and is adding a new method to MediaPlayer (`setCacheLoadThresholdForType`) that allows to change them.
> Make cache thresholds customizable

- src/streaming/vo/TextRequest.js
Hi,
this PR has to solve an issue in Firefox with MSS streams (for instance : http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest). ResponseType of XMLHttpRequest was set to 'text' value, the responses body was not well encoded. The use of default responseType solve this issue.
Nico
> set default value to responseType of XMLHttpRequest.

- samples/dash-if-reference-player/app/sources.json
- src/streaming/MediaPlayer.js
This PR fixes #2359 and then enable Thumbnails support for live streams. 
@TobbeEdgeware, for your information, I have added the live stream with thumbnails stream that you created to the Dash reference player list of sample streams. Thanks to it I was able to detect the issue. Thanks!
> Fix issue with live stream thumbnails

- samples/dash-if-reference-player/app/sources.json
This sample was provided by the CTA and contains an aggressive exercising of many features of the IMSC1 standard. Uses IMSC1 Text contained in a sidecar .ttml file.
> Adding new IMSC1 sample to reference player

- src/dash/controllers/RepresentationController.js
- src/streaming/MediaPlayerEvents.js
- src/streaming/controllers/EventController.js
- src/streaming/controllers/StreamController.js
- test/unit/streaming.controllers.EventController.js
Implements the event duration portion of the spec for emsg MPD Validity Expiration events, so the event duration field can be used to set the remaining duration of a live stream. It also allows a stream to be ended at the event time when presentation_time_delta and event_duration are 0.
It **does not** implement the checking of the message_data field or the presentation_time_delta field to verify that the reloaded manifest has the correct validity
> Implement duration change for MPD Validity Expiration events

- src/mss/MssHandler.js
- src/streaming/Stream.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/StreamController.js
- test/unit/streaming.controllers.StreamController.js
Hi,
this PR has to solve an issue with multi period stream. For instance, the user is watching the first period of a VOD stream. The end of period stream buffering is detected, but the user decide to do a pause. Before this PR, the timer in StreamController which had to send PLAYBACK_ENDED event was not stopped.
I still have some questions about the same behavior with a Live stream : what is the player expected to do?
Nico
> Multiperiod pause and end detection bug fix

- samples/dash-if-reference-player/app/css/main.css
- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/index.html
Fix #2379 
Show a dialog when there is an error on the player instead of only logging on console. As errors are not unified it tries to guess the best string to show. When #2179 is fixed, it can show a more user friendly error.
> Show dialog when there is an error on the player

- src/streaming/MediaPlayer.js
Code clean up. Remove methods that were deprecated on 2.6.2 or below. 
As a procedure, I propose to remove methods that were deprecated 3 versions behind the stable one. Otherwise we will be accumulating a lot of "useless" code that we still need to maintain.
> Remove methods deprecated three versions behind stable one

- src/streaming/controllers/PlaybackController.js
- src/streaming/vo/URIFragmentData.js
This PR adds a new parameter 'r' to specify relative start time of a live stream as specified in #2330. This parameter has a value between 0 and the DVR window size in seconds.
Also, it fixes a problem when the live stream play time was at the beginning of the DVR window, as it starting seeking from time to time. This was due to currentTime of the player is updated at the 'timeupdate' event. This event can take up 250ms to be fired. Therefore, when checking if the currentTime is behind the DVR window size, the delayed of the event is taken into account.
> #2330 Add 'r' parameter to specify relative start time in a live stream

- src/streaming/controllers/BufferController.js
- src/streaming/rules/scheduling/NextFragmentRequestRule.js
Fixes #2239 and enables fast switch of tracks. Whenever a request for track change is received, and if track switching mode is set to TRACK_SWITCH_MODE_ALWAYS_REPLACE, BufferController will remove its buffer completely so track change is effective immediately.
> Fast Audio track switching

- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/index.html
Hi,
this PR has to show track switch mode for audio and video, not only for video as it is now. By default, track switch mode is neverReplace for video and alwaysReplace for audio.
Nico
> update track switch mode for audio and video

- contrib/akamai/controlbar/ControlBar.js
- contrib/akamai/controlbar/controlbar.css
- contrib/akamai/controlbar/snippet.html
- samples/chromecast/receiver/js/main.js
- samples/dash-if-reference-player/index.html
This PR adds a new bar to the progress control that shows the current buffer level. By default it shows video buffer level. In case there is no video track, it shows audio buffer level.
> Add buffer level bar to control bar

- src/streaming/controllers/BufferController.js
- src/streaming/controllers/SourceBufferController.js
Fix #2415.
In some situations, like when there are track changes, we have to allow the buffer to be removed even when it has reached the end of the stream. This PR adds the possibility of indicating to SourceBufferController that a buffer must be removed, independently of the playback context, and use it to force removal of buffers when there are track switches.
> Allow buffer removal when MediaSource is ended

- src/streaming/controllers/ScheduleController.js
Hi,
when a seek command occurs, dash.js has to download as quick as possible datas at the new specific time. In the log message, just below, we can see that between the seek command and the call to the new video segment for the time 544.31, some video datas have been appended. Those datas are timestamped at the time before the seek.
````
[125688] Seeking to: 544.31 <= A seek command occurs
[125689] Waiting for more buffer before starting playback for video 
[125689] Waiting for more buffer before starting playback for audio 
[125693] AbrController (audio) stay on 0/0 (buffer: 0) 
[125693] ScheduleController - audio - getNextFragment 
[125693] Getting the request for audio time : 544.31 
[125694] Index for audio time 544.31 is 135 
[125694] SegmentTemplate: 541.44 / 634.566 
[125694] …
```
> Improve seek velocity

- contrib/akamai/controlbar/controlbar.css
- samples/dash-if-reference-player/app/css/main.css
This PR fixes a couple of css issues of our Reference Player:
*  In Chrome, while staying in fullscreen mode, as soon as control bar is hidden the layout of the player  gets broken (screen gets white and player is moved out of the display area). I have checked this is happening at least since dash.js v2.4.0.
* In Edge/IE, the new control bar is not rendered correctly. Background of the progress bar is never drawn.
> Fix css issues in controlbar and reference player

- index.d.ts
- samples/dash-if-reference-player/app/css/main.css
- samples/dash-if-reference-player/app/main.js
- samples/dash-if-reference-player/index.html
- src/streaming/MediaPlayer.js
- src/streaming/controllers/StreamController.js
- src/streaming/models/MediaPlayerModel.js
- test/unit/mocks/MediaPlayerModelMock.js
- test/unit/streaming.MediaPlayerSpec.js
Enable dash.js to jump over small time gaps in the stream. A gap is defined as small when it is shorter or equal to the limit defined with the `MediaPlayer` method `setSmallGapLimit`. By default, `smallGapLimit` value is set to 0.8.
By default jump gap feature is disabled. If you want to enable it you must use the `MediaPlayer` method `setJumpGaps`. 
This PR also adds a new UI control to Dash Reference Player that allows the user to enable/disable jump gap feature with the UI. By default jump gaps feature is enabled for the Dash Reference Player.
Note: Some of the work done here is based on a PR previously sent by @Weiren1991 (#2102). There were some things to fix there and some conflicts to resolve, so I preferred to sent a new PR and keep everything as cleaner as possible. Anyway, …
> Jump gaps feature

- src/streaming/controllers/BufferController.js
This PR fixes an issue reported by @nicosang. There were playback stall issues while clearing completely the buffer (because an audio track switch, for example) when playback was very close to the end of the stream.
> Don't clear buffer when we are close to the end of stream

- src/dash/vo/Representation.js
Fix #2425, coming from a regression introduced in #2336. hasInitialization must return true whenever an initialization url or an initialization range is defined, no matter what is the value of segmentInfoType. 
This was also wrong in 2.6.4 and before (always returned true) although didn't make fail the stream in #2425.
> hasInitialization must return true if there is an initialization range

- build/typings/index.d.ts
- index.d.ts
- samples/protection/getLicense.html
- src/streaming/MediaPlayer.js
- src/streaming/protection/Protection.js
- src/streaming/protection/ProtectionEvents.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/models/ProtectionModel_21Jan2015.js
This PR enables using protection controller in order to deal with licenses without attaching a video element to the player.
This can be useful to obtain a license without playing a stream.
As to anticipate persistent license support in chrome, an example use case is to retrieve and store licensein CDM when recording a stream in order to enable playback afterwards while being disconnected from network.
A sample is provided to demonstrate license acquisition using ProtectionController.
Additionnaly, we could eventually add an API in MediaPlayer or ProtectionController to get a license as it is done in the sample.
> Use protection module without video element

- src/streaming/Stream.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/utils/ErrorHandler.js
Fix #2326
For ClearKey KeySystem, whenever the user provides ClearKey parameters we should use them instead of the ones that comes with the "encrypted" event.
> Overwrite initData when user provided parameters for generating it

- src/streaming/StreamProcessor.js
- src/streaming/controllers/BufferController.js
- src/streaming/controllers/ScheduleController.js
- src/streaming/models/FragmentModel.js
- src/streaming/rules/scheduling/NextFragmentRequestRule.js
Hi,
this PR has to improve fast audio switch. The main idea is that when an audio switch occurs, the stream has not to stop playing. In order to achieve this goal, those steps are executed :
- push the new initialize segment
- request media segment at the current playing time of stream
- when this new media segment has been downloaded, fully clean audio buffer and push this new media segment
A test can be done with the stream : http://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd
Nico
> Improve audio switch

- src/mss/MssFragmentInfoController.js
- src/mss/MssFragmentMoofProcessor.js
- src/streaming/controllers/MediaSourceController.js
Hi,
this PR has to avoid 412 precondition failed error. This type of error can occur when player wants to request not already available segment. Each time that tfrf box is processed, dash.js player will only add first segment of the two entries of this box. This part of the code is used to know timestamp of the next segment, for live stream use case,  without reloading smooth manifest. Thus, request scheduler is better adjust. 
Nico
> [MSS] Update fragment info management

- src/streaming/protection/Protection.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/models/ProtectionModel_21Jan2015.js
Hi,
this PR has to return a DRM error when key system access is not available due to an [insecure origin](https://www.chromestatus.com/feature/5724389932793856). So, dash.js can't use requestMediaKeySystemAccess function to detect EME version, but has to return a explicit error in this use case.
In order to validate this PR, dash-if reference page has to be opened in chrome (use ip address not localhost) and try to play a widevine protected content.
Nico
> Add DRM error for insecure origin

- index.d.ts
- src/streaming/MediaPlayerEvents.js
- src/streaming/controllers/ScheduleController.js
This follows the already established method for identifying when a quality change has been rendered to allow us to dispatch an event when a track change has been rendered.  This is helpful when switching audio or video tracks for UI feedback.
> Add an event when a track change has rendered.

- package.json
- src/streaming/utils/ObjectUtils.js
Use https://github.com/epoberezkin/fast-deep-equal for better performance in object comparison.
> Use fast-deep-equal

- index.d.ts
- src/streaming/MediaPlayerEvents.js
- src/streaming/utils/TTMLParser.js
This PR provides a new TTML_PARSED event emitted every time a TTML (XML) string has been parsed to get a JavaScript object representing the TTML document.
TTML_PARSED events have the following structure:
```
{
type: "ttmlParsed", // dashjs.MediaPlayer.events.TTML_PARSED
ttmlString: string,
ttmlDoc: Object
}
```
* The `ttmlString` property is the content of the downloaded TTML segment as string.
* The `ttmlDoc` property is the result of the `ttmlString` parsing. This a JavaScript object.
TTML_EVENT offers the opportunity to change the content of captions or the value of TTML properties before they are processed for screen rendering. This is useful to fix invalid or unadapted values.
> New TTML_PARSED event

- samples/dash-if-reference-player/app/sources.json
- samples/protection/getLicense.html
- src/streaming/MediaPlayer.js
- src/streaming/Stream.js
- src/streaming/protection/Protection.js
- src/streaming/protection/controllers/ProtectionController.js
- src/streaming/protection/models/ProtectionModel_21Jan2015.js
This PR adds support for MultiKey DRM (Fix #1595). Tested sucessfully with Clear Key, Widevine and PlayReady.
When initializing a stream, Stream class uses ProtectionController to initialize all possible adaptations of the current period. Later on, in the session creation process and once each keysystem is selected and initData available, we will create just the sessions with unique combinations of initData/keysystem.
> Add support for MultiKey DRM
