README.md
This fix allows avoiding grunt build failure.
=> Fixing grunt build failure

contrib/videojs/example.html, contrib/webmjs/example.html
Fix #343 by putting new paths in HTML.
=> Fix issue #343 - fix JS paths in contrib HTML

app/js/streaming/protection/eme/ProtectionModel_01b.js
Queue up pending sessions until we receive the associated key
message
When multiple keys are requested initially, the createKeySession
calls in before the first keymessage is generated.  This means that
we can't detect whether or not multiple key sessions are supported
until after multiple key sessions have already been created.  This
is something that we can't avoid with this early EME API version.
The outcome is that if you try to play encrypted content that uses
more than one key on a user agent that implements the 01b API and
DOES NOT support sessionIDs, you will get unpredictable results.
At this point, I do not know of any browsers that will cause this
error, so I just log an error message
=> Fix EME 01b multi-session bug

Gruntfile.js, samples/basic-page-embed/auto-load-multi-video.html, samples/basic-page-embed/auto-load-single-video-with-context-and-source.html, samples/basic-page-embed/auto-load-single-video-with-reference.html, samples/basic-page-embed/auto-load-single-video.html, samples/basic-page-embed/manual-load-single-video.html
updated grunt dash.min to not include the 3rd party libs.  
changed paths in samples to debug.js
=> updated grunt dash.min to not include the 3rd party libs.  

src/streaming/controllers/PlaybackController.js
fixes #357 "Possible bug in PlaybackController"
=> fixes #357 "Possible bug in PlaybackController"

src/streaming/protection/drm/KeySystem_PlayReady.js
=> Updates for DRM

src/dash/DashAdapter.js, src/dash/DashCreate.js, src/dash/DashHandler.js, src/dash/TimelineConverter.js, src/dash/extensions/BaseURLExtensions.js, src/dash/extensions/DashManifestExtensions.js, src/dash/extensions/DashMetricsExtensions.js, src/dash/vo/Event.js, src/streaming/FragmentLoader.js, src/streaming/ManifestLoader.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/VTTParser.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/EventController.js, src/streaming/controllers/FragmentController.js, src/streaming/controllers/ProtectionController.js, src/streaming/extensions/SourceBufferExtensions.js, src/streaming/models/ProtectionModel_01b.js, src/streaming/models/URIQueryAndFragmentModel.js, src/streaming/protection/CommonEncryption.js, src/streaming/protection/drm/KeySystem.js, src/streaming/protection/drm/KeySystem_ClearKey.js, src/streaming/protection/drm/KeySystem_PlayReady.js, src/streaming/utils/Debug.js
Removes code duplicates, unused variables, redundant var initializations, spelling errors, jsdoc errors etc.
=> Code cleanup

src/streaming/TextSourceBuffer.js, src/streaming/VTTParser.js, src/streaming/extensions/TextTrackExtensions.js
Fix for vtt issue 331, 328, 123 + support for multi-sublines and basic styles.
Regarding Issue 123, all caption start and end times are valid now and styles are captured and applied to captions.
=> WebVTT bug fixes and enhancements 

README.md
Updated build and quick start of readme.md
=> Fix for issue #417

src/streaming/rules/ABRRules/ThroughputRule.js
=> fixes "Uncaught TypeError: Cannot read property 'bandwidth' of undefined"

src/streaming/Stream.js, src/streaming/controllers/FragmentController.js, src/streaming/models/FragmentModel.js, src/streaming/rules/SchedulingRules/SameTimeRequestRule.js
=> fixes playback freezing at the end of the stream

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/app/sources.json
Also added entries to the sources list for CableLabs CommonEncryption content.
=> Set protection data from sources.json

src/streaming/models/ProtectionModel_21Jan2015.js
when we iterate in key systems, the context was lost.
=> fix context problem

src/streaming/controllers/ProtectionController.js, src/streaming/extensions/ProtectionExtensions.js
- don't use 'this.debug' but this.log
- a manifest could be not protected
=> Content protection small bugs

src/streaming/extensions/ProtectionExtensions.js
No functional changes, just moved code to the prototype and moved private members to public.
=> Extension methods should be in the prototype

samples/dash-if-reference-player/app/sources.json
=> updates sources.json

AUTHORS.md, src/dash/controllers/RepresentationController.js, src/dash/extensions/DashMetricsExtensions.js
=> Authors file

src/dash/DashHandler.js, src/dash/controllers/RepresentationController.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/TTMLParser.js, src/streaming/controllers/StreamController.js, src/streaming/extensions/MediaSourceExtensions.js
Summary of changes - 
DashHandler.js - Check for missing duration with SegmentTemplate that should default to using the period duration per spec.
RepresentationController.js - Fix for byte range with mulitple Representations.
StreamController.js - Add additional listeners for playback.
TTMLParser.js - Profile tag is not mandatory.
StreamProcessor.js - Checking for the processor type instead of id allowing other adaptations of the same type to be set as mediaInfo.
=> Some fixes from Adobe

src/streaming/controllers/BufferController.js
=> Fixes notifications of bytesAppended event of BufferController

src/dash/extensions/DashManifestExtensions.js, src/dash/vo/Representation.js, src/streaming/VTTParser.js, src/streaming/models/FragmentModel.js
1) Expose maxPlayOutRate in Representation Object for trick play
2) Fixes and improvements in VttParser - making styling attributes as Int and sanity checks on Vtt cues as per the spec
3) Bug fix in abortRequests in FragmentModel
=> Some fixes and improvements from Adobe

src/streaming/controllers/EventController.js
Changed collections of events to be objects instead of arrays, since the eventID is used as index, and can take very big values.
The logging now prints out the eventId, and repeated events (id already added) are logged, but not added as before.
Added white space where missing.
=> Fixed bug reported as issue #561.

src/streaming/MediaPlayer.js
Updated some API docs and made doc entries more consistent with types declaration and return values.
=> Adding jsdoc updates to MediaPlayer API.

src/streaming/extensions/SourceBufferExtensions.js
Remove operation fails if buffer is in appending/updating state
=> Fixing error in buffer remove

src/streaming/Stream.js, src/streaming/controllers/ProtectionController.js
=> fixes multi-period live streaming

src/dash/extensions/DashManifestExtensions.js, src/streaming/Stream.js
=> Provides a meaningful error for multiplexed mpd's

src/streaming/controllers/AbrController.js
Do not allow abandonment logic to run if auto switch mode is false.
=> Fix for issue #609.

src/streaming/utils/DOMStorage.js
Thanks to @blacktrash for catching this.
=> Fixes a possible SecurityError if Storage access is denied

src/streaming/controllers/StreamController.js
=> Check MediaError target.error is not null

src/streaming/XlinkLoader.js
Fix a bug to play the default content when an element can not be resolved
=> Fix Xlink bug to resolve default period on 404error

samples/captioning/multi-track-captions.html, src/streaming/TextSourceBuffer.js, src/streaming/extensions/TextTrackExtensions.js, src/streaming/rules/SchedulingRules/PlaybackTimeRule.js, src/streaming/rules/SchedulingRules/SameTimeRequestRule.js
Fixes stalls when sametimerule does not find fragmented text for time.
Does not create and schedule fragments if all tracks are turned off
Fixes sorting issue with track menu
=> bugfixes multi track

samples/ad-insertion/adinsertion_inband.html, samples/ad-insertion/adinsertion_inline.html
Fix for the ad-insertion sample sites
=> Changed ad insertion sample sites

samples/captioning/multi-track-captions.html, src/lib/objectiron.js, src/lib/xml2json.js, src/streaming/MediaPlayer.js, src/streaming/TTMLParser.js, src/streaming/TextSourceBuffer.js, src/streaming/extensions/TextTrackExtensions.js, src/streaming/models/VideoModel.js
A full-styled HTML-based rendering of EBU-TT-D and other TTML subtitles.
The reason for a separate rendering mechanism is that TextTrackCue/VTTCue have very rudimentary styling support.
The rendering has been developed by Solène Buet at EBU and should be a complete EBU-TT-D rendering.
Torbjörn Einarsson and Kenth Andersson from MobiTV have worked with Solène to integrate the HTML rendering in the TextTrackCue/VTTCue timing framework, so that such a track will behave like any other track. The focus has been on EBU-TT-D, but most other TTML subtitle sources should work as well. A list of the supported TTML features in EBU-TT-D are described in Appendix A of the EBU-TT.D spec:https://tech.ebu.ch/docs/tech/tech3380.pdf
To turn on the rendering, the MediaPlayer must be given a \<div\> object …
=> New Feature: HTML-rendered-TTML

src/streaming/TTMLParser.js, src/streaming/TextSourceBuffer.js, src/streaming/controllers/BufferController.js, src/streaming/extensions/TextTrackExtensions.js
Fixes the stall issue when switching tracks and .start error when tracks are disabled entirely.
=> Bugfix for multi text track

samples/dash-if-reference-player/app/main.js
compare code review comment: https://github.com/Dash-Industry-Forum/dash.js/commit/7776bdb5bcdf6b5fb5c8fc7e80049a169d5a89bc
=> workaround for fixing out of range buffered ranges errors

src/dash/DashHandler.js, src/streaming/Stream.js
=> Bugfixing (Fixes live streaming with multiple periods, fixes possible stall at the end of the stream) 

contrib/akamai/controlbar/ControlBar.js, src/streaming/TextSourceBuffer.js
Fix issue with NaN timecode for MultiPeriod.
Fix CCMenu position between fullscreen
Fix positionMenu RTE
Adds feature to hide/show controls in fullscreen 4 seconds after mouse is still. 
Fixes spec deviation in MPD for tracks that are using role for main instead of caption type.
=> Control Bar BugFixes

src/dash/DashHandler.js, src/streaming/controllers/BufferController.js, src/streaming/models/FragmentModel.js, src/streaming/rules/SchedulingRules/SameTimeRequestRule.js
Contains fixes that prevents live playback stalls
=> Bugfixing (live streaming)

src/streaming/controllers/StreamController.js
=> Fixes a possible null reference error for streams with multiplexed content

src/streaming/controllers/PlaybackController.js, src/streaming/rules/SchedulingRules/SameTimeRequestRule.js
=> Fixes calculations of currentTime in SameTimeRequestRule

src/streaming/extensions/TextTrackExtensions.js
This fix resizes the TTML caption div to match the video size inside the video element, to do this we assume that the video element scales the video to fit, while keeping aspect ratio and at the same time keeps the video centered.
=> Fixed so that the TTML rendering view is resized to match the video

src/streaming/controllers/PlaybackController.js
=> Fixes seeking

src/streaming/TTMLParser.js
Added support for xml:space on top-level tt-tag in TTML files.
=> Added xml:space support for preserving white-spaces

contrib/akamai/controlbar/README.md, contrib/akamai/controlbar/controlbar.css, samples/captioning/multi-track-captions.html, samples/captioning/ttml-ebutt-sample.html, samples/dash-if-reference-player/app/css/main.css, samples/dash-if-reference-player/eme.html, samples/dash-if-reference-player/index.html, src/streaming/controllers/StreamController.js, src/streaming/models/URIQueryAndFragmentModel.js
Plus added control bar to caption samples and fixed some style issue when using control bar in raw application with no other normalizing css.
=> Fix for Issue #777 and Issue #763

src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js
make WALLCLOCK_TIME_UPDATE_INTERVAL configurable and adjust buffer pruning logic with this value
=> adjust buffer pruning interval

src/streaming/MediaPlayer.js, src/streaming/controllers/BufferController.js, src/streaming/extensions/MediaSourceExtensions.js
This contains a couple of minor fixups for issues we found while testing the current 1.5.2 branch.
=> [1.5.2] Buffer and metric fixes

src/streaming/FragmentLoader.js, src/streaming/ManifestLoader.js
=> [1.5.2] Fix #913

src/streaming/extensions/TextTrackExtensions.js
=> Don't resize text size if text track is not in mode showing. Fixes #918.

src/streaming/TextSourceBuffer.js
=> Added missing remove function to TextSourceBuffer.

src/streaming/MediaPlayer.js, src/streaming/controllers/AbrController.js
Mostly taken straight from 1.6.0, with a couple of extra checks.
In future we might want to look at refactoring into something like a set of "hard limit" abr rules instead of multiple checkFoo(...)
=> Add back representation ratio, portal restriction and individual ABR toggling APIs

src/dash/DashHandler.js
This is small performance improvement that was added in 1.6.0 (https://github.com/bbc/dash.js/commit/35bb5ee603341fbf7b4818c511a29d08ca9f13a2)
=> Optimise for sequential segments

Gruntfile.js, src/streaming/FragmentLoader.js, src/streaming/MediaPlayer.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/models/MediaPlayerModel.js, src/streaming/rules/abr/AbandonRequestsRule.js, src/streaming/rules/abr/BufferOccupancyRule.js, src/streaming/rules/abr/ThroughputRule.js, src/streaming/rules/scheduling/BufferLevelRule.js
Added API layer to media player to set and configure buffer and abr values.
=> Fix for #947 and #1028

src/streaming/controllers/PlaybackController.js
As discussed on the call, I'm PRing the code in 1.6 that was used to address issue #998.
=> Potential fix for #998

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js
Also fixed another RTE at startup for streams with DVRwindow info that may not be present right at startup in the currentRepresentationInfo.
=> Fix for #984

src/streaming/FragmentLoader.js, src/streaming/MediaPlayer.js, src/streaming/models/MediaPlayerModel.js
we need these 2 values configurable in order to achieve automatic playback recovery in case of lost internet connection.
I will make a follow up PR for documenting all these configurable params in JSDOC
=> make FragmentRetryAttempts + FragmentRetryInterval configurable

src/streaming/controllers/StreamController.js
Implements Dash-Industry-Forum/dash.js#1059
=> Will now report MediaError.msExtendedCode in log messages when available

test/dash.TimeLineConverterSpec.js, test/streaming.FragmentModelSpec.js
=> Fixes #1014

samples/dash-if-reference-player/app/sources.json
More info about the videos: https://github.com/Axinom/dash-test-vectors
These will also be included into the DASH-IF test vectors set in the near future.
=> Added Axinom test vectors

Gruntfile.js, samples/ad-insertion/adinsertion_inband.html, samples/ad-insertion/adinsertion_inline.html, samples/ad-insertion/xlink.html, samples/captioning/caption_vtt.html, samples/captioning/multi-track-captions.html, samples/captioning/ttml-ebutt-sample.html, samples/chromecast/index.html, samples/dash-if-reference-player/eme.html, samples/dash-if-reference-player/index.html, samples/getting-started-basic-embed/auto-load-multi-video.html, samples/getting-started-basic-embed/auto-load-single-video-src.html, samples/getting-started-basic-embed/auto-load-single-video-with-context-and-source.html, samples/getting-started-basic-embed/auto-load-single-video-with-reference.html, samples/getting-started-basic-embed/auto-load-single-video.html, samples/getting-started-basic-embed/manual-load-single-video.html, samples/live-streaming/live-delay-comparison.html, test/helpers/DashUtil.html
This fixes the remaining issues from #1057
@AkamaiDASH take a look if you want and land it if you'd like. If I don't hear anything by this afternoon / evening when I get out of jury duty I'll land this.
=> Fixes for dash.all.debug.js

Gruntfile.js
Still need to add watch copy task on changes in build.
=> Fixes debug task and makes watch task create all.debug. 

src/dash/DashHandler.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js
Chrome does not init play firefox works well. In chrome you need to press the play button even if autoPlay is set to true on MediaPlayer.  I am going to close this issue and create a new one with just to focus on startup.   Segment
=> Fix for issue #1045. 

src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js
Changed fix for #1018 but maintained code in different place. Fix still works for #1018
=> Fix for #1027 and fix #1072 for tested with auto-load-multi-video.html

src/streaming/extensions/TextTrackExtensions.js
Cleaned up user agent logic a bit and tested on Edge Ie11 firefox and chrome.  Text tracks are all working as expected. Cleaning up and reloading as expected.
=> Fix for #1040

README.md
=> Adding browserstack logo to README.

README.md
@wilaw you want to review this for accuracy?
=> Describe the MediaPlayerFactory setup steps.

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html
Adds an ability to turn on/off  the new BOLA adaption logic. Also fixes alignment issue with "Cache media settings" which is renamed to "Save settings".
=> Adding BOLA UI element to reference player

src/core/FactoryMaker.js, src/dash/DashMetrics.js, src/streaming/MediaPlayer.js, src/streaming/MediaPlayerEvents.js
Adds JSDocs to new API.   At min a doc stub has been added to present in jsdoc output.
=> Fix for #1001

src/streaming/MediaPlayer.js
jsdoc for buffer pruning values + some minor doc changes
=> jsdoc MediaPlayer API buffer pruning

src/dash/DashAdapter.js, src/streaming/TextSourceBuffer.js
=> Fixed broken import of cea608parser and a namechange of segmentType

src/dash/DashAdapter.js, src/dash/DashHandler.js, src/dash/DashMetrics.js, src/dash/utils/FragmentedTextBoxParser.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/TextSourceBuffer.js, src/streaming/VirtualBuffer.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/EventController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/SourceBufferController.js, src/streaming/controllers/StreamController.js, src/streaming/controllers/TimeSyncController.js, src/streaming/controllers/XlinkController.js, src/streaming/metrics/controllers/MetricsHandlersController.js, src/streaming/protection/CommonEncryption.js, src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/rules/abr/BolaAbandonRule.js, src/streaming/rules/abr/BolaRule.js, src/streaming/rules/synchronization/LiveEdgeBinarySearchRule.js, src/streaming/rules/synchronization/LiveEdgeWithTimeSynchronizationRule.js, src/streaming/utils/TTMLParser.js, src/streaming/utils/VTTParser.js, src/streaming/vo/metrics/HTTPRequest.js
=> Typos in comments, local variables and CSS

README.md, docs/migration/Migration-2.0.md, samples/dash-if-reference-player/app/notes.json, samples/dash-if-reference-player/app/player_libraries.json, src/streaming/MediaPlayer.js
Added migration doc
updated release notes in player
changed one media player doc line
=> Update to readme.md

src/dash/models/DashManifestModel.js, src/streaming/Stream.js, src/streaming/TextSourceBuffer.js, src/streaming/controllers/MediaController.js, src/streaming/controllers/SourceBufferController.js
Basic support for WebVTT text as a stream of MP4 segments based on request #992.
Tested with the sequence http://media.axprod.net/TestVectors/v6-Clear/Manifest_1080p.mpd 
Also made a cleanup of the code for initialMedia setup.
=> Implemented basic segmented WebVTT support.

src/dash/DashHandler.js
Make sure we use do not keep IDX on handler for dynamic segtimline streams but all other cases use the previous logic.
=> Fix for issue #1185

src/streaming/rules/abr/BolaRule.js
Fix some startup oscillations, fix issue that incorrectly throttled buffer growth at lower bitrates, use smoother estimation of recent throughput (used to avoid oscillations), fix detection of last download completion time.
=> BOLA updates

src/core/events/CoreEvents.js, src/dash/DashAdapter.js, src/streaming/ManifestUpdater.js, src/streaming/Stream.js, src/streaming/controllers/StreamController.js
Also some minor code refactors.
=> Fix for issue #1187 and partial fix for issue #1033

src/streaming/controllers/ScheduleController.js
Call stop on stream complete to stop validate.  also clean up validate as there were some left over calls that were hacks; since resolved.
=> Fix for issue #1203

test/helpers/VOHelper.js, test/streaming.AbrControllerSpec.js
Correct DummyMediaInfo object and remove duplicated condition check in
AbrController test case in previous PR #1221
=> Fix AbrController test

src/streaming/TextSourceBuffer.js
fixing console.log to use internal log in TextSourceBuffer.
=> Partial Fix for #1228

src/dash/DashHandler.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js
I have tested and compared all smoke test streams in as many permutations of OS browser and not seeing issues with this change.  I want to be careful here as I basically only removed code to solve the issue.
=> Possible solution for #1218

samples/dash-if-reference-player/app/sources.json
Adding a new VOD sample file http://dash.edgesuite.net/akamai/bbb_30fps/bbb_30fps.mpd.
This contains representations from 250kbps 320x180 up to 15Mbps 3840x2160. The resolution, bitrate, frame count and time are burnt in to each frame, making this useful for studying adaption algorithms as you can easily visually identify any switch.
=> Updating sources file with new content

src/dash/DashHandler.js
=> Fix for failing initial index on segment timeline

src/dash/DashHandler.js, src/streaming/controllers/StreamController.js
Third iteration of this fix. This time I hope there are no more edge cases.  Race condition was introduced with last solution.
=> Removes race condition introduced while trying to fix #1275.  

src/streaming/controllers/StreamController.js
We can look at value per specific user agent as well if needed.
=> Addition change for #1033 changed value to suite all browsers.  

src/streaming/utils/Capabilities.js
=> Remove fail fast if video is not an instance of HTMLMediaElement

ISSUE_TEMPLATE.md
This should render the MD in the template for all new issues opened. Please feel free to expand upon this.  More discussion at the F2F
=> Adding initial issue template for GIT issues. 

contrib/akamai/controlbar/ControlBar.js
=> Fix #1353 - Fix deprecated method call in ControlBar

src/streaming/protection/vo/ClearKeyKeySet.js, src/streaming/protection/vo/KeyError.js, src/streaming/protection/vo/KeyMessage.js, src/streaming/protection/vo/KeyPair.js, src/streaming/protection/vo/KeySystemAccess.js, src/streaming/protection/vo/KeySystemConfiguration.js, src/streaming/protection/vo/LicenseRequestComplete.js, src/streaming/protection/vo/MediaCapability.js, src/streaming/protection/vo/NeedKey.js, src/streaming/protection/vo/ProtectionData.js
=> More JSDoc3/Closure compliance changes

index.js, package.json, src/core/Version.js, src/streaming/MediaPlayer.js
Some players may need to print out version before they can init player.
=> Solving chicken/egg issue with version string.

src/dash/utils/ListSegmentsGetter.js
=> Fixes #1379 - map BaseURL to SegmentURL correctly when media is not present

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/Stream.js
With this change I have fixed multitrack (audio / video) playback for live streams with manifest updates.   On manifest update, I insure the correct adaptation info set is sent to be converted into MediaInfo based on the current track for any  given media type.
=> fix for 1375

src/dash/DashAdapter.js, src/dash/DashMetrics.js, src/dash/constants/DashMetricsList.js
Removed loads of repeated code, an unused method and import, and did `//TODO need to refactor all that reference to be able to export like all other const on factory object.`
=> Simple refactor of DashMetrics

src/dash/WebmSegmentBaseLoader.js, src/streaming/Stream.js, src/streaming/controllers/BufferController.js, src/streaming/utils/EBMLParser.js
This PR is related to issue #1301 
It's a refactor of the code in contrib/webmjs with some updates to get it work with Dash.js v2. I hope I kept up with the code organization scheme of Dash.js.
Test Manifest:
http://yt-dash-mse-test.commondatastorage.googleapis.com/media/feelings_vp9-20130806-manifest.mpd
=> Integrate/Update support of WebM in current version of Dash.js (v2.2.0)

src/streaming/controllers/StreamController.js
finally! thanks @bbcrddave for the assist!
=> Fix for issue #887

src/streaming/protection/controllers/ProtectionController.js
Apologies a  protection log needed to be cleaned up.
=> #1145 cleanup protection log

src/dash/DashHandler.js, src/dash/models/DashManifestModel.js, src/dash/utils/TimelineSegmentsGetter.js
See #1457 for discussion.
Tested with relevant test vectors and MPD in issue report.
=> Fix #1457 - Enable SegmentTimeline within SegmentList

src/dash/utils/SegmentsGetter.js, src/dash/utils/SegmentsUtils.js, src/dash/utils/TimelineConverter.js
Reverts Dash-Industry-Forum/dash.js#1387  We are reverting this code due to regression issue and will solve the bug and more in 2.3
=> Revert "For SegmentTemplate, only include available segments in DVRInfo"

src/dash/controllers/RepresentationController.js, src/dash/models/DashManifestModel.js, src/streaming/MediaPlayer.js, src/streaming/TextTracks.js, src/streaming/controllers/MediaController.js, src/streaming/protection/controllers/ProtectionKeyController.js
I suppose it's better to use Strict Equality Comparison Operator.
=> use Strict Equality Comparison Operator

samples/dash-if-reference-player/app/sources.json
Wowza have provided us with some test streams generated by their service. Let's add them to the sample content list.
=> Add Wowza test streams

samples/dash-if-reference-player/app/sources.json, src/streaming/utils/TTMLParser.js
This is not finished yet and too early to merge, but at least the timing for embedded subtitles in divs is in place and working with the trombone2 test sequence provided in #1402.
The positioning needs to be handled, so that is a next step.
External images (non self-contained subtitles as in IMSC-1) is another step.
=> Support for image subtitles

samples/dash-if-reference-player/app/sources.json
Reverts Dash-Industry-Forum/dash.js#1531
=> Revert "Removed local test URL from sources"

src/streaming/utils/TTMLParser.js
Reverts Dash-Industry-Forum/dash.js#1529
=> Revert "Support for image subtitles"

samples/dash-if-reference-player/app/sources.json
This is a revert of #1532 which reverted #1531 which was a partial revert of #1529. Now all of #1529 should be gone.
=> Revert 1532 revert of 1531 which was a partial revert of 1529

samples/dash-if-reference-player/app/sources.json
Adding Akamai 24x7 ref stream to ref player samples.
=> Adding new live stream sample to ref player

src/streaming/controllers/PlaybackController.js
At some point we reverted (intentionally and forgot about, or accidentally), this change.
Let's put it back in :)
=> Fix regression resulting in #t no longer working (see issue #1361)

contrib/akamai/controlbar/ControlBar.js
controlbar.js code issue. minor change.
=> Fix for #1571

contrib/akamai/controlbar/ControlBar.js
=> Fixes #1587, #1588

samples/dash-if-reference-player/app/sources.json
=> Fixed link for v7 encrypted single-key (audio only)

src/dash/parser/maps/RepresentationBaseValuesMap.js, src/dash/parser/maps/SegmentValuesMap.js
in a constructor, we don't need to use 'return'. It was not really an issue but rather a syntax mistake.
=> corrected syntax on heritage

src/streaming/MediaPlayer.js
=> Add method isDynamic to MediaPlayer

src/dash/models/DashManifestModel.js, src/streaming/ManifestUpdater.js, test/dash.DashManifestModel.js
On top of the change the DashManifestModel for minUpdatePeriod for manifest refresh, I refactored ManifestUpdater to be current and abstracted the call to refresh from the timer handler so it is externally executable.
=> Fix for #869

src/streaming/TextSourceBuffer.js
remove dash adapter reference, not used...
=> little PR to remove unused reference.

src/streaming/TextTracks.js, src/streaming/utils/TTMLParser.js
TTML subtitles could defined font size and line height by percentage, cell or pixels.
For instance, subtitles font size could be defined like this :
_tts:fontSize='1c 2c'_
=> Update TTML subtitles management.

src/streaming/utils/TTMLParser.js
alpha TTML value is between 0 and 255, it's between 0 and 1 for CSS
=> convert rgba TTML syntax to rgba HTML syntax

src/streaming/controllers/ScheduleController.js, src/streaming/utils/InitCache.js
The initial request is a switch init data like others.
=> Simplify ScheduleController without initial request

src/streaming/controllers/StreamController.js
=> Fix #1638 - ensure activeStream is not undefined in onEnded

samples/dash-if-reference-player/app/sources.json, src/streaming/utils/TTMLParser.js
Fix of minor bug introduced with latest image subtitle addition.
=> Bug fix image subtitles

src/streaming/controllers/ScheduleController.js, src/streaming/utils/InitCache.js
Reverts Dash-Industry-Forum/dash.js#1669
=> Revert "Simplify ScheduleController without initial request"

samples/dash-if-reference-player/app/sources.json, src/streaming/TextSourceBuffer.js
Fixes bug introduced with fontStyle units in 3bb4adfe.
=> Fix cea608 scaling

src/dash/SegmentBaseLoader.js
Tested using http://dash.edgesuite.net/dash264/TestCases/1a/sony/SNE_DASH_SD_CASE1A_REVISED.mpd and another public test vector, and also indepentently tested by @alanimgur as described in #1672.
=> Fix #1672, #1254 - use XHRLoader for SegmentBase requests

samples/dash-if-reference-player/app/main.js
=> bug fix on javascript syntax

samples/dash-if-reference-player/app/main.js
some issues appear with the stream 'IRT reference with EBU-TT-D subtitles'
=> the chart is drawn only for video and audio data.

src/dash/DashAdapter.js, src/dash/DashMetrics.js, src/dash/models/DashManifestModel.js
With the live sample 'Multiperiod SegmentTemplate. New period every minute (livesim)', there was errors in the console logs with undefined objects. I just added tests...
=> Bug fix undefined objects

src/streaming/TextTracks.js
=> Fixes #1762 where VTT subtitle positioning was omitted

src/dash/utils/FragmentedTextBoxParser.js, src/streaming/utils/IsoFile.js
Fixes #1804.
Test content http://vm2.dashif.org/dash/vod/testpic_2s/imsc1_img.mpd now works again.
=> Fixes parsing of subs box for IMSC 1 image subtitles after update of isoboxer library.

src/streaming/MediaPlayer.js, src/streaming/controllers/AbrController.js
=> Added setMinAllowedBitrateFor

samples/dash-if-reference-player/app/main.js
add a test to validate 'repSwitch'
=> Inprove Web app robustness.

src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/models/MetricsModel.js
=> Code refactoring

src/dash/controllers/RepresentationController.js, src/mss/MssHandler.js, src/streaming/StreamProcessor.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/SourceBufferController.js, src/streaming/controllers/StreamController.js, src/streaming/rules/abr/ABRRulesCollection.js, src/streaming/rules/abr/BolaRule.js, src/streaming/rules/scheduling/BufferLevelRule.js
=> Remove unused reference

index.d.ts
For those who using dashjs in TypeScript project
=> Adding typescript definitions for MediaPlayer

src/streaming/utils/TTMLParser.js
=> Fix typo in TTMLParser

src/mss/MssFragmentProcessor.js
This PR fixes issue #1850. Thanks @Andgoncharov!
=> bug fix in big endian conversion #1850

src/streaming/utils/URLUtils.js, test/streaming.utils.URLUtils.js
=> Fix #1862 - correctly handle scheme-relative URLs in IE11

src/streaming/text/TextController.js, src/streaming/text/TextTracks.js
=> Fix issue #1868 : crash on TextTracks

src/streaming/controllers/BufferController.js, src/streaming/text/TextSourceBuffer.js
=> Fix #1873 - supply correct args to trigger for VIDEO_CHUNK_RECEIVED

src/core/EventBus.js
Caused by #1774 , hopefully fixes  #1889 
Based on https://github.com/Dash-Industry-Forum/dash.js/pull/1774#issuecomment-296976290
=> fix(EventBus): Fix faulty logic for `off`, caused by #1774

externals/cea608-parser.js
=> Update cea608-parser to version 1.0.1

package.json
=> Update codem-isoboxer version

src/streaming/text/TextController.js, src/streaming/text/TextTracks.js
The goal of this PR is to fix the issue #1922
=> Fix issue #1922: TextTrack::deleteTrackCues - Wrong object passed from TextController

src/core/EventBus.js
Per https://github.com/Dash-Industry-Forum/dash.js/pull/1891#issuecomment-298868561
=> fix(EventBus): add null check to handlers

src/streaming/StreamProcessor.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/ScheduleController.js, src/streaming/rules/RulesContext.js, src/streaming/rules/abr/AbandonRequestsRule.js, src/streaming/rules/abr/BolaAbandonRule.js, src/streaming/rules/abr/BolaRule.js, src/streaming/rules/abr/InsufficientBufferRule.js, src/streaming/rules/abr/ThroughputRule.js, src/streaming/rules/scheduling/BufferLevelRule.js
Hello
The goal of this PR is to simplify access to ABRController from ABR and scheduling rules and to remove getABRController from streamController (this is not the role of the SP to give AbrController instance)
Jérémie
=> Abr AbrController accessors

src/streaming/rules/abr/ThroughputRule.js
=> Do not use latency to check if segment is from cache

src/streaming/text/TextTracks.js
add missing parameters to render properly cea608 subtitles. bug fix #1975
=> bug fix #1975 on cea608 subtitles rendering

src/streaming/text/TextTracks.js
Hi,
this PR has to simplify subtitles management after imsc1.js integration. Now, all the captions have 'html' type.
=>Remove scaleImageCue and convertToPixels functions, not used.
Nicolas
=> Update subtitles management 

src/streaming/controllers/BufferController.js
Hi
This PR solves the issue #2014, on version 2.6
Jérémie
=> Fix Issue #2014 : Bitrate doesn't change

Gruntfile.js, src/dash/DashAdapter.js, src/dash/DashMetrics.js, src/dash/models/DashManifestModel.js, src/dash/utils/FragmentedTextBoxParser.js, src/mss/MssFragmentMoovProcessor.js, src/mss/MssFragmentProcessor.js, src/streaming/XHRLoader.js, src/streaming/controllers/StreamController.js, src/streaming/models/FragmentModel.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js, src/streaming/utils/IsoFile.js, src/streaming/utils/TTMLParser.js, test/unit/dash.DashAdapter.js, test/unit/dash.DashManifestModel.js, test/unit/dash.DashMetrics.js, test/unit/dash.utils.FragmentedTextBoxParser.js, test/unit/mss.MssFragmentProcessor.js, test/unit/streaming.FragmentModelSpec.js, test/unit/streaming.XHRLoader.js, test/unit/streaming.controllers.StreamController.js, test/unit/streaming.utils.InitCache.js, test/unit/streaming.utils.IsoFile.js, test/unit/streaming.utils.TTMLParser.js
Hi,
this PR has to improve unit tests for DashManifestModel class by adding a check of the parameters. Some errors may occur during development round, maybe it could be better to throw an error......
Some others unit tests have been added.
Nicolas
=> Improve unit tests

src/dash/DashAdapter.js, src/streaming/Stream.js, test/unit/dash.DashAdapter.js, test/unit/dash.DashMetrics.js, test/unit/streaming.XHRLoader.js
Hi
This PR fixes broken build dated of June, 19th. 
It fixes thrown error and updates unit tests
Jérémie
=> Controller creation merge

src/dash/DashHandler.js, src/dash/SegmentBaseLoader.js, src/dash/controllers/RepresentationController.js, src/streaming/FragmentLoader.js, src/streaming/ManifestLoader.js, src/streaming/XlinkLoader.js, src/streaming/controllers/SourceBufferController.js, src/streaming/controllers/TimeSyncController.js, src/streaming/protection/drm/KeySystemPlayReady.js, src/streaming/utils/EBMLParser.js, src/streaming/vo/DashJSError.js
Hi,
this PR has to resolve the issue #2021 : use the good Error class...
Nicolas
=> use the good specific error class

samples/dash-if-reference-player/app/sources.json
Now with HTTPS URLs for that DRM goodness.
=> Axinom URLs to HTTPS

samples/dash-if-reference-player/app/sources.json
Followup to #2023 - apparently I forgot to change license server URLs! So many URLs! Hopefully got them all this time.
=> Axinom license server URLs to HTTPS

src/streaming/MediaPlayer.js, src/streaming/text/TextTracks.js, test/unit/helpers/Helpers.js, test/unit/helpers/SpecHelper.js, test/unit/mocks/AbrControllerMock.js, test/unit/mocks/CapabilitiesMock.js, test/unit/mocks/MediaControllerMock.js, test/unit/mocks/MediaPlayerModelMock.js, test/unit/mocks/PlaybackControllerMock.js, test/unit/mocks/StreamControllerMock.js, test/unit/mocks/VideoElementMock.js, test/unit/streaming.MediaPlayerSpec.js
Hello
This PR adds some unit tests on MediaPlayer object
Jeremie
=> Mediaplayer unit tests

src/dash/SegmentBaseLoader.js, test/unit/dash.SegmentBaseLoader.js
Hi,
This PR initiate a first version of SegmentBaseLoader unit tests.
Nicolas
=> SegmentBaseLoader tests

src/dash/WebmSegmentBaseLoader.js, test/unit/dash.WebSegmentBaseLoader.js
Hi,
This PR initiate a first version of WebmSegmentBaseLoader unit tests.
Nicolas
=> WebmSegmentBaseLoader tests

test/unit/streaming.BufferControllerSpec.js
Hi,
This PR initiate a first version of BufferController unit tests.
Jérémie
=> BufferController tests

src/streaming/Stream.js, test/unit/streaming.Stream.js
Hi,
This PR initiate a first version of Stream unit tests.
Nicolas
=> Stream tests

src/dash/DashHandler.js, src/dash/controllers/RepresentationController.js, src/streaming/StreamProcessor.js, src/streaming/controllers/ScheduleController.js, src/streaming/rules/abr/BolaRule.js, src/streaming/rules/abr/ThroughputRule.js, test/unit/helpers/ObjectsHelper.js
Hi,
this PR has to centralize dynamic attribute of a manifest. In my opinion, isDynamic could not be an attribute of ScheduleController, nor DashHandler. There is, at the end, only two way to access this attribute :
- from PlaybackController
- from accessors of StreamProcessor, which manipulate manifestInfo vo.
Nicolas
=> Update access to  isDynamic attribute

src/mss/MssFragmentMoovProcessor.js, src/streaming/StreamProcessor.js, src/streaming/models/FragmentModel.js
Hi
This PR fix a merge pb in development branch, using MSS streams
It has to be merged in 2.6 version
Jérémie
=> MSS integration : Fix pb of merge in development branch

README.md
Prevents mixed active content warnings.
Fixes #2059
=> Example code uses HTTPS

src/streaming/text/NotFragmentedTextBufferController.js, src/streaming/text/TextBufferController.js, test/unit/streaming.text.NotFragmentedTextBufferController.js
Hi,
This PR initializes unit tests for NotFragmentTextBufferController
It fixes on error in switch init data
Jérémie
=> NotFragmentTextBufferController Unit Tests

src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js, src/streaming/utils/LiveEdgeFinder.js, test/unit/streaming.utils.LiveEdgeFinder.js
Hi,
this PR has to define LiveEdgeFinder as an instance of class, not a singleton. A first version of unit test file has also been created.
Nicolas
=> Update live edge finder management

src/streaming/controllers/BufferController.js, src/streaming/text/NotFragmentedTextBufferController.js, src/streaming/text/TextBufferController.js, test/unit/streaming.text.TextBufferController.js
Hi,
This PR initializes unit tests for TextBufferController
Jérémie
=> TextBufferController Unit Tests

src/dash/controllers/RepresentationController.js, src/streaming/StreamProcessor.js, test/unit/dash.DashAdapter.js, test/unit/dash.controllers.RepresentationControllerSpec.js
Hi,
this PR has to standardize the config object used by RepresentationController : use only setConfig. Unit test file has also been update.
Nicolas
=> Update representation controller

src/streaming/text/TextController.js, test/unit/streaming.text.TextController.js
HI 
This PR initializes unit test for text controller
Jérémie
=> TextController - Initializes unit tests

src/dash/models/DashManifestModel.js, test/unit/dash.models.DashManifestModel.js, test/unit/streaming.utils.URLUtils.js
=> Fix #2091 - relative baseurl at mpd level doesn't resolve correctly

src/dash/DashHandler.js, src/dash/utils/SegmentsUtils.js, src/dash/utils/TimelineSegmentsGetter.js, src/mss/MssFragmentMoofProcessor.js, src/mss/parser/MssParser.js, src/streaming/controllers/PlaybackController.js, src/streaming/rules/scheduling/BufferLevelRule.js
HI 
Integration of PR #1991 has fixed a pb on segment timeline.
This fix has highlighted a pb on MSS segment timeline management for MSS Live streams. This PR fixes the pb
Jérémie
=> MSS Live Playing : fix a pb highlighted by integration of PR # 1991 

index.d.ts, src/streaming/MediaPlayer.js, test/unit/mocks/VideoElementMock.js, test/unit/streaming.MediaPlayerSpec.js
Enable to set and get playback rate directly by using mediaPlayer instance, like mute and volume.
=> Enable to set and get playback rate.

test/unit/core.EventBus.js, test/unit/mocks/StreamProcessorMock.js, test/unit/streaming.controllers.ScheduleController.js
=> add EventBus unit test

src/mss/MssFragmentMoofProcessor.js
This PR corrects MSS to DASH framgent processing in order to update saio 'offset' field value for encrypted fragments.
=> [MSS] Update saio offset field for encrypted fragments

src/dash/models/DashManifestModel.js, test/unit/dash.models.DashManifestModel.js, test/unit/mocks/AdapterMock.js, test/unit/mocks/MediaControllerMock.js, test/unit/streaming.MediaPlayerSpec.js
as explain in issue #1928, the getAdaptationForType function returns a mistake.....
=> Update getAdaptationForType function

src/mss/MssFragmentInfoController.js
While building I noticed a duplicate export. I tried a quick search to see if it had been fixed elsewhere but didn't find anything, so I figured I'd make a tiny contribution.
=> Remove duplicate default export

src/streaming/controllers/PlaybackController.js
=> Bug fix issue #2192

src/streaming/rules/abr/BolaRule.js
=> Fix BolaRule to not get newQuality from abandon event

src/dash/utils/ListSegmentsGetter.js, src/dash/utils/SegmentsGetter.js, src/dash/utils/TemplateSegmentsGetter.js, src/dash/utils/TimelineSegmentsGetter.js
Hi,
availabilityUpperLimit parameter is defined but never used.....
Nico
=> remove unused parameter

src/mss/MssFragmentMoovProcessor.js, src/mss/MssFragmentProcessor.js, src/mss/MssHandler.js, src/mss/parser/MssParser.js, src/streaming/MediaPlayer.js, src/streaming/protection/controllers/ProtectionController.js
Hi
This PR includes pssh for all key systems (computed using protectionController) when init data is processed
Previously, only PlayReady pssh was added.
This PR is relative to Smooth Streaming encrypted streams
Jérémie
=> [MSS] Processing moov pssh

samples/ad-insertion/inband.html, samples/ad-insertion/inline.html, samples/ad-insertion/scte.html, samples/ad-insertion/xlink.html, samples/captioning/multi-track-captions.html, samples/captioning/ttml-ebutt-sample.html, samples/index.html
- Remove reference to eme.html
- Fix multi-track-captions sample. Previous version was incomplete
- Homogenize script references in ad-insertion samples
=> Fix samples and remove broken ones (eme)

src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/protection/servers/DRMToday.js, test/unit/streaming.protection.servers.DRMToday.js, test/unit/streaming.protection.servers.PlayReady.js
=> Drm today fix

src/streaming/controllers/PlaybackController.js
=> Bug fix for live with audio only

src/streaming/MediaPlayer.js, test/unit/streaming.MediaPlayerSpec.js
Hi,
this PR has to be sure that a mediaController has been created before calling some functions of MediaPlayer. 
Nico
=> Improve robustness of MediaPlayer

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js
=> Bug fix start time live stream

test/functional/config/applications.js, test/functional/runTestsWin.bat, test/functional/tests.html, test/functional/tests/play/pause.js, test/functional/tests/play/play.js, test/functional/tests/play/seek.js, test/functional/testsCommon.js
Hi,
this PR updates the local functional tests in order to support mss use case. So, regression on module management can be easily detected with a local test.
Nico
=> update functional tests

samples/dash-if-reference-player/app/sources.json
Add some official MS Playready test streams from
the Microsoft PlayReady Test Server.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
=> sources.json: Add Microsoft Playready test vectors

Gruntfile.js
Hopefully should solve https://github.com/Dash-Industry-Forum/dash.js/issues/2244#issuecomment-340505192.
=> Refix #2244 - pass compact false option to babelify

Gruntfile.js, README.md, package.json
Changes suggested for project README.md file. It updates Quick Start Guide for developers including information about recently updated grunt tasks (grunt dev) that make easier the development process. 
Please, feel free to comment. The easier we keep this guidelines, the better. 
Related with #2223
=> Readme changes

src/streaming/controllers/AbrController.js, test/unit/streaming.controllers.AbrControllerSpec.js
Hi,
add a test to be sure that abandonmentStateDict array is defined.
Nico
=> Update abr controller unit test

src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/AbrController.js
add unRegisterStreamType function to remove stream processor reference in abrController. Bug #2270 fix
=> bug fix 2270

Gruntfile.js
Hi,
this PR has to solve the issue #1959 by using relative paths in source map.
Nico
=> set exorcise base folder in order to have relative paths in sourcemap.

src/dash/DashHandler.js, src/dash/models/DashManifestModel.js, src/dash/utils/SegmentsUtils.js, src/streaming/controllers/StreamController.js
Hi,
this PR should solve the issue #2279. The main issue is a javascript weird behaviour :
example : 0.2+0.1 = 0.30000000000000004
=> Infinite loop multi period bug

contrib/akamai/controlbar/ControlBar.js, samples/dash-if-reference-player/app/css/main.css, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/events/CoreEvents.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/text/TextController.js, src/streaming/text/TextTracks.js, test/unit/streaming.text.TextController.js
Hi
This PR adds the possibility to configure some settings about captions : 
- display or not on stream loading
- choose prefered language
Jérémie
=> Text default settings

samples/dash-if-reference-player/app/sources.json, src/streaming/constants/ProtectionConstants.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/controllers/ProtectionKeyController.js, src/streaming/protection/drm/KeySystemClearKey.js, src/streaming/protection/drm/KeySystemPlayReady.js, src/streaming/protection/drm/KeySystemW3CClearKey.js, src/streaming/protection/drm/KeySystemWidevine.js, src/streaming/protection/models/ProtectionModel_01b.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js, src/streaming/protection/servers/DRMToday.js
- Move KeySystem DRM constants to ProtectionConstants.js
- Clean up ClearKey integration
- Add keys to ClearKey samples in sources.json
- Fix issue when protdata is not provided in ClearKey sources
=> Clean clearkey support implementation

src/dash/WebmSegmentBaseLoader.js
=> Fix #2298 - be more permissive in webm parsing

src/streaming/MediaPlayerEvents.js, src/streaming/Stream.js, src/streaming/controllers/StreamController.js
Issue #2209
New event SOURCE_INITIALIZED triggered when the source is setup and ready. Updated doc for STREAM_INITIALIZED.
=> New event SOURCE_INITIALIZED

.travis.yml
Use different jobs for running functional tests on every browser instead of matrix expansion (not suitable for stages)
=> Travis configuration for functional tests

test/functional/config/streams.json
- remove non-https streams
- add/update https MSS test stream
=> [functional tests] updates streams list

src/streaming/protection/controllers/ProtectionController.js
Closed old request did not want to deal with i rebase and squash.. Much quicker path... sorry for the delay @epiclabsDASH
=> Fix for issue 2256  maintaining backwards capability

.travis.yml, Gruntfile.js, package.json, samples/dash-if-reference-player/app/css/main.css, samples/dash-if-reference-player/index.html
Now that we have a basic continuous delivering process for the development branch we need a quick way to easy know the latest change built. This PR adds a label to dash-if-reference-player that, in deployment phase, is filled in with information about the latest commit.
=> Add commit info in automatic deployment

src/mss/parser/MssParser.js
Hi,
this PR has to fix issue #2332 .
Nico
=> MSS parser bug fix

src/streaming/controllers/StreamController.js, src/streaming/controllers/TimeSyncController.js, src/streaming/models/BaseURLTreeModel.js
=> Fix #2333 - ensure UTCTiming is resolved relative to MPD base uri or BaseURLs

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js
Hi,
this PR has to solve issue #2363. The main problem was due to audio and video detection that didn't reseted when a stream period switch.
Nico
=> Multiperiod without audio bug fix

samples/index.html, samples/smooth-streaming/mss.html
Add a new sample that shows how to use dash.js to play Smooth Streaming content
=> Add a sample for MSS

src/streaming/text/TextTracks.js
Changed regexp for image subtitles to allow multi-digit numbers of subtitles in one segment.
=> Bug fix. Allow for more image subtitles in one segment.

Gruntfile.js
Changes in the nightly build procedure so all samples are pushed after a change in development branch.
=> Upload all samples in deployment process

package.json, src/streaming/text/TextTracks.js
Hi,
this PR has to add smooth scrolling of subtitles like describe in issue #2372. Before merging, any feedback will be appreciate.
Thanks,
Nico
=> Add smooth scrolling for subtitles

src/streaming/controllers/StreamController.js
=> bug fix about upper case of mediaSource

src/streaming/text/TextTracks.js
=> Improve subtitles display in pause mode

contrib/akamai/controlbar/ControlBar.js, contrib/akamai/controlbar/controlbar.css, samples/dash-if-reference-player/index.html
Improving UI of thumbnails to scale thumbnails according to a percentage of the player height (#2316)
=> Scaling thumbnails to be a percentage of player height

contrib/akamai/controlbar/ControlBar.js, contrib/akamai/controlbar/controlbar.css, contrib/akamai/controlbar/snippet.html, samples/dash-if-reference-player/index.html
Change playing progress bar to be a div instead of an input[type=range]. This also solves a problem when seeking with thumbnails in which thumbnails where showing a timestamp to seek, but after clicking, the player was going to a timestamp a few seconds before than specified.
=> Changing playing progress

contrib/akamai/controlbar/ControlBar.js
This PR fixes two errors in Firefox in the progress bar:
1. When clicking to seek, sometimes it was not working
2. When clicking, dragging and dropping, it was not seeking
=> Fix error in player bar in Firefox

samples/ad-insertion/inband.html, samples/ad-insertion/inline.html
Update ad insertion samples with the new stream urls generated by @dsilhavy (thanks!)
=> Update ad insertion samples

build/typings/index.d.ts, index.d.ts
=> update typeScript interface

build/typings/index.d.ts, index.d.ts
=> update MediaPlayerEvents in typeScript declaration

src/streaming/text/NotFragmentedTextBufferController.js, src/streaming/text/TextBufferController.js
Hi,
since PR #2274, VTT subtitles didn't show anymore.
@robertbryer , do you agree with my modifications?
Thanks,
Nico
=> Vtt subtitles bug fix

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js
Enhance jump gaps feature so it detects gaps at the end of the stream (ex: video track longer than audio track situations).
=> Fixes in StreamController and jumpGaps feature

build/typings/index.d.ts, index.d.ts, samples/getting-started-basic-embed/listening-to-events.html, src/streaming/MediaPlayerEvents.js, src/streaming/controllers/PlaybackController.js
This PR add trigger of PLAYBACK_WAITING event when 'waiting' event is raised on video element
=> Add PLAYBACK_WAITING event

samples/dash-if-reference-player/app/sources.json, src/streaming/Stream.js, src/streaming/protection/ProtectionEvents.js, src/streaming/protection/controllers/ProtectionController.js, src/streaming/protection/models/ProtectionModel_21Jan2015.js
Hi,
this PR has to return an error when a license has expired during visualization of a stream. Before those modifications, when the license expired, no error message was shown to the user.
A sample stream has been added by axinom team in order to test this specific use case : many thanks to them!
Nico
=> Management of DRM license with an expiration value

ISSUE_TEMPLATE.md
People do not delete the spaces, leading to this:
So let's delete them from the issue template and bring about a better world.
=> Improve issue template for less ugly checkboxes

src/streaming/FragmentLoader.js, src/streaming/XHRLoader.js, test/unit/streaming.XHRLoader.js
=> #2477 remove xhr.status check before triggering LOADING_ABANDONED event in FragmentLoader

src/streaming/text/TextSourceBuffer.js
In multiperiod dash feeds, the DTS gets reset to zero. The `timestampOffset` of the source buffer is correspondingly adjusted, but the caption start time is not. This PR simply fixes that by also adjusting the start time of captions.
=> Shift caption start time by MSETimeOffset * videoTimescale

build/typings/index.d.ts
=> update typescript definition

samples/dash-if-reference-player/app/sources.json
For more info about this stream see https://github.com/Axinom/dash-test-vectors#live-clear
=> Added Axinom Live-Clear reference stream

contrib/akamai/controlbar/ControlBar.js, contrib/akamai/controlbar/controlbar.css
=> Added resolution to bitrate list in the controlbar

src/streaming/models/FragmentModel.js, test/unit/helpers/VOHelper.js, test/unit/streaming.models.FragmentModelSpec.js
Hi,
this PR has to not remove initialization segment from executedRequests array. Unit tests are also updated.
Nico
=> Update removeExecutedRequestsBeforeTime function

src/streaming/models/FragmentModel.js
Revert PR #2531. We need to find a way of re-implementing it without breaking multi-track support.
=> Revert PR #2531

src/mss/MssHandler.js
=> MSS create datachunk now supports endFragment parameter

samples/dash-if-reference-player/app/main.js
Recover Reference Player changes of PR #2451 that were removed during the merge of PR #2427.
=> Fix merge problems in persistent licenses functionality caused after merging #2427

src/core/FactoryMaker.js
The `extend(parentNameString, childInstance, override)` method allows to extend (override = true) or replace (override = false) internal dash.js objects.
This PR fixes `FactoryMaker` to not uselessly create an instance of the parent class when the extension fully replaces it (override = false).
It also removes the internal `extensions` variable and the `getExtensionContext()` method of `FactoryMaker` because the context of an extension is always the one passed to `getExtensionContext()`. Thus, there is no need to look for it, and no need to store extension contexts either.
=> Fix instantiation of extensions

src/streaming/models/FragmentModel.js
This PR fixes the issue with this [stream](http://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd) found in #2531 , which is reverted now, I've also tested the MSS streams to check that no regression with #2252 is caused
=> Redundant segment download when changing quality

contrib/akamai/controlbar/ControlBar.js, samples/captioning/multi-track-captions.html, samples/captioning/ttml-ebutt-sample.html, samples/thumbnails/thumbnails.html
This PR fixes the thumbnail sample, it behaved poorly, specially in fullscreen mode, and updates the bars on captioning samples.
Solves #2587
=> Fixed the thumbnail sample

src/streaming/MediaPlayerFactory.js, src/streaming/Stream.js, src/streaming/models/VideoModel.js
=> Case insensitive comparison for nodeName

Gruntfile.js, test/functional/config/applications.js, test/functional/config/browsers/windows.js, test/functional/config/streams.json, test/functional/config/testsConfig.js, test/functional/tests/play/pause.js, test/functional/tests/play/seek.js, test/functional/tests/player_functions.js, test/functional/tests/tests_functions.js
Functional tests now run on nightly player and change some tests.
=> Functional tests improvements to make them work in IE/Edge

src/streaming/PreBufferSink.js, src/streaming/SourceBufferSink.js, src/streaming/controllers/BufferController.js, src/streaming/text/NotFragmentedTextBufferController.js, src/streaming/text/TextBufferController.js, test/unit/mocks/MediaSourceBufferMock.js
=> Wait until buffer is ready when changing timestamp offset

build/typings/index.d.ts, src/streaming/SourceBufferSink.js, src/streaming/text/TextController.js, src/streaming/text/TextSourceBuffer.js
Hi,
this PR has to solve issue #2629.
@panofr, could you please take a look at it?
thanks,
Nico
=> Fix subtitles in multiple period

src/streaming/controllers/BufferController.js
Removed the append queue control from BufferController, it's already handled in the SourceBufferSink and it's causing issues elsewhere, see #2644
=> Removed the buffer append queue control from BufferController

src/streaming/controllers/PlaybackController.js, test/unit/streaming.controllers.PlaybackControllers.js
=> add float management to uri parameters

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, test/unit/streaming.controllers.PlaybackControllers.js
PLAYBACK_ENDED event won't mess with multiperiod streams.
=> Fixes PLAYBACK_ENDED stopping streams after first period

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js
Hi,
this PR has mainly to solve issue #2667 with an update of the seek command.
Nico
=> Add internal seek

src/streaming/models/FragmentModel.js
Removed FragmentModel isInBuffer check because it's causing issues wi…th some streams, and the issue it fixed is already covered in SourceBufferSink
=> Removed isInBuffer check

build/typings/index.d.ts, index.d.ts, samples/dash-if-reference-player/app/main.js, src/streaming/MediaPlayer.js, src/streaming/models/MediaPlayerModel.js, test/unit/streaming.models.MediaPlayerModel.js
Hi,
this PR has to protect the function which enables, or disables low latency mode.
Nico
=> Fix low latency API

samples/control/controlbar.html, samples/control/logging.html, samples/index.html, samples/samples.json
Adds two new samples. Also removed the button links and made the title of the samples clickable.
Continuation of #2615
=> Control bar and logging examples

build/typings/index.d.ts, index.d.ts, src/streaming/MediaPlayer.js, test/unit/streaming.MediaPlayerSpec.js
Hi,
this PR has to add missing functions in the TypeScript API. @sara3988, could you, please, tell me if all the functions are correctly defined?
thanks,
Nico
=> Update TypeScript api

build/typings/index.d.ts, index.d.ts, src/streaming/MediaPlayerEvents.js, src/streaming/text/TextTracks.js
Add new `CAPTION_CONTAINER_RESIZE` event and small refactoring of `TextTracks.checkVideoSize()`.
=> Add CAPTION_CONTAINER_RESIZE event

src/streaming/Stream.js, test/unit/streaming.Stream.js
Hi,
this PR has to solve issue #2704. 
Nico
=> Update CompareCodecs function

src/streaming/net/FetchLoader.js, src/streaming/net/HTTPLoader.js
This PR fixes a low latency issue reported by @wilaw , it crashed when a network error like ERR_NETWORK_CHANGED happened, and didn't recover.
=> Fixes a crash when a network error happened, but status code was 200

src/streaming/controllers/MediaSourceController.js, src/streaming/controllers/ScheduleController.js
Hi,
this PR has to solve issue #2702 by stopping scheduleController when buffering is completed. Any feedback would be appreciate...
Nico
=> End detection bug fix

src/dash/DashAdapter.js, src/dash/DashHandler.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/controllers/MediaController.js, src/streaming/text/TextTracks.js, test/unit/dash.DashAdapter.js, test/unit/dash.DashHandlerSpec.js, test/unit/mocks/AdapterMock.js, test/unit/mocks/DashManifestModelMock.js, test/unit/mocks/StreamMock.js, test/unit/streaming.controllers.MediaController.js, test/unit/streaming.text.TextController.js, test/unit/streaming.thumbnail.ThumbnailController.js
Hi,
this PR has to remove unused code and add some simplifications.
Nico
=> Refactoring branch

src/mss/MssFragmentInfoController.js, src/mss/MssFragmentMoofProcessor.js, src/mss/MssFragmentProcessor.js, src/mss/MssHandler.js, src/mss/parser/MssParser.js, src/streaming/MediaPlayer.js, src/streaming/controllers/StreamController.js
Start-over streams = static streams from live streams with  duration that may progress (updated using tfrf boxes from FragmentInfo requests)
=> Add support for MSS start-over streams

src/dash/DashAdapter.js, src/dash/DashHandler.js, src/streaming/Stream.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/MediaController.js, src/streaming/controllers/ScheduleController.js, src/streaming/rules/scheduling/NextFragmentRequestRule.js, src/streaming/text/TextController.js, src/streaming/text/TextSourceBuffer.js, test/unit/mocks/ErrorHandlerMock.js, test/unit/streaming.text.TextSourceBuffer.js
Hi,
this PR has to solve issues #2689 and, I hope, #2529. Any feedback would be appreciate. Improve subtitles management when subtitles are disabled at loading.
Nico
=> Subtitles bugfix

src/mss/MssFragmentProcessor.js
Hi,
this PR has to not create mssFragmentMoofProcessor and mssFragmentMoovProcessor each time a fragment needs to be processed....
Nico
=> [MSS] update mss objects management

package-lock.json, package.json, src/streaming/vo/IsoBox.js
Fix #2730 adding support for emsg boxes version 1 (update to latest version of codem-isoboxer required).
=> Add support for emsg boxes version 1

samples/audio-only/index.html, samples/getting-started/listening-to-SCTE-EMSG-events.html, samples/highlighter.js, samples/samples.json
- Cosmetic changes in samples styles.
- Recover the "Listening to SCTE events" sample.
- Typo corrections.
- Use audio tag for audio only sample.
=> Polish dash.js samples

src/streaming/Stream.js, src/streaming/rules/scheduling/BufferLevelRule.js, src/streaming/thumbnail/ThumbnailController.js, src/streaming/thumbnail/ThumbnailTracks.js, test/unit/mocks/StreamProcessorMock.js, test/unit/mocks/TextControllerMock.js, test/unit/streaming.Stream.js, test/unit/streaming.rules.scheduling.BufferLevelRule.js, test/unit/streaming.thumbnail.ThumbnailController.js
Hi,
this PR has to update unit tests for :
- BufferLevelRule
- Stream
- ThumbnailController
Nico
=> Update unit tests

build/typings/index.d.ts, index.d.ts
Update ProtectionController typings as requests in #2745.
=> Update ProtectionController typings

src/streaming/rules/RulesContext.js, src/streaming/rules/abr/BolaRule.js, src/streaming/rules/abr/ThroughputRule.js, test/unit/mocks/RulesContextMock.js, test/unit/mocks/StreamProcessorMock.js, test/unit/streaming.rules.RulesContext.js, test/unit/streaming.rules.abr.ThroughputRule.js
Hi,
this PR has to update RulesContext by replacing streamProcessor reference by scheduleController one. Some unit tests have been also added.
Nico
=> Improve RulesContext definition

src/streaming/models/BaseURLTreeModel.js, src/streaming/utils/BaseURLSelector.js, test/unit/mocks/DashManifestModelMock.js, test/unit/streaming.models.BaseURLTreeModel.js, test/unit/streaming.utils.BaseURLSelector.js
Hi,
this PR has to add tests in BaseURLTreeModel and BaseURLSelector classes.
Nico
=> Update base URL classes

src/streaming/MediaPlayer.js, src/streaming/models/MediaPlayerModel.js, test/unit/mocks/MediaPlayerModelMock.js
Hi,
this PR has to update the default timing source as described in #2757 by @wilaw.
@wilaw , is there something else to do with this update?
Nico
=> Update default timing source

src/streaming/controllers/StreamController.js, test/unit/helpers/ObjectsHelper.js, test/unit/mocks/AdapterMock.js, test/unit/mocks/ManifestLoaderMock.js, test/unit/mocks/ManifestModelMock.js, test/unit/mocks/MetricsModelMock.js, test/unit/mocks/ProtectionControllerMock.js, test/unit/streaming.controllers.StreamController.js
Hi,
this PR has to update StreamController unit tests.
Nico
=> StreamController unit tests

src/dash/DashAdapter.js, src/dash/DashHandler.js, src/dash/models/DashManifestModel.js, src/dash/utils/TimelineSegmentsGetter.js, src/mss/MssHandler.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js, src/streaming/models/MediaPlayerModel.js, src/streaming/models/VideoModel.js, src/streaming/rules/ThroughputHistory.js, test/unit/mocks/MediaPlayerModelMock.js, test/unit/mocks/StreamControllerMock.js, test/unit/streaming.MediaPlayerSpec.js, test/unit/streaming.Stream.js, test/unit/streaming.controllers.AbrControllerSpec.js, test/unit/streaming.controllers.ScheduleController.js, test/unit/streaming.controllers.StreamController.js
Hi,
this PR has to simplify code by mutualising, remove useless functions, etc...
Nico
=> New Refactoring

package-lock.json, package.json
Hi,
this PR has to update imsc library.
Nico
=> Update imsc version

src/core/errors/Errors.js, test/unit/core.errors.Errors.js
Hi,
this PR has to also use 11 value for error codes....
Nico
=> Reorder error codes

index.d.ts
....in the right file. ;-) #2807
=> remove ClearKeySet import

src/streaming/MediaPlayer.js, src/streaming/PreBufferSink.js, src/streaming/SourceBufferSink.js, src/streaming/StreamProcessor.js, src/streaming/constants/Constants.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/PlaybackController.js, src/streaming/models/MediaPlayerModel.js, src/streaming/models/VideoModel.js, src/streaming/rules/SwitchRequest.js, src/streaming/text/EmbeddedTextHtmlRender.js, src/streaming/thumbnail/ThumbnailController.js, src/streaming/utils/TTMLParser.js, test/unit/mocks/MediaPlayerModelMock.js, test/unit/mocks/URIFragmentModelMock.js, test/unit/streaming.MediaPlayerSpec.js, test/unit/streaming.constants.Constants.js, test/unit/streaming.controllers.AbrControllerSpec.js, test/unit/streaming.controllers.PlaybackControllers.js, test/unit/streaming.models.MediaPlayerModel.js
Hi,
this new refactoring branch has to, mainly, test parameters set in the mediaPlayer API. Tests are made in the  specific class that has to use this parameter.
Nico
=> Clean and refactoring

samples/dash-if-reference-player/app/sources.json
Regarding Reference Player:
- Remove samples that are not working any more.
- Modify DRM samples so they use HTTPS.
=> Remove not working samples

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html
Hi,
this PR has to improve sample page in order to reproduce more easily issue #2829 by :
- add setInitialBitrateFor call
- add setAutoSwitchQualityFor call
- add setQualityFor call
Nico
=> Update demo sample page

src/streaming/protection/models/ProtectionModel_21Jan2015.js
Hi,
this PR has to solve issue #2806. initData should be an uint8Array....
this sample stream can be used to validate this PR :
`        {
"name": "ClearKey Bug Fix",
"url": "https://m.dtv.fi/dash/dasherh264v2/drm/manifest_clearkey.mpd",
"protData": {
"org.w3.clearkey": {
"clearkeys": {
"QyFWeBI0EjQSNBI0EjQSNA": "EjQSNBI0EjQSNBI0EjQSNA"
}
}
}
},
`
Nico
=> Fix ClearKey issue

src/streaming/protection/models/ProtectionModel_21Jan2015.js
Hi,
this PR has to reverse PR #2827. Widewine protected content can't be played.
Nico
=> ClearKey regression fix

ISSUE_TEMPLATE.md
=> update conformance tool url

src/streaming/MediaPlayer.js, src/streaming/controllers/PlaybackController.js
Hi,
this PR has to solve issue #2805 by adding test about streamInfo definition in PlaybackController. @metalgigio, could you, please, take a look at this PR? does it solve your problem?
Nico
=> Reset on edge bug fix

src/streaming/controllers/BufferController.js
Hi,
this PR has to solve issue #2869.
Nico
=> parseFloat bug fix

src/streaming/controllers/EventController.js
Hi,
this PR implements an initial implementation of callback event in order to solve issue #2871.
Nico
=> callback event support

samples/advanced/auto-play-browser-policy.html, samples/samples.json
Add a new sample that shows how to deal with autoplay browsers policy with dash.js.
=> Add autoplay policy sample

src/streaming/controllers/PlaybackController.js
The issue has been introduced by PR #2813 (Low latency improvements)
=> Fix stall state management when not in low latency mode

src/streaming/Stream.js
Fix issue with calls to getAdaptationsForType introduced in #2881
=> Fix calls to getAdaptationForType

src/dash/models/DashManifestModel.js, src/streaming/MediaPlayer.js
Add compatibility with xml+bin SCTE events passed in the manifest, as described in DASH IOP (https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf, 5.4.2.2.1)
Fix #2907.
=> Add support for xml+bin SCTE messages

src/mss/parser/MssParser.js, src/streaming/MediaPlayer.js, test/unit/mss.parser.MssParser.js
Hi,
this PR has to complete start-over management for mss streams.
Nico
=> [Mss]bug fix about Start-Over

package-lock.json, package.json
Hi,
this PR has to update dash.js with latest imsc1 version.
Nico
=> update imsc1 version 1.0.1 => 1.0.2

src/streaming/MediaPlayer.js, src/streaming/constants/Constants.js
Hi,
this PR has to solve issue #2890 by adding, in JS doc, comments about errors that can be thrown when a function is called and the MediaPlayer is not in a specific state or if a parameter is not conform.
Nico
=> Update JS doc

src/streaming/MediaPlayer.js
Hi,
this PR has to solve issue #2919.
Nico
=> fix comments issue

contrib/akamai/controlbar/ControlBar.js, index.d.ts, src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/text/TextController.js, src/streaming/text/TextSourceBuffer.js, src/streaming/text/TextTracks.js
**Purpose**
Allow "Label" to be passed into the DASH manifest AdaptationSet.  This will allow human readable labels for things like caption tracks and audio tracks.
See DASH IOP 4.3 here https://dashif.org/docs/DASH-IF-IOP-v4.3.pdf  (page 35)
Sample manifest: https://s3-us-west-1.amazonaws.com/sev-a-g/ed.mpd
=> Parse label from DASH manifest AdaptationSet

src/streaming/controllers/BufferController.js
Previously set with stable buffer time
=> Set minBufferTime as the buffer level for playback restart after being stalled

src/mss/parser/MssParser.js
Set minBufferTime as video segment duration x2
=> [MSS] Correct minBufferTime setting

test/unit/mocks/AdapterMock.js, test/unit/mocks/VideoModelMock.js, test/unit/streaming.controllers.AbrControllerSpec.js
Hi,
this PR has to add a unit test in order to illustrate issue #2936 and fixed in PR #2935.
thanks @richardbushell.
Nico
=> unit test for checkPortalSize issue

samples/advanced/monitoring.html
Fix monitoring sample so it uses the new method for retrieving current rendition bandwidth.
=> Fix monitoring dash.js sample

contrib/akamai/controlbar/ControlBar.js
Hi,
this PR has to fix some little syntax problems....and also remove live-icon css class when the user switches from Live to VOD stream.
Nico
=> Control bar syntax fix

Gruntfile.js, package-lock.json, package.json
Hi,
This PR fixes the fact that built files in folder build/es5 were not in es5 but in es6: const declaration were still declared as const, instead of var.
Jeremie
=> Fix build in es5

contrib/akamai/controlbar/ControlBar.js
=> Fix liveSeek on manifest update

src/streaming/text/TextTracks.js, test/unit/mocks/VideoElementMock.js, test/unit/mocks/VideoModelMock.js, test/unit/streaming.text.TextTracks.js
Hi,
since PR #2962, subtitles are not displayed. :-( This PR has to fix this regression and add a unit test to avoid this kind of regression.
Nico
=> Subtitles regression fix

src/dash/DashHandler.js, src/dash/controllers/RepresentationController.js, src/streaming/MediaPlayer.js, src/streaming/Stream.js, src/streaming/text/NotFragmentedTextBufferController.js, test/unit/mocks/AbrControllerMock.js, test/unit/mocks/AdapterMock.js, test/unit/mocks/StreamMock.js, test/unit/mocks/TextControllerMock.js, test/unit/streaming.MediaPlayerSpec.js, test/unit/streaming.Stream.js
Hi,
this PR has to add unit tests of Stream class. Some parts of code have been modified to avoid issues...
Nico
=> Update stream unit test

src/mss/MssFragmentMoovProcessor.js, src/mss/parser/MssParser.js, test/unit/data/mss/manifestSubtype.xml, test/unit/mss.parser.MssParser.js
Hi,
this PR adds a unit test in MSS package about equivalence of MSS subtype and Dash role...
Nico
=> Update MSS parser unit tests

src/dash/DashAdapter.js, src/streaming/text/TextController.js, src/streaming/text/TextSourceBuffer.js
Hi,
this PR has to solve issue #2999 by doing a reset of fragmented text attributes in TextSourceBuffer at the end of period.
@panofr,  could you, please, take a look? As explained in the issue, if you can test, on your side, with same multi period stream with TTML fragmented text, it would be great...
Nico
=> Multi period with fragmented text bug fix

samples/dash-if-reference-player/app/sources.json
=> Fix thumbnail sample hostnames to point to a hostname with a valid cert

samples/dash-if-reference-player/app/sources.json
v7-MultiDRM-MultiKey-MultiPeriod had the keys for v7-MultiDRM-MultiKey!
=> Fix some invalid keys in sources.json

src/dash/DashHandler.js, src/dash/models/DashManifestModel.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js, src/streaming/rules/abr/AbandonRequestsRule.js, src/streaming/rules/abr/InsufficientBufferRule.js, src/streaming/rules/abr/ThroughputRule.js, test/unit/streaming.controllers.StreamController.js
Hi,
this PR has to update log messages and fixes a refactoring bug fix described in issue #3023 .
@o-hreshchuk, could you, please, take a look at it?
thanks,
Nico
=> Update log management + refactoring bug fix

.circleci/config.yml, test/functional/config/browsers/windows.js, test/functional/config/streams.js, test/functional/tests/seek.js, test/functional/tests/setup.js
This is an update of functional tests in order:
- to update chromedriver
- to run tests on streams only if one of declared key systems is supported by the browser
- to run only on chrome (for the time being)
Next step is to check the streams state/availability and any compatibility issue with current development version.
As a reminder, functional tests are executed on circleci every sunday night.
=> Update funtional tests

src/streaming/controllers/ScheduleController.js
=> Fix issue #3048

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js
Hi,
this PR has to solve issue #3040 by adding the search of Audio channel configuration in representation if the value has not been found in adaptation.
@jakubfrydrych , could you, please, take a look at it?
Nico
=> update AudioChannelConfiguration management

src/mss/parser/MssParser.js
Regression introduce in previous PR #3051.
Sorry for that.
=>  [MSS] fix regression on minBufferTime

src/dash/WebmSegmentBaseLoader.js, src/streaming/models/MetricsModel.js
Hi,
this PR has to solve issue about metrics for webM content : mediaType was undefined.
Nico
=> metrics bug fix for webM content

src/dash/models/DashManifestModel.js, src/dash/parser/DashParser.js
=> Manage both regular and namespaced scte35 tags

src/streaming/constants/MetricsConstants.js, src/streaming/controllers/AbrController.js, src/streaming/controllers/ScheduleController.js, src/streaming/rules/abr/ThroughputRule.js, test/unit/mocks/AbrControllerMock.js
Hi,
this PR has to solve issue #3087 by removing circular dependency.
Nico
=> remove circular dependency

samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/dashjs_config.json
Hi,
This PR has to update default configuration in sample page in order to be conform with options panel.
Nico
=> Sample page update

src/streaming/text/TextTracks.js
For example with https://livesim.dashif.org/dash/vod/testpic_2s/xml_subs.mpd sample stream, there are captions at timestamp 0. There are not displayed because the video width and height is 0 before loadedmetadata fires.
This PR avoid errors in imsc library when caption container has a size of 0.
It also waits for loadedmetadata event to call checkVideoSize in order to calculate the caption container size at the right time to be able to display the first caption at time 0 (and not to wait next 500ms interval of the checkVideoSize call)
=> Allow default text track at time 0 to be displayed

samples/dash-if-reference-player/app/sources.json, src/streaming/thumbnail/ThumbnailController.js, src/streaming/thumbnail/ThumbnailTracks.js, test/unit/streaming.thumbnail.ThumbnailController.js
Hi,
this PR has to add support of thumbnails with SegmentTimeline representation as expected in issue #3067 . Any feedback will be really appreciate....
Nico
=> Add thumbnail support for SegmentTimeline representation

src/streaming/metrics/metrics/MetricsHandlerFactory.js, src/streaming/metrics/reporting/ReportingFactory.js
Hi,
this PR has to solve an issue about logger reference...
Nico
=> fix logger reference

src/dash/DashHandler.js
Hi,
this PR has to solve issue #3055, any feedback would be appreciate....
Thanks,
Nico
=> Update getNextSegmentRequest function

src/streaming/controllers/PlaybackController.js
Hi,
this PR has to solve issue #3146. The idea is to reset commonEarliestTime only when needed. It means only when the value of commonEarliestTime was in the cleared range. Before this PR, commonEarliestTime was reseted each time the user did a seek command. The problem is that if there is a discontinuity in video buffer, and audio buffer is not fully cleared no new audio media segment is pushed (see BufferLevelRule) : commonEarliestTime, in this case, for audio is never updated, internal seek not done, the stream don't start.
In the sample stream of this issue, audio really starts at 0, but video starts at 1.782s....
@tomraut, could you, please, take a look?
Nico
=> Update common earliest time management

src/streaming/ManifestUpdater.js
This solves issue https://github.com/Dash-Industry-Forum/dash.js/issues/3123
=> [Fix] Use clearTimeout function to reset a timeout.

src/dash/parser/matchers/DurationMatcher.js
....as described in issue #2997.
thanks @zutto!
Nico
=> update parseFloat call

index.d.ts, src/core/Settings.js, src/streaming/SourceBufferSink.js, src/streaming/controllers/BufferController.js, test/unit/mocks/MediaSourceBufferMock.js
Hi,
this PR has to fix issue #3152. AppendWindowEnd is used by default, if the user doesn't want to use it, he has to update settings object.
Any feedback will be appreciate....
Nico
=> Use appendWindowEnd attribute of SourceBuffer

src/dash/utils/TimelineSegmentsGetter.js, test/unit/dash.utils.TimelineSegmentsGetter.js
Hi,
this PR has to update getSegmentByTime function. In SegmentTimeline, segments are contiguous, remove 1.5 factor in order to be more precise.
Nico
=> Update SegmentTimeline getter

src/streaming/controllers/AbrController.js
ABR Strategy settings accessor is obsoleted and is no longer accessible
=> Fixed obsoleted ABR settings accessor

test/functional/config/browsers/mac.js, test/functional/readme.md
Fix minor issues with the functional tests for MAC devices
=> Bugfix functional tests mac

.circleci/config.yml, package.json, test/functional/config.js, test/functional/config/applications.js, test/functional/config/selenium.js, test/functional/readme.md, test/functional/tests/ended.js, test/functional/tests/pause.js, test/functional/tests/play.js, test/functional/tests/playFromTime.js, test/functional/tests/scripts/utils.js, test/functional/tests/seek.js, test/functional/tests/setup.js
This PR enhance functional tests execution from CircleCI in order to get a readable report (from JUnit formatted report)
=> Functional tests report

test/functional/readme.md
Changed the third Windows example.
Now it would go through 13 tests.
=> fixed third example for windows test

src/streaming/controllers/PlaybackController.js
Hi,
this PR has to do an internal seek command only if it is needed when first media segments are pushed....
Nico
=> Optimization for audio or video only streams

src/dash/SegmentBaseLoader.js, src/dash/controllers/SegmentBaseController.js, src/streaming/thumbnail/ThumbnailTracks.js
Fix regression introduced by PR #3099 (adding of SegmentBaseController)
=> Fix thumbnail tracks

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/streaming/Stream.js, src/streaming/controllers/EventController.js, src/streaming/controllers/StreamController.js, test/unit/streaming.controllers.EventController.js
This PR fixes the handling for inline and inband events. It includes
- Fix a bug in the calculation of inline event start times
- Fix a bug which causes events at period boundary to be ignored
- Make EventController a Singleton
- Move EventController initialization to StreamController. Each Stream will use the same EventController
- Updated EventController unit tests
=> Bugfix dashevents

src/core/events/CoreEvents.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/thumbnail/ThumbnailController.js, src/streaming/thumbnail/ThumbnailTracks.js, test/unit/Streaming.StreamProcessor.js, test/unit/streaming.Stream.js, test/unit/streaming.thumbnail.ThumbnailController.js
... from StreamProcessor to Stream
(next forthcoming step: remove circular dependency from BufferController to StreamProcessor)
=> Code refactoring: remove circular dependencies

README.md
Existing link is being decommissioned in near future
=> Update Slack link in readme

src/streaming/Stream.js
=> Fix regression on track switch

index.d.ts
=> fix: startRecord type missing

src/dash/DashAdapter.js, src/dash/DashMetrics.js
=> Add JSDoc for DashAdapter

samples/ad-insertion/js/scte.js, samples/advanced/abr/index.html, samples/advanced/auto-play-browser-policy.html, samples/advanced/extend.html, samples/advanced/listening-to-SCTE-EMSG-events.html, samples/audio-only/index.html, samples/captioning/multi-track-captions.html, samples/captioning/ttml-ebutt-sample.html, samples/control/controlbar.html, samples/control/logging.html, samples/getting-started/manual-load-with-custom-settings.html, samples/live-streaming/live-delay-comparison-custom-manifest.html, samples/live-streaming/live-delay-comparison-using-fragmentCount.html, samples/live-streaming/live-delay-comparison-using-setLiveDelay.html, samples/low-latency/index.html, samples/multiperiod/index.html, samples/offline/app/main.js, samples/samples.json
- Remove invalid urls to livesim streams
- Fix syntax highlighting errors in the samples section caused by one line comment "//"
=> Fix sample pages bugs

src/mss/parser/MssParser.js
=> Fix issue #3359 (MSS timestamp offset with timestamps > 2^53)

src/dash/utils/SegmentBaseGetter.js, src/streaming/SourceBufferSink.js, src/streaming/controllers/GapController.js, src/streaming/controllers/ScheduleController.js, src/streaming/controllers/StreamController.js
- Fix a bug in the index calculation for SegmentBase and Multiperiod
- Fix a bug in GapController when parsing timestamps
- Use isNaN() when setting the availabilityWindow
=> Fix multiperiod

src/dash/DashAdapter.js, src/dash/controllers/RepresentationController.js, src/dash/models/DashManifestModel.js, src/streaming/MediaPlayer.js, src/streaming/SourceBufferSink.js, src/streaming/Stream.js, src/streaming/controllers/GapController.js, src/streaming/controllers/StreamController.js, src/streaming/utils/LiveEdgeFinder.js, test/unit/dash.models.DashManifestModel.js
The goal of this PR is to 
- Remove UseCalculatedLiveEdge attribute. This was used before to adjust the clientTimeOffset for SegmentTimeline depending on the DVRwindow. This is not a good approach, as the clientTimeOffset should be derived from the UTC timing source. In addition, we are using the segments in the SegmentTimeline as a reference for the DVR window.
- Set appendWindow in a single function
- Remove outdated streams from the stream list
=> Feature sliding periods

src/streaming/MediaPlayerEvents.js, src/streaming/StreamProcessor.js, src/streaming/controllers/BufferController.js, src/streaming/controllers/GapController.js, src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js
- Rename GAP playback seek event
- Separate function to check if source buffers can be reused
- Set seek target when we are switching periods and the period switch was causes by a seek.
- Fix SEEK_TARGET event which did not include mediatype and stream id
=> Feature optimizations

src/streaming/models/CmcdModel.js, test/unit/streaming.models.CmcdModel.js
Fix CID included in CMCD parameters if not set explicitly
=> Remove default CID from CMCD

src/core/EventBus.js
Regression introduced in PR #3372
=> Fix EventBus

src/streaming/Stream.js, src/streaming/protection/controllers/ProtectionController.js
This PR fixes javascript error in case of  AdaptationSet removal at MPD update.
But that does manage adding/removing content (AdaptationSet) at MPD update
=> Fix script error in case of  AdaptationSet removal at MPD update

src/dash/DashAdapter.js, src/dash/DashHandler.js, src/dash/models/DashManifestModel.js, src/dash/vo/EventStream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/EventController.js, src/streaming/vo/FragmentRequest.js, test/unit/dash.DashAdapter.js, test/unit/streaming.controllers.EventController.js
The goal of this PR is to fix timing issues with DASH events. In addition, new unit tests are added
=> Rewrite the event timing calculation and dispatching logic

src/streaming/rules/abr/ABRRulesCollection.js, test/unit/streaming.rules.abr.ABRRulesCollection.js
=> Add missing reason to SwitchRequest in ABRRulesCollection.js

src/streaming/controllers/AbrController.js
=> Fix reporting of wrong playback index to DroppedFramesHistory

test/functional/tests/audioSwitch.js, test/functional/tests/initialText.js, test/functional/tests/textSwitch.js
deepEqualing the whole track led to assertion errors. 
Fixed by asserting representative attributes
=> bugfix audio test asserts

src/streaming/MediaPlayer.js
=> Fix MediaPlayer.time() for live streams

index.d.ts, samples/advanced/custom-capabilities-filters.html, samples/samples.json, src/streaming/MediaPlayer.js, src/streaming/utils/CapabilitiesFilter.js, test/unit/streaming.utils.CapabilitiesFilter.js
Adding API to enable custom filtering of used representations
#3555
=> Implemented MediaPlayer API to register custom capabilities filters

index.d.ts, src/core/Settings.js, src/streaming/MediaPlayer.js, src/streaming/constants/Constants.js, src/streaming/controllers/MediaController.js, test/unit/streaming.controllers.MediaController.js
=> Add TRACK_SELECTION_MODE_FIRST_TRACK

index.d.ts, samples/advanced/cmcd.html, samples/dash-if-reference-player/app/main.js, samples/dash-if-reference-player/index.html, src/core/Settings.js, src/streaming/MediaPlayer.js, src/streaming/constants/Constants.js, src/streaming/models/CmcdModel.js, src/streaming/net/FetchLoader.js, src/streaming/net/HTTPLoader.js, src/streaming/net/XHRLoader.js, src/streaming/protection/Protection.js, src/streaming/protection/controllers/ProtectionController.js, test/unit/streaming.models.CmcdModel.js
This PR adds the option to provide CMCD data via query parameter, HTTP header or both.
=> [WIP] CMCD as HTTP headers

index.d.ts, src/core/Settings.js, src/streaming/Stream.js, src/streaming/StreamProcessor.js, src/streaming/controllers/GapController.js, src/streaming/controllers/StreamController.js
- Allow adjustment of the threshold parameter in the GapController
- Use promises for updating the internal info after an MPD update to avoid race conditions
=> Feature mp optimizations

src/streaming/controllers/PlaybackController.js, src/streaming/controllers/StreamController.js, test/unit/mocks/MediaPlayerModelMock.js, test/unit/streaming.controllers.PlaybackControllers.js
=> Fix setting of the live delay via ServiceDescriptor

src/streaming/controllers/PlaybackController.js
- Migrated all ServiceDescription settings to new/renamed `_applyServiceDescription()`
- Reorganised and renamed old function ('_applyServiceDescription()`) to
`_checkEnableLowLatency()` to better reflect its operation.
=> Simplified setting of ServiceDescription parameters

src/streaming/Stream.js, src/streaming/controllers/MediaController.js, src/streaming/text/TextController.js, src/streaming/text/TextSourceBuffer.js, test/unit/streaming.controllers.MediaController.js
=> Fix media settings storage for non-fragmented text tracks

src/dash/models/DashManifestModel.js, src/streaming/text/TextSourceBuffer.js, src/streaming/text/TextTracks.js
This PR is fixing a regression in text tracks (see issue #3685).
It's also fixing cues adding and removing to avoid duplicate identical cues
=> Fix text tracks

src/streaming/controllers/StreamController.js
=> Fix detecting target stream when skipping gap at the and of period

samples/dash-if-reference-player/app/main.js
=> Fix download time visualization in reference client

src/streaming/controllers/PlaybackController.js, src/streaming/models/VideoModel.js
=> Ignore readystate when resetting the playbackrate

samples/dash-if-reference-player/app/sources.json, src/dash/SegmentBaseLoader.js, src/dash/WebmSegmentBaseLoader.js, src/streaming/MediaPlayer.js
This fixes the initialization of the player as reported in #3724
=> Fix initialization after reset has been called

src/streaming/controllers/StreamController.js
=> Fix outer period seek to 0

index.d.ts, src/core/Settings.js, src/streaming/controllers/TimeSyncController.js
This PR allows enabling/disabling the UTC synchronization via the settings object. Enabled by default.
=> Enable/Disable UTC sync via settings flag

samples/dash-if-reference-player/app/sources.json
Added set of new test vectors (12 in total)
4x non-encrypted
4x cbcs encrypted
4x cenc encrypted
=> Update sources.json with new Axinom test vectors

src/streaming/models/CmcdModel.js, test/unit/streaming.models.CmcdModel.js
=> Improve special character escaping in CMCD string values

index.d.ts
Adding this since it was missed in #3926
=> chore: Add detectPlayreadyMessageFormat to settings type

src/streaming/protection/controllers/ProtectionController.js
This PR fixes the license request and retry mechanism which is not aborted when we stop or reset ProtectionController
=> Abort license request on reset

src/streaming/protection/controllers/ProtectionController.js, test/functional/config/smokeVectors.json
Fixes issues mentioned in #3931
=> Fix/clearkey from ref UI: Check for initData in protData before overwriting 

src/streaming/MediaPlayerEvents.js
=> Fix wrong description of PLAYBACK_LOADED_DATA event

src/streaming/SourceBufferSink.js
=> Fix wrong call to _abortBeforeAppend

src/streaming/rules/DroppedFramesHistory.js
=> Add missing streamId to DroppedFramesHistory.js

src/streaming/text/TextTracks.js
=> Catch errors when applying styles on WebVTT cue

mochahook.js
Keep the ABR alive until both buffering and playback end
=> Keep ABR alive until playback ends

src/mss/MssFragmentProcessor.js, src/mss/MssHandler.js, src/streaming/ManifestLoader.js, test/unit/mss.MssFragmentProcessor.js
Supposed to fix #4139. Would be nice to get @bbert opinion, maybe there is a better way to do this.
=> Initialize box processors when MSS content is actually being played

src/streaming/models/VideoModel.js
=> Fix nullpointer if video element is set to null

src/streaming/net/HTTPLoader.js, src/streaming/rules/abr/lolp/LoLpRule.js, test/unit/streaming.net.HTTPLoader.js, test/unit/streaming.net.XHRLoader.js
=> Fix throughput on abort 

package.json, src/dash/DashAdapter.js, src/dash/parser/matchers/LangMatcher.js, src/streaming/controllers/MediaController.js
https://github.com/Dash-Industry-Forum/dash.js/issues/4257
=> update bcp-47 dependencies to latest, ESM-only version

.circleci/config.yml
See https://github.com/CircleCI-Public/browser-tools-orb/issues/90
=> Use fixed version of Chrome driver as latest one is unavailable

index.d.ts, src/core/Settings.js, src/streaming/rules/abr/AbandonRequestsRule.js
=> Adds settings parameters to configure the AbandonRequestsRule.js

src/streaming/text/TextTracks.js
Supposed to address #4290. Needs more testing before merge.
=> Remove outdated cues from track when adding a new cue.

src/streaming/StreamProcessor.js
=> Fix invalid warning log in StreamProcessor.js

src/dash/DashAdapter.js, src/dash/models/DashManifestModel.js, src/dash/vo/MediaInfo.js, src/dash/vo/Period.js, src/dash/vo/StreamInfo.js, src/streaming/controllers/StreamController.js, src/streaming/utils/Capabilities.js, test/unit/dash.models.DashManifestModel.js
Fixes a bug that was introduced during refactoring. For the first transition from an unencrypted to an encrypted period, our current implementation must reset the MSE. The check for encrypted periods was broken and gets fixed with this PR
=> Fix transition from unencrypted to encrypted periods

src/dash/DashAdapter.js, src/dash/vo/Event.js, src/streaming/constants/Constants.js
Use the Common Media Library to parse the payload of ID3 inband events.
=> feat: parse ID3 payload for inband events

src/streaming/MediaPlayer.js, src/streaming/MediaPlayerEvents.js
=> Add PLAYBACK_INITIALIZED event

.github/workflows/deploy.yml, test/functional/config/test-configurations/local/all.json
=> Adjust deployment script

src/dash/constants/DashConstants.js, src/dash/vo/ContentProtection.js, test/unit/test/dash/dash.vo.ContentProtection.js
=> Account for lower case laUrl in MPDs

samples/live-streaming/mpd-patching.html, test/functional/config/test-configurations/streams/all.json, test/functional/config/test-configurations/streams/smoke.json
=> Update URLs to livesim2 streams for MPD patching

src/streaming/controllers/BlacklistController.js, src/streaming/utils/BaseURLSelector.js, src/streaming/utils/baseUrlResolution/ContentSteeringSelector.js
=> Fix content steering blacklist duration

src/streaming/StreamProcessor.js
=> Fix init segment loading error handling

src/core/Settings.js, src/core/events/CoreEvents.js, src/streaming/controllers/AbrController.js, src/streaming/models/MetricsModel.js, src/streaming/rules/abr/BolaRule.js, test/functional/config/test-configurations/streams/all.json
Addresses the following issues:
* #4301 
* #4377 (minor refactoring)
* #4474
=> Fixes some minor issues with the BOLA rule

build/webpack.base.cjs
=> Transpile imports from node_modules to ES5 as well

build/webpack.prod.cjs
=> fix: ignore webpack esm export analysis

src/dash/DashAdapter.js
This PR is fixing issue https://github.com/Dash-Industry-Forum/dash.js/issues/4580
@stschr can you check it
=> Fix issue #4580

src/streaming/MediaPlayer.js
=> Do not allow switching to a track that  has an unusable key

build/webpack.base.cjs
This addresses the issue reported in #4619 and discussed in #4617
=> Change Babel build target to Chrome 51

pages/features/index_features.md, pages/usage/cmcd.md, pages/usage/custom-callback-functions.md, pages/usage/live-streaming.md, pages/usage/network-interceptor.md, pages/usage/settings.md
This PR adds additional documentation on
* CMCD
* Live Streaming
* Network Interceptors
* Mapping between IOP,dash.js,Livesim2 features
=> Add additional documentation

src/dash/DashAdapter.js, src/streaming/protection/models/DefaultProtectionModel.js, src/streaming/protection/models/ProtectionModel_01b.js, src/streaming/protection/models/ProtectionModel_3Feb2014.js
=> Fix MSS bug when trying to derive a normalized key id

index.d.ts
This resolves https://github.com/Dash-Industry-Forum/dash.js/issues/4697
=> fix typo in index.d.ts with filterVideoColorimetryEssentialProperties

src/core/Utils.js, src/streaming/controllers/EventController.js
As I was looking into callback events I also checked #4325. This PR should parse the UInt8 payload of the inband events and convert it to a valid string (URL).
=> Parse UInt8 payload of inband callback events to a string

src/dash/controllers/ContentSteeringController.js
=> preserve last used pathway order in Content Steering #4714

src/streaming/controllers/BufferController.js, src/streaming/controllers/FragmentController.js, src/streaming/models/FragmentModel.js, src/streaming/models/MetricsModel.js, src/streaming/vo/DataChunk.js, src/streaming/vo/FragmentRequest.js, src/streaming/vo/metrics/HTTPRequest.js
=> Remove unused request.quality

src/streaming/Stream.js, test/functional/config/test-configurations/streams/smoke.json
=> Fix AdaptationSet switch for multiple different keys

src/streaming/net/HTTPLoader.js, src/streaming/vo/FragmentRequest.js, test/functional/config/test-configurations/streams/drm.json
=> Avoid sending duplicate AnnexI parameters when retrying a request

index.d.ts, src/dash/DashHandler.js, src/dash/constants/DashConstants.js, src/dash/models/DashManifestModel.js, src/dash/utils/TemplateSegmentsGetter.js, src/dash/vo/Representation.js, test/unit/config/karma.unit.conf.cjs, test/unit/test/dash/dash.DashHandler.js, test/unit/test/dash/dash.utils.TemplateSegmentsGetter.js
=> Don't fetch segment if endNumber is reached

src/streaming/rules/abr/ABRRulesCollection.js
=> Fix addition of custom abandonFragmentRules

index.d.ts
Hopefully this fixes https://github.com/Dash-Industry-Forum/dash.js/issues/4754#issuecomment-2842335963
=> TypeScript fixes for MediaSettings

pages/developers/migration-guides/4-to-5.md
This addresses https://github.com/Dash-Industry-Forum/dash.js/pull/4299#issuecomment-2886650795
=> Add RequestModifier to the migration guide

src/streaming/text/CueSet.js, src/streaming/text/TextTracks.js, test/unit/test/streaming/streaming.text.TextTracks.js
=> [TextTracks] Improve performance of addCaptions and fix duplicate check

src/dash/DashAdapter.js, test/unit/test/dash/dash.DashAdapter.js
Small improvement: consider schemeIdUri when checking for main AdaptationSet
=> add check for schemeIdUri in getIsMain()

src/streaming/controllers/ThroughputController.js, src/streaming/net/HTTPLoader.js
=> Check that Performance methods exist before invoking them

samples/dash-if-reference-player/app/css/main.css, samples/dash-if-reference-player/app/main.js
This PR is fixing 2 minor issues in reference sample:
- control bar handling generating exception once playback is stopped
- video element initial size (missing css rule `aspect-ratio`)
=> Fix reference sample

.github/workflows/publish_npm.yml
=> Add GitHub workflow for trusted publishing
